/*--------------------------------------------------------------------------

 minad - MINimalistic AutoDoc

 Copyright (C) 2005-2012 Rupert Hausberger <naTmeg@gmx.net>

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

--------------------------------------------------------------------------*/

static UBYTE *ndk39[] =
{
	"amigaguide",
	"amigaguide_dtc",
	"amiga_lib",
	"aml",
	"animation_dtc",
	"arexx_cl",
	"asl",
	"audio",
	"battclock",
	"battmem",
	"bevel_ic",
	"bitmap_ic",
	"bullet",
	"button_gc",
	"cardres",
	"cd",
	"checkbox_gc",
	"chooser_gc",
	"cia",
	"clicktab_gc",
	"clipboard",
	"colorwheel_gc",
	"commodities",
	"console",
	"datatypes",
	"datebrowser_gc",
	"ddebug_lib",
	"debug_lib",
	"disk",
	"diskfont",
	"dos",
	"drawlist_ic",
	"exec",
	"expansion",
	"filesysres",
	"fuelgauge_gc",
	"gadtools",
	"gameport",
	"getfile_gc",
	"getfont_gc",
	"getscreenmode_gc",
	"glyph_ic",
	"gradientslider_gc",
	"graphics",
	"hdwrench",
	"icon",
	"iffparse",
	"input",
	"integer_gc",
	"intuition",
	"keyboard",
	"keymap",
	"label_ic",
	"layers",
	"layout_gc",
	"listbrowser_gc",
	"locale",
	"lowlevel",
	"mathffp",
	"mathieeedoubbas",
	"mathieeedoubtrans",
	"mathieeesingbas",
	"mathieeesingtrans",
	"mathtrans",
	"misc",
	"narrator",
	"nonvolatile",
	"page_gc",
	"palette_gc",
	"parallel",
	"penmap_ic",
	"picture_dtc",
	"port-handler",
	"potgo",
	"printer",
	"queue-handler",
	"radiobutton_gc",
	"reaction_lib",
	"realtime",
	"resource",
	"rexxsyslib",
	"scroller_gc",
	"serial",
	"sound_dtc",
	"space_gc",
	"speedbar_gc",
	"string_gc",
	"texteditor_gc",
	"text_dtc",
	"timer",
	"trackdisk",
	"translator",
	"utility",
	"virtual_gc",
	"wb",
	"window_cl",
	NULL
};

