        { 1  , "ABRT", "Abort" },
        { 2  , "FPE", "Floating point exception" },
        { 3  , "ILL", "Illegal instruction" },
        { 4  , "INT", "Interrupt" },
        { 5  , "SEGV", "Memory fault" },
        { 6  , "TERM", "Terminated" },
        { 7  , "QUIT", "Quit" },
        { 8  , "CHLD", "Child exited" },
        { 9  , "HUP", "Hangup" },
        { 10  , "PIPE", "Broken pipe" },
        { 11  , "KILL", "Killed" },
        { 12  , "ALRM", "Alarm clock" },
        { 13 , (char *) 0, "Signal 13" } ,
        { 14 , (char *) 0, "Signal 14" } ,
        { 15 , (char *) 0, "Signal 15" } ,
        { 16 , (char *) 0, "Signal 16" } ,
        { 17 , (char *) 0, "Signal 17" } ,
        { 18 , (char *) 0, "Signal 18" } ,
        { 19 , (char *) 0, "Signal 19" } ,
        { 20 , (char *) 0, "Signal 20" } ,
        { 21 , (char *) 0, "Signal 21" } ,
        { 22 , (char *) 0, "Signal 22" } ,
        { 23 , (char *) 0, "Signal 23" } ,
        { 24 , (char *) 0, "Signal 24" } ,
        { 25 , (char *) 0, "Signal 25" } ,
        { 26 , (char *) 0, "Signal 26" } ,
        { 27 , (char *) 0, "Signal 27" } ,
        { 28 , (char *) 0, "Signal 28" } ,
        { 29 , (char *) 0, "Signal 29" } ,
        { 30 , (char *) 0, "Signal 30" } ,
        { 31 , (char *) 0, "Signal 31" } ,
