/* this was generated by 4p.
   this should be optimized later, since it's kinda silly to have
   it stored like this.. it's MEGA HUGE.  urk.  oh well.  It'll make
   future versions a lot smaller. heh.
 */

#include <stdio.h>
#include "jsui.h"

#define A (JSUI_C_WFG)
#define B (JSUI_C_WBG)


int brushbuffer_w = 50;
int brushbuffer_h = 22;
int brushbuffer_data[] = {
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
    A, A, A, A, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
    B, B, B, B, B, B, B, B, A, B, B, B, B, B, B, B, B, B, B, B, B, 
    B, B, B, B, B, B, B, B, B, B, B, A, B, A, A, A, A, A, A, A, A, 
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, B, A, B, B, B, B, 
    B, B, B, B, B, B, B, B, B, B, B, B, B, A, A, A, B, B, B, A, B, 
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, B, B, B, A, 
    A, A, B, A, B, B, B, B, B, B, B, B, B, B, A, A, A, B, B, B, A, 
    A, A, A, A, B, B, A, B, A, A, A, A, A, A, A, A, A, A, B, B, B, 
    A, A, A, B, B, B, B, B, A, A, B, A, B, B, B, B, B, A, B, B, B, 
    A, A, A, A, A, B, A, A, A, A, A, A, A, B, A, B, A, A, A, A, A, 
    B, A, A, A, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, A, B, 
    A, B, B, A, A, A, B, B, A, A, A, A, A, B, A, A, A, A, A, A, A, 
    B, A, B, A, B, A, A, B, B, B, A, A, B, B, B, B, B, A, B, B, B, 
    B, B, B, B, A, B, A, B, B, B, B, B, A, B, B, B, A, A, A, A, A, 
    B, A, A, A, A, A, A, A, B, A, B, A, A, A, A, A, B, A, A, A, B, 
    B, B, B, B, A, B, B, B, B, B, B, B, A, B, A, B, B, B, B, B, B, 
    B, B, B, B, A, A, A, B, B, B, A, A, A, A, A, B, B, A, B, A, A, 
    A, A, A, A, A, A, A, A, B, B, B, A, A, A, B, B, B, B, B, A, A, 
    B, A, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, A, A, 
    A, B, B, B, A, B, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
    A, A, B, B, B, A, A, A, B, A, B, B, B, B, B, B, B, B, B, B, B, 
    B, B, B, B, B, B, B, B, B, B, B, B, A, B, A, A, A, A, A, A, A, 
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, B, A, B, A, A, 
    A, A, A, B, B, A, A, A, A, B, B, A, A, A, B, B, A, A, B, B, A, 
    B, A, B, B, B, B, B, A, A, B, B, B, B, A, A, B, B, B, A, A, B, 
    B, A, A, B, A, B, A, A, A, A, A, B, B, A, A, A, A, B, B, A, A, 
    A, B, B, A, A, B, B, A, B, A, B, B, B, B, B, A, A, B, B, B, B, 
    A, A, B, B, B, A, A, B, B, A, A, B, A, B, A, A, A, A, A, B, B, 
    A, A, A, A, B, B, A, A, A, B, B, B, B, B, B, A, B, A, B, B, B, 
    B, B, A, A, B, B, B, B, A, A, B, B, B, A, A, A, A, A, A, B, A, 
    B, A, A, A, A, A, B, B, A, A, A, A, B, B, B, B, B, B, B, B, B, 
    B, B, A, B, A, B, B, B, B, B, A, A, B, B, B, B, A, A, A, A, A, 
    A, A, A, A, A, A, B, A, B, A, A, A, A, A, B, B, B, B, B, B, B, 
    B, B, B, B, A, B, B, B, B, B, A, B, A, B, B, B, B, B, A, A, A, 
    A, A, A, A, A, A, A, A, B, A, A, A, A, A, B, A, B, B, B, B, B, 
    B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, A, B, A, 
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
    A, B, A, B, B, B, B, B, B, B, B, B, B, B, B, B, B, A, B, B, B, 
    B, B, B, B, B, A, B, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
    B, A, A, A, A, A, A, A, A, B, A, B, B, B, B, B, B, A, B, B, B, 
    B, B, B, B, B, B, B, A, B, B, A, B, B, A, B, A, A, A, A, A, A, 
    B, A, A, A, A, A, A, A, A, A, A, B, A, A, B, A, A, B, A, B, B, 
    B, B, A, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
    A, B, A, A, A, A, B, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
    A, A, A, A, B, A, B, B, B, B, B, B, A, B, B, B, B, B, B, B, B, 
    B, B, A, B, B, B, B, B, A, B, A, A, A, A, A, A, B, A, A, A, A, 
    A, A, A, A, A, A, B, A, A, A, A, A, B, A, B, B, B, B, B, B, B, 
    B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, A, B, A, A, A, 
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, B, 
    A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
    A, A, A, A, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
    B, B, B, B, B, B, B, B
};


#undef A
#undef B

IPAGE brushes_bitmap = { 
    0, 50, 22, 
    NULL, NULL, 
    NULL, 
    3, brushbuffer_data, NULL, 0,
    NULL, NULL, NULL, 
    NULL, 
    0, 0, 0, 0, 
    0, 0, 
    0, NULL
};  

