/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Group"
#define F_CLASS_VERSION                         11
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "11.00 (2005/08/10)"

#include <feelin/class_startup.c>

#include "Private.h"
