
OBJS = \
	Main.o					\
	Application.o			\
	Globals.o				
	
Program			= FryingPan 

TARGETS			= aros os3 morphos os4
OBJDIRS			= GUI 
MAKEDIRS		= GUI-MUI Engine

BUILD_LIBRARY	= 0
PREP			= 

INCOPTS			= -I../ -I../@Own
LIBOPTS			= -lGeneric -lC

OWNSTARTUP		= 1
AROS_LIBOPTS	= 
M68K_LIBOPTS	=
MOS_LIBOPTS		=
OS4_LIBOPTS		=

	include ../Generic/Makefile.mk

// vim: noet ts=4
