#ifndef APDF_MSGS_H
#define APDF_MSGS_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_OPEN_REQ_TITLE 0
#define MSG_OPEN_REQ_POS 1
#define MSG_OPEN_REQ_NEG 2
#define MSG_EXECUTE_REQ 3
#define MSG_EXECUTE_REQ_ANSWERS 4
#define MSG_COMMODITY_DESCRIPTION 5
#define MSG_GLOBAL_SETTINGS_WIN 6
#define MSG_SETTINGS_SAVE_GAD 7
#define MSG_SETTINGS_USE_GAD 8
#define MSG_SETTINGS_CANCEL_GAD 9
#define MSG_LOG_WIN 10
#define MSG_LOG_AUTO_OPEN_GAD 11
#define MSG_LOG_CLEAR_GAD 12
#define MSG_USED_MODULE 13
#define MSG_ABORT_GAD 14
#define MSG_ABORTED 15
#define MSG_BACK_GAD 16
#define MSG_FORWARD_GAD 17
#define MSG_PAGE_GAD 18
#define MSG_ZOOM_GAD 19
#define MSG_SEARCH_GAD 20
#define MSG_NEXT_GAD 21
#define MSG_SEARCHING 22
#define MSG_NOT_FOUND 23
#define MSG_OUTLINES_WIN 24
#define MSG_LOADING 25
#define MSG_SAVE_MODE_PS_LEV2 26
#define MSG_SAVE_MODE_PS_LEV1 27
#define MSG_SAVE_MODE_TEXT 28
#define MSG_SAVE_MODE_PBM_PPM_IMAGES 29
#define MSG_SAVE_MODE_PBM_PPM_JPEG_IMAGES 30
#define MSG_SAVE_WIN 31
#define MSG_SAVE_FILE_GAD 32
#define MSG_SAVE_FILE_HELP 33
#define MSG_SELECT_FILE_NAME_REQ 34
#define MSG_SAVE_MODE_GAD 35
#define MSG_SAVE_MODE_HELP 36
#define MSG_FIRST_PAGE_GAD 37
#define MSG_LAST_PAGE_GAD 38
#define MSG_SAVE_ZOOM_GAD 39
#define MSG_SAVE_ROTATE_GAD 40
#define MSG_SAVE_SAVE_GAD 41
#define MSG_SAVE_CANCEL_GAD 42
#define MSG_SAVING 43
#define MSG_SAVED 44
#define MSG_DOCPREFS_GENERAL_PAGE 45
#define MSG_DOCPREFS_FONTMAP_PAGE 46
#define MSG_DOCPREFS_OPEN_PAGE_GAD 47
#define MSG_DOCPREFS_OPEN_PAGE_HELP 48
#define MSG_DOCPREFS_ZOOM_GAD 49
#define MSG_DOCPREFS_ZOOM_HELP 50
#define MSG_DOCPREFS_ROTATE_GAD 51
#define MSG_DOCPREFS_ROTATE_HELP 52
#define MSG_DOCPREFS_ANTIALIASING_GAD 53
#define MSG_DOCPREFS_ANTIALIASING_HELP 54
#define MSG_DOCPREFS_AA_TEXT_GAD 55
#define MSG_DOCPREFS_AA_FILL_GAD 56
#define MSG_DOCPREFS_AA_STROKE_GAD 57
#define MSG_DOCPREFS_CROPBOX_GAD 58
#define MSG_DOCPREFS_CROPBOX_HELP 59
#define MSG_DOCPREFS_CB_LEFT_GAD 60
#define MSG_DOCPREFS_CB_TOP_GAD 61
#define MSG_DOCPREFS_CB_RIGHT_GAD 62
#define MSG_DOCPREFS_CB_BOTTOM_GAD 63
#define MSG_DOCPREFS_CB_GRAB_GAD 64
#define MSG_DOCPREFS_CB_GRAB_HELP 65
#define MSG_REQ_OK 66
#define MSG_FONTS_WIN 67
#define MSG_FONTS_REMOVE 68
#define MSG_FONTS_CLEAR 69
#define MSG_FONTS_SCAN 70
#define MSG_FONTS_SCANNING 71
#define MSG_FONTMAP_PDFFONT 72
#define MSG_FONTMAP_SUBSTITUTED_FONT 73
#define MSG_FONTMAP_TYPE 74
#define MSG_FONTMAP_HELP 75
#define MSG_FONTMAP_ADD_GAD 76
#define MSG_FONTMAP_REMOVE_GAD 77
#define MSG_FONTMAP_PDFFONT_GAD 78
#define MSG_FONTMAP_FONT_GAD 79
#define MSG_FONTMAP_SELECT_FONT_REQ 80
#define MSG_FONTMAP_TYPE_GAD 81
#define MSG_FONTINFO_PDFFONT 82
#define MSG_FONTINFO_TYPE 83
#define MSG_FONTINFO_EMB 84
#define MSG_FONTINFO_PROPERTIES 85
#define MSG_FONTINFO_HELP 86
#define MSG_PREFS_LOADALL 87
#define MSG_FIT_PAGE 88
#define MSG_FIT_WIDTH 89
#define MSG_PREFS_ABOUT_PAGE 90
#define MSG_PREFS_GENERAL_PAGE 91
#define MSG_PREFS_FONT_DIRS_PAGE 92
#define MSG_PREFS_FONTMAP_PAGE 93
#define MSG_PREFS_ADVANCED_PAGE 94
#define MSG_PREFS_AUTO_OPEN_GAD 95
#define MSG_PREFS_AUTO_OPEN_HELP 96
#define MSG_PREFS_DISKOBJ_GAD 97
#define MSG_PREFS_DISKOBJ_HELP 98
#define MSG_PREFS_GZIPCMD_GAD 99
#define MSG_PREFS_GZIPCMD_HELP 100
#define MSG_PREFS_TMPDIR_GAD 101
#define MSG_PREFS_TMPDIR_HELP 102
#define MSG_PREFS_TMPDIR_REQ 103
#define MSG_PREFS_URLCMD_GAD 104
#define MSG_PREFS_URLCMD_HELP 105
#define MSG_PREFS_PRTDEV_GAD 106
#define MSG_PREFS_PRTDEV_HELP 107
#define MSG_PREFS_DEFICON_GAD 108
#define MSG_PREFS_DEFICON_HELP 109
#define MSG_PREFS_SELECTCOLOR_GAD 110
#define MSG_PREFS_SELECTCOLOR_HELP 111
#define MSG_PREFS_SELECTCOLOR_REQ 112
#define MSG_PREFS_ZOOM_GAD 113
#define MSG_PREFS_ZOOM_HELP 114
#define MSG_PREFS_ANTIALIASING_GAD 115
#define MSG_PREFS_ANTIALIASING_HELP 116
#define MSG_PREFS_AATEXT_GAD 117
#define MSG_PREFS_AAFILL_GAD 118
#define MSG_PREFS_AASTROKE_GAD 119
#define MSG_PREFS_FONTDIRS_HELP 120
#define MSG_PREFS_FONTDIR_REQ 121
#define MSG_PREFS_FONTDIR_NEW_GAD 122
#define MSG_PREFS_FONTDIR_REMOVE_GAD 123
#define MSG_PREFS_MODULEDIR_GAD 124
#define MSG_PREFS_MODULEDIR_HELP 125
#define MSG_PREFS_MODULEDIR_REQ 126
#define MSG_PREFS_MODULE_GAD 127
#define MSG_PREFS_MODULE_HELP 128
#define MSG_PREFS_MODULE_REQ 129
#define MSG_PREFS_MAXCOLORS_GAD 130
#define MSG_PREFS_MAXCOLORS_HELP 131
#define MSG_PREFS_CACHESZ_GAD 132
#define MSG_PREFS_CACHESZ_HELP 133
#define MSG_PREFS_CACHEBLOCSZ_GAD 134
#define MSG_PREFS_CACHEBLOCSZ_HELP 135
#define MSG_SAVEAS_REQ 136
#define MSG_SAVEAS_REQ_POS 137
#define MSG_SAVEAS_REQ_NEG 138
#define MSG_ERROR_REQ 139
#define MSG_LOADING_PLOBJ 140
#define MSG_LOAD_ERR 141
#define MSG_INFO_TITLE 142
#define MSG_INFO_AUTHOR 143
#define MSG_INFO_SUBJECT 144
#define MSG_INFO_CREATOR 145
#define MSG_INFO_PRODUCER 146
#define MSG_INFO_KEYWORDS 147
#define MSG_INFO_CREATION_DATE 148
#define MSG_INFO_MODDATE 149
#define MSG_INFO_NUMPAGES 150
#define MSG_INFO_ENCRYPTED 151
#define MSG_INFO_PRINTING 152
#define MSG_INFO_COPY 153
#define MSG_INFO_YES 154
#define MSG_INFO_NO 155
#define MSG_SIDES_GAD 156
#define MSG_SIDES_HELP 157
#define MSG_SIDES_BOTH 158
#define MSG_SIDES_EVEN 159
#define MSG_SIDES_ODD 160
#define MSG_LOG_AUTO_OPEN_HELP 161
#define MSG_ENTER_PASSWORD_WIN 162
#define MSG_PASSWORD_OK 163
#define MSG_PASSWORD_CANCEL 164
#define MSG_INFO_LINEARIZED 165
#define MSG_PREFS_DEFAULT_PARAMS_TITLE 166
#define MSG_PREFS_CONTINUOUS_GAD 167
#define MSG_PREFS_CONTINUOUS_HELP 168
#define MSG_PREFS_DISPLAY_MODE_GAD 169
#define MSG_PREFS_DISPLAY_MODE_HELP 170
#define MSG_PREFS_DISPMODE_ONEPASS 171
#define MSG_PREFS_DISPMODE_TEXTFIRST 172
#define MSG_PREFS_DISPMODE_PROGRESSIVE 173
#define MSG_PREFS_COLUMNS_GAD 174
#define MSG_PREFS_COLUMNS_HELP 175
#define MSG_PREFS_ROWS_GAD 176
#define MSG_PREFS_ROWS_HELP 177
#define MSG_DOCPREFS_CONTINUOUS_GAD 178
#define MSG_DOCPREFS_CONTINUOUS_HELP 179
#define MSG_DOCPREFS_DISPLAY_MODE_GAD 180
#define MSG_DOCPREFS_DISPLAY_MODE_HELP 181
#define MSG_DOCPREFS_DISPMODE_ONEPASS 182
#define MSG_DOCPREFS_DISPMODE_TEXTFIRST 183
#define MSG_DOCPREFS_DISPMODE_PROGRESSIVE 184
#define MSG_DOCPREFS_COLUMNS_GAD 185
#define MSG_DOCPREFS_COLUMNS_HELP 186
#define MSG_DOCPREFS_ROWS_GAD 187
#define MSG_DOCPREFS_ROWS_HELP 188
#define MSG_DOCPREFS_TOOLBAR_GAD 189
#define MSG_DOCPREFS_TOOLBAR_HELP 190
#define MSG_DOCPREFS_NAVBAR_GAD 191
#define MSG_DOCPREFS_NAVBAR_HELP 192
#define MSG_PREFS_MAKE_BITMAP_GAD 193
#define MSG_PREFS_MAKE_BITMAP_HELP 194
#define MSG_PREFS_SPARE_MEM_GAD 195
#define MSG_PREFS_SPARE_MEM_HELP 196
#define MSG_PREFS_UPDATE_TIME_GAD 197
#define MSG_PREFS_UPDATE_TIME_HELP 198
#define MSG_PREFS_ICON_REQ 199
#define MSG_PREFS_DEFICON_REQ 200
#define MSG_OWNERPW_GAD 201
#define MSG_USERPW_GAD 202
#define MSG_PREFS_EXTOUTLINES_GAD 203
#define MSG_PREFS_EXTOUTLINES_HELP 204
#define MSG_PREFS_OPENOUTLINES_GAD 205
#define MSG_PREFS_OPENOUTLINES_HELP 206
#define MSG_DOCPREFS_OUTLINES_GAD 207
#define MSG_DOCPREFS_OUTLINES_HELP 208
#define MSG_ERROR_ERR 1000
#define MSG_REQUIRES_68020_ERR 1001
#define MSG_REQUIRES_3_0_ERR 1002
#define MSG_NO_MUIMASTER_ERR 1003
#define MSG_CANT_CREATE_CC_ERR 1004
#define MSG_CANT_CREATE_CONFIG_OBJ_ERR 1005
#define MSG_ERROR_HEADER_ERR 1006
#define MSG_CANT_FIND_MODULE_ERR 1007
#define MSG_CANT_CREATE_SERVER_ERR 1008
#define MSG_SERVER_INIT_ERR 1009
#define MSG_CANT_CREATE_MUI_APP_ERR 1010
#define MSG_CANT_LOAD_DOC_ERR 1011
#define MSG_CANT_SAVE_PREFS_ERR 1012
#define MSG_SAVE_ERR 1013
#define MSG_CANT_SAVE_ERR 1014
#define MSG_PROJECT_MENU 2000
#define MSG_ABOUT_MENU 2001
#define MSG_ABOUT_MUI_MENU 2002
#define MSG_NEW_DOC_MENU 2003
#define MSG_NEW_VIEW_MENU 2004
#define MSG_OPEN_MENU 2005
#define MSG_SAVEAS_MENU 2006
#define MSG_PRINT_MENU 2007
#define MSG_HIDE_MENU 2008
#define MSG_QUIT_MENU 2009
#define MSG_EDIT_MENU 2010
#define MSG_COPY_MENU 2011
#define MSG_VIEW_MENU 2012
#define MSG_REFRESH_MENU 2013
#define MSG_CROP_MENU 2014
#define MSG_UNCROP_MENU 2015
#define MSG_ROTATE_LEFT_MENU 2016
#define MSG_ROTATE_RIGHT_MENU 2017
#define MSG_INFO_MENU 2018
#define MSG_OUTLINES_MENU 2019
#define MSG_FONTS_MENU 2020
#define MSG_ERRORS_LOG_MENU 2021
#define MSG_SETTINGS_MENU 2022
#define MSG_GLOBAL_SETTINGS_MENU 2023
#define MSG_DOC_SETTINGS_MENU 2024
#define MSG_MUI_MENU 2025
#define MSG_TEXT_AA_MENU 2026
#define MSG_STROKE_AA_MENU 2027
#define MSG_FILL_AA_MENU 2028
#define MSG_PDF_OPERATIONS_MENU 2029
#define MSG_SAVE_FILE_TO_MENU 2030
#define MSG_ZOOM_MENU 2031
#define MSG_ADD_ROW_MENU 2032
#define MSG_ADD_COLUMN_MENU 2033
#define MSG_REM_ROW_MENU 2034
#define MSG_REM_COLUMN_MENU 2035
#define MSG_CONTINUOUS_MENU 2036
#define MSG_DISPLAY_MODE_MENU 2037
#define MSG_ONE_PASS_MENU 2038
#define MSG_TEXT_FIRST_MENU 2039
#define MSG_PROGRESSIVE_MENU 2040
#define MSG_SHOW_NAV_BAR_MENU 2041
#define MSG_SHOW_TOOL_BAR_MENU 2042
#define MSG_SAVE_FORM_AS_MENU 2043
#define MSG_IMPORT_FDF_MENU 2044
#define MSG_FULL_SCREEN_MENU 2045

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_OPEN_REQ_TITLE_STR "Open..."
#define MSG_OPEN_REQ_POS_STR "Open"
#define MSG_OPEN_REQ_NEG_STR "Cancel"
#define MSG_EXECUTE_REQ_STR "Execute command?"
#define MSG_EXECUTE_REQ_ANSWERS_STR "Ok|Cancel"
#define MSG_COMMODITY_DESCRIPTION_STR "PDF documents viewer"
#define MSG_GLOBAL_SETTINGS_WIN_STR "Global settings"
#define MSG_SETTINGS_SAVE_GAD_STR "_Save"
#define MSG_SETTINGS_USE_GAD_STR "_Use"
#define MSG_SETTINGS_CANCEL_GAD_STR "_Cancel"
#define MSG_LOG_WIN_STR "Log"
#define MSG_LOG_AUTO_OPEN_GAD_STR "a\0Auto open"
#define MSG_LOG_CLEAR_GAD_STR "_Clear"
#define MSG_USED_MODULE_STR "Used module:"
#define MSG_ABORT_GAD_STR "_Abort"
#define MSG_ABORTED_STR "Aborted."
#define MSG_BACK_GAD_STR "_Back"
#define MSG_FORWARD_GAD_STR "_Forward"
#define MSG_PAGE_GAD_STR "Page"
#define MSG_ZOOM_GAD_STR "z\0Zoom"
#define MSG_SEARCH_GAD_STR "s\0Search"
#define MSG_NEXT_GAD_STR "_Next"
#define MSG_SEARCHING_STR "Searching..."
#define MSG_NOT_FOUND_STR "Not found"
#define MSG_OUTLINES_WIN_STR "Outlines"
#define MSG_LOADING_STR "Loading..."
#define MSG_SAVE_MODE_PS_LEV2_STR "Postscript (level 2)"
#define MSG_SAVE_MODE_PS_LEV1_STR "Postscript (level 1)"
#define MSG_SAVE_MODE_TEXT_STR "Text"
#define MSG_SAVE_MODE_PBM_PPM_IMAGES_STR "PBM/PPM images"
#define MSG_SAVE_MODE_PBM_PPM_JPEG_IMAGES_STR "PBM/PPM/JPEG images"
#define MSG_SAVE_WIN_STR "Save as..."
#define MSG_SAVE_FILE_GAD_STR "File"
#define MSG_SAVE_FILE_HELP_STR "Name of the destination file."
#define MSG_SELECT_FILE_NAME_REQ_STR "Select a file name..."
#define MSG_SAVE_MODE_GAD_STR "Mode"
#define MSG_SAVE_MODE_HELP_STR "Save mode:\n- Postscript modes save all.\n- Text mode saves only text as a\nplain ASCII file.\n- Images modes save only embedded\nimages."
#define MSG_FIRST_PAGE_GAD_STR "First page"
#define MSG_LAST_PAGE_GAD_STR "Last page"
#define MSG_SAVE_ZOOM_GAD_STR "Zoom"
#define MSG_SAVE_ROTATE_GAD_STR "Rotate"
#define MSG_SAVE_SAVE_GAD_STR "_Save"
#define MSG_SAVE_CANCEL_GAD_STR "_Cancel"
#define MSG_SAVING_STR "Saving..."
#define MSG_SAVED_STR "Saved."
#define MSG_DOCPREFS_GENERAL_PAGE_STR "General"
#define MSG_DOCPREFS_FONTMAP_PAGE_STR "Fontmap"
#define MSG_DOCPREFS_OPEN_PAGE_GAD_STR "Page"
#define MSG_DOCPREFS_OPEN_PAGE_HELP_STR "Page at which the document\nshould be opened."
#define MSG_DOCPREFS_ZOOM_GAD_STR "Zoom"
#define MSG_DOCPREFS_ZOOM_HELP_STR "Initial zoom value."
#define MSG_DOCPREFS_ROTATE_GAD_STR "Rotate"
#define MSG_DOCPREFS_ROTATE_HELP_STR "Initial rotate value."
#define MSG_DOCPREFS_ANTIALIASING_GAD_STR "Anti-aliasing"
#define MSG_DOCPREFS_ANTIALIASING_HELP_STR "Initial states of the\nanti-aliasing parameters."
#define MSG_DOCPREFS_AA_TEXT_GAD_STR "Text"
#define MSG_DOCPREFS_AA_FILL_GAD_STR "Fill"
#define MSG_DOCPREFS_AA_STROKE_GAD_STR "Stroke"
#define MSG_DOCPREFS_CROPBOX_GAD_STR "Crop-box"
#define MSG_DOCPREFS_CROPBOX_HELP_STR "Initial state of the\ncrop-box."
#define MSG_DOCPREFS_CB_LEFT_GAD_STR "Left"
#define MSG_DOCPREFS_CB_TOP_GAD_STR "Top"
#define MSG_DOCPREFS_CB_RIGHT_GAD_STR "Right"
#define MSG_DOCPREFS_CB_BOTTOM_GAD_STR "Bottom"
#define MSG_DOCPREFS_CB_GRAB_GAD_STR "Grab"
#define MSG_DOCPREFS_CB_GRAB_HELP_STR "Drag-drop this button into\na view of this document to\ncopy the crop-box values."
#define MSG_REQ_OK_STR "Ok"
#define MSG_FONTS_WIN_STR "Fonts"
#define MSG_FONTS_REMOVE_STR "_Remove"
#define MSG_FONTS_CLEAR_STR "_Clear"
#define MSG_FONTS_SCAN_STR "_Scan"
#define MSG_FONTS_SCANNING_STR "Scanning..."
#define MSG_FONTMAP_PDFFONT_STR "\33u\33bPDF font"
#define MSG_FONTMAP_SUBSTITUTED_FONT_STR "\33u\33bSubstituted font"
#define MSG_FONTMAP_TYPE_STR "\33u\33bType"
#define MSG_FONTMAP_HELP_STR "Map between PDF font names\nand actual font files."
#define MSG_FONTMAP_ADD_GAD_STR "_Add"
#define MSG_FONTMAP_REMOVE_GAD_STR "_Remove"
#define MSG_FONTMAP_PDFFONT_GAD_STR "_PDF font"
#define MSG_FONTMAP_FONT_GAD_STR "_Font"
#define MSG_FONTMAP_SELECT_FONT_REQ_STR "Select a font..."
#define MSG_FONTMAP_TYPE_GAD_STR "_Type"
#define MSG_FONTINFO_PDFFONT_STR "\33u\33bPDF font"
#define MSG_FONTINFO_TYPE_STR "\33u\33bType"
#define MSG_FONTINFO_EMB_STR "\33u\33bEmb"
#define MSG_FONTINFO_PROPERTIES_STR "\33u\33bProperties"
#define MSG_FONTINFO_HELP_STR "List of fonts used in the\ndocument, with their properties.\nYou can drag-drop the entries in\nfontmap listviews."
#define MSG_PREFS_LOADALL_STR "Load all"
#define MSG_FIT_PAGE_STR "Fit page"
#define MSG_FIT_WIDTH_STR "Fit width"
#define MSG_PREFS_ABOUT_PAGE_STR "About"
#define MSG_PREFS_GENERAL_PAGE_STR "General"
#define MSG_PREFS_FONT_DIRS_PAGE_STR "Font dirs"
#define MSG_PREFS_FONTMAP_PAGE_STR "Font map"
#define MSG_PREFS_ADVANCED_PAGE_STR "Advanced"
#define MSG_PREFS_AUTO_OPEN_GAD_STR "_Auto open log"
#define MSG_PREFS_AUTO_OPEN_HELP_STR "Initial state of the \"Auto open\"\ngadget of the log window."
#define MSG_PREFS_DISKOBJ_GAD_STR "DiskObject"
#define MSG_PREFS_DISKOBJ_HELP_STR "Icon used when iconified."
#define MSG_PREFS_GZIPCMD_GAD_STR "Gzip command"
#define MSG_PREFS_GZIPCMD_HELP_STR "Command used for\nLZW decompression\nCalled with <file>.Z and\nshould produce <file>"
#define MSG_PREFS_TMPDIR_GAD_STR "Temp. directory"
#define MSG_PREFS_TMPDIR_HELP_STR "Directory used to store files\ntoo big to fit in the cache\nUsing a RAM disk here doesn't\nmake sense !"
#define MSG_PREFS_TMPDIR_REQ_STR "Select a directory..."
#define MSG_PREFS_URLCMD_GAD_STR "URL command"
#define MSG_PREFS_URLCMD_HELP_STR "Command used when an\nURL is activated.\nShould contain a \"%s\" that\nwill be replaced by the URL."
#define MSG_PREFS_PRTDEV_GAD_STR "Print device"
#define MSG_PREFS_PRTDEV_HELP_STR "Device used to print\nPostscript files."
#define MSG_PREFS_DEFICON_GAD_STR "Default icon"
#define MSG_PREFS_DEFICON_HELP_STR "Icon added to documents that\ndon't have one when saving\ndocument specific settings."
#define MSG_PREFS_SELECTCOLOR_GAD_STR "Selection color"
#define MSG_PREFS_SELECTCOLOR_HELP_STR "Color used to draw the\nselection box."
#define MSG_PREFS_SELECTCOLOR_REQ_STR "Selection color"
#define MSG_PREFS_ZOOM_GAD_STR "Zoom"
#define MSG_PREFS_ZOOM_HELP_STR "Initial zoom value."
#define MSG_PREFS_ANTIALIASING_GAD_STR "Anti-aliasing"
#define MSG_PREFS_ANTIALIASING_HELP_STR "Initial state of the\nanti-aliasing parameters."
#define MSG_PREFS_AATEXT_GAD_STR "_Text"
#define MSG_PREFS_AAFILL_GAD_STR "_Fill"
#define MSG_PREFS_AASTROKE_GAD_STR "_Stroke"
#define MSG_PREFS_FONTDIRS_HELP_STR "List of directories searched\nfor Type1/TrueType fonts."
#define MSG_PREFS_FONTDIR_REQ_STR "Select a font directory..."
#define MSG_PREFS_FONTDIR_NEW_GAD_STR "_New"
#define MSG_PREFS_FONTDIR_REMOVE_GAD_STR "_Remove"
#define MSG_PREFS_MODULEDIR_GAD_STR "Modules directory"
#define MSG_PREFS_MODULEDIR_HELP_STR "Directory containing the modules."
#define MSG_PREFS_MODULEDIR_REQ_STR "Select the modules directory..."
#define MSG_PREFS_MODULE_GAD_STR "Module"
#define MSG_PREFS_MODULE_HELP_STR "Module used for PDF decoding.\nYou probably don't need to set this."
#define MSG_PREFS_MODULE_REQ_STR "Select a module..."
#define MSG_PREFS_MAXCOLORS_GAD_STR "Max colors per picture"
#define MSG_PREFS_MAXCOLORS_HELP_STR "Maximum number of colors\nused when remapping a picture.\n(Ignored on TrueColor screens.)"
#define MSG_PREFS_CACHESZ_GAD_STR "Cache size"
#define MSG_PREFS_CACHESZ_HELP_STR "Maximum cache size per file.\n\"Load all\" means: load\nthe whole file in memory."
#define MSG_PREFS_CACHEBLOCSZ_GAD_STR "Cache block size"
#define MSG_PREFS_CACHEBLOCSZ_HELP_STR "Size of a cache block.\nIgnored in \"Load all\" mode."
#define MSG_SAVEAS_REQ_STR "Save as..."
#define MSG_SAVEAS_REQ_POS_STR "Save"
#define MSG_SAVEAS_REQ_NEG_STR "Cancel"
#define MSG_ERROR_REQ_STR "Error"
#define MSG_LOADING_PLOBJ_STR "\33cLoading..."
#define MSG_LOAD_ERR_STR "\33cError"
#define MSG_INFO_TITLE_STR "Title"
#define MSG_INFO_AUTHOR_STR "Author"
#define MSG_INFO_SUBJECT_STR "Subject"
#define MSG_INFO_CREATOR_STR "Document created by"
#define MSG_INFO_PRODUCER_STR "PDF file produced by"
#define MSG_INFO_KEYWORDS_STR "Keywords"
#define MSG_INFO_CREATION_DATE_STR "Creation date"
#define MSG_INFO_MODDATE_STR "Last modification"
#define MSG_INFO_NUMPAGES_STR "Pages"
#define MSG_INFO_ENCRYPTED_STR "Encrypted"
#define MSG_INFO_PRINTING_STR "Printing allowed"
#define MSG_INFO_COPY_STR "Copy/paste allowed"
#define MSG_INFO_YES_STR "Yes"
#define MSG_INFO_NO_STR "No"
#define MSG_SIDES_GAD_STR "Sides"
#define MSG_SIDES_HELP_STR "Choose the page sides to print."
#define MSG_SIDES_BOTH_STR "Both"
#define MSG_SIDES_EVEN_STR "Even"
#define MSG_SIDES_ODD_STR "Odd"
#define MSG_LOG_AUTO_OPEN_HELP_STR "Open this window everytime\na message is added?"
#define MSG_ENTER_PASSWORD_WIN_STR "Enter password"
#define MSG_PASSWORD_OK_STR "Ok"
#define MSG_PASSWORD_CANCEL_STR "Cancel"
#define MSG_INFO_LINEARIZED_STR "Optimized"
#define MSG_PREFS_DEFAULT_PARAMS_TITLE_STR "Default parameters"
#define MSG_PREFS_CONTINUOUS_GAD_STR "_Continuous"
#define MSG_PREFS_CONTINUOUS_HELP_STR "Initial state of the\n\"Continuous\" parameter."
#define MSG_PREFS_DISPLAY_MODE_GAD_STR "Display mode"
#define MSG_PREFS_DISPLAY_MODE_HELP_STR "Initial state of the\ndisplay mode parameter."
#define MSG_PREFS_DISPMODE_ONEPASS_STR "One pass"
#define MSG_PREFS_DISPMODE_TEXTFIRST_STR "Text first"
#define MSG_PREFS_DISPMODE_PROGRESSIVE_STR "Progressive"
#define MSG_PREFS_COLUMNS_GAD_STR "Columns"
#define MSG_PREFS_COLUMNS_HELP_STR "Initial number\nof columns."
#define MSG_PREFS_ROWS_GAD_STR "Rows"
#define MSG_PREFS_ROWS_HELP_STR "Initial number\nof rows."
#define MSG_DOCPREFS_CONTINUOUS_GAD_STR "_Continuous"
#define MSG_DOCPREFS_CONTINUOUS_HELP_STR "Initial state of the\n\"Continuous\" parameter."
#define MSG_DOCPREFS_DISPLAY_MODE_GAD_STR "Display mode"
#define MSG_DOCPREFS_DISPLAY_MODE_HELP_STR "Initial state of the\ndisplay mode parameter."
#define MSG_DOCPREFS_DISPMODE_ONEPASS_STR "One pass"
#define MSG_DOCPREFS_DISPMODE_TEXTFIRST_STR "Text first"
#define MSG_DOCPREFS_DISPMODE_PROGRESSIVE_STR "Progressive"
#define MSG_DOCPREFS_COLUMNS_GAD_STR "Columns"
#define MSG_DOCPREFS_COLUMNS_HELP_STR "Initial number\nof columns."
#define MSG_DOCPREFS_ROWS_GAD_STR "Rows"
#define MSG_DOCPREFS_ROWS_HELP_STR "Initial number\nof rows."
#define MSG_DOCPREFS_TOOLBAR_GAD_STR "Show tool bar"
#define MSG_DOCPREFS_TOOLBAR_HELP_STR "Should the tool bar\nbe shown at startup?"
#define MSG_DOCPREFS_NAVBAR_GAD_STR "Show navigation bar"
#define MSG_DOCPREFS_NAVBAR_HELP_STR "Should the navigation bar\nbe shown at startup?"
#define MSG_PREFS_MAKE_BITMAP_GAD_STR "Make _BitMap"
#define MSG_PREFS_MAKE_BITMAP_HELP_STR "Build a BitMap from the page graphics\nafter rendering. If you have enough free\ngraphic memory, this gives a better\nscrolling speed."
#define MSG_PREFS_SPARE_MEM_GAD_STR "_Spare memory"
#define MSG_PREFS_SPARE_MEM_HELP_STR "Never use more than 3 bytes per pixel\nwhen building true color page data.\nIf not checked, use the screen's native\nformat, which might need 4 bytes per pixel,\nbut is usually faster."
#define MSG_PREFS_UPDATE_TIME_GAD_STR "Update time"
#define MSG_PREFS_UPDATE_TIME_HELP_STR "Delay between refreshes in\nprogressive display mode."
#define MSG_PREFS_ICON_REQ_STR "Choose an icon"
#define MSG_PREFS_DEFICON_REQ_STR "Choose an icon"
#define MSG_OWNERPW_GAD_STR "Owner password"
#define MSG_USERPW_GAD_STR "User password"
#define MSG_PREFS_EXTOUTLINES_GAD_STR "Separate outlines"
#define MSG_PREFS_EXTOUTLINES_HELP_STR "Should outlines appear in an\nexternal window or inside the main\nwindow ?"
#define MSG_PREFS_OPENOUTLINES_GAD_STR "Open outlines"
#define MSG_PREFS_OPENOUTLINES_HELP_STR "Open outlines automatically ?"
#define MSG_DOCPREFS_OUTLINES_GAD_STR "Open outlines"
#define MSG_DOCPREFS_OUTLINES_HELP_STR "Open outlines automatically ?"
#define MSG_ERROR_ERR_STR "Error"
#define MSG_REQUIRES_68020_ERR_STR "Apdf requires at least a 68020.\n"
#define MSG_REQUIRES_3_0_ERR_STR "Apdf requires at least AmgaOS 3.0.\n"
#define MSG_NO_MUIMASTER_ERR_STR "Can't open \"muimaster.library\".\n"
#define MSG_CANT_CREATE_CC_ERR_STR "Can't create custom class.\n"
#define MSG_CANT_CREATE_CONFIG_OBJ_ERR_STR "Can't create config object.\n"
#define MSG_ERROR_HEADER_ERR_STR "Error:\x20"
#define MSG_CANT_FIND_MODULE_ERR_STR "Can't find any of the following modules:\n"
#define MSG_CANT_CREATE_SERVER_ERR_STR "Can't create server.\n"
#define MSG_SERVER_INIT_ERR_STR "Server initialization failed.\n"
#define MSG_CANT_CREATE_MUI_APP_ERR_STR "Can't create MUI application.\n"
#define MSG_CANT_LOAD_DOC_ERR_STR "Can't load document.\n"
#define MSG_CANT_SAVE_PREFS_ERR_STR "Can't save prefs.\n"
#define MSG_SAVE_ERR_STR "Save error."
#define MSG_CANT_SAVE_ERR_STR "Can't save file."
#define MSG_PROJECT_MENU_STR "Project"
#define MSG_ABOUT_MENU_STR "?\0About..."
#define MSG_ABOUT_MUI_MENU_STR "About MUI..."
#define MSG_NEW_DOC_MENU_STR "N\0New document..."
#define MSG_NEW_VIEW_MENU_STR "V\0New view"
#define MSG_OPEN_MENU_STR "O\0Open..."
#define MSG_SAVEAS_MENU_STR "A\0Save as..."
#define MSG_PRINT_MENU_STR "P\0Print..."
#define MSG_HIDE_MENU_STR "H\0Hide"
#define MSG_QUIT_MENU_STR "Q\0Quit"
#define MSG_EDIT_MENU_STR "Edit"
#define MSG_COPY_MENU_STR "C\0Copy"
#define MSG_VIEW_MENU_STR "View"
#define MSG_REFRESH_MENU_STR "Refresh"
#define MSG_CROP_MENU_STR "K\0Crop"
#define MSG_UNCROP_MENU_STR "U\0UnCrop"
#define MSG_ROTATE_LEFT_MENU_STR "L\0Rotate left"
#define MSG_ROTATE_RIGHT_MENU_STR "R\0Rotate right"
#define MSG_INFO_MENU_STR "Informations..."
#define MSG_OUTLINES_MENU_STR "Outlines..."
#define MSG_FONTS_MENU_STR "Fonts..."
#define MSG_ERRORS_LOG_MENU_STR "Errors log..."
#define MSG_SETTINGS_MENU_STR "Settings"
#define MSG_GLOBAL_SETTINGS_MENU_STR "Global settings..."
#define MSG_DOC_SETTINGS_MENU_STR "Document settings..."
#define MSG_MUI_MENU_STR "MUI..."
#define MSG_TEXT_AA_MENU_STR "Text anti-aliasing"
#define MSG_STROKE_AA_MENU_STR "Strokes anti-aliasing"
#define MSG_FILL_AA_MENU_STR "Fills anti-aliasing"
#define MSG_PDF_OPERATIONS_MENU_STR "PDF operations"
#define MSG_SAVE_FILE_TO_MENU_STR "Save file to..."
#define MSG_ZOOM_MENU_STR "Zoom"
#define MSG_ADD_ROW_MENU_STR "Add row"
#define MSG_ADD_COLUMN_MENU_STR "Add column"
#define MSG_REM_ROW_MENU_STR "Remove row"
#define MSG_REM_COLUMN_MENU_STR "Remove column"
#define MSG_CONTINUOUS_MENU_STR "Continuous"
#define MSG_DISPLAY_MODE_MENU_STR "Display mode"
#define MSG_ONE_PASS_MENU_STR "One pass"
#define MSG_TEXT_FIRST_MENU_STR "Text first"
#define MSG_PROGRESSIVE_MENU_STR "Progressive"
#define MSG_SHOW_NAV_BAR_MENU_STR "Show navigation bar"
#define MSG_SHOW_TOOL_BAR_MENU_STR "Show tool bar"
#define MSG_SAVE_FORM_AS_MENU_STR "Save form as..."
#define MSG_IMPORT_FDF_MENU_STR "Import FDF file..."
#define MSG_FULL_SCREEN_MENU_STR "Full screen"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG   cca_ID;
    STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
    {MSG_OPEN_REQ_TITLE,(STRPTR)MSG_OPEN_REQ_TITLE_STR},
    {MSG_OPEN_REQ_POS,(STRPTR)MSG_OPEN_REQ_POS_STR},
    {MSG_OPEN_REQ_NEG,(STRPTR)MSG_OPEN_REQ_NEG_STR},
    {MSG_EXECUTE_REQ,(STRPTR)MSG_EXECUTE_REQ_STR},
    {MSG_EXECUTE_REQ_ANSWERS,(STRPTR)MSG_EXECUTE_REQ_ANSWERS_STR},
    {MSG_COMMODITY_DESCRIPTION,(STRPTR)MSG_COMMODITY_DESCRIPTION_STR},
    {MSG_GLOBAL_SETTINGS_WIN,(STRPTR)MSG_GLOBAL_SETTINGS_WIN_STR},
    {MSG_SETTINGS_SAVE_GAD,(STRPTR)MSG_SETTINGS_SAVE_GAD_STR},
    {MSG_SETTINGS_USE_GAD,(STRPTR)MSG_SETTINGS_USE_GAD_STR},
    {MSG_SETTINGS_CANCEL_GAD,(STRPTR)MSG_SETTINGS_CANCEL_GAD_STR},
    {MSG_LOG_WIN,(STRPTR)MSG_LOG_WIN_STR},
    {MSG_LOG_AUTO_OPEN_GAD,(STRPTR)MSG_LOG_AUTO_OPEN_GAD_STR},
    {MSG_LOG_CLEAR_GAD,(STRPTR)MSG_LOG_CLEAR_GAD_STR},
    {MSG_USED_MODULE,(STRPTR)MSG_USED_MODULE_STR},
    {MSG_ABORT_GAD,(STRPTR)MSG_ABORT_GAD_STR},
    {MSG_ABORTED,(STRPTR)MSG_ABORTED_STR},
    {MSG_BACK_GAD,(STRPTR)MSG_BACK_GAD_STR},
    {MSG_FORWARD_GAD,(STRPTR)MSG_FORWARD_GAD_STR},
    {MSG_PAGE_GAD,(STRPTR)MSG_PAGE_GAD_STR},
    {MSG_ZOOM_GAD,(STRPTR)MSG_ZOOM_GAD_STR},
    {MSG_SEARCH_GAD,(STRPTR)MSG_SEARCH_GAD_STR},
    {MSG_NEXT_GAD,(STRPTR)MSG_NEXT_GAD_STR},
    {MSG_SEARCHING,(STRPTR)MSG_SEARCHING_STR},
    {MSG_NOT_FOUND,(STRPTR)MSG_NOT_FOUND_STR},
    {MSG_OUTLINES_WIN,(STRPTR)MSG_OUTLINES_WIN_STR},
    {MSG_LOADING,(STRPTR)MSG_LOADING_STR},
    {MSG_SAVE_MODE_PS_LEV2,(STRPTR)MSG_SAVE_MODE_PS_LEV2_STR},
    {MSG_SAVE_MODE_PS_LEV1,(STRPTR)MSG_SAVE_MODE_PS_LEV1_STR},
    {MSG_SAVE_MODE_TEXT,(STRPTR)MSG_SAVE_MODE_TEXT_STR},
    {MSG_SAVE_MODE_PBM_PPM_IMAGES,(STRPTR)MSG_SAVE_MODE_PBM_PPM_IMAGES_STR},
    {MSG_SAVE_MODE_PBM_PPM_JPEG_IMAGES,(STRPTR)MSG_SAVE_MODE_PBM_PPM_JPEG_IMAGES_STR},
    {MSG_SAVE_WIN,(STRPTR)MSG_SAVE_WIN_STR},
    {MSG_SAVE_FILE_GAD,(STRPTR)MSG_SAVE_FILE_GAD_STR},
    {MSG_SAVE_FILE_HELP,(STRPTR)MSG_SAVE_FILE_HELP_STR},
    {MSG_SELECT_FILE_NAME_REQ,(STRPTR)MSG_SELECT_FILE_NAME_REQ_STR},
    {MSG_SAVE_MODE_GAD,(STRPTR)MSG_SAVE_MODE_GAD_STR},
    {MSG_SAVE_MODE_HELP,(STRPTR)MSG_SAVE_MODE_HELP_STR},
    {MSG_FIRST_PAGE_GAD,(STRPTR)MSG_FIRST_PAGE_GAD_STR},
    {MSG_LAST_PAGE_GAD,(STRPTR)MSG_LAST_PAGE_GAD_STR},
    {MSG_SAVE_ZOOM_GAD,(STRPTR)MSG_SAVE_ZOOM_GAD_STR},
    {MSG_SAVE_ROTATE_GAD,(STRPTR)MSG_SAVE_ROTATE_GAD_STR},
    {MSG_SAVE_SAVE_GAD,(STRPTR)MSG_SAVE_SAVE_GAD_STR},
    {MSG_SAVE_CANCEL_GAD,(STRPTR)MSG_SAVE_CANCEL_GAD_STR},
    {MSG_SAVING,(STRPTR)MSG_SAVING_STR},
    {MSG_SAVED,(STRPTR)MSG_SAVED_STR},
    {MSG_DOCPREFS_GENERAL_PAGE,(STRPTR)MSG_DOCPREFS_GENERAL_PAGE_STR},
    {MSG_DOCPREFS_FONTMAP_PAGE,(STRPTR)MSG_DOCPREFS_FONTMAP_PAGE_STR},
    {MSG_DOCPREFS_OPEN_PAGE_GAD,(STRPTR)MSG_DOCPREFS_OPEN_PAGE_GAD_STR},
    {MSG_DOCPREFS_OPEN_PAGE_HELP,(STRPTR)MSG_DOCPREFS_OPEN_PAGE_HELP_STR},
    {MSG_DOCPREFS_ZOOM_GAD,(STRPTR)MSG_DOCPREFS_ZOOM_GAD_STR},
    {MSG_DOCPREFS_ZOOM_HELP,(STRPTR)MSG_DOCPREFS_ZOOM_HELP_STR},
    {MSG_DOCPREFS_ROTATE_GAD,(STRPTR)MSG_DOCPREFS_ROTATE_GAD_STR},
    {MSG_DOCPREFS_ROTATE_HELP,(STRPTR)MSG_DOCPREFS_ROTATE_HELP_STR},
    {MSG_DOCPREFS_ANTIALIASING_GAD,(STRPTR)MSG_DOCPREFS_ANTIALIASING_GAD_STR},
    {MSG_DOCPREFS_ANTIALIASING_HELP,(STRPTR)MSG_DOCPREFS_ANTIALIASING_HELP_STR},
    {MSG_DOCPREFS_AA_TEXT_GAD,(STRPTR)MSG_DOCPREFS_AA_TEXT_GAD_STR},
    {MSG_DOCPREFS_AA_FILL_GAD,(STRPTR)MSG_DOCPREFS_AA_FILL_GAD_STR},
    {MSG_DOCPREFS_AA_STROKE_GAD,(STRPTR)MSG_DOCPREFS_AA_STROKE_GAD_STR},
    {MSG_DOCPREFS_CROPBOX_GAD,(STRPTR)MSG_DOCPREFS_CROPBOX_GAD_STR},
    {MSG_DOCPREFS_CROPBOX_HELP,(STRPTR)MSG_DOCPREFS_CROPBOX_HELP_STR},
    {MSG_DOCPREFS_CB_LEFT_GAD,(STRPTR)MSG_DOCPREFS_CB_LEFT_GAD_STR},
    {MSG_DOCPREFS_CB_TOP_GAD,(STRPTR)MSG_DOCPREFS_CB_TOP_GAD_STR},
    {MSG_DOCPREFS_CB_RIGHT_GAD,(STRPTR)MSG_DOCPREFS_CB_RIGHT_GAD_STR},
    {MSG_DOCPREFS_CB_BOTTOM_GAD,(STRPTR)MSG_DOCPREFS_CB_BOTTOM_GAD_STR},
    {MSG_DOCPREFS_CB_GRAB_GAD,(STRPTR)MSG_DOCPREFS_CB_GRAB_GAD_STR},
    {MSG_DOCPREFS_CB_GRAB_HELP,(STRPTR)MSG_DOCPREFS_CB_GRAB_HELP_STR},
    {MSG_REQ_OK,(STRPTR)MSG_REQ_OK_STR},
    {MSG_FONTS_WIN,(STRPTR)MSG_FONTS_WIN_STR},
    {MSG_FONTS_REMOVE,(STRPTR)MSG_FONTS_REMOVE_STR},
    {MSG_FONTS_CLEAR,(STRPTR)MSG_FONTS_CLEAR_STR},
    {MSG_FONTS_SCAN,(STRPTR)MSG_FONTS_SCAN_STR},
    {MSG_FONTS_SCANNING,(STRPTR)MSG_FONTS_SCANNING_STR},
    {MSG_FONTMAP_PDFFONT,(STRPTR)MSG_FONTMAP_PDFFONT_STR},
    {MSG_FONTMAP_SUBSTITUTED_FONT,(STRPTR)MSG_FONTMAP_SUBSTITUTED_FONT_STR},
    {MSG_FONTMAP_TYPE,(STRPTR)MSG_FONTMAP_TYPE_STR},
    {MSG_FONTMAP_HELP,(STRPTR)MSG_FONTMAP_HELP_STR},
    {MSG_FONTMAP_ADD_GAD,(STRPTR)MSG_FONTMAP_ADD_GAD_STR},
    {MSG_FONTMAP_REMOVE_GAD,(STRPTR)MSG_FONTMAP_REMOVE_GAD_STR},
    {MSG_FONTMAP_PDFFONT_GAD,(STRPTR)MSG_FONTMAP_PDFFONT_GAD_STR},
    {MSG_FONTMAP_FONT_GAD,(STRPTR)MSG_FONTMAP_FONT_GAD_STR},
    {MSG_FONTMAP_SELECT_FONT_REQ,(STRPTR)MSG_FONTMAP_SELECT_FONT_REQ_STR},
    {MSG_FONTMAP_TYPE_GAD,(STRPTR)MSG_FONTMAP_TYPE_GAD_STR},
    {MSG_FONTINFO_PDFFONT,(STRPTR)MSG_FONTINFO_PDFFONT_STR},
    {MSG_FONTINFO_TYPE,(STRPTR)MSG_FONTINFO_TYPE_STR},
    {MSG_FONTINFO_EMB,(STRPTR)MSG_FONTINFO_EMB_STR},
    {MSG_FONTINFO_PROPERTIES,(STRPTR)MSG_FONTINFO_PROPERTIES_STR},
    {MSG_FONTINFO_HELP,(STRPTR)MSG_FONTINFO_HELP_STR},
    {MSG_PREFS_LOADALL,(STRPTR)MSG_PREFS_LOADALL_STR},
    {MSG_FIT_PAGE,(STRPTR)MSG_FIT_PAGE_STR},
    {MSG_FIT_WIDTH,(STRPTR)MSG_FIT_WIDTH_STR},
    {MSG_PREFS_ABOUT_PAGE,(STRPTR)MSG_PREFS_ABOUT_PAGE_STR},
    {MSG_PREFS_GENERAL_PAGE,(STRPTR)MSG_PREFS_GENERAL_PAGE_STR},
    {MSG_PREFS_FONT_DIRS_PAGE,(STRPTR)MSG_PREFS_FONT_DIRS_PAGE_STR},
    {MSG_PREFS_FONTMAP_PAGE,(STRPTR)MSG_PREFS_FONTMAP_PAGE_STR},
    {MSG_PREFS_ADVANCED_PAGE,(STRPTR)MSG_PREFS_ADVANCED_PAGE_STR},
    {MSG_PREFS_AUTO_OPEN_GAD,(STRPTR)MSG_PREFS_AUTO_OPEN_GAD_STR},
    {MSG_PREFS_AUTO_OPEN_HELP,(STRPTR)MSG_PREFS_AUTO_OPEN_HELP_STR},
    {MSG_PREFS_DISKOBJ_GAD,(STRPTR)MSG_PREFS_DISKOBJ_GAD_STR},
    {MSG_PREFS_DISKOBJ_HELP,(STRPTR)MSG_PREFS_DISKOBJ_HELP_STR},
    {MSG_PREFS_GZIPCMD_GAD,(STRPTR)MSG_PREFS_GZIPCMD_GAD_STR},
    {MSG_PREFS_GZIPCMD_HELP,(STRPTR)MSG_PREFS_GZIPCMD_HELP_STR},
    {MSG_PREFS_TMPDIR_GAD,(STRPTR)MSG_PREFS_TMPDIR_GAD_STR},
    {MSG_PREFS_TMPDIR_HELP,(STRPTR)MSG_PREFS_TMPDIR_HELP_STR},
    {MSG_PREFS_TMPDIR_REQ,(STRPTR)MSG_PREFS_TMPDIR_REQ_STR},
    {MSG_PREFS_URLCMD_GAD,(STRPTR)MSG_PREFS_URLCMD_GAD_STR},
    {MSG_PREFS_URLCMD_HELP,(STRPTR)MSG_PREFS_URLCMD_HELP_STR},
    {MSG_PREFS_PRTDEV_GAD,(STRPTR)MSG_PREFS_PRTDEV_GAD_STR},
    {MSG_PREFS_PRTDEV_HELP,(STRPTR)MSG_PREFS_PRTDEV_HELP_STR},
    {MSG_PREFS_DEFICON_GAD,(STRPTR)MSG_PREFS_DEFICON_GAD_STR},
    {MSG_PREFS_DEFICON_HELP,(STRPTR)MSG_PREFS_DEFICON_HELP_STR},
    {MSG_PREFS_SELECTCOLOR_GAD,(STRPTR)MSG_PREFS_SELECTCOLOR_GAD_STR},
    {MSG_PREFS_SELECTCOLOR_HELP,(STRPTR)MSG_PREFS_SELECTCOLOR_HELP_STR},
    {MSG_PREFS_SELECTCOLOR_REQ,(STRPTR)MSG_PREFS_SELECTCOLOR_REQ_STR},
    {MSG_PREFS_ZOOM_GAD,(STRPTR)MSG_PREFS_ZOOM_GAD_STR},
    {MSG_PREFS_ZOOM_HELP,(STRPTR)MSG_PREFS_ZOOM_HELP_STR},
    {MSG_PREFS_ANTIALIASING_GAD,(STRPTR)MSG_PREFS_ANTIALIASING_GAD_STR},
    {MSG_PREFS_ANTIALIASING_HELP,(STRPTR)MSG_PREFS_ANTIALIASING_HELP_STR},
    {MSG_PREFS_AATEXT_GAD,(STRPTR)MSG_PREFS_AATEXT_GAD_STR},
    {MSG_PREFS_AAFILL_GAD,(STRPTR)MSG_PREFS_AAFILL_GAD_STR},
    {MSG_PREFS_AASTROKE_GAD,(STRPTR)MSG_PREFS_AASTROKE_GAD_STR},
    {MSG_PREFS_FONTDIRS_HELP,(STRPTR)MSG_PREFS_FONTDIRS_HELP_STR},
    {MSG_PREFS_FONTDIR_REQ,(STRPTR)MSG_PREFS_FONTDIR_REQ_STR},
    {MSG_PREFS_FONTDIR_NEW_GAD,(STRPTR)MSG_PREFS_FONTDIR_NEW_GAD_STR},
    {MSG_PREFS_FONTDIR_REMOVE_GAD,(STRPTR)MSG_PREFS_FONTDIR_REMOVE_GAD_STR},
    {MSG_PREFS_MODULEDIR_GAD,(STRPTR)MSG_PREFS_MODULEDIR_GAD_STR},
    {MSG_PREFS_MODULEDIR_HELP,(STRPTR)MSG_PREFS_MODULEDIR_HELP_STR},
    {MSG_PREFS_MODULEDIR_REQ,(STRPTR)MSG_PREFS_MODULEDIR_REQ_STR},
    {MSG_PREFS_MODULE_GAD,(STRPTR)MSG_PREFS_MODULE_GAD_STR},
    {MSG_PREFS_MODULE_HELP,(STRPTR)MSG_PREFS_MODULE_HELP_STR},
    {MSG_PREFS_MODULE_REQ,(STRPTR)MSG_PREFS_MODULE_REQ_STR},
    {MSG_PREFS_MAXCOLORS_GAD,(STRPTR)MSG_PREFS_MAXCOLORS_GAD_STR},
    {MSG_PREFS_MAXCOLORS_HELP,(STRPTR)MSG_PREFS_MAXCOLORS_HELP_STR},
    {MSG_PREFS_CACHESZ_GAD,(STRPTR)MSG_PREFS_CACHESZ_GAD_STR},
    {MSG_PREFS_CACHESZ_HELP,(STRPTR)MSG_PREFS_CACHESZ_HELP_STR},
    {MSG_PREFS_CACHEBLOCSZ_GAD,(STRPTR)MSG_PREFS_CACHEBLOCSZ_GAD_STR},
    {MSG_PREFS_CACHEBLOCSZ_HELP,(STRPTR)MSG_PREFS_CACHEBLOCSZ_HELP_STR},
    {MSG_SAVEAS_REQ,(STRPTR)MSG_SAVEAS_REQ_STR},
    {MSG_SAVEAS_REQ_POS,(STRPTR)MSG_SAVEAS_REQ_POS_STR},
    {MSG_SAVEAS_REQ_NEG,(STRPTR)MSG_SAVEAS_REQ_NEG_STR},
    {MSG_ERROR_REQ,(STRPTR)MSG_ERROR_REQ_STR},
    {MSG_LOADING_PLOBJ,(STRPTR)MSG_LOADING_PLOBJ_STR},
    {MSG_LOAD_ERR,(STRPTR)MSG_LOAD_ERR_STR},
    {MSG_INFO_TITLE,(STRPTR)MSG_INFO_TITLE_STR},
    {MSG_INFO_AUTHOR,(STRPTR)MSG_INFO_AUTHOR_STR},
    {MSG_INFO_SUBJECT,(STRPTR)MSG_INFO_SUBJECT_STR},
    {MSG_INFO_CREATOR,(STRPTR)MSG_INFO_CREATOR_STR},
    {MSG_INFO_PRODUCER,(STRPTR)MSG_INFO_PRODUCER_STR},
    {MSG_INFO_KEYWORDS,(STRPTR)MSG_INFO_KEYWORDS_STR},
    {MSG_INFO_CREATION_DATE,(STRPTR)MSG_INFO_CREATION_DATE_STR},
    {MSG_INFO_MODDATE,(STRPTR)MSG_INFO_MODDATE_STR},
    {MSG_INFO_NUMPAGES,(STRPTR)MSG_INFO_NUMPAGES_STR},
    {MSG_INFO_ENCRYPTED,(STRPTR)MSG_INFO_ENCRYPTED_STR},
    {MSG_INFO_PRINTING,(STRPTR)MSG_INFO_PRINTING_STR},
    {MSG_INFO_COPY,(STRPTR)MSG_INFO_COPY_STR},
    {MSG_INFO_YES,(STRPTR)MSG_INFO_YES_STR},
    {MSG_INFO_NO,(STRPTR)MSG_INFO_NO_STR},
    {MSG_SIDES_GAD,(STRPTR)MSG_SIDES_GAD_STR},
    {MSG_SIDES_HELP,(STRPTR)MSG_SIDES_HELP_STR},
    {MSG_SIDES_BOTH,(STRPTR)MSG_SIDES_BOTH_STR},
    {MSG_SIDES_EVEN,(STRPTR)MSG_SIDES_EVEN_STR},
    {MSG_SIDES_ODD,(STRPTR)MSG_SIDES_ODD_STR},
    {MSG_LOG_AUTO_OPEN_HELP,(STRPTR)MSG_LOG_AUTO_OPEN_HELP_STR},
    {MSG_ENTER_PASSWORD_WIN,(STRPTR)MSG_ENTER_PASSWORD_WIN_STR},
    {MSG_PASSWORD_OK,(STRPTR)MSG_PASSWORD_OK_STR},
    {MSG_PASSWORD_CANCEL,(STRPTR)MSG_PASSWORD_CANCEL_STR},
    {MSG_INFO_LINEARIZED,(STRPTR)MSG_INFO_LINEARIZED_STR},
    {MSG_PREFS_DEFAULT_PARAMS_TITLE,(STRPTR)MSG_PREFS_DEFAULT_PARAMS_TITLE_STR},
    {MSG_PREFS_CONTINUOUS_GAD,(STRPTR)MSG_PREFS_CONTINUOUS_GAD_STR},
    {MSG_PREFS_CONTINUOUS_HELP,(STRPTR)MSG_PREFS_CONTINUOUS_HELP_STR},
    {MSG_PREFS_DISPLAY_MODE_GAD,(STRPTR)MSG_PREFS_DISPLAY_MODE_GAD_STR},
    {MSG_PREFS_DISPLAY_MODE_HELP,(STRPTR)MSG_PREFS_DISPLAY_MODE_HELP_STR},
    {MSG_PREFS_DISPMODE_ONEPASS,(STRPTR)MSG_PREFS_DISPMODE_ONEPASS_STR},
    {MSG_PREFS_DISPMODE_TEXTFIRST,(STRPTR)MSG_PREFS_DISPMODE_TEXTFIRST_STR},
    {MSG_PREFS_DISPMODE_PROGRESSIVE,(STRPTR)MSG_PREFS_DISPMODE_PROGRESSIVE_STR},
    {MSG_PREFS_COLUMNS_GAD,(STRPTR)MSG_PREFS_COLUMNS_GAD_STR},
    {MSG_PREFS_COLUMNS_HELP,(STRPTR)MSG_PREFS_COLUMNS_HELP_STR},
    {MSG_PREFS_ROWS_GAD,(STRPTR)MSG_PREFS_ROWS_GAD_STR},
    {MSG_PREFS_ROWS_HELP,(STRPTR)MSG_PREFS_ROWS_HELP_STR},
    {MSG_DOCPREFS_CONTINUOUS_GAD,(STRPTR)MSG_DOCPREFS_CONTINUOUS_GAD_STR},
    {MSG_DOCPREFS_CONTINUOUS_HELP,(STRPTR)MSG_DOCPREFS_CONTINUOUS_HELP_STR},
    {MSG_DOCPREFS_DISPLAY_MODE_GAD,(STRPTR)MSG_DOCPREFS_DISPLAY_MODE_GAD_STR},
    {MSG_DOCPREFS_DISPLAY_MODE_HELP,(STRPTR)MSG_DOCPREFS_DISPLAY_MODE_HELP_STR},
    {MSG_DOCPREFS_DISPMODE_ONEPASS,(STRPTR)MSG_DOCPREFS_DISPMODE_ONEPASS_STR},
    {MSG_DOCPREFS_DISPMODE_TEXTFIRST,(STRPTR)MSG_DOCPREFS_DISPMODE_TEXTFIRST_STR},
    {MSG_DOCPREFS_DISPMODE_PROGRESSIVE,(STRPTR)MSG_DOCPREFS_DISPMODE_PROGRESSIVE_STR},
    {MSG_DOCPREFS_COLUMNS_GAD,(STRPTR)MSG_DOCPREFS_COLUMNS_GAD_STR},
    {MSG_DOCPREFS_COLUMNS_HELP,(STRPTR)MSG_DOCPREFS_COLUMNS_HELP_STR},
    {MSG_DOCPREFS_ROWS_GAD,(STRPTR)MSG_DOCPREFS_ROWS_GAD_STR},
    {MSG_DOCPREFS_ROWS_HELP,(STRPTR)MSG_DOCPREFS_ROWS_HELP_STR},
    {MSG_DOCPREFS_TOOLBAR_GAD,(STRPTR)MSG_DOCPREFS_TOOLBAR_GAD_STR},
    {MSG_DOCPREFS_TOOLBAR_HELP,(STRPTR)MSG_DOCPREFS_TOOLBAR_HELP_STR},
    {MSG_DOCPREFS_NAVBAR_GAD,(STRPTR)MSG_DOCPREFS_NAVBAR_GAD_STR},
    {MSG_DOCPREFS_NAVBAR_HELP,(STRPTR)MSG_DOCPREFS_NAVBAR_HELP_STR},
    {MSG_PREFS_MAKE_BITMAP_GAD,(STRPTR)MSG_PREFS_MAKE_BITMAP_GAD_STR},
    {MSG_PREFS_MAKE_BITMAP_HELP,(STRPTR)MSG_PREFS_MAKE_BITMAP_HELP_STR},
    {MSG_PREFS_SPARE_MEM_GAD,(STRPTR)MSG_PREFS_SPARE_MEM_GAD_STR},
    {MSG_PREFS_SPARE_MEM_HELP,(STRPTR)MSG_PREFS_SPARE_MEM_HELP_STR},
    {MSG_PREFS_UPDATE_TIME_GAD,(STRPTR)MSG_PREFS_UPDATE_TIME_GAD_STR},
    {MSG_PREFS_UPDATE_TIME_HELP,(STRPTR)MSG_PREFS_UPDATE_TIME_HELP_STR},
    {MSG_PREFS_ICON_REQ,(STRPTR)MSG_PREFS_ICON_REQ_STR},
    {MSG_PREFS_DEFICON_REQ,(STRPTR)MSG_PREFS_DEFICON_REQ_STR},
    {MSG_OWNERPW_GAD,(STRPTR)MSG_OWNERPW_GAD_STR},
    {MSG_USERPW_GAD,(STRPTR)MSG_USERPW_GAD_STR},
    {MSG_PREFS_EXTOUTLINES_GAD,(STRPTR)MSG_PREFS_EXTOUTLINES_GAD_STR},
    {MSG_PREFS_EXTOUTLINES_HELP,(STRPTR)MSG_PREFS_EXTOUTLINES_HELP_STR},
    {MSG_PREFS_OPENOUTLINES_GAD,(STRPTR)MSG_PREFS_OPENOUTLINES_GAD_STR},
    {MSG_PREFS_OPENOUTLINES_HELP,(STRPTR)MSG_PREFS_OPENOUTLINES_HELP_STR},
    {MSG_DOCPREFS_OUTLINES_GAD,(STRPTR)MSG_DOCPREFS_OUTLINES_GAD_STR},
    {MSG_DOCPREFS_OUTLINES_HELP,(STRPTR)MSG_DOCPREFS_OUTLINES_HELP_STR},
    {MSG_ERROR_ERR,(STRPTR)MSG_ERROR_ERR_STR},
    {MSG_REQUIRES_68020_ERR,(STRPTR)MSG_REQUIRES_68020_ERR_STR},
    {MSG_REQUIRES_3_0_ERR,(STRPTR)MSG_REQUIRES_3_0_ERR_STR},
    {MSG_NO_MUIMASTER_ERR,(STRPTR)MSG_NO_MUIMASTER_ERR_STR},
    {MSG_CANT_CREATE_CC_ERR,(STRPTR)MSG_CANT_CREATE_CC_ERR_STR},
    {MSG_CANT_CREATE_CONFIG_OBJ_ERR,(STRPTR)MSG_CANT_CREATE_CONFIG_OBJ_ERR_STR},
    {MSG_ERROR_HEADER_ERR,(STRPTR)MSG_ERROR_HEADER_ERR_STR},
    {MSG_CANT_FIND_MODULE_ERR,(STRPTR)MSG_CANT_FIND_MODULE_ERR_STR},
    {MSG_CANT_CREATE_SERVER_ERR,(STRPTR)MSG_CANT_CREATE_SERVER_ERR_STR},
    {MSG_SERVER_INIT_ERR,(STRPTR)MSG_SERVER_INIT_ERR_STR},
    {MSG_CANT_CREATE_MUI_APP_ERR,(STRPTR)MSG_CANT_CREATE_MUI_APP_ERR_STR},
    {MSG_CANT_LOAD_DOC_ERR,(STRPTR)MSG_CANT_LOAD_DOC_ERR_STR},
    {MSG_CANT_SAVE_PREFS_ERR,(STRPTR)MSG_CANT_SAVE_PREFS_ERR_STR},
    {MSG_SAVE_ERR,(STRPTR)MSG_SAVE_ERR_STR},
    {MSG_CANT_SAVE_ERR,(STRPTR)MSG_CANT_SAVE_ERR_STR},
    {MSG_PROJECT_MENU,(STRPTR)MSG_PROJECT_MENU_STR},
    {MSG_ABOUT_MENU,(STRPTR)MSG_ABOUT_MENU_STR},
    {MSG_ABOUT_MUI_MENU,(STRPTR)MSG_ABOUT_MUI_MENU_STR},
    {MSG_NEW_DOC_MENU,(STRPTR)MSG_NEW_DOC_MENU_STR},
    {MSG_NEW_VIEW_MENU,(STRPTR)MSG_NEW_VIEW_MENU_STR},
    {MSG_OPEN_MENU,(STRPTR)MSG_OPEN_MENU_STR},
    {MSG_SAVEAS_MENU,(STRPTR)MSG_SAVEAS_MENU_STR},
    {MSG_PRINT_MENU,(STRPTR)MSG_PRINT_MENU_STR},
    {MSG_HIDE_MENU,(STRPTR)MSG_HIDE_MENU_STR},
    {MSG_QUIT_MENU,(STRPTR)MSG_QUIT_MENU_STR},
    {MSG_EDIT_MENU,(STRPTR)MSG_EDIT_MENU_STR},
    {MSG_COPY_MENU,(STRPTR)MSG_COPY_MENU_STR},
    {MSG_VIEW_MENU,(STRPTR)MSG_VIEW_MENU_STR},
    {MSG_REFRESH_MENU,(STRPTR)MSG_REFRESH_MENU_STR},
    {MSG_CROP_MENU,(STRPTR)MSG_CROP_MENU_STR},
    {MSG_UNCROP_MENU,(STRPTR)MSG_UNCROP_MENU_STR},
    {MSG_ROTATE_LEFT_MENU,(STRPTR)MSG_ROTATE_LEFT_MENU_STR},
    {MSG_ROTATE_RIGHT_MENU,(STRPTR)MSG_ROTATE_RIGHT_MENU_STR},
    {MSG_INFO_MENU,(STRPTR)MSG_INFO_MENU_STR},
    {MSG_OUTLINES_MENU,(STRPTR)MSG_OUTLINES_MENU_STR},
    {MSG_FONTS_MENU,(STRPTR)MSG_FONTS_MENU_STR},
    {MSG_ERRORS_LOG_MENU,(STRPTR)MSG_ERRORS_LOG_MENU_STR},
    {MSG_SETTINGS_MENU,(STRPTR)MSG_SETTINGS_MENU_STR},
    {MSG_GLOBAL_SETTINGS_MENU,(STRPTR)MSG_GLOBAL_SETTINGS_MENU_STR},
    {MSG_DOC_SETTINGS_MENU,(STRPTR)MSG_DOC_SETTINGS_MENU_STR},
    {MSG_MUI_MENU,(STRPTR)MSG_MUI_MENU_STR},
    {MSG_TEXT_AA_MENU,(STRPTR)MSG_TEXT_AA_MENU_STR},
    {MSG_STROKE_AA_MENU,(STRPTR)MSG_STROKE_AA_MENU_STR},
    {MSG_FILL_AA_MENU,(STRPTR)MSG_FILL_AA_MENU_STR},
    {MSG_PDF_OPERATIONS_MENU,(STRPTR)MSG_PDF_OPERATIONS_MENU_STR},
    {MSG_SAVE_FILE_TO_MENU,(STRPTR)MSG_SAVE_FILE_TO_MENU_STR},
    {MSG_ZOOM_MENU,(STRPTR)MSG_ZOOM_MENU_STR},
    {MSG_ADD_ROW_MENU,(STRPTR)MSG_ADD_ROW_MENU_STR},
    {MSG_ADD_COLUMN_MENU,(STRPTR)MSG_ADD_COLUMN_MENU_STR},
    {MSG_REM_ROW_MENU,(STRPTR)MSG_REM_ROW_MENU_STR},
    {MSG_REM_COLUMN_MENU,(STRPTR)MSG_REM_COLUMN_MENU_STR},
    {MSG_CONTINUOUS_MENU,(STRPTR)MSG_CONTINUOUS_MENU_STR},
    {MSG_DISPLAY_MODE_MENU,(STRPTR)MSG_DISPLAY_MODE_MENU_STR},
    {MSG_ONE_PASS_MENU,(STRPTR)MSG_ONE_PASS_MENU_STR},
    {MSG_TEXT_FIRST_MENU,(STRPTR)MSG_TEXT_FIRST_MENU_STR},
    {MSG_PROGRESSIVE_MENU,(STRPTR)MSG_PROGRESSIVE_MENU_STR},
    {MSG_SHOW_NAV_BAR_MENU,(STRPTR)MSG_SHOW_NAV_BAR_MENU_STR},
    {MSG_SHOW_TOOL_BAR_MENU,(STRPTR)MSG_SHOW_TOOL_BAR_MENU_STR},
    {MSG_SAVE_FORM_AS_MENU,(STRPTR)MSG_SAVE_FORM_AS_MENU_STR},
    {MSG_IMPORT_FDF_MENU,(STRPTR)MSG_IMPORT_FDF_MENU_STR},
    {MSG_FULL_SCREEN_MENU,(STRPTR)MSG_FULL_SCREEN_MENU_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

static const char CatCompBlock[] =
{
    "\x00\x00\x00\x00\x00\x08"
    MSG_OPEN_REQ_TITLE_STR "\x00"
    "\x00\x00\x00\x01\x00\x06"
    MSG_OPEN_REQ_POS_STR "\x00\x00"
    "\x00\x00\x00\x02\x00\x08"
    MSG_OPEN_REQ_NEG_STR "\x00\x00"
    "\x00\x00\x00\x03\x00\x12"
    MSG_EXECUTE_REQ_STR "\x00\x00"
    "\x00\x00\x00\x04\x00\x0A"
    MSG_EXECUTE_REQ_ANSWERS_STR "\x00"
    "\x00\x00\x00\x05\x00\x16"
    MSG_COMMODITY_DESCRIPTION_STR "\x00\x00"
    "\x00\x00\x00\x06\x00\x10"
    MSG_GLOBAL_SETTINGS_WIN_STR "\x00"
    "\x00\x00\x00\x07\x00\x06"
    MSG_SETTINGS_SAVE_GAD_STR "\x00"
    "\x00\x00\x00\x08\x00\x06"
    MSG_SETTINGS_USE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x09\x00\x08"
    MSG_SETTINGS_CANCEL_GAD_STR "\x00"
    "\x00\x00\x00\x0A\x00\x04"
    MSG_LOG_WIN_STR "\x00"
    "\x00\x00\x00\x0B\x00\x0C"
    MSG_LOG_AUTO_OPEN_GAD_STR "\x00"
    "\x00\x00\x00\x0C\x00\x08"
    MSG_LOG_CLEAR_GAD_STR "\x00\x00"
    "\x00\x00\x00\x0D\x00\x0E"
    MSG_USED_MODULE_STR "\x00\x00"
    "\x00\x00\x00\x0E\x00\x08"
    MSG_ABORT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x0F\x00\x0A"
    MSG_ABORTED_STR "\x00\x00"
    "\x00\x00\x00\x10\x00\x06"
    MSG_BACK_GAD_STR "\x00"
    "\x00\x00\x00\x11\x00\x0A"
    MSG_FORWARD_GAD_STR "\x00\x00"
    "\x00\x00\x00\x12\x00\x06"
    MSG_PAGE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x13\x00\x08"
    MSG_ZOOM_GAD_STR "\x00\x00"
    "\x00\x00\x00\x14\x00\x0A"
    MSG_SEARCH_GAD_STR "\x00\x00"
    "\x00\x00\x00\x15\x00\x06"
    MSG_NEXT_GAD_STR "\x00"
    "\x00\x00\x00\x16\x00\x0E"
    MSG_SEARCHING_STR "\x00\x00"
    "\x00\x00\x00\x17\x00\x0A"
    MSG_NOT_FOUND_STR "\x00"
    "\x00\x00\x00\x18\x00\x0A"
    MSG_OUTLINES_WIN_STR "\x00\x00"
    "\x00\x00\x00\x19\x00\x0C"
    MSG_LOADING_STR "\x00\x00"
    "\x00\x00\x00\x1A\x00\x16"
    MSG_SAVE_MODE_PS_LEV2_STR "\x00\x00"
    "\x00\x00\x00\x1B\x00\x16"
    MSG_SAVE_MODE_PS_LEV1_STR "\x00\x00"
    "\x00\x00\x00\x1C\x00\x06"
    MSG_SAVE_MODE_TEXT_STR "\x00\x00"
    "\x00\x00\x00\x1D\x00\x10"
    MSG_SAVE_MODE_PBM_PPM_IMAGES_STR "\x00\x00"
    "\x00\x00\x00\x1E\x00\x14"
    MSG_SAVE_MODE_PBM_PPM_JPEG_IMAGES_STR "\x00"
    "\x00\x00\x00\x1F\x00\x0C"
    MSG_SAVE_WIN_STR "\x00\x00"
    "\x00\x00\x00\x20\x00\x06"
    MSG_SAVE_FILE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x21\x00\x1E"
    MSG_SAVE_FILE_HELP_STR "\x00"
    "\x00\x00\x00\x22\x00\x16"
    MSG_SELECT_FILE_NAME_REQ_STR "\x00"
    "\x00\x00\x00\x23\x00\x06"
    MSG_SAVE_MODE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x24\x00\x86"
    MSG_SAVE_MODE_HELP_STR "\x00\x00"
    "\x00\x00\x00\x25\x00\x0C"
    MSG_FIRST_PAGE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x26\x00\x0A"
    MSG_LAST_PAGE_GAD_STR "\x00"
    "\x00\x00\x00\x27\x00\x06"
    MSG_SAVE_ZOOM_GAD_STR "\x00\x00"
    "\x00\x00\x00\x28\x00\x08"
    MSG_SAVE_ROTATE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x29\x00\x06"
    MSG_SAVE_SAVE_GAD_STR "\x00"
    "\x00\x00\x00\x2A\x00\x08"
    MSG_SAVE_CANCEL_GAD_STR "\x00"
    "\x00\x00\x00\x2B\x00\x0A"
    MSG_SAVING_STR "\x00"
    "\x00\x00\x00\x2C\x00\x08"
    MSG_SAVED_STR "\x00\x00"
    "\x00\x00\x00\x2D\x00\x08"
    MSG_DOCPREFS_GENERAL_PAGE_STR "\x00"
    "\x00\x00\x00\x2E\x00\x08"
    MSG_DOCPREFS_FONTMAP_PAGE_STR "\x00"
    "\x00\x00\x00\x2F\x00\x06"
    MSG_DOCPREFS_OPEN_PAGE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x30\x00\x2E"
    MSG_DOCPREFS_OPEN_PAGE_HELP_STR "\x00\x00"
    "\x00\x00\x00\x31\x00\x06"
    MSG_DOCPREFS_ZOOM_GAD_STR "\x00\x00"
    "\x00\x00\x00\x32\x00\x14"
    MSG_DOCPREFS_ZOOM_HELP_STR "\x00"
    "\x00\x00\x00\x33\x00\x08"
    MSG_DOCPREFS_ROTATE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x34\x00\x16"
    MSG_DOCPREFS_ROTATE_HELP_STR "\x00"
    "\x00\x00\x00\x35\x00\x0E"
    MSG_DOCPREFS_ANTIALIASING_GAD_STR "\x00"
    "\x00\x00\x00\x36\x00\x30"
    MSG_DOCPREFS_ANTIALIASING_HELP_STR "\x00"
    "\x00\x00\x00\x37\x00\x06"
    MSG_DOCPREFS_AA_TEXT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x38\x00\x06"
    MSG_DOCPREFS_AA_FILL_GAD_STR "\x00\x00"
    "\x00\x00\x00\x39\x00\x08"
    MSG_DOCPREFS_AA_STROKE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x3A\x00\x0A"
    MSG_DOCPREFS_CROPBOX_GAD_STR "\x00\x00"
    "\x00\x00\x00\x3B\x00\x20"
    MSG_DOCPREFS_CROPBOX_HELP_STR "\x00\x00"
    "\x00\x00\x00\x3C\x00\x06"
    MSG_DOCPREFS_CB_LEFT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x3D\x00\x04"
    MSG_DOCPREFS_CB_TOP_GAD_STR "\x00"
    "\x00\x00\x00\x3E\x00\x06"
    MSG_DOCPREFS_CB_RIGHT_GAD_STR "\x00"
    "\x00\x00\x00\x3F\x00\x08"
    MSG_DOCPREFS_CB_BOTTOM_GAD_STR "\x00\x00"
    "\x00\x00\x00\x40\x00\x06"
    MSG_DOCPREFS_CB_GRAB_GAD_STR "\x00\x00"
    "\x00\x00\x00\x41\x00\x50"
    MSG_DOCPREFS_CB_GRAB_HELP_STR "\x00"
    "\x00\x00\x00\x42\x00\x04"
    MSG_REQ_OK_STR "\x00\x00"
    "\x00\x00\x00\x43\x00\x06"
    MSG_FONTS_WIN_STR "\x00"
    "\x00\x00\x00\x44\x00\x08"
    MSG_FONTS_REMOVE_STR "\x00"
    "\x00\x00\x00\x45\x00\x08"
    MSG_FONTS_CLEAR_STR "\x00\x00"
    "\x00\x00\x00\x46\x00\x06"
    MSG_FONTS_SCAN_STR "\x00"
    "\x00\x00\x00\x47\x00\x0C"
    MSG_FONTS_SCANNING_STR "\x00"
    "\x00\x00\x00\x48\x00\x0E"
    MSG_FONTMAP_PDFFONT_STR "\x00\x00"
    "\x00\x00\x00\x49\x00\x16"
    MSG_FONTMAP_SUBSTITUTED_FONT_STR "\x00\x00"
    "\x00\x00\x00\x4A\x00\x0A"
    MSG_FONTMAP_TYPE_STR "\x00\x00"
    "\x00\x00\x00\x4B\x00\x32"
    MSG_FONTMAP_HELP_STR "\x00"
    "\x00\x00\x00\x4C\x00\x06"
    MSG_FONTMAP_ADD_GAD_STR "\x00\x00"
    "\x00\x00\x00\x4D\x00\x08"
    MSG_FONTMAP_REMOVE_GAD_STR "\x00"
    "\x00\x00\x00\x4E\x00\x0A"
    MSG_FONTMAP_PDFFONT_GAD_STR "\x00"
    "\x00\x00\x00\x4F\x00\x06"
    MSG_FONTMAP_FONT_GAD_STR "\x00"
    "\x00\x00\x00\x50\x00\x12"
    MSG_FONTMAP_SELECT_FONT_REQ_STR "\x00\x00"
    "\x00\x00\x00\x51\x00\x06"
    MSG_FONTMAP_TYPE_GAD_STR "\x00"
    "\x00\x00\x00\x52\x00\x0E"
    MSG_FONTINFO_PDFFONT_STR "\x00\x00"
    "\x00\x00\x00\x53\x00\x0A"
    MSG_FONTINFO_TYPE_STR "\x00\x00"
    "\x00\x00\x00\x54\x00\x08"
    MSG_FONTINFO_EMB_STR "\x00"
    "\x00\x00\x00\x55\x00\x10"
    MSG_FONTINFO_PROPERTIES_STR "\x00\x00"
    "\x00\x00\x00\x56\x00\x70"
    MSG_FONTINFO_HELP_STR "\x00\x00"
    "\x00\x00\x00\x57\x00\x0A"
    MSG_PREFS_LOADALL_STR "\x00\x00"
    "\x00\x00\x00\x58\x00\x0A"
    MSG_FIT_PAGE_STR "\x00\x00"
    "\x00\x00\x00\x59\x00\x0A"
    MSG_FIT_WIDTH_STR "\x00"
    "\x00\x00\x00\x5A\x00\x06"
    MSG_PREFS_ABOUT_PAGE_STR "\x00"
    "\x00\x00\x00\x5B\x00\x08"
    MSG_PREFS_GENERAL_PAGE_STR "\x00"
    "\x00\x00\x00\x5C\x00\x0A"
    MSG_PREFS_FONT_DIRS_PAGE_STR "\x00"
    "\x00\x00\x00\x5D\x00\x0A"
    MSG_PREFS_FONTMAP_PAGE_STR "\x00\x00"
    "\x00\x00\x00\x5E\x00\x0A"
    MSG_PREFS_ADVANCED_PAGE_STR "\x00\x00"
    "\x00\x00\x00\x5F\x00\x10"
    MSG_PREFS_AUTO_OPEN_GAD_STR "\x00\x00"
    "\x00\x00\x00\x60\x00\x3C"
    MSG_PREFS_AUTO_OPEN_HELP_STR "\x00\x00"
    "\x00\x00\x00\x61\x00\x0C"
    MSG_PREFS_DISKOBJ_GAD_STR "\x00\x00"
    "\x00\x00\x00\x62\x00\x1A"
    MSG_PREFS_DISKOBJ_HELP_STR "\x00"
    "\x00\x00\x00\x63\x00\x0E"
    MSG_PREFS_GZIPCMD_GAD_STR "\x00\x00"
    "\x00\x00\x00\x64\x00\x52"
    MSG_PREFS_GZIPCMD_HELP_STR "\x00"
    "\x00\x00\x00\x65\x00\x10"
    MSG_PREFS_TMPDIR_GAD_STR "\x00"
    "\x00\x00\x00\x66\x00\x66"
    MSG_PREFS_TMPDIR_HELP_STR "\x00\x00"
    "\x00\x00\x00\x67\x00\x16"
    MSG_PREFS_TMPDIR_REQ_STR "\x00"
    "\x00\x00\x00\x68\x00\x0C"
    MSG_PREFS_URLCMD_GAD_STR "\x00"
    "\x00\x00\x00\x69\x00\x60"
    MSG_PREFS_URLCMD_HELP_STR "\x00\x00"
    "\x00\x00\x00\x6A\x00\x0E"
    MSG_PREFS_PRTDEV_GAD_STR "\x00\x00"
    "\x00\x00\x00\x6B\x00\x28"
    MSG_PREFS_PRTDEV_HELP_STR "\x00\x00"
    "\x00\x00\x00\x6C\x00\x0E"
    MSG_PREFS_DEFICON_GAD_STR "\x00\x00"
    "\x00\x00\x00\x6D\x00\x54"
    MSG_PREFS_DEFICON_HELP_STR "\x00"
    "\x00\x00\x00\x6E\x00\x10"
    MSG_PREFS_SELECTCOLOR_GAD_STR "\x00"
    "\x00\x00\x00\x6F\x00\x26"
    MSG_PREFS_SELECTCOLOR_HELP_STR "\x00"
    "\x00\x00\x00\x70\x00\x10"
    MSG_PREFS_SELECTCOLOR_REQ_STR "\x00"
    "\x00\x00\x00\x71\x00\x06"
    MSG_PREFS_ZOOM_GAD_STR "\x00\x00"
    "\x00\x00\x00\x72\x00\x14"
    MSG_PREFS_ZOOM_HELP_STR "\x00"
    "\x00\x00\x00\x73\x00\x0E"
    MSG_PREFS_ANTIALIASING_GAD_STR "\x00"
    "\x00\x00\x00\x74\x00\x30"
    MSG_PREFS_ANTIALIASING_HELP_STR "\x00\x00"
    "\x00\x00\x00\x75\x00\x06"
    MSG_PREFS_AATEXT_GAD_STR "\x00"
    "\x00\x00\x00\x76\x00\x06"
    MSG_PREFS_AAFILL_GAD_STR "\x00"
    "\x00\x00\x00\x77\x00\x08"
    MSG_PREFS_AASTROKE_GAD_STR "\x00"
    "\x00\x00\x00\x78\x00\x38"
    MSG_PREFS_FONTDIRS_HELP_STR "\x00\x00"
    "\x00\x00\x00\x79\x00\x1C"
    MSG_PREFS_FONTDIR_REQ_STR "\x00\x00"
    "\x00\x00\x00\x7A\x00\x06"
    MSG_PREFS_FONTDIR_NEW_GAD_STR "\x00\x00"
    "\x00\x00\x00\x7B\x00\x08"
    MSG_PREFS_FONTDIR_REMOVE_GAD_STR "\x00"
    "\x00\x00\x00\x7C\x00\x12"
    MSG_PREFS_MODULEDIR_GAD_STR "\x00"
    "\x00\x00\x00\x7D\x00\x22"
    MSG_PREFS_MODULEDIR_HELP_STR "\x00"
    "\x00\x00\x00\x7E\x00\x20"
    MSG_PREFS_MODULEDIR_REQ_STR "\x00"
    "\x00\x00\x00\x7F\x00\x08"
    MSG_PREFS_MODULE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x80\x00\x44"
    MSG_PREFS_MODULE_HELP_STR "\x00\x00"
    "\x00\x00\x00\x81\x00\x14"
    MSG_PREFS_MODULE_REQ_STR "\x00\x00"
    "\x00\x00\x00\x82\x00\x18"
    MSG_PREFS_MAXCOLORS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x83\x00\x58"
    MSG_PREFS_MAXCOLORS_HELP_STR "\x00"
    "\x00\x00\x00\x84\x00\x0C"
    MSG_PREFS_CACHESZ_GAD_STR "\x00\x00"
    "\x00\x00\x00\x85\x00\x4E"
    MSG_PREFS_CACHESZ_HELP_STR "\x00"
    "\x00\x00\x00\x86\x00\x12"
    MSG_PREFS_CACHEBLOCSZ_GAD_STR "\x00\x00"
    "\x00\x00\x00\x87\x00\x34"
    MSG_PREFS_CACHEBLOCSZ_HELP_STR "\x00\x00"
    "\x00\x00\x00\x88\x00\x0C"
    MSG_SAVEAS_REQ_STR "\x00\x00"
    "\x00\x00\x00\x89\x00\x06"
    MSG_SAVEAS_REQ_POS_STR "\x00\x00"
    "\x00\x00\x00\x8A\x00\x08"
    MSG_SAVEAS_REQ_NEG_STR "\x00\x00"
    "\x00\x00\x00\x8B\x00\x06"
    MSG_ERROR_REQ_STR "\x00"
    "\x00\x00\x00\x8C\x00\x0E"
    MSG_LOADING_PLOBJ_STR "\x00\x00"
    "\x00\x00\x00\x8D\x00\x08"
    MSG_LOAD_ERR_STR "\x00"
    "\x00\x00\x00\x8E\x00\x06"
    MSG_INFO_TITLE_STR "\x00"
    "\x00\x00\x00\x8F\x00\x08"
    MSG_INFO_AUTHOR_STR "\x00\x00"
    "\x00\x00\x00\x90\x00\x08"
    MSG_INFO_SUBJECT_STR "\x00"
    "\x00\x00\x00\x91\x00\x14"
    MSG_INFO_CREATOR_STR "\x00"
    "\x00\x00\x00\x92\x00\x16"
    MSG_INFO_PRODUCER_STR "\x00\x00"
    "\x00\x00\x00\x93\x00\x0A"
    MSG_INFO_KEYWORDS_STR "\x00\x00"
    "\x00\x00\x00\x94\x00\x0E"
    MSG_INFO_CREATION_DATE_STR "\x00"
    "\x00\x00\x00\x95\x00\x12"
    MSG_INFO_MODDATE_STR "\x00"
    "\x00\x00\x00\x96\x00\x06"
    MSG_INFO_NUMPAGES_STR "\x00"
    "\x00\x00\x00\x97\x00\x0A"
    MSG_INFO_ENCRYPTED_STR "\x00"
    "\x00\x00\x00\x98\x00\x12"
    MSG_INFO_PRINTING_STR "\x00\x00"
    "\x00\x00\x00\x99\x00\x14"
    MSG_INFO_COPY_STR "\x00\x00"
    "\x00\x00\x00\x9A\x00\x04"
    MSG_INFO_YES_STR "\x00"
    "\x00\x00\x00\x9B\x00\x04"
    MSG_INFO_NO_STR "\x00\x00"
    "\x00\x00\x00\x9C\x00\x06"
    MSG_SIDES_GAD_STR "\x00"
    "\x00\x00\x00\x9D\x00\x20"
    MSG_SIDES_HELP_STR "\x00"
    "\x00\x00\x00\x9E\x00\x06"
    MSG_SIDES_BOTH_STR "\x00\x00"
    "\x00\x00\x00\x9F\x00\x06"
    MSG_SIDES_EVEN_STR "\x00\x00"
    "\x00\x00\x00\xA0\x00\x04"
    MSG_SIDES_ODD_STR "\x00"
    "\x00\x00\x00\xA1\x00\x30"
    MSG_LOG_AUTO_OPEN_HELP_STR "\x00\x00"
    "\x00\x00\x00\xA2\x00\x10"
    MSG_ENTER_PASSWORD_WIN_STR "\x00\x00"
    "\x00\x00\x00\xA3\x00\x04"
    MSG_PASSWORD_OK_STR "\x00\x00"
    "\x00\x00\x00\xA4\x00\x08"
    MSG_PASSWORD_CANCEL_STR "\x00\x00"
    "\x00\x00\x00\xA5\x00\x0A"
    MSG_INFO_LINEARIZED_STR "\x00"
    "\x00\x00\x00\xA6\x00\x14"
    MSG_PREFS_DEFAULT_PARAMS_TITLE_STR "\x00\x00"
    "\x00\x00\x00\xA7\x00\x0C"
    MSG_PREFS_CONTINUOUS_GAD_STR "\x00"
    "\x00\x00\x00\xA8\x00\x2E"
    MSG_PREFS_CONTINUOUS_HELP_STR "\x00\x00"
    "\x00\x00\x00\xA9\x00\x0E"
    MSG_PREFS_DISPLAY_MODE_GAD_STR "\x00\x00"
    "\x00\x00\x00\xAA\x00\x2E"
    MSG_PREFS_DISPLAY_MODE_HELP_STR "\x00\x00"
    "\x00\x00\x00\xAB\x00\x0A"
    MSG_PREFS_DISPMODE_ONEPASS_STR "\x00\x00"
    "\x00\x00\x00\xAC\x00\x0C"
    MSG_PREFS_DISPMODE_TEXTFIRST_STR "\x00\x00"
    "\x00\x00\x00\xAD\x00\x0C"
    MSG_PREFS_DISPMODE_PROGRESSIVE_STR "\x00"
    "\x00\x00\x00\xAE\x00\x08"
    MSG_PREFS_COLUMNS_GAD_STR "\x00"
    "\x00\x00\x00\xAF\x00\x1C"
    MSG_PREFS_COLUMNS_HELP_STR "\x00\x00"
    "\x00\x00\x00\xB0\x00\x06"
    MSG_PREFS_ROWS_GAD_STR "\x00\x00"
    "\x00\x00\x00\xB1\x00\x18"
    MSG_PREFS_ROWS_HELP_STR "\x00"
    "\x00\x00\x00\xB2\x00\x0C"
    MSG_DOCPREFS_CONTINUOUS_GAD_STR "\x00"
    "\x00\x00\x00\xB3\x00\x2E"
    MSG_DOCPREFS_CONTINUOUS_HELP_STR "\x00\x00"
    "\x00\x00\x00\xB4\x00\x0E"
    MSG_DOCPREFS_DISPLAY_MODE_GAD_STR "\x00\x00"
    "\x00\x00\x00\xB5\x00\x2E"
    MSG_DOCPREFS_DISPLAY_MODE_HELP_STR "\x00\x00"
    "\x00\x00\x00\xB6\x00\x0A"
    MSG_DOCPREFS_DISPMODE_ONEPASS_STR "\x00\x00"
    "\x00\x00\x00\xB7\x00\x0C"
    MSG_DOCPREFS_DISPMODE_TEXTFIRST_STR "\x00\x00"
    "\x00\x00\x00\xB8\x00\x0C"
    MSG_DOCPREFS_DISPMODE_PROGRESSIVE_STR "\x00"
    "\x00\x00\x00\xB9\x00\x08"
    MSG_DOCPREFS_COLUMNS_GAD_STR "\x00"
    "\x00\x00\x00\xBA\x00\x1C"
    MSG_DOCPREFS_COLUMNS_HELP_STR "\x00\x00"
    "\x00\x00\x00\xBB\x00\x06"
    MSG_DOCPREFS_ROWS_GAD_STR "\x00\x00"
    "\x00\x00\x00\xBC\x00\x18"
    MSG_DOCPREFS_ROWS_HELP_STR "\x00"
    "\x00\x00\x00\xBD\x00\x0E"
    MSG_DOCPREFS_TOOLBAR_GAD_STR "\x00"
    "\x00\x00\x00\xBE\x00\x2A"
    MSG_DOCPREFS_TOOLBAR_HELP_STR "\x00\x00"
    "\x00\x00\x00\xBF\x00\x14"
    MSG_DOCPREFS_NAVBAR_GAD_STR "\x00"
    "\x00\x00\x00\xC0\x00\x30"
    MSG_DOCPREFS_NAVBAR_HELP_STR "\x00\x00"
    "\x00\x00\x00\xC1\x00\x0E"
    MSG_PREFS_MAKE_BITMAP_GAD_STR "\x00\x00"
    "\x00\x00\x00\xC2\x00\x84"
    MSG_PREFS_MAKE_BITMAP_HELP_STR "\x00"
    "\x00\x00\x00\xC3\x00\x0E"
    MSG_PREFS_SPARE_MEM_GAD_STR "\x00"
    "\x00\x00\x00\xC4\x00\xB6"
    MSG_PREFS_SPARE_MEM_HELP_STR "\x00\x00"
    "\x00\x00\x00\xC5\x00\x0C"
    MSG_PREFS_UPDATE_TIME_GAD_STR "\x00"
    "\x00\x00\x00\xC6\x00\x36"
    MSG_PREFS_UPDATE_TIME_HELP_STR "\x00\x00"
    "\x00\x00\x00\xC7\x00\x10"
    MSG_PREFS_ICON_REQ_STR "\x00\x00"
    "\x00\x00\x00\xC8\x00\x10"
    MSG_PREFS_DEFICON_REQ_STR "\x00\x00"
    "\x00\x00\x00\xC9\x00\x10"
    MSG_OWNERPW_GAD_STR "\x00\x00"
    "\x00\x00\x00\xCA\x00\x0E"
    MSG_USERPW_GAD_STR "\x00"
    "\x00\x00\x00\xCB\x00\x12"
    MSG_PREFS_EXTOUTLINES_GAD_STR "\x00"
    "\x00\x00\x00\xCC\x00\x4A"
    MSG_PREFS_EXTOUTLINES_HELP_STR "\x00\x00"
    "\x00\x00\x00\xCD\x00\x0E"
    MSG_PREFS_OPENOUTLINES_GAD_STR "\x00"
    "\x00\x00\x00\xCE\x00\x1E"
    MSG_PREFS_OPENOUTLINES_HELP_STR "\x00"
    "\x00\x00\x00\xCF\x00\x0E"
    MSG_DOCPREFS_OUTLINES_GAD_STR "\x00"
    "\x00\x00\x00\xD0\x00\x1E"
    MSG_DOCPREFS_OUTLINES_HELP_STR "\x00"
    "\x00\x00\x03\xE8\x00\x06"
    MSG_ERROR_ERR_STR "\x00"
    "\x00\x00\x03\xE9\x00\x22"
    MSG_REQUIRES_68020_ERR_STR "\x00\x00"
    "\x00\x00\x03\xEA\x00\x24"
    MSG_REQUIRES_3_0_ERR_STR "\x00"
    "\x00\x00\x03\xEB\x00\x22"
    MSG_NO_MUIMASTER_ERR_STR "\x00\x00"
    "\x00\x00\x03\xEC\x00\x1C"
    MSG_CANT_CREATE_CC_ERR_STR "\x00"
    "\x00\x00\x03\xED\x00\x1E"
    MSG_CANT_CREATE_CONFIG_OBJ_ERR_STR "\x00\x00"
    "\x00\x00\x03\xEE\x00\x08"
    MSG_ERROR_HEADER_ERR_STR "\x00"
    "\x00\x00\x03\xEF\x00\x2A"
    MSG_CANT_FIND_MODULE_ERR_STR "\x00"
    "\x00\x00\x03\xF0\x00\x16"
    MSG_CANT_CREATE_SERVER_ERR_STR "\x00"
    "\x00\x00\x03\xF1\x00\x20"
    MSG_SERVER_INIT_ERR_STR "\x00\x00"
    "\x00\x00\x03\xF2\x00\x20"
    MSG_CANT_CREATE_MUI_APP_ERR_STR "\x00\x00"
    "\x00\x00\x03\xF3\x00\x16"
    MSG_CANT_LOAD_DOC_ERR_STR "\x00"
    "\x00\x00\x03\xF4\x00\x14"
    MSG_CANT_SAVE_PREFS_ERR_STR "\x00\x00"
    "\x00\x00\x03\xF5\x00\x0C"
    MSG_SAVE_ERR_STR "\x00"
    "\x00\x00\x03\xF6\x00\x12"
    MSG_CANT_SAVE_ERR_STR "\x00\x00"
    "\x00\x00\x07\xD0\x00\x08"
    MSG_PROJECT_MENU_STR "\x00"
    "\x00\x00\x07\xD1\x00\x0C"
    MSG_ABOUT_MENU_STR "\x00\x00"
    "\x00\x00\x07\xD2\x00\x0E"
    MSG_ABOUT_MUI_MENU_STR "\x00\x00"
    "\x00\x00\x07\xD3\x00\x12"
    MSG_NEW_DOC_MENU_STR "\x00"
    "\x00\x00\x07\xD4\x00\x0C"
    MSG_NEW_VIEW_MENU_STR "\x00\x00"
    "\x00\x00\x07\xD5\x00\x0A"
    MSG_OPEN_MENU_STR "\x00"
    "\x00\x00\x07\xD6\x00\x0E"
    MSG_SAVEAS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xD7\x00\x0C"
    MSG_PRINT_MENU_STR "\x00\x00"
    "\x00\x00\x07\xD8\x00\x08"
    MSG_HIDE_MENU_STR "\x00\x00"
    "\x00\x00\x07\xD9\x00\x08"
    MSG_QUIT_MENU_STR "\x00\x00"
    "\x00\x00\x07\xDA\x00\x06"
    MSG_EDIT_MENU_STR "\x00\x00"
    "\x00\x00\x07\xDB\x00\x08"
    MSG_COPY_MENU_STR "\x00\x00"
    "\x00\x00\x07\xDC\x00\x06"
    MSG_VIEW_MENU_STR "\x00\x00"
    "\x00\x00\x07\xDD\x00\x08"
    MSG_REFRESH_MENU_STR "\x00"
    "\x00\x00\x07\xDE\x00\x08"
    MSG_CROP_MENU_STR "\x00\x00"
    "\x00\x00\x07\xDF\x00\x0A"
    MSG_UNCROP_MENU_STR "\x00\x00"
    "\x00\x00\x07\xE0\x00\x0E"
    MSG_ROTATE_LEFT_MENU_STR "\x00"
    "\x00\x00\x07\xE1\x00\x10"
    MSG_ROTATE_RIGHT_MENU_STR "\x00\x00"
    "\x00\x00\x07\xE2\x00\x10"
    MSG_INFO_MENU_STR "\x00"
    "\x00\x00\x07\xE3\x00\x0C"
    MSG_OUTLINES_MENU_STR "\x00"
    "\x00\x00\x07\xE4\x00\x0A"
    MSG_FONTS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xE5\x00\x0E"
    MSG_ERRORS_LOG_MENU_STR "\x00"
    "\x00\x00\x07\xE6\x00\x0A"
    MSG_SETTINGS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xE7\x00\x14"
    MSG_GLOBAL_SETTINGS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xE8\x00\x16"
    MSG_DOC_SETTINGS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xE9\x00\x08"
    MSG_MUI_MENU_STR "\x00\x00"
    "\x00\x00\x07\xEA\x00\x14"
    MSG_TEXT_AA_MENU_STR "\x00\x00"
    "\x00\x00\x07\xEB\x00\x16"
    MSG_STROKE_AA_MENU_STR "\x00"
    "\x00\x00\x07\xEC\x00\x14"
    MSG_FILL_AA_MENU_STR "\x00"
    "\x00\x00\x07\xED\x00\x10"
    MSG_PDF_OPERATIONS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xEE\x00\x10"
    MSG_SAVE_FILE_TO_MENU_STR "\x00"
    "\x00\x00\x07\xEF\x00\x06"
    MSG_ZOOM_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF0\x00\x08"
    MSG_ADD_ROW_MENU_STR "\x00"
    "\x00\x00\x07\xF1\x00\x0C"
    MSG_ADD_COLUMN_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF2\x00\x0C"
    MSG_REM_ROW_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF3\x00\x0E"
    MSG_REM_COLUMN_MENU_STR "\x00"
    "\x00\x00\x07\xF4\x00\x0C"
    MSG_CONTINUOUS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF5\x00\x0E"
    MSG_DISPLAY_MODE_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF6\x00\x0A"
    MSG_ONE_PASS_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF7\x00\x0C"
    MSG_TEXT_FIRST_MENU_STR "\x00\x00"
    "\x00\x00\x07\xF8\x00\x0C"
    MSG_PROGRESSIVE_MENU_STR "\x00"
    "\x00\x00\x07\xF9\x00\x14"
    MSG_SHOW_NAV_BAR_MENU_STR "\x00"
    "\x00\x00\x07\xFA\x00\x0E"
    MSG_SHOW_TOOL_BAR_MENU_STR "\x00"
    "\x00\x00\x07\xFB\x00\x10"
    MSG_SAVE_FORM_AS_MENU_STR "\x00"
    "\x00\x00\x07\xFC\x00\x14"
    MSG_IMPORT_FDF_MENU_STR "\x00\x00"
    "\x00\x00\x07\xFD\x00\x0C"
    MSG_FULL_SCREEN_MENU_STR "\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};


#ifdef CATCOMP_CODE

STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
LONG   *l;
UWORD  *w;
STRPTR  builtIn;

    l = (LONG *)CatCompBlock;

    while (*l != stringNum)
    {
        w = (UWORD *)((ULONG)l + 4);
        l = (LONG *)((ULONG)l + (ULONG)*w + 6);
    }
    builtIn = (STRPTR)((ULONG)l + 6);

#undef LocaleBase
#define LocaleBase li->li_LocaleBase
    
    if (LocaleBase)
        return(GetCatalogStr(li->li_Catalog,stringNum,builtIn));
#undef LocaleBase

    return(builtIn);
}


#endif /* CATCOMP_CODE */


/****************************************************************************/


#endif /* APDF_MSGS_H */
