# Makefile for Win32

TOP = ..

!include "$(TOP)/names.win"

!include <win32.mak>

SRCS= \
   bounce.c  \
   gamma.c    \
   gears.c    \
   isosurf.c  \
   osdemo.c   \
   reflect.c  \
   spin.c     \
   stex3d.c   \
   test0.c    \
   texobj.c   \
   winpos.c   

EXTRALIBS = $(MESAGL).lib $(MESAGLU).lib $(MESATK).lib $(MESAAUX).lib

!include "$(TOP)/mesawin32.mak"

