# Makefile for demo programs for MS-DOS with DJGPP

##### MACROS #####

INCDIR = ../include

GL_LIBS =  ../lib/tkdos.a ../lib/dosglub.a ../lib/dosaux.a ../lib/dosmesa.a

LIB_DEP = $(GL_LIBS)

PROGS = bounce gears isosurf morph3d reflect spin stex3d texobj winpos 

##### RULES #####

.c: $(LIB_DEP)
	gcc -I$(INCDIR) -O3 -m486 -s $< $(LIB_DEP) -o $@


##### TARGETS #####

default: $(PROGS)

clean:
	del *.

realclean: clean
	del *.exe



