/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER

#include <stdio.h>
#if defined(__SASC) && defined(_AMIGA)
#include <fcntl.h>
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int yywrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
static void yy_push_state YY_PROTO(( int new_state ));
static void yy_pop_state YY_PROTO(( void ));
static int yy_top_state YY_PROTO(( void ));

static void *yy_flex_alloc YY_PROTO(( unsigned int ));
static void *yy_flex_realloc YY_PROTO(( void *, unsigned int ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
#define OUTER 1
#define TYPE 2
#define INNER 3
#define INFRA 4
#define INTER 5
#define INTRA 6
typedef unsigned char YY_CHAR;
typedef int yy_state_type;

#define FLEX_DEBUG
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
extern char *yytext;
#define yytext_ptr yytext

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, const char *, int ));
#endif

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 55
static const short int yy_accept[199] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   55,   53,   49,   50,   53,   52,
       49,   50,   52,   52,    9,   12,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   51,   49,   51,   51,
       51,   26,   23,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   38,   38,   36,   38,   38,   38,   37,   38,
       31,   28,   27,   31,   31,   30,   41,   41,   41,   41,
       41,   41,   44,   49,    0,    0,    0,   13,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   25,   24,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   39,

       32,   35,   37,    0,   33,   28,   29,   41,   41,   41,
       40,   41,   41,    0,    0,   48,    0,    4,   11,   11,
        6,   11,    5,   11,    7,   11,   22,   22,   15,   22,
       22,   22,   14,   22,   34,   41,   41,   41,    0,    0,
       11,   11,   11,   11,    8,   22,   22,   21,   16,   22,
       22,   41,    0,    0,    0,    3,   11,   11,   11,   22,
       22,   22,   22,   41,   41,    0,    0,    0,   11,    2,
       11,   18,   19,   22,   17,   41,   41,    0,    0,   47,
       10,    1,   22,   41,   41,    0,   22,   41,    0,   20,
       41,    0,   41,    0,   41,   46,   41,    0

    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    6,    1,    1,    1,
        1,    1,    7,    1,    1,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,   10,    1,
       11,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       26,   30,   31,   32,   33,   34,   26,   26,   26,   26,
        1,   12,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   26,   30,   31,   32,   33,   34,   26,   26,
       26,   26,   35,    1,   36,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[37] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1
    } ;

static const short int yy_base[210] =
    {   0,
        0,    2,   10,    0,   45,   47,   55,    0,   91,  127,
      103,  112,  163,  199,  355,  356,  352,  349,  344,  356,
      349,  346,  314,  340,  356,  356,    0,  325,  318,  318,
      305,  303,  298,  275,  272,  273,  356,  300,  265,  289,
      291,  356,  356,    0,  268,  279,  278,  277,  266,  275,
      274,  264,  356,  288,  285,  283,  251,  278,    0,  104,
      356,  283,  277,  245,  261,  356,    0,  266,  263,  261,
      257,  235,  356,  262,  241,  259,   90,  356,    0,  229,
      233,  240,  242,  229,  224,  227,  224,  235,  356,  356,
        0,  234,  226,  218,  224,  229,  225,  201,  207,  229,

      356,  356,    0,  194,  356,  227,  356,    0,  226,  205,
        0,   97,  271,  207,  222,  356,  197,    0,  192,  208,
        0,  206,    0,  197,    0,  201,  204,  199,    0,  187,
      191,  196,    0,  185,  356,  189,  114,    0,  119,  180,
      164,  162,  180,  175,    0,  160,  159,    0,    0,  160,
      173,  139,  117,  170,  165,    0,  161,  160,  168,  165,
      164,  163,  156,  121,  161,  149,  158,  153,  129,    0,
      128,    0,    0,  132,    0,  126,  135,  137,  140,  356,
        0,    0,  135,  134,  141,  136,  129,  133,  111,    0,
      110,  111,   40,   22,   21,  356,    0,  356,  307,  311,

      315,  319,  322,  325,    4,  329,  333,  337,  341
    } ;

static const short int yy_def[210] =
    {   0,
      199,  199,  198,    3,  199,  199,  198,    7,  200,  200,
      201,  201,  202,  202,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  198,  198,  198,  198,
      198,  198,  198,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  198,  198,  198,  198,  198,  198,  205,  198,
      198,  198,  198,  198,  198,  198,  206,  206,  206,  206,
      206,  207,  198,  198,  198,  208,  198,  198,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  198,  198,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  198,

      198,  198,  205,  198,  198,  198,  198,  206,  206,  206,
      206,  209,  207,  198,  208,  198,  198,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  204,  204,  204,  204,
      204,  204,  204,  204,  198,  206,  209,  206,  198,  198,
      203,  203,  203,  203,  203,  204,  204,  204,  204,  204,
      204,  206,  198,  198,  198,  203,  203,  203,  203,  204,
      204,  204,  204,  206,  206,  198,  198,  198,  203,  203,
      203,  204,  204,  204,  204,  206,  206,  198,  198,  198,
      203,  203,  204,  206,  206,  198,  204,  206,  198,  204,
      206,  198,  206,  198,  206,  198,  206,    0,  198,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198
    } ;

static const short int yy_nxt[393] =
    {   0,
      198,   17,   18,   17,   18,  103,  198,   19,  198,   19,
       20,   21,   22,   20,   20,   23,   20,   24,   20,   25,
       26,   20,   27,   27,   28,   29,   30,   27,   31,   32,
       27,   33,   27,   27,   27,   27,   27,   27,   34,   27,
       35,   36,   27,   27,   20,   20,   17,   18,   17,   18,
      197,  196,   19,  195,   19,   37,   38,   18,   37,   37,
       39,   40,   41,   37,   42,   43,   37,   44,   44,   44,
       45,   46,   44,   44,   47,   48,   44,   44,   44,   49,
       44,   44,   44,   44,   50,   51,   44,   52,   44,   37,
       37,   53,   54,   55,   53,   56,   57,   53,   58,  138,

       53,   53,   60,   53,   62,   63,  115,  117,   64,  104,
       65,  114,   66,   62,   63,  105,  138,   64,  153,   65,
      153,   66,  164,  115,  194,   53,   53,   53,   54,   55,
       53,   56,   57,   53,   58,  154,   53,   53,   60,   53,
      164,  153,  164,  193,  192,  191,  190,  166,  189,  188,
      187,  176,  186,  185,  184,  165,  154,  165,  183,  182,
      181,   53,   53,   67,   68,   69,   67,   70,   67,   67,
       71,  180,   73,   67,   67,   67,  179,  178,  177,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  163,  162,
      161,  160,  159,  158,  157,  156,  155,   67,   67,   67,

       68,   69,   67,   70,   67,   67,   71,  152,   73,   67,
       67,   67,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  116,  139,  136,  109,  106,  135,
      100,  134,  133,   67,   67,  108,  108,  108,  108,  108,
      108,  108,  108,  132,  131,  108,  108,  108,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  116,  114,   74,  112,  111,  110,  109,   76,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  107,
       75,  108,  108,  108,  106,   76,  102,  101,   75,  100,
       99,   98,   97,   96,   95,   94,   93,   92,   76,   90,

       89,   74,   88,   87,   86,  108,  108,   16,   16,   16,
       16,   59,   59,   59,   59,   61,   61,   61,   61,   72,
       72,   72,   72,   79,   85,   79,   91,   84,   91,  108,
      108,   83,  108,  113,  113,   82,  113,  115,  115,  115,
      115,  137,  137,  137,  137,   81,   80,   76,   78,   77,
       74,   76,   75,   74,  198,   15,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198

    } ;

static const short int yy_chk[393] =
    {   0,
        0,    1,    1,    2,    2,  205,    0,    1,    0,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,    5,    6,    6,
      195,  194,    5,  193,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    9,    9,    9,    9,    9,    9,    9,    9,  112,

        9,    9,    9,    9,   11,   11,  112,   77,   11,   60,
       11,   77,   11,   12,   12,   60,  137,   12,  153,   12,
      139,   12,  164,  137,  192,    9,    9,   10,   10,   10,
       10,   10,   10,   10,   10,  139,   10,   10,   10,   10,
      152,  179,  185,  191,  189,  188,  187,  153,  186,  184,
      183,  164,  178,  177,  176,  152,  179,  185,  174,  171,
      169,   10,   10,   13,   13,   13,   13,   13,   13,   13,
       13,  168,   13,   13,   13,   13,  167,  166,  165,  163,
      162,  161,  160,  159,  158,  157,  155,  154,  151,  150,
      147,  146,  144,  143,  142,  141,  140,   13,   13,   14,

       14,   14,   14,   14,   14,   14,   14,  136,   14,   14,
       14,   14,  134,  132,  131,  130,  128,  127,  126,  124,
      122,  120,  119,  117,  115,  114,  110,  109,  106,  104,
      100,   99,   98,   14,   14,   72,   72,   72,   72,   72,
       72,   72,   72,   97,   96,   72,   72,   72,   95,   94,
       93,   92,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   76,   75,   74,   71,   70,   69,   68,   65,   72,
       72,  113,  113,  113,  113,  113,  113,  113,  113,   64,
       63,  113,  113,  113,   62,   58,   57,   56,   55,   54,
       52,   51,   50,   49,   48,   47,   46,   45,   41,   40,

       39,   38,   36,   35,   34,  113,  113,  199,  199,  199,
      199,  200,  200,  200,  200,  201,  201,  201,  201,  202,
      202,  202,  202,  203,   33,  203,  204,   32,  204,  206,
      206,   31,  206,  207,  207,   30,  207,  208,  208,  208,
      208,  209,  209,  209,  209,   29,   28,   24,   23,   22,
       21,   19,   18,   17,   15,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const short int yy_rule_linenum[54] =
    {   0,
       71,   72,   74,   76,   77,   78,   79,   80,   82,   86,
       87,   88,   89,   91,   92,   93,   94,   95,   96,   97,
       98,   99,  100,  101,  102,  103,  106,  107,  108,  109,
      110,  112,  113,  114,  115,  116,  117,  118,  119,  121,
      122,  123,  124,  125,  126,  128,  129,  131,  133,  134,
      136,  137,  138
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
# line 1 "Lex.l"
# line 3 "Lex.l"
/*
	> FLEX -d -i -I lex.l
	> Dcc lex.yy.c -mD -c
**
    21-08-94 - added FLAG, REFERENCE

*/

#include "Dyn.h"
#include "y.tab.h"

#define VALUE ebody

#define _ESC "\\"
#define _KET "%}"

#define _ERROR 33333
#define ERROR fprintf(stderr, "Scanner Error! line %d\n", lineno); return _ERROR;

int lineno = 0;

#define LINENO getlineno()

#define unget(c) ungetc((c),stdin)

DSTR typename = EmptyDyn;
DSTR structname=EmptyDyn;
DSTR value    = EmptyDyn;
DSTR nodename = EmptyDyn;

/* #define SHOW printf ("<%s>\n", yytext); */
#define SHOW ;

char lline[256];
char *getlineno(void) {
    sprintf (lline, "\n#line %d \"%s\"\n\t", lineno+1, "STDIN");
    return "\t"; /* Das sieht mit #line _echt_ _haesslich_ aus */
}
/* HELP_STR  (([?]) | ([Hh][Ee][Ll][Pp])) */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

# line 69 "Lex.l"



	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 199 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 356 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 54 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 54 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 55 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_USER_ACTION
# line 71 "Lex.l"
{		   SHOW; return PROJECT; }
	YY_BREAK
case 2:
YY_USER_ACTION
# line 72 "Lex.l"
{		   SHOW; return GLOBAL; }
	YY_BREAK
case 3:
YY_USER_ACTION
# line 74 "Lex.l"
{		   SHOW; return CONST; }
	YY_BREAK
case 4:
YY_USER_ACTION
# line 76 "Lex.l"
{		   SHOW; return BIT; }
	YY_BREAK
case 5:
YY_USER_ACTION
# line 77 "Lex.l"
{		   SHOW; return INT; }
	YY_BREAK
case 6:
YY_USER_ACTION
# line 78 "Lex.l"
{		   SHOW; return FUNC; }
	YY_BREAK
case 7:
YY_USER_ACTION
# line 79 "Lex.l"
{		   SHOW; return STRING; }
	YY_BREAK
case 8:
YY_USER_ACTION
# line 80 "Lex.l"
{		   SHOW; return TREE; }
	YY_BREAK
case 9:
YY_USER_ACTION
# line 82 "Lex.l"
{		   SHOW; return SEMI; }
	YY_BREAK
case 10:
YY_USER_ACTION
# line 86 "Lex.l"
{	     ECHO; SHOW;			      return DEFAULT; }
	YY_BREAK
case 11:
YY_USER_ACTION
# line 87 "Lex.l"
{		   SHOW; yylval = (int)strdup(yytext); return OUTER_LABEL; }
	YY_BREAK
case 12:
YY_USER_ACTION
# line 88 "Lex.l"
{		   SHOW;			      return ASS; }
	YY_BREAK
case 13:
YY_USER_ACTION
# line 89 "Lex.l"
{ BEGIN INNER; SHOW;			      return BRA; }
	YY_BREAK
case 14:
YY_USER_ACTION
# line 91 "Lex.l"
{		   SHOW;			      return SET; }
	YY_BREAK
case 15:
YY_USER_ACTION
# line 92 "Lex.l"
{		   SHOW;			      return GET; }
	YY_BREAK
case 16:
YY_USER_ACTION
# line 93 "Lex.l"
{		   SHOW;			      return LOCK; }
	YY_BREAK
case 17:
YY_USER_ACTION
# line 94 "Lex.l"
{		   SHOW;			      return UNLOCK; }
	YY_BREAK
case 18:
YY_USER_ACTION
# line 95 "Lex.l"
{		   SHOW;			      return CREATE; }
	YY_BREAK
case 19:
YY_USER_ACTION
# line 96 "Lex.l"
{		   SHOW;			      return DELETE; }
	YY_BREAK
case 20:
YY_USER_ACTION
# line 97 "Lex.l"
{		   SHOW;			      return REFERENCE; }
	YY_BREAK
case 21:
YY_USER_ACTION
# line 98 "Lex.l"
{		   SHOW;			      return HELP; }
	YY_BREAK
case 22:
YY_USER_ACTION
# line 99 "Lex.l"
{		   SHOW; yylval = (int)strdup(yytext); return INNER_LABEL; }
	YY_BREAK
case 23:
YY_USER_ACTION
# line 100 "Lex.l"
{ BEGIN INTER; SHOW; DynClear(&value);            return ASS; }
	YY_BREAK
case 24:
YY_USER_ACTION
# line 101 "Lex.l"
{ BEGIN INTER; SHOW; DynClear(&value);            return ADD; }
	YY_BREAK
case 25:
YY_USER_ACTION
# line 102 "Lex.l"
{ BEGIN OUTER; SHOW;			      return KET; }
	YY_BREAK
case 26:
YY_USER_ACTION
# line 103 "Lex.l"
{		   SHOW;			      return SEMI; }
	YY_BREAK
case 27:
YY_USER_ACTION
# line 106 "Lex.l"
{ ++lineno; }
	YY_BREAK
case 28:
YY_USER_ACTION
# line 107 "Lex.l"
{ }
	YY_BREAK
case 29:
YY_USER_ACTION
# line 108 "Lex.l"
{ BEGIN INFRA; SHOW; DynSet(&value, 1, LINENO);               }
	YY_BREAK
case 30:
YY_USER_ACTION
# line 109 "Lex.l"
{ BEGIN INNER; SHOW;			    return SEMI;  }
	YY_BREAK
case 31:
YY_USER_ACTION
# line 110 "Lex.l"
{ BEGIN INTRA;	 DynSet(&value, 2, LINENO, yytext);       }
	YY_BREAK
case 32:
YY_USER_ACTION
# line 112 "Lex.l"
{		   SHOW; DynAppend(&value, 1, "value"); }
	YY_BREAK
case 33:
YY_USER_ACTION
# line 113 "Lex.l"
{		   SHOW; DynAppend(&value, 1, _ESC);    }
	YY_BREAK
case 34:
YY_USER_ACTION
# line 114 "Lex.l"
{		   SHOW; DynAppend(&value, 1, _KET);    }
	YY_BREAK
case 35:
YY_USER_ACTION
# line 115 "Lex.l"
{ BEGIN INTER; SHOW; yylval = (int)strdup(DynValue(&value)); return VALUE;  }
	YY_BREAK
case 36:
YY_USER_ACTION
# line 116 "Lex.l"
{ ++ lineno;   SHOW  DynAppend(&value, 1, yytext); }
	YY_BREAK
case 37:
YY_USER_ACTION
# line 117 "Lex.l"
{		   SHOW; DynAppend(&value, 1, yytext); }
	YY_BREAK
case 38:
YY_USER_ACTION
# line 118 "Lex.l"
{		   SHOW; DynAppend(&value, 1, yytext);  }
	YY_BREAK
case 39:
YY_USER_ACTION
# line 119 "Lex.l"
{		   SHOW; DynAppend(&value, 1, yytext);  }
	YY_BREAK
case 40:
YY_USER_ACTION
# line 121 "Lex.l"
{		   SHOW; DynAppend(&value, 1, "value"); }
	YY_BREAK
case 41:
YY_USER_ACTION
# line 122 "Lex.l"
{ BEGIN INNER; SHOW; DynAppend(&value, 1, yytext); yylval = (int)strdup(DynValue(&value)); return VALUE; }
	YY_BREAK
case 42:
YY_USER_ACTION
# line 123 "Lex.l"
{ ++ lineno;   SHOW  DynAppend(&value, 1, yytext); }
	YY_BREAK
case 43:
YY_USER_ACTION
# line 124 "Lex.l"
{		   SHOW; DynAppend(&value, 1, yytext); }
	YY_BREAK
case 44:
YY_USER_ACTION
# line 125 "Lex.l"
{		   SHOW; DynAppend(&value, 1, yytext); }
	YY_BREAK
case 45:
YY_USER_ACTION
# line 126 "Lex.l"
{		   SHOW; DynAppend(&value, 1, yytext);  }
	YY_BREAK
case 46:
YY_USER_ACTION
# line 128 "Lex.l"
{ BEGIN OUTER; lineno ++; }
	YY_BREAK
case 47:
YY_USER_ACTION
# line 129 "Lex.l"
{ BEGIN 0;	   lineno ++; return 0; }
	YY_BREAK
case 48:
YY_USER_ACTION
# line 131 "Lex.l"
{ ++lineno; /* Kommentare */ }
	YY_BREAK
case 49:
YY_USER_ACTION
# line 133 "Lex.l"
{  }
	YY_BREAK
case 50:
YY_USER_ACTION
# line 134 "Lex.l"
{ ++lineno; }
	YY_BREAK
case 51:
YY_USER_ACTION
# line 136 "Lex.l"
{		   SHOW; ERROR; }
	YY_BREAK
case 52:
YY_USER_ACTION
# line 137 "Lex.l"
{		   SHOW; ERROR; }
	YY_BREAK
case 53:
YY_USER_ACTION
# line 138 "Lex.l"
{ /* C-source ... nop */ }
	YY_BREAK
case 54:
YY_USER_ACTION
# line 140 "Lex.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(OUTER):
case YY_STATE_EOF(TYPE):
case YY_STATE_EOF(INNER):
case YY_STATE_EOF(INFRA):
case YY_STATE_EOF(INTER):
case YY_STATE_EOF(INTRA):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
							yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 199 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 199 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 198);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;


	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

	b->yy_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_buffer_status = YY_BUFFER_NEW;
	}


#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		int new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}


static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, const char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( unsigned int size )
#else
static void *yy_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, unsigned int size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 140 "Lex.l"


/*
[;]		    { BEGIN OUTER; SHOW; }
.		    { SHOW; ERROR; }
<OUTER>[\t ]	    { ; }
<OUTER>[\n]	    { ++ lineno; }
<OUTER>.	    { SHOW; ERROR; }
<TYPE>[\t ]	    { ; }
<TYPE>[\n]	    { ++ lineno; }
<TYPE>. 	    { SHOW; ERROR; }
<INNER>[\t ]	    { ; }
<INNER>[\n]	    { ++ lineno; }

<OUTER>PSEUDO	    {		   SHOW; return PSEUDO; }

<OUTER>WORD	    {		   SHOW; return WORD; }
<OUTER>UWORD	    {		   SHOW; return UWORD; }
<OUTER>LONG	    {		   SHOW; return LONG; }
<OUTER>ULONG	    {		   SHOW; return ULONG; }
<OUTER>STRING	    {		   SHOW; return STRING; }
<OUTER>STRUCT	    { BEGIN TYPE;  SHOW; return STRUCT; }
<TYPE>{LABEL}	    { BEGIN OUTER; SHOW; DynSet(&typename, 1, yytext);   return TYPE_LABEL; }

<OUTER>[*]	    {		   SHOW;				 return POINTER; }

   Nach Assign sind wir in INTER,
   das ueberprueft, ob eine Klammer folgt -> INFRA,
		       ein Semikolon	  -> INNER,
		 oder ein anderes Zeichen -> INTRA

<INNER>{FLG_STR}    {		   SHOW;			      return FLAGS; }

 */
