
OBJS = \
	initmem.o		\
	malloc.o			\
	realloc.o		\
	free.o			\
	new.o				\
	delete.o			\
	virtual.o		\
	strcpy.o			\
	strncpy.o		\
	strcat.o			\
	strncat.o		\
	strcmp.o			\
	stricmp.o		\
	strncmp.o		\
	strnicmp.o		\
	strchr.o			\
	strlen.o			\
	bzero.o			\
	memset.o			\
	memcpy.o			\
	memmove.o		\
	memcmp.o			\
	bcopy.o			\
	DoMethod.o		\
	DoSuperMethod.o\
	udiv6432.o		\
	div6432.o		\
	udiv64.o			\
	div64.o			\
	abort.o			\
	umod64.o			\
	mod64.o			\
	shl64.o			\
	shr64.o			\
	slab.o			\
	StartCode.o		\
	request.o
	
Program			= libC.a

TARGETS			= os3 morphos os4 aros
OBJDIRS			= 
MAKEDIRS			= 
CCFLAGS			= -O3 -fregmove
INSTALLDIR		= ../lib

NOLINK			= 0
BUILD_LIBRARY	= 1

	include ../Makefile.mk
