/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "PopPreParse"
#define F_CLASS_VERSION                         1
#define F_CLASS_REVISION                        2
#define F_CLASS_VERSION_STRING                  "01.02 (2005/08/10)"

#include <feelin/class_startup.c>

#include "Private.h"