/* autogenerated by bdf2c!  do not edit */

/* "Copyright (c) 1984, 1987 Adobe Systems Incorporated. All Rights Reserved. Copyright (c) 1988, 1991 Digital Equipment Corporation. All Rights Reserved." */


#include "internal.h"
/*
typedef struct {
   int width, height;
   int xorig, yorig;
   int xmove;
   const unsigned char *bitmap;
} GLUTBitmapChar;

typedef struct {
   const char *name;
   int height;
   int num;
   const GLUTBitmapChar *const *table;
} GLUTBitmapFont;
*/


static const unsigned char hel12_ch32data[] = {
   0x0
};
static const GLUTBitmapChar hel12_ch32 = { 1, 1, 0, 0, 4, hel12_ch32data };

static const unsigned char hel12_ch33data[] = {
   0x80,0x0,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar hel12_ch33 = { 1, 9, -1, 0, 3, hel12_ch33data };

static const unsigned char hel12_ch34data[] = {
   0xa0,0xa0,0xa0
};
static const GLUTBitmapChar hel12_ch34 = { 3, 3, -1, -6, 5, hel12_ch34data };

static const unsigned char hel12_ch35data[] = {
   0x50,0x50,0x50,0xfc,0x28,0xfc,0x28,0x28
};
static const GLUTBitmapChar hel12_ch35 = { 6, 8, 0, 0, 7, hel12_ch35data };

static const unsigned char hel12_ch36data[] = {
   0x20,0x70,0xa8,0xa8,0x28,0x70,0xa0,0xa8,0x70,0x20
};
static const GLUTBitmapChar hel12_ch36 = { 5, 10, -1, 1, 7, hel12_ch36data };

static const unsigned char hel12_ch37data[] = {
   0x23,0x0,0x14,0x80,0x14,0x80,0x13,0x0,0x8,0x0,0x68,0x0,0x94,0x0,0x94,0x0,
   0x62,0x0
};
static const GLUTBitmapChar hel12_ch37 = { 9, 9, -1, 0, 11, hel12_ch37data };

static const unsigned char hel12_ch38data[] = {
   0x72,0x8c,0x84,0x8a,0x50,0x30,0x48,0x48,0x30
};
static const GLUTBitmapChar hel12_ch38 = { 7, 9, -1, 0, 9, hel12_ch38data };

static const unsigned char hel12_ch39data[] = {
   0x80,0x40,0xc0
};
static const GLUTBitmapChar hel12_ch39 = { 2, 3, -1, -6, 3, hel12_ch39data };

static const unsigned char hel12_ch40data[] = {
   0x20,0x40,0x40,0x80,0x80,0x80,0x80,0x80,0x80,0x40,0x40,0x20
};
static const GLUTBitmapChar hel12_ch40 = { 3, 12, -1, 3, 4, hel12_ch40data };

static const unsigned char hel12_ch41data[] = {
   0x80,0x40,0x40,0x20,0x20,0x20,0x20,0x20,0x20,0x40,0x40,0x80
};
static const GLUTBitmapChar hel12_ch41 = { 3, 12, 0, 3, 4, hel12_ch41data };

static const unsigned char hel12_ch42data[] = {
   0xa0,0x40,0xa0
};
static const GLUTBitmapChar hel12_ch42 = { 3, 3, -1, -6, 5, hel12_ch42data };

static const unsigned char hel12_ch43data[] = {
   0x20,0x20,0xf8,0x20,0x20
};
static const GLUTBitmapChar hel12_ch43 = { 5, 5, -1, -1, 7, hel12_ch43data };

static const unsigned char hel12_ch44data[] = {
   0x80,0x40,0x40
};
static const GLUTBitmapChar hel12_ch44 = { 2, 3, -1, 2, 4, hel12_ch44data };

static const unsigned char hel12_ch45data[] = {
   0xf8
};
static const GLUTBitmapChar hel12_ch45 = { 5, 1, -1, -3, 8, hel12_ch45data };

static const unsigned char hel12_ch46data[] = {
   0x80
};
static const GLUTBitmapChar hel12_ch46 = { 1, 1, -1, 0, 3, hel12_ch46data };

static const unsigned char hel12_ch47data[] = {
   0x80,0x80,0x40,0x40,0x40,0x20,0x20,0x10,0x10
};
static const GLUTBitmapChar hel12_ch47 = { 4, 9, 0, 0, 4, hel12_ch47data };

static const unsigned char hel12_ch48data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch48 = { 5, 9, -1, 0, 7, hel12_ch48data };

static const unsigned char hel12_ch49data[] = {
   0x20,0x20,0x20,0x20,0x20,0x20,0x20,0xe0,0x20
};
static const GLUTBitmapChar hel12_ch49 = { 3, 9, -1, 0, 7, hel12_ch49data };

static const unsigned char hel12_ch50data[] = {
   0xf8,0x80,0x80,0x40,0x20,0x10,0x8,0x88,0x70
};
static const GLUTBitmapChar hel12_ch50 = { 5, 9, -1, 0, 7, hel12_ch50data };

static const unsigned char hel12_ch51data[] = {
   0x70,0x88,0x88,0x8,0x8,0x30,0x8,0x88,0x70
};
static const GLUTBitmapChar hel12_ch51 = { 5, 9, -1, 0, 7, hel12_ch51data };

static const unsigned char hel12_ch52data[] = {
   0x8,0x8,0xfc,0x88,0x48,0x28,0x28,0x18,0x8
};
static const GLUTBitmapChar hel12_ch52 = { 6, 9, 0, 0, 7, hel12_ch52data };

static const unsigned char hel12_ch53data[] = {
   0x70,0x88,0x88,0x8,0x8,0xf0,0x80,0x80,0xf8
};
static const GLUTBitmapChar hel12_ch53 = { 5, 9, -1, 0, 7, hel12_ch53data };

static const unsigned char hel12_ch54data[] = {
   0x70,0x88,0x88,0x88,0xc8,0xb0,0x80,0x88,0x70
};
static const GLUTBitmapChar hel12_ch54 = { 5, 9, -1, 0, 7, hel12_ch54data };

static const unsigned char hel12_ch55data[] = {
   0x40,0x40,0x20,0x20,0x20,0x10,0x10,0x8,0xf8
};
static const GLUTBitmapChar hel12_ch55 = { 5, 9, -1, 0, 7, hel12_ch55data };

static const unsigned char hel12_ch56data[] = {
   0x70,0x88,0x88,0x88,0x88,0x70,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch56 = { 5, 9, -1, 0, 7, hel12_ch56data };

static const unsigned char hel12_ch57data[] = {
   0x70,0x88,0x8,0x8,0x78,0x88,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch57 = { 5, 9, -1, 0, 7, hel12_ch57data };

static const unsigned char hel12_ch58data[] = {
   0x80,0x0,0x0,0x0,0x0,0x80
};
static const GLUTBitmapChar hel12_ch58 = { 1, 6, -1, 0, 3, hel12_ch58data };

static const unsigned char hel12_ch59data[] = {
   0x80,0x40,0x40,0x0,0x0,0x0,0x0,0x40
};
static const GLUTBitmapChar hel12_ch59 = { 2, 8, 0, 2, 3, hel12_ch59data };

static const unsigned char hel12_ch60data[] = {
   0xc,0x30,0xc0,0x30,0xc
};
static const GLUTBitmapChar hel12_ch60 = { 6, 5, 0, -1, 7, hel12_ch60data };

static const unsigned char hel12_ch61data[] = {
   0xf8,0x0,0xf8
};
static const GLUTBitmapChar hel12_ch61 = { 5, 3, -1, -2, 7, hel12_ch61data };

static const unsigned char hel12_ch62data[] = {
   0xc0,0x30,0xc,0x30,0xc0
};
static const GLUTBitmapChar hel12_ch62 = { 6, 5, -1, -1, 7, hel12_ch62data };

static const unsigned char hel12_ch63data[] = {
   0x20,0x0,0x20,0x20,0x10,0x10,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch63 = { 5, 9, -1, 0, 7, hel12_ch63data };

static const unsigned char hel12_ch64data[] = {
   0x3e,0x0,0x40,0x0,0x9b,0x0,0xa6,0x80,0xa2,0x40,0xa2,0x40,0x92,0x40,0x4d,0x40,
   0x60,0x80,0x1f,0x0
};
static const GLUTBitmapChar hel12_ch64 = { 10, 10, -1, 1, 12, hel12_ch64data };

static const unsigned char hel12_ch65data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x28,0x10
};
static const GLUTBitmapChar hel12_ch65 = { 7, 9, -1, 0, 9, hel12_ch65data };

static const unsigned char hel12_ch66data[] = {
   0xf8,0x84,0x84,0x84,0xf8,0x84,0x84,0x84,0xf8
};
static const GLUTBitmapChar hel12_ch66 = { 6, 9, -1, 0, 8, hel12_ch66data };

static const unsigned char hel12_ch67data[] = {
   0x3c,0x42,0x80,0x80,0x80,0x80,0x80,0x42,0x3c
};
static const GLUTBitmapChar hel12_ch67 = { 7, 9, -1, 0, 9, hel12_ch67data };

static const unsigned char hel12_ch68data[] = {
   0xf8,0x84,0x82,0x82,0x82,0x82,0x82,0x84,0xf8
};
static const GLUTBitmapChar hel12_ch68 = { 7, 9, -1, 0, 9, hel12_ch68data };

static const unsigned char hel12_ch69data[] = {
   0xfc,0x80,0x80,0x80,0xfc,0x80,0x80,0x80,0xfc
};
static const GLUTBitmapChar hel12_ch69 = { 6, 9, -1, 0, 8, hel12_ch69data };

static const unsigned char hel12_ch70data[] = {
   0x80,0x80,0x80,0x80,0xf8,0x80,0x80,0x80,0xfc
};
static const GLUTBitmapChar hel12_ch70 = { 6, 9, -1, 0, 8, hel12_ch70data };

static const unsigned char hel12_ch71data[] = {
   0x3a,0x46,0x82,0x82,0x8e,0x80,0x80,0x42,0x3c
};
static const GLUTBitmapChar hel12_ch71 = { 7, 9, -1, 0, 9, hel12_ch71data };

static const unsigned char hel12_ch72data[] = {
   0x82,0x82,0x82,0x82,0xfe,0x82,0x82,0x82,0x82
};
static const GLUTBitmapChar hel12_ch72 = { 7, 9, -1, 0, 9, hel12_ch72data };

static const unsigned char hel12_ch73data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar hel12_ch73 = { 1, 9, -1, 0, 3, hel12_ch73data };

static const unsigned char hel12_ch74data[] = {
   0x70,0x88,0x88,0x8,0x8,0x8,0x8,0x8,0x8
};
static const GLUTBitmapChar hel12_ch74 = { 5, 9, -1, 0, 7, hel12_ch74data };

static const unsigned char hel12_ch75data[] = {
   0x82,0x84,0x88,0x90,0xe0,0xa0,0x90,0x88,0x84
};
static const GLUTBitmapChar hel12_ch75 = { 7, 9, -1, 0, 8, hel12_ch75data };

static const unsigned char hel12_ch76data[] = {
   0xf8,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar hel12_ch76 = { 5, 9, -1, 0, 7, hel12_ch76data };

static const unsigned char hel12_ch77data[] = {
   0x88,0x80,0x88,0x80,0x94,0x80,0x94,0x80,0xa2,0x80,0xa2,0x80,0xc1,0x80,0xc1,0x80,
   0x80,0x80
};
static const GLUTBitmapChar hel12_ch77 = { 9, 9, -1, 0, 11, hel12_ch77data };

static const unsigned char hel12_ch78data[] = {
   0x82,0x86,0x8a,0x8a,0x92,0xa2,0xa2,0xc2,0x82
};
static const GLUTBitmapChar hel12_ch78 = { 7, 9, -1, 0, 9, hel12_ch78data };

static const unsigned char hel12_ch79data[] = {
   0x3c,0x42,0x81,0x81,0x81,0x81,0x81,0x42,0x3c
};
static const GLUTBitmapChar hel12_ch79 = { 8, 9, -1, 0, 10, hel12_ch79data };

static const unsigned char hel12_ch80data[] = {
   0x80,0x80,0x80,0x80,0xf8,0x84,0x84,0x84,0xf8
};
static const GLUTBitmapChar hel12_ch80 = { 6, 9, -1, 0, 8, hel12_ch80data };

static const unsigned char hel12_ch81data[] = {
   0x3d,0x42,0x85,0x89,0x81,0x81,0x81,0x42,0x3c
};
static const GLUTBitmapChar hel12_ch81 = { 8, 9, -1, 0, 10, hel12_ch81data };

static const unsigned char hel12_ch82data[] = {
   0x84,0x84,0x84,0x88,0xf8,0x84,0x84,0x84,0xf8
};
static const GLUTBitmapChar hel12_ch82 = { 6, 9, -1, 0, 8, hel12_ch82data };

static const unsigned char hel12_ch83data[] = {
   0x78,0x84,0x84,0x4,0x18,0x60,0x80,0x84,0x78
};
static const GLUTBitmapChar hel12_ch83 = { 6, 9, -1, 0, 8, hel12_ch83data };

static const unsigned char hel12_ch84data[] = {
   0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0xfe
};
static const GLUTBitmapChar hel12_ch84 = { 7, 9, 0, 0, 7, hel12_ch84data };

static const unsigned char hel12_ch85data[] = {
   0x78,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x84
};
static const GLUTBitmapChar hel12_ch85 = { 6, 9, -1, 0, 8, hel12_ch85data };

static const unsigned char hel12_ch86data[] = {
   0x10,0x10,0x28,0x28,0x44,0x44,0x44,0x82,0x82
};
static const GLUTBitmapChar hel12_ch86 = { 7, 9, -1, 0, 9, hel12_ch86data };

static const unsigned char hel12_ch87data[] = {
   0x22,0x0,0x22,0x0,0x22,0x0,0x55,0x0,0x55,0x0,0x49,0x0,0x88,0x80,0x88,0x80,
   0x88,0x80
};
static const GLUTBitmapChar hel12_ch87 = { 9, 9, -1, 0, 11, hel12_ch87data };

static const unsigned char hel12_ch88data[] = {
   0x82,0x44,0x44,0x28,0x10,0x28,0x44,0x44,0x82
};
static const GLUTBitmapChar hel12_ch88 = { 7, 9, -1, 0, 9, hel12_ch88data };

static const unsigned char hel12_ch89data[] = {
   0x10,0x10,0x10,0x10,0x28,0x44,0x44,0x82,0x82
};
static const GLUTBitmapChar hel12_ch89 = { 7, 9, -1, 0, 9, hel12_ch89data };

static const unsigned char hel12_ch90data[] = {
   0xfe,0x80,0x40,0x20,0x10,0x8,0x4,0x2,0xfe
};
static const GLUTBitmapChar hel12_ch90 = { 7, 9, -1, 0, 9, hel12_ch90data };

static const unsigned char hel12_ch91data[] = {
   0xc0,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0xc0
};
static const GLUTBitmapChar hel12_ch91 = { 2, 12, -1, 3, 3, hel12_ch91data };

static const unsigned char hel12_ch92data[] = {
   0x10,0x10,0x20,0x20,0x20,0x40,0x40,0x80,0x80
};
static const GLUTBitmapChar hel12_ch92 = { 4, 9, 0, 0, 4, hel12_ch92data };

static const unsigned char hel12_ch93data[] = {
   0xc0,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0xc0
};
static const GLUTBitmapChar hel12_ch93 = { 2, 12, 0, 3, 3, hel12_ch93data };

static const unsigned char hel12_ch94data[] = {
   0x88,0x50,0x20
};
static const GLUTBitmapChar hel12_ch94 = { 5, 3, 0, -5, 6, hel12_ch94data };

static const unsigned char hel12_ch95data[] = {
   0xfe
};
static const GLUTBitmapChar hel12_ch95 = { 7, 1, 0, 2, 7, hel12_ch95data };

static const unsigned char hel12_ch96data[] = {
   0xc0,0x80,0x40
};
static const GLUTBitmapChar hel12_ch96 = { 2, 3, 0, -6, 3, hel12_ch96data };

static const unsigned char hel12_ch97data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70
};
static const GLUTBitmapChar hel12_ch97 = { 6, 7, -1, 0, 7, hel12_ch97data };

static const unsigned char hel12_ch98data[] = {
   0xb0,0xc8,0x88,0x88,0x88,0xc8,0xb0,0x80,0x80
};
static const GLUTBitmapChar hel12_ch98 = { 5, 9, -1, 0, 7, hel12_ch98data };

static const unsigned char hel12_ch99data[] = {
   0x70,0x88,0x80,0x80,0x80,0x88,0x70
};
static const GLUTBitmapChar hel12_ch99 = { 5, 7, -1, 0, 7, hel12_ch99data };

static const unsigned char hel12_ch100data[] = {
   0x68,0x98,0x88,0x88,0x88,0x98,0x68,0x8,0x8
};
static const GLUTBitmapChar hel12_ch100 = { 5, 9, -1, 0, 7, hel12_ch100data };

static const unsigned char hel12_ch101data[] = {
   0x70,0x88,0x80,0xf8,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch101 = { 5, 7, -1, 0, 7, hel12_ch101data };

static const unsigned char hel12_ch102data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0xe0,0x40,0x30
};
static const GLUTBitmapChar hel12_ch102 = { 4, 9, 0, 0, 3, hel12_ch102data };

static const unsigned char hel12_ch103data[] = {
   0x70,0x88,0x8,0x68,0x98,0x88,0x88,0x88,0x98,0x68
};
static const GLUTBitmapChar hel12_ch103 = { 5, 10, -1, 3, 7, hel12_ch103data };

static const unsigned char hel12_ch104data[] = {
   0x88,0x88,0x88,0x88,0x88,0xc8,0xb0,0x80,0x80
};
static const GLUTBitmapChar hel12_ch104 = { 5, 9, -1, 0, 7, hel12_ch104data };

static const unsigned char hel12_ch105data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x0,0x80
};
static const GLUTBitmapChar hel12_ch105 = { 1, 9, -1, 0, 3, hel12_ch105data };

static const unsigned char hel12_ch106data[] = {
   0x80,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0x40
};
static const GLUTBitmapChar hel12_ch106 = { 2, 12, 0, 3, 3, hel12_ch106data };

static const unsigned char hel12_ch107data[] = {
   0x88,0x90,0xa0,0xc0,0xc0,0xa0,0x90,0x80,0x80
};
static const GLUTBitmapChar hel12_ch107 = { 5, 9, -1, 0, 6, hel12_ch107data };

static const unsigned char hel12_ch108data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar hel12_ch108 = { 1, 9, -1, 0, 3, hel12_ch108data };

static const unsigned char hel12_ch109data[] = {
   0x92,0x92,0x92,0x92,0x92,0xda,0xa4
};
static const GLUTBitmapChar hel12_ch109 = { 7, 7, -1, 0, 9, hel12_ch109data };

static const unsigned char hel12_ch110data[] = {
   0x88,0x88,0x88,0x88,0x88,0xc8,0xb0
};
static const GLUTBitmapChar hel12_ch110 = { 5, 7, -1, 0, 7, hel12_ch110data };

static const unsigned char hel12_ch111data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch111 = { 5, 7, -1, 0, 7, hel12_ch111data };

static const unsigned char hel12_ch112data[] = {
   0x80,0x80,0x80,0xb0,0xc8,0x88,0x88,0x88,0xc8,0xb0
};
static const GLUTBitmapChar hel12_ch112 = { 5, 10, -1, 3, 7, hel12_ch112data };

static const unsigned char hel12_ch113data[] = {
   0x8,0x8,0x8,0x68,0x98,0x88,0x88,0x88,0x98,0x68
};
static const GLUTBitmapChar hel12_ch113 = { 5, 10, -1, 3, 7, hel12_ch113data };

static const unsigned char hel12_ch114data[] = {
   0x80,0x80,0x80,0x80,0x80,0xc0,0xa0
};
static const GLUTBitmapChar hel12_ch114 = { 3, 7, -1, 0, 4, hel12_ch114data };

static const unsigned char hel12_ch115data[] = {
   0x60,0x90,0x10,0x60,0x80,0x90,0x60
};
static const GLUTBitmapChar hel12_ch115 = { 4, 7, -1, 0, 6, hel12_ch115data };

static const unsigned char hel12_ch116data[] = {
   0x60,0x40,0x40,0x40,0x40,0x40,0xe0,0x40,0x40
};
static const GLUTBitmapChar hel12_ch116 = { 3, 9, 0, 0, 3, hel12_ch116data };

static const unsigned char hel12_ch117data[] = {
   0x68,0x98,0x88,0x88,0x88,0x88,0x88
};
static const GLUTBitmapChar hel12_ch117 = { 5, 7, -1, 0, 7, hel12_ch117data };

static const unsigned char hel12_ch118data[] = {
   0x20,0x20,0x50,0x50,0x88,0x88,0x88
};
static const GLUTBitmapChar hel12_ch118 = { 5, 7, -1, 0, 7, hel12_ch118data };

static const unsigned char hel12_ch119data[] = {
   0x22,0x0,0x22,0x0,0x55,0x0,0x49,0x0,0x49,0x0,0x88,0x80,0x88,0x80
};
static const GLUTBitmapChar hel12_ch119 = { 9, 7, 0, 0, 9, hel12_ch119data };

static const unsigned char hel12_ch120data[] = {
   0x84,0x84,0x48,0x30,0x30,0x48,0x84
};
static const GLUTBitmapChar hel12_ch120 = { 6, 7, 0, 0, 6, hel12_ch120data };

static const unsigned char hel12_ch121data[] = {
   0x80,0x40,0x20,0x20,0x50,0x50,0x90,0x88,0x88,0x88
};
static const GLUTBitmapChar hel12_ch121 = { 5, 10, -1, 3, 7, hel12_ch121data };

static const unsigned char hel12_ch122data[] = {
   0xf0,0x80,0x40,0x40,0x20,0x10,0xf0
};
static const GLUTBitmapChar hel12_ch122 = { 4, 7, -1, 0, 6, hel12_ch122data };

static const unsigned char hel12_ch123data[] = {
   0x30,0x40,0x40,0x40,0x40,0x40,0x80,0x40,0x40,0x40,0x40,0x30
};
static const GLUTBitmapChar hel12_ch123 = { 4, 12, 0, 3, 4, hel12_ch123data };

static const unsigned char hel12_ch124data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar hel12_ch124 = { 1, 12, -1, 3, 3, hel12_ch124data };

static const unsigned char hel12_ch125data[] = {
   0xc0,0x20,0x20,0x20,0x20,0x20,0x10,0x20,0x20,0x20,0x20,0xc0
};
static const GLUTBitmapChar hel12_ch125 = { 4, 12, 0, 3, 4, hel12_ch125data };

static const unsigned char hel12_ch126data[] = {
   0x98,0x64
};
static const GLUTBitmapChar hel12_ch126 = { 6, 2, 0, -3, 7, hel12_ch126data };

static const unsigned char hel12_ch160data[] = {
   0x0
};
static const GLUTBitmapChar hel12_ch160 = { 1, 1, 0, 0, 4, hel12_ch160data };

static const unsigned char hel12_ch161data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x0,0x80
};
static const GLUTBitmapChar hel12_ch161 = { 1, 10, -1, 3, 3, hel12_ch161data };

static const unsigned char hel12_ch162data[] = {
   0x40,0x70,0xc8,0xa0,0xa0,0xa0,0xa8,0x70,0x10
};
static const GLUTBitmapChar hel12_ch162 = { 5, 9, -1, 1, 7, hel12_ch162data };

static const unsigned char hel12_ch163data[] = {
   0xb0,0x48,0x20,0x20,0xf0,0x40,0x40,0x48,0x30
};
static const GLUTBitmapChar hel12_ch163 = { 5, 9, -1, 0, 7, hel12_ch163data };

static const unsigned char hel12_ch164data[] = {
   0x84,0x78,0x48,0x48,0x78,0x84
};
static const GLUTBitmapChar hel12_ch164 = { 6, 6, 0, -1, 7, hel12_ch164data };

static const unsigned char hel12_ch165data[] = {
   0x20,0x20,0xf8,0x20,0xf8,0x20,0x50,0x88,0x88
};
static const GLUTBitmapChar hel12_ch165 = { 5, 9, -1, 0, 7, hel12_ch165data };

static const unsigned char hel12_ch166data[] = {
   0x80,0x80,0x80,0x80,0x0,0x0,0x0,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar hel12_ch166 = { 1, 11, -1, 2, 3, hel12_ch166data };

static const unsigned char hel12_ch167data[] = {
   0x70,0x88,0x8,0x30,0x48,0x88,0x88,0x90,0x60,0x80,0x88,0x70
};
static const GLUTBitmapChar hel12_ch167 = { 5, 12, 0, 3, 6, hel12_ch167data };

static const unsigned char hel12_ch168data[] = {
   0xa0
};
static const GLUTBitmapChar hel12_ch168 = { 3, 1, 0, -8, 3, hel12_ch168data };

static const unsigned char hel12_ch169data[] = {
   0x3e,0x0,0x41,0x0,0x9c,0x80,0xa2,0x80,0xa0,0x80,0xa2,0x80,0x9c,0x80,0x41,0x0,
   0x3e,0x0
};
static const GLUTBitmapChar hel12_ch169 = { 9, 9, -1, 0, 11, hel12_ch169data };

static const unsigned char hel12_ch170data[] = {
   0xe0,0x0,0xa0,0x20,0xe0
};
static const GLUTBitmapChar hel12_ch170 = { 3, 5, -1, -4, 5, hel12_ch170data };

static const unsigned char hel12_ch171data[] = {
   0x28,0x50,0xa0,0x50,0x28
};
static const GLUTBitmapChar hel12_ch171 = { 5, 5, -1, -1, 7, hel12_ch171data };

static const unsigned char hel12_ch172data[] = {
   0x4,0x4,0x4,0xfc
};
static const GLUTBitmapChar hel12_ch172 = { 6, 4, -1, -2, 8, hel12_ch172data };

static const unsigned char hel12_ch173data[] = {
   0xf0
};
static const GLUTBitmapChar hel12_ch173 = { 4, 1, 0, -3, 5, hel12_ch173data };

static const unsigned char hel12_ch174data[] = {
   0x3e,0x0,0x41,0x0,0x94,0x80,0x94,0x80,0x98,0x80,0x94,0x80,0x9c,0x80,0x41,0x0,
   0x3e,0x0
};
static const GLUTBitmapChar hel12_ch174 = { 9, 9, -1, 0, 11, hel12_ch174data };

static const unsigned char hel12_ch175data[] = {
   0xf0
};
static const GLUTBitmapChar hel12_ch175 = { 4, 1, 0, -8, 4, hel12_ch175data };

static const unsigned char hel12_ch176data[] = {
   0x60,0x90,0x90,0x60
};
static const GLUTBitmapChar hel12_ch176 = { 4, 4, 0, -4, 5, hel12_ch176data };

static const unsigned char hel12_ch177data[] = {
   0xf8,0x0,0x20,0x20,0xf8,0x20,0x20
};
static const GLUTBitmapChar hel12_ch177 = { 5, 7, -1, 0, 7, hel12_ch177data };

static const unsigned char hel12_ch178data[] = {
   0xf0,0x40,0x20,0x90,0x60
};
static const GLUTBitmapChar hel12_ch178 = { 4, 5, 0, -3, 4, hel12_ch178data };

static const unsigned char hel12_ch179data[] = {
   0xc0,0x20,0x40,0x20,0xe0
};
static const GLUTBitmapChar hel12_ch179 = { 3, 5, 0, -3, 4, hel12_ch179data };

static const unsigned char hel12_ch180data[] = {
   0x80,0x40
};
static const GLUTBitmapChar hel12_ch180 = { 2, 2, 0, -8, 2, hel12_ch180data };

static const unsigned char hel12_ch181data[] = {
   0x80,0x80,0x80,0xe8,0x98,0x88,0x88,0x88,0x88,0x88
};
static const GLUTBitmapChar hel12_ch181 = { 5, 10, -1, 3, 7, hel12_ch181data };

static const unsigned char hel12_ch182data[] = {
   0x28,0x28,0x28,0x28,0x28,0x28,0x68,0xe8,0xe8,0xe8,0x68,0x3c
};
static const GLUTBitmapChar hel12_ch182 = { 6, 12, 0, 3, 7, hel12_ch182data };

static const unsigned char hel12_ch183data[] = {
   0x80
};
static const GLUTBitmapChar hel12_ch183 = { 1, 1, -1, -3, 3, hel12_ch183data };

static const unsigned char hel12_ch184data[] = {
   0xc0,0x20,0x20,0x40
};
static const GLUTBitmapChar hel12_ch184 = { 3, 4, 0, 3, 3, hel12_ch184data };

static const unsigned char hel12_ch185data[] = {
   0x40,0x40,0x40,0xc0,0x40
};
static const GLUTBitmapChar hel12_ch185 = { 2, 5, -1, -3, 4, hel12_ch185data };

static const unsigned char hel12_ch186data[] = {
   0xe0,0x0,0xe0,0xa0,0xe0
};
static const GLUTBitmapChar hel12_ch186 = { 3, 5, -1, -4, 5, hel12_ch186data };

static const unsigned char hel12_ch187data[] = {
   0xa0,0x50,0x28,0x50,0xa0
};
static const GLUTBitmapChar hel12_ch187 = { 5, 5, -1, -1, 7, hel12_ch187data };

static const unsigned char hel12_ch188data[] = {
   0x41,0x0,0x27,0x80,0x15,0x0,0x13,0x0,0x49,0x0,0x44,0x0,0x44,0x0,0xc2,0x0,
   0x41,0x0
};
static const GLUTBitmapChar hel12_ch188 = { 9, 9, 0, 0, 10, hel12_ch188data };

static const unsigned char hel12_ch189data[] = {
   0x47,0x80,0x22,0x0,0x11,0x0,0x14,0x80,0x4b,0x0,0x48,0x0,0x44,0x0,0xc2,0x0,
   0x41,0x0
};
static const GLUTBitmapChar hel12_ch189 = { 9, 9, 0, 0, 10, hel12_ch189data };

static const unsigned char hel12_ch190data[] = {
   0x21,0x0,0x17,0x80,0x15,0x0,0xb,0x0,0xc9,0x0,0x24,0x0,0x44,0x0,0x22,0x0,
   0xe1,0x0
};
static const GLUTBitmapChar hel12_ch190 = { 9, 9, 0, 0, 10, hel12_ch190data };

static const unsigned char hel12_ch191data[] = {
   0x70,0x88,0x88,0x40,0x40,0x20,0x20,0x0,0x20
};
static const GLUTBitmapChar hel12_ch191 = { 5, 9, -1, 3, 7, hel12_ch191data };

static const unsigned char hel12_ch192data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x10,0x10,0x0,0x10,0x20
};
static const GLUTBitmapChar hel12_ch192 = { 7, 12, -1, 0, 9, hel12_ch192data };

static const unsigned char hel12_ch193data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x10,0x10,0x0,0x10,0x8
};
static const GLUTBitmapChar hel12_ch193 = { 7, 12, -1, 0, 9, hel12_ch193data };

static const unsigned char hel12_ch194data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x10,0x10,0x0,0x28,0x10
};
static const GLUTBitmapChar hel12_ch194 = { 7, 12, -1, 0, 9, hel12_ch194data };

static const unsigned char hel12_ch195data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x10,0x10,0x0,0x28,0x14
};
static const GLUTBitmapChar hel12_ch195 = { 7, 12, -1, 0, 9, hel12_ch195data };

static const unsigned char hel12_ch196data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x10,0x10,0x0,0x28
};
static const GLUTBitmapChar hel12_ch196 = { 7, 11, -1, 0, 9, hel12_ch196data };

static const unsigned char hel12_ch197data[] = {
   0x82,0x82,0x82,0x7c,0x44,0x44,0x28,0x10,0x10,0x10,0x28,0x10
};
static const GLUTBitmapChar hel12_ch197 = { 7, 12, -1, 0, 9, hel12_ch197data };

static const unsigned char hel12_ch198data[] = {
   0x8f,0x80,0x88,0x0,0x88,0x0,0x78,0x0,0x4f,0x80,0x48,0x0,0x28,0x0,0x28,0x0,
   0x1f,0x80
};
static const GLUTBitmapChar hel12_ch198 = { 9, 9, -1, 0, 11, hel12_ch198data };

static const unsigned char hel12_ch199data[] = {
   0x30,0x8,0x8,0x3c,0x42,0x80,0x80,0x80,0x80,0x80,0x42,0x3c
};
static const GLUTBitmapChar hel12_ch199 = { 7, 12, -1, 3, 9, hel12_ch199data };

static const unsigned char hel12_ch200data[] = {
   0xfc,0x80,0x80,0x80,0xfc,0x80,0x80,0x80,0xfc,0x0,0x10,0x20
};
static const GLUTBitmapChar hel12_ch200 = { 6, 12, -1, 0, 8, hel12_ch200data };

static const unsigned char hel12_ch201data[] = {
   0xfc,0x80,0x80,0x80,0xfc,0x80,0x80,0x80,0xfc,0x0,0x10,0x8
};
static const GLUTBitmapChar hel12_ch201 = { 6, 12, -1, 0, 8, hel12_ch201data };

static const unsigned char hel12_ch202data[] = {
   0xfc,0x80,0x80,0x80,0xfc,0x80,0x80,0x80,0xfc,0x0,0x28,0x10
};
static const GLUTBitmapChar hel12_ch202 = { 6, 12, -1, 0, 8, hel12_ch202data };

static const unsigned char hel12_ch203data[] = {
   0xfc,0x80,0x80,0x80,0xfc,0x80,0x80,0x80,0xfc,0x0,0x28
};
static const GLUTBitmapChar hel12_ch203 = { 6, 11, -1, 0, 8, hel12_ch203data };

static const unsigned char hel12_ch204data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0x40,0x80
};
static const GLUTBitmapChar hel12_ch204 = { 2, 12, 0, 0, 3, hel12_ch204data };

static const unsigned char hel12_ch205data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x0,0x80,0x40
};
static const GLUTBitmapChar hel12_ch205 = { 2, 12, -1, 0, 3, hel12_ch205data };

static const unsigned char hel12_ch206data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0xa0,0x40
};
static const GLUTBitmapChar hel12_ch206 = { 3, 12, 0, 0, 3, hel12_ch206data };

static const unsigned char hel12_ch207data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0xa0
};
static const GLUTBitmapChar hel12_ch207 = { 3, 11, 0, 0, 3, hel12_ch207data };

static const unsigned char hel12_ch208data[] = {
   0x7c,0x42,0x41,0x41,0xf1,0x41,0x41,0x42,0x7c
};
static const GLUTBitmapChar hel12_ch208 = { 8, 9, 0, 0, 9, hel12_ch208data };

static const unsigned char hel12_ch209data[] = {
   0x82,0x86,0x8a,0x8a,0x92,0xa2,0xa2,0xc2,0x82,0x0,0x28,0x14
};
static const GLUTBitmapChar hel12_ch209 = { 7, 12, -1, 0, 9, hel12_ch209data };

static const unsigned char hel12_ch210data[] = {
   0x3c,0x42,0x81,0x81,0x81,0x81,0x81,0x42,0x3c,0x0,0x8,0x10
};
static const GLUTBitmapChar hel12_ch210 = { 8, 12, -1, 0, 10, hel12_ch210data };

static const unsigned char hel12_ch211data[] = {
   0x3c,0x42,0x81,0x81,0x81,0x81,0x81,0x42,0x3c,0x0,0x8,0x4
};
static const GLUTBitmapChar hel12_ch211 = { 8, 12, -1, 0, 10, hel12_ch211data };

static const unsigned char hel12_ch212data[] = {
   0x3c,0x42,0x81,0x81,0x81,0x81,0x81,0x42,0x3c,0x0,0x14,0x8
};
static const GLUTBitmapChar hel12_ch212 = { 8, 12, -1, 0, 10, hel12_ch212data };

static const unsigned char hel12_ch213data[] = {
   0x3c,0x42,0x81,0x81,0x81,0x81,0x81,0x42,0x3c,0x0,0x28,0x14
};
static const GLUTBitmapChar hel12_ch213 = { 8, 12, -1, 0, 10, hel12_ch213data };

static const unsigned char hel12_ch214data[] = {
   0x3c,0x42,0x81,0x81,0x81,0x81,0x81,0x42,0x3c,0x0,0x24
};
static const GLUTBitmapChar hel12_ch214 = { 8, 11, -1, 0, 10, hel12_ch214data };

static const unsigned char hel12_ch215data[] = {
   0x88,0x50,0x20,0x50,0x88
};
static const GLUTBitmapChar hel12_ch215 = { 5, 5, -1, -1, 7, hel12_ch215data };

static const unsigned char hel12_ch216data[] = {
   0x80,0x0,0x5e,0x0,0x21,0x0,0x50,0x80,0x48,0x80,0x44,0x80,0x44,0x80,0x42,0x80,
   0x21,0x0,0x1e,0x80,0x0,0x40
};
static const GLUTBitmapChar hel12_ch216 = { 10, 11, 0, 1, 10, hel12_ch216data };

static const unsigned char hel12_ch217data[] = {
   0x78,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x0,0x10,0x20
};
static const GLUTBitmapChar hel12_ch217 = { 6, 12, -1, 0, 8, hel12_ch217data };

static const unsigned char hel12_ch218data[] = {
   0x78,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x0,0x10,0x8
};
static const GLUTBitmapChar hel12_ch218 = { 6, 12, -1, 0, 8, hel12_ch218data };

static const unsigned char hel12_ch219data[] = {
   0x78,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x0,0x28,0x10
};
static const GLUTBitmapChar hel12_ch219 = { 6, 12, -1, 0, 8, hel12_ch219data };

static const unsigned char hel12_ch220data[] = {
   0x78,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x84,0x0,0x48
};
static const GLUTBitmapChar hel12_ch220 = { 6, 11, -1, 0, 8, hel12_ch220data };

static const unsigned char hel12_ch221data[] = {
   0x10,0x10,0x10,0x10,0x28,0x44,0x44,0x82,0x82,0x0,0x10,0x8
};
static const GLUTBitmapChar hel12_ch221 = { 7, 12, -1, 0, 9, hel12_ch221data };

static const unsigned char hel12_ch222data[] = {
   0x80,0x80,0xf8,0x84,0x84,0x84,0xf8,0x80,0x80
};
static const GLUTBitmapChar hel12_ch222 = { 6, 9, -1, 0, 8, hel12_ch222data };

static const unsigned char hel12_ch223data[] = {
   0xb0,0x88,0x88,0x88,0xb0,0x88,0x88,0x88,0x70
};
static const GLUTBitmapChar hel12_ch223 = { 5, 9, -1, 0, 7, hel12_ch223data };

static const unsigned char hel12_ch224data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70,0x0,0x10,0x20
};
static const GLUTBitmapChar hel12_ch224 = { 6, 10, -1, 0, 7, hel12_ch224data };

static const unsigned char hel12_ch225data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70,0x0,0x20,0x10
};
static const GLUTBitmapChar hel12_ch225 = { 6, 10, -1, 0, 7, hel12_ch225data };

static const unsigned char hel12_ch226data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70,0x0,0x50,0x20
};
static const GLUTBitmapChar hel12_ch226 = { 6, 10, -1, 0, 7, hel12_ch226data };

static const unsigned char hel12_ch227data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70,0x0,0x50,0x28
};
static const GLUTBitmapChar hel12_ch227 = { 6, 10, -1, 0, 7, hel12_ch227data };

static const unsigned char hel12_ch228data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70,0x0,0x50
};
static const GLUTBitmapChar hel12_ch228 = { 6, 9, -1, 0, 7, hel12_ch228data };

static const unsigned char hel12_ch229data[] = {
   0x74,0x88,0x88,0x78,0x8,0x88,0x70,0x30,0x48,0x30
};
static const GLUTBitmapChar hel12_ch229 = { 6, 10, -1, 0, 7, hel12_ch229data };

static const unsigned char hel12_ch230data[] = {
   0x77,0x0,0x88,0x80,0x88,0x0,0x7f,0x80,0x8,0x80,0x88,0x80,0x77,0x0
};
static const GLUTBitmapChar hel12_ch230 = { 9, 7, -1, 0, 11, hel12_ch230data };

static const unsigned char hel12_ch231data[] = {
   0x60,0x10,0x20,0x70,0x88,0x80,0x80,0x80,0x88,0x70
};
static const GLUTBitmapChar hel12_ch231 = { 5, 10, -1, 3, 7, hel12_ch231data };

static const unsigned char hel12_ch232data[] = {
   0x70,0x88,0x80,0xf8,0x88,0x88,0x70,0x0,0x20,0x40
};
static const GLUTBitmapChar hel12_ch232 = { 5, 10, -1, 0, 7, hel12_ch232data };

static const unsigned char hel12_ch233data[] = {
   0x70,0x88,0x80,0xf8,0x88,0x88,0x70,0x0,0x20,0x10
};
static const GLUTBitmapChar hel12_ch233 = { 5, 10, -1, 0, 7, hel12_ch233data };

static const unsigned char hel12_ch234data[] = {
   0x70,0x88,0x80,0xf8,0x88,0x88,0x70,0x0,0x50,0x20
};
static const GLUTBitmapChar hel12_ch234 = { 5, 10, -1, 0, 7, hel12_ch234data };

static const unsigned char hel12_ch235data[] = {
   0x70,0x88,0x80,0xf8,0x88,0x88,0x70,0x0,0x50
};
static const GLUTBitmapChar hel12_ch235 = { 5, 9, -1, 0, 7, hel12_ch235data };

static const unsigned char hel12_ch236data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0x40,0x80
};
static const GLUTBitmapChar hel12_ch236 = { 2, 10, 0, 0, 3, hel12_ch236data };

static const unsigned char hel12_ch237data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x0,0x80,0x40
};
static const GLUTBitmapChar hel12_ch237 = { 2, 10, -1, 0, 3, hel12_ch237data };

static const unsigned char hel12_ch238data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0xa0,0x40
};
static const GLUTBitmapChar hel12_ch238 = { 3, 10, 0, 0, 3, hel12_ch238data };

static const unsigned char hel12_ch239data[] = {
   0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x0,0xa0
};
static const GLUTBitmapChar hel12_ch239 = { 3, 9, 0, 0, 3, hel12_ch239data };

static const unsigned char hel12_ch240data[] = {
   0x70,0x88,0x88,0x88,0x88,0x78,0x8,0x50,0x30,0x68
};
static const GLUTBitmapChar hel12_ch240 = { 5, 10, -1, 0, 7, hel12_ch240data };

static const unsigned char hel12_ch241data[] = {
   0x88,0x88,0x88,0x88,0x88,0xc8,0xb0,0x0,0x50,0x28
};
static const GLUTBitmapChar hel12_ch241 = { 5, 10, -1, 0, 7, hel12_ch241data };

static const unsigned char hel12_ch242data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x70,0x0,0x20,0x40
};
static const GLUTBitmapChar hel12_ch242 = { 5, 10, -1, 0, 7, hel12_ch242data };

static const unsigned char hel12_ch243data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x70,0x0,0x20,0x10
};
static const GLUTBitmapChar hel12_ch243 = { 5, 10, -1, 0, 7, hel12_ch243data };

static const unsigned char hel12_ch244data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x70,0x0,0x50,0x20
};
static const GLUTBitmapChar hel12_ch244 = { 5, 10, -1, 0, 7, hel12_ch244data };

static const unsigned char hel12_ch245data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x70,0x0,0x50,0x28
};
static const GLUTBitmapChar hel12_ch245 = { 5, 10, -1, 0, 7, hel12_ch245data };

static const unsigned char hel12_ch246data[] = {
   0x70,0x88,0x88,0x88,0x88,0x88,0x70,0x0,0x50
};
static const GLUTBitmapChar hel12_ch246 = { 5, 9, -1, 0, 7, hel12_ch246data };

static const unsigned char hel12_ch247data[] = {
   0x20,0x0,0xf8,0x0,0x20
};
static const GLUTBitmapChar hel12_ch247 = { 5, 5, -1, -1, 7, hel12_ch247data };

static const unsigned char hel12_ch248data[] = {
   0xb8,0x44,0x64,0x54,0x4c,0x44,0x3a
};
static const GLUTBitmapChar hel12_ch248 = { 7, 7, 0, 0, 7, hel12_ch248data };

static const unsigned char hel12_ch249data[] = {
   0x68,0x98,0x88,0x88,0x88,0x88,0x88,0x0,0x20,0x40
};
static const GLUTBitmapChar hel12_ch249 = { 5, 10, -1, 0, 7, hel12_ch249data };

static const unsigned char hel12_ch250data[] = {
   0x68,0x98,0x88,0x88,0x88,0x88,0x88,0x0,0x20,0x10
};
static const GLUTBitmapChar hel12_ch250 = { 5, 10, -1, 0, 7, hel12_ch250data };

static const unsigned char hel12_ch251data[] = {
   0x68,0x98,0x88,0x88,0x88,0x88,0x88,0x0,0x50,0x20
};
static const GLUTBitmapChar hel12_ch251 = { 5, 10, -1, 0, 7, hel12_ch251data };

static const unsigned char hel12_ch252data[] = {
   0x68,0x98,0x88,0x88,0x88,0x88,0x88,0x0,0x50
};
static const GLUTBitmapChar hel12_ch252 = { 5, 9, -1, 0, 7, hel12_ch252data };

static const unsigned char hel12_ch253data[] = {
   0x80,0x40,0x20,0x20,0x50,0x50,0x90,0x88,0x88,0x88,0x0,0x20,0x10
};
static const GLUTBitmapChar hel12_ch253 = { 5, 13, -1, 3, 7, hel12_ch253data };

static const unsigned char hel12_ch254data[] = {
   0x80,0x80,0x80,0xb0,0xc8,0x88,0x88,0x88,0xc8,0xb0,0x80,0x80
};
static const GLUTBitmapChar hel12_ch254 = { 5, 12, -1, 3, 7, hel12_ch254data };

static const unsigned char hel12_ch255data[] = {
   0xc0,0x20,0x20,0x20,0x30,0x50,0x50,0x48,0x88,0x88,0x0,0x50
};
static const GLUTBitmapChar hel12_ch255 = { 5, 12, -1, 3, 7, hel12_ch255data };


static const GLUTBitmapChar *hel12_chars[] = {
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   &hel12_ch32, &hel12_ch33, &hel12_ch34, &hel12_ch35, &hel12_ch36, &hel12_ch37, &hel12_ch38, &hel12_ch39, 
   &hel12_ch40, &hel12_ch41, &hel12_ch42, &hel12_ch43, &hel12_ch44, &hel12_ch45, &hel12_ch46, &hel12_ch47, 
   &hel12_ch48, &hel12_ch49, &hel12_ch50, &hel12_ch51, &hel12_ch52, &hel12_ch53, &hel12_ch54, &hel12_ch55, 
   &hel12_ch56, &hel12_ch57, &hel12_ch58, &hel12_ch59, &hel12_ch60, &hel12_ch61, &hel12_ch62, &hel12_ch63, 
   &hel12_ch64, &hel12_ch65, &hel12_ch66, &hel12_ch67, &hel12_ch68, &hel12_ch69, &hel12_ch70, &hel12_ch71, 
   &hel12_ch72, &hel12_ch73, &hel12_ch74, &hel12_ch75, &hel12_ch76, &hel12_ch77, &hel12_ch78, &hel12_ch79, 
   &hel12_ch80, &hel12_ch81, &hel12_ch82, &hel12_ch83, &hel12_ch84, &hel12_ch85, &hel12_ch86, &hel12_ch87, 
   &hel12_ch88, &hel12_ch89, &hel12_ch90, &hel12_ch91, &hel12_ch92, &hel12_ch93, &hel12_ch94, &hel12_ch95, 
   &hel12_ch96, &hel12_ch97, &hel12_ch98, &hel12_ch99, &hel12_ch100, &hel12_ch101, &hel12_ch102, &hel12_ch103, 
   &hel12_ch104, &hel12_ch105, &hel12_ch106, &hel12_ch107, &hel12_ch108, &hel12_ch109, &hel12_ch110, &hel12_ch111, 
   &hel12_ch112, &hel12_ch113, &hel12_ch114, &hel12_ch115, &hel12_ch116, &hel12_ch117, &hel12_ch118, &hel12_ch119, 
   &hel12_ch120, &hel12_ch121, &hel12_ch122, &hel12_ch123, &hel12_ch124, &hel12_ch125, &hel12_ch126, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   &hel12_ch160, &hel12_ch161, &hel12_ch162, &hel12_ch163, &hel12_ch164, &hel12_ch165, &hel12_ch166, &hel12_ch167, 
   &hel12_ch168, &hel12_ch169, &hel12_ch170, &hel12_ch171, &hel12_ch172, &hel12_ch173, &hel12_ch174, &hel12_ch175, 
   &hel12_ch176, &hel12_ch177, &hel12_ch178, &hel12_ch179, &hel12_ch180, &hel12_ch181, &hel12_ch182, &hel12_ch183, 
   &hel12_ch184, &hel12_ch185, &hel12_ch186, &hel12_ch187, &hel12_ch188, &hel12_ch189, &hel12_ch190, &hel12_ch191, 
   &hel12_ch192, &hel12_ch193, &hel12_ch194, &hel12_ch195, &hel12_ch196, &hel12_ch197, &hel12_ch198, &hel12_ch199, 
   &hel12_ch200, &hel12_ch201, &hel12_ch202, &hel12_ch203, &hel12_ch204, &hel12_ch205, &hel12_ch206, &hel12_ch207, 
   &hel12_ch208, &hel12_ch209, &hel12_ch210, &hel12_ch211, &hel12_ch212, &hel12_ch213, &hel12_ch214, &hel12_ch215, 
   &hel12_ch216, &hel12_ch217, &hel12_ch218, &hel12_ch219, &hel12_ch220, &hel12_ch221, &hel12_ch222, &hel12_ch223, 
   &hel12_ch224, &hel12_ch225, &hel12_ch226, &hel12_ch227, &hel12_ch228, &hel12_ch229, &hel12_ch230, &hel12_ch231, 
   &hel12_ch232, &hel12_ch233, &hel12_ch234, &hel12_ch235, &hel12_ch236, &hel12_ch237, &hel12_ch238, &hel12_ch239, 
   &hel12_ch240, &hel12_ch241, &hel12_ch242, &hel12_ch243, &hel12_ch244, &hel12_ch245, &hel12_ch246, &hel12_ch247, 
   &hel12_ch248, &hel12_ch249, &hel12_ch250, &hel12_ch251, &hel12_ch252, &hel12_ch253, &hel12_ch254, &hel12_ch255
};

static const GLUTBitmapFont _glutBitmapHelvetica12 = {
   "-Adobe-Helvetica-Medium-R-Normal--12-120-75-75-P-67-ISO8859-1",
   15, 256, hel12_chars
};

/* GLUTAPI void *glutBitmapHelvetica12 = &_glutBitmapHelvetica12; */
void * glutBitmapHelvetica12 = (void *)&_glutBitmapHelvetica12;
