/* autogenerated by bdf2c!  do not edit */

/* "Copyright (c) 1984, 1987 Adobe Systems Incorporated. All Rights Reserved. Copyright (c) 1988, 1991 Digital Equipment Corporation. All Rights Reserved." */


#include "internal.h"
/*
typedef struct {
   int width, height;
   int xorig, yorig;
   int xmove;
   const unsigned char *bitmap;
} GLUTBitmapChar;

typedef struct {
   const char *name;
   int height;
   int num;
   const GLUTBitmapChar *const *table;
} GLUTBitmapFont;
*/


static const unsigned char tr10_ch32data[] = {
   0x0
};
static const GLUTBitmapChar tr10_ch32 = { 1, 1, 0, 0, 2, tr10_ch32data };

static const unsigned char tr10_ch33data[] = {
   0x80,0x0,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar tr10_ch33 = { 1, 7, -1, 0, 3, tr10_ch33data };

static const unsigned char tr10_ch34data[] = {
   0xa0,0xa0
};
static const GLUTBitmapChar tr10_ch34 = { 3, 2, 0, -5, 4, tr10_ch34data };

static const unsigned char tr10_ch35data[] = {
   0x50,0x50,0xf8,0x50,0xf8,0x50,0x50
};
static const GLUTBitmapChar tr10_ch35 = { 5, 7, 0, 0, 5, tr10_ch35data };

static const unsigned char tr10_ch36data[] = {
   0x20,0xe0,0x90,0x10,0x60,0x80,0x90,0x70,0x20
};
static const GLUTBitmapChar tr10_ch36 = { 4, 9, 0, 1, 5, tr10_ch36data };

static const unsigned char tr10_ch37data[] = {
   0x44,0x2a,0x2a,0x56,0xa8,0xa4,0x7e
};
static const GLUTBitmapChar tr10_ch37 = { 7, 7, 0, 0, 8, tr10_ch37data };

static const unsigned char tr10_ch38data[] = {
   0x76,0x8d,0x98,0x74,0x6e,0x50,0x30
};
static const GLUTBitmapChar tr10_ch38 = { 8, 7, 0, 0, 8, tr10_ch38data };

static const unsigned char tr10_ch39data[] = {
   0x40,0xc0
};
static const GLUTBitmapChar tr10_ch39 = { 2, 2, 0, -5, 3, tr10_ch39data };

static const unsigned char tr10_ch40data[] = {
   0x20,0x40,0x40,0x80,0x80,0x80,0x40,0x40,0x20
};
static const GLUTBitmapChar tr10_ch40 = { 3, 9, 0, 2, 4, tr10_ch40data };

static const unsigned char tr10_ch41data[] = {
   0x80,0x40,0x40,0x20,0x20,0x20,0x40,0x40,0x80
};
static const GLUTBitmapChar tr10_ch41 = { 3, 9, 0, 2, 4, tr10_ch41data };

static const unsigned char tr10_ch42data[] = {
   0xa0,0x40,0xa0
};
static const GLUTBitmapChar tr10_ch42 = { 3, 3, 0, -4, 5, tr10_ch42data };

static const unsigned char tr10_ch43data[] = {
   0x20,0x20,0xf8,0x20,0x20
};
static const GLUTBitmapChar tr10_ch43 = { 5, 5, 0, 0, 6, tr10_ch43data };

static const unsigned char tr10_ch44data[] = {
   0x80,0x80,0x80
};
static const GLUTBitmapChar tr10_ch44 = { 1, 3, -1, 2, 3, tr10_ch44data };

static const unsigned char tr10_ch45data[] = {
   0xf0
};
static const GLUTBitmapChar tr10_ch45 = { 4, 1, -1, -2, 7, tr10_ch45data };

static const unsigned char tr10_ch46data[] = {
   0x80
};
static const GLUTBitmapChar tr10_ch46 = { 1, 1, -1, 0, 3, tr10_ch46data };

static const unsigned char tr10_ch47data[] = {
   0x80,0x80,0x40,0x40,0x40,0x20,0x20
};
static const GLUTBitmapChar tr10_ch47 = { 3, 7, 0, 0, 3, tr10_ch47data };

static const unsigned char tr10_ch48data[] = {
   0x60,0x90,0x90,0x90,0x90,0x90,0x60
};
static const GLUTBitmapChar tr10_ch48 = { 4, 7, 0, 0, 5, tr10_ch48data };

static const unsigned char tr10_ch49data[] = {
   0xe0,0x40,0x40,0x40,0x40,0xc0,0x40
};
static const GLUTBitmapChar tr10_ch49 = { 3, 7, -1, 0, 5, tr10_ch49data };

static const unsigned char tr10_ch50data[] = {
   0xf0,0x40,0x20,0x20,0x10,0x90,0x60
};
static const GLUTBitmapChar tr10_ch50 = { 4, 7, 0, 0, 5, tr10_ch50data };

static const unsigned char tr10_ch51data[] = {
   0xe0,0x10,0x10,0x60,0x10,0x90,0x60
};
static const GLUTBitmapChar tr10_ch51 = { 4, 7, 0, 0, 5, tr10_ch51data };

static const unsigned char tr10_ch52data[] = {
   0x10,0x10,0xf8,0x90,0x50,0x30,0x10
};
static const GLUTBitmapChar tr10_ch52 = { 5, 7, 0, 0, 5, tr10_ch52data };

static const unsigned char tr10_ch53data[] = {
   0xe0,0x90,0x10,0x10,0xe0,0x40,0x70
};
static const GLUTBitmapChar tr10_ch53 = { 4, 7, 0, 0, 5, tr10_ch53data };

static const unsigned char tr10_ch54data[] = {
   0x60,0x90,0x90,0x90,0xe0,0x40,0x30
};
static const GLUTBitmapChar tr10_ch54 = { 4, 7, 0, 0, 5, tr10_ch54data };

static const unsigned char tr10_ch55data[] = {
   0x40,0x40,0x40,0x20,0x20,0x90,0xf0
};
static const GLUTBitmapChar tr10_ch55 = { 4, 7, 0, 0, 5, tr10_ch55data };

static const unsigned char tr10_ch56data[] = {
   0x60,0x90,0x90,0x60,0x90,0x90,0x60
};
static const GLUTBitmapChar tr10_ch56 = { 4, 7, 0, 0, 5, tr10_ch56data };

static const unsigned char tr10_ch57data[] = {
   0xc0,0x20,0x70,0x90,0x90,0x90,0x60
};
static const GLUTBitmapChar tr10_ch57 = { 4, 7, 0, 0, 5, tr10_ch57data };

static const unsigned char tr10_ch58data[] = {
   0x80,0x0,0x0,0x0,0x80
};
static const GLUTBitmapChar tr10_ch58 = { 1, 5, -1, 0, 3, tr10_ch58data };

static const unsigned char tr10_ch59data[] = {
   0x80,0x80,0x80,0x0,0x0,0x0,0x80
};
static const GLUTBitmapChar tr10_ch59 = { 1, 7, -1, 2, 3, tr10_ch59data };

static const unsigned char tr10_ch60data[] = {
   0x20,0x40,0x80,0x40,0x20
};
static const GLUTBitmapChar tr10_ch60 = { 3, 5, -1, 0, 5, tr10_ch60data };

static const unsigned char tr10_ch61data[] = {
   0xf8,0x0,0xf8
};
static const GLUTBitmapChar tr10_ch61 = { 5, 3, 0, -1, 6, tr10_ch61data };

static const unsigned char tr10_ch62data[] = {
   0x80,0x40,0x20,0x40,0x80
};
static const GLUTBitmapChar tr10_ch62 = { 3, 5, 0, 0, 5, tr10_ch62data };

static const unsigned char tr10_ch63data[] = {
   0x40,0x0,0x40,0x40,0x20,0xa0,0xe0
};
static const GLUTBitmapChar tr10_ch63 = { 3, 7, 0, 0, 4, tr10_ch63data };

static const unsigned char tr10_ch64data[] = {
   0x3e,0x40,0x92,0xad,0xa5,0xa5,0x9d,0x42,0x3c
};
static const GLUTBitmapChar tr10_ch64 = { 8, 9, 0, 2, 9, tr10_ch64data };

static const unsigned char tr10_ch65data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10
};
static const GLUTBitmapChar tr10_ch65 = { 7, 7, 0, 0, 8, tr10_ch65data };

static const unsigned char tr10_ch66data[] = {
   0xf0,0x48,0x48,0x70,0x48,0x48,0xf0
};
static const GLUTBitmapChar tr10_ch66 = { 5, 7, 0, 0, 6, tr10_ch66data };

static const unsigned char tr10_ch67data[] = {
   0x78,0xc4,0x80,0x80,0x80,0xc4,0x7c
};
static const GLUTBitmapChar tr10_ch67 = { 6, 7, 0, 0, 7, tr10_ch67data };

static const unsigned char tr10_ch68data[] = {
   0xf8,0x4c,0x44,0x44,0x44,0x4c,0xf8
};
static const GLUTBitmapChar tr10_ch68 = { 6, 7, 0, 0, 7, tr10_ch68data };

static const unsigned char tr10_ch69data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8
};
static const GLUTBitmapChar tr10_ch69 = { 5, 7, 0, 0, 6, tr10_ch69data };

static const unsigned char tr10_ch70data[] = {
   0xe0,0x40,0x40,0x70,0x40,0x48,0xf8
};
static const GLUTBitmapChar tr10_ch70 = { 5, 7, 0, 0, 6, tr10_ch70data };

static const unsigned char tr10_ch71data[] = {
   0x78,0xc4,0x84,0x9c,0x80,0xc4,0x7c
};
static const GLUTBitmapChar tr10_ch71 = { 6, 7, 0, 0, 7, tr10_ch71data };

static const unsigned char tr10_ch72data[] = {
   0xee,0x44,0x44,0x7c,0x44,0x44,0xee
};
static const GLUTBitmapChar tr10_ch72 = { 7, 7, 0, 0, 8, tr10_ch72data };

static const unsigned char tr10_ch73data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0
};
static const GLUTBitmapChar tr10_ch73 = { 3, 7, 0, 0, 4, tr10_ch73data };

static const unsigned char tr10_ch74data[] = {
   0xc0,0xa0,0x20,0x20,0x20,0x20,0x70
};
static const GLUTBitmapChar tr10_ch74 = { 4, 7, 0, 0, 4, tr10_ch74data };

static const unsigned char tr10_ch75data[] = {
   0xec,0x48,0x50,0x60,0x50,0x48,0xec
};
static const GLUTBitmapChar tr10_ch75 = { 6, 7, 0, 0, 7, tr10_ch75data };

static const unsigned char tr10_ch76data[] = {
   0xf8,0x48,0x40,0x40,0x40,0x40,0xe0
};
static const GLUTBitmapChar tr10_ch76 = { 5, 7, 0, 0, 6, tr10_ch76data };

static const unsigned char tr10_ch77data[] = {
   0xeb,0x80,0x49,0x0,0x55,0x0,0x55,0x0,0x63,0x0,0x63,0x0,0xe3,0x80
};
static const GLUTBitmapChar tr10_ch77 = { 9, 7, 0, 0, 10, tr10_ch77data };

static const unsigned char tr10_ch78data[] = {
   0xe4,0x4c,0x4c,0x54,0x54,0x64,0xee
};
static const GLUTBitmapChar tr10_ch78 = { 7, 7, 0, 0, 8, tr10_ch78data };

static const unsigned char tr10_ch79data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78
};
static const GLUTBitmapChar tr10_ch79 = { 6, 7, 0, 0, 7, tr10_ch79data };

static const unsigned char tr10_ch80data[] = {
   0xe0,0x40,0x40,0x70,0x48,0x48,0xf0
};
static const GLUTBitmapChar tr10_ch80 = { 5, 7, 0, 0, 6, tr10_ch80data };

static const unsigned char tr10_ch81data[] = {
   0xc,0x18,0x70,0xcc,0x84,0x84,0x84,0xcc,0x78
};
static const GLUTBitmapChar tr10_ch81 = { 6, 9, 0, 2, 7, tr10_ch81data };

static const unsigned char tr10_ch82data[] = {
   0xec,0x48,0x50,0x70,0x48,0x48,0xf0
};
static const GLUTBitmapChar tr10_ch82 = { 6, 7, 0, 0, 7, tr10_ch82data };

static const unsigned char tr10_ch83data[] = {
   0xe0,0x90,0x10,0x60,0xc0,0x90,0x70
};
static const GLUTBitmapChar tr10_ch83 = { 4, 7, 0, 0, 5, tr10_ch83data };

static const unsigned char tr10_ch84data[] = {
   0x70,0x20,0x20,0x20,0x20,0xa8,0xf8
};
static const GLUTBitmapChar tr10_ch84 = { 5, 7, 0, 0, 6, tr10_ch84data };

static const unsigned char tr10_ch85data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee
};
static const GLUTBitmapChar tr10_ch85 = { 7, 7, 0, 0, 8, tr10_ch85data };

static const unsigned char tr10_ch86data[] = {
   0x10,0x10,0x28,0x28,0x6c,0x44,0xee
};
static const GLUTBitmapChar tr10_ch86 = { 7, 7, 0, 0, 8, tr10_ch86data };

static const unsigned char tr10_ch87data[] = {
   0x22,0x0,0x22,0x0,0x55,0x0,0x55,0x0,0xc9,0x80,0x88,0x80,0xdd,0xc0
};
static const GLUTBitmapChar tr10_ch87 = { 10, 7, 0, 0, 10, tr10_ch87data };

static const unsigned char tr10_ch88data[] = {
   0xee,0x44,0x28,0x10,0x28,0x44,0xee
};
static const GLUTBitmapChar tr10_ch88 = { 7, 7, 0, 0, 8, tr10_ch88data };

static const unsigned char tr10_ch89data[] = {
   0x38,0x10,0x10,0x28,0x28,0x44,0xee
};
static const GLUTBitmapChar tr10_ch89 = { 7, 7, 0, 0, 8, tr10_ch89data };

static const unsigned char tr10_ch90data[] = {
   0xf8,0x88,0x40,0x20,0x10,0x88,0xf8
};
static const GLUTBitmapChar tr10_ch90 = { 5, 7, 0, 0, 6, tr10_ch90data };

static const unsigned char tr10_ch91data[] = {
   0xc0,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0xc0
};
static const GLUTBitmapChar tr10_ch91 = { 2, 9, 0, 2, 3, tr10_ch91data };

static const unsigned char tr10_ch92data[] = {
   0x20,0x20,0x40,0x40,0x40,0x80,0x80
};
static const GLUTBitmapChar tr10_ch92 = { 3, 7, 0, 0, 3, tr10_ch92data };

static const unsigned char tr10_ch93data[] = {
   0xc0,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0xc0
};
static const GLUTBitmapChar tr10_ch93 = { 2, 9, 0, 2, 3, tr10_ch93data };

static const unsigned char tr10_ch94data[] = {
   0xa0,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch94 = { 3, 3, -1, -4, 5, tr10_ch94data };

static const unsigned char tr10_ch95data[] = {
   0xf8
};
static const GLUTBitmapChar tr10_ch95 = { 5, 1, 0, 3, 5, tr10_ch95data };

static const unsigned char tr10_ch96data[] = {
   0xc0,0x80
};
static const GLUTBitmapChar tr10_ch96 = { 2, 2, 0, -5, 3, tr10_ch96data };

static const unsigned char tr10_ch97data[] = {
   0xe0,0xa0,0x60,0x20,0xc0
};
static const GLUTBitmapChar tr10_ch97 = { 3, 5, 0, 0, 4, tr10_ch97data };

static const unsigned char tr10_ch98data[] = {
   0xe0,0x90,0x90,0x90,0xe0,0x80,0x80
};
static const GLUTBitmapChar tr10_ch98 = { 4, 7, 0, 0, 5, tr10_ch98data };

static const unsigned char tr10_ch99data[] = {
   0x60,0x80,0x80,0x80,0x60
};
static const GLUTBitmapChar tr10_ch99 = { 3, 5, 0, 0, 4, tr10_ch99data };

static const unsigned char tr10_ch100data[] = {
   0x68,0x90,0x90,0x90,0x70,0x10,0x30
};
static const GLUTBitmapChar tr10_ch100 = { 5, 7, 0, 0, 5, tr10_ch100data };

static const unsigned char tr10_ch101data[] = {
   0x60,0x80,0xc0,0xa0,0x60
};
static const GLUTBitmapChar tr10_ch101 = { 3, 5, 0, 0, 4, tr10_ch101data };

static const unsigned char tr10_ch102data[] = {
   0xe0,0x40,0x40,0x40,0xe0,0x40,0x30
};
static const GLUTBitmapChar tr10_ch102 = { 4, 7, 0, 0, 4, tr10_ch102data };

static const unsigned char tr10_ch103data[] = {
   0xe0,0x90,0x60,0x40,0xa0,0xa0,0x70
};
static const GLUTBitmapChar tr10_ch103 = { 4, 7, 0, 2, 5, tr10_ch103data };

static const unsigned char tr10_ch104data[] = {
   0xd8,0x90,0x90,0x90,0xe0,0x80,0x80
};
static const GLUTBitmapChar tr10_ch104 = { 5, 7, 0, 0, 5, tr10_ch104data };

static const unsigned char tr10_ch105data[] = {
   0x40,0x40,0x40,0x40,0xc0,0x0,0x40
};
static const GLUTBitmapChar tr10_ch105 = { 2, 7, 0, 0, 3, tr10_ch105data };

static const unsigned char tr10_ch106data[] = {
   0x80,0x40,0x40,0x40,0x40,0x40,0xc0,0x0,0x40
};
static const GLUTBitmapChar tr10_ch106 = { 2, 9, 0, 2, 3, tr10_ch106data };

static const unsigned char tr10_ch107data[] = {
   0x98,0x90,0xe0,0xa0,0x90,0x80,0x80
};
static const GLUTBitmapChar tr10_ch107 = { 5, 7, 0, 0, 5, tr10_ch107data };

static const unsigned char tr10_ch108data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xc0
};
static const GLUTBitmapChar tr10_ch108 = { 3, 7, 0, 0, 4, tr10_ch108data };

static const unsigned char tr10_ch109data[] = {
   0xdb,0x92,0x92,0x92,0xec
};
static const GLUTBitmapChar tr10_ch109 = { 8, 5, 0, 0, 8, tr10_ch109data };

static const unsigned char tr10_ch110data[] = {
   0xd8,0x90,0x90,0x90,0xe0
};
static const GLUTBitmapChar tr10_ch110 = { 5, 5, 0, 0, 5, tr10_ch110data };

static const unsigned char tr10_ch111data[] = {
   0x60,0x90,0x90,0x90,0x60
};
static const GLUTBitmapChar tr10_ch111 = { 4, 5, 0, 0, 5, tr10_ch111data };

static const unsigned char tr10_ch112data[] = {
   0xc0,0x80,0xe0,0x90,0x90,0x90,0xe0
};
static const GLUTBitmapChar tr10_ch112 = { 4, 7, 0, 2, 5, tr10_ch112data };

static const unsigned char tr10_ch113data[] = {
   0x38,0x10,0x70,0x90,0x90,0x90,0x70
};
static const GLUTBitmapChar tr10_ch113 = { 5, 7, 0, 2, 5, tr10_ch113data };

static const unsigned char tr10_ch114data[] = {
   0xe0,0x40,0x40,0x60,0xa0
};
static const GLUTBitmapChar tr10_ch114 = { 3, 5, 0, 0, 4, tr10_ch114data };

static const unsigned char tr10_ch115data[] = {
   0xe0,0x20,0x60,0x80,0xe0
};
static const GLUTBitmapChar tr10_ch115 = { 3, 5, 0, 0, 4, tr10_ch115data };

static const unsigned char tr10_ch116data[] = {
   0x30,0x40,0x40,0x40,0xe0,0x40
};
static const GLUTBitmapChar tr10_ch116 = { 4, 6, 0, 0, 4, tr10_ch116data };

static const unsigned char tr10_ch117data[] = {
   0x68,0x90,0x90,0x90,0x90
};
static const GLUTBitmapChar tr10_ch117 = { 5, 5, 0, 0, 5, tr10_ch117data };

static const unsigned char tr10_ch118data[] = {
   0x20,0x60,0x50,0x90,0xd8
};
static const GLUTBitmapChar tr10_ch118 = { 5, 5, 0, 0, 5, tr10_ch118data };

static const unsigned char tr10_ch119data[] = {
   0x28,0x6c,0x54,0x92,0xdb
};
static const GLUTBitmapChar tr10_ch119 = { 8, 5, 0, 0, 8, tr10_ch119data };

static const unsigned char tr10_ch120data[] = {
   0xd8,0x50,0x20,0x50,0xd8
};
static const GLUTBitmapChar tr10_ch120 = { 5, 5, 0, 0, 6, tr10_ch120data };

static const unsigned char tr10_ch121data[] = {
   0x40,0x40,0x20,0x30,0x50,0x48,0xdc
};
static const GLUTBitmapChar tr10_ch121 = { 6, 7, 1, 2, 5, tr10_ch121data };

static const unsigned char tr10_ch122data[] = {
   0xf0,0x90,0x40,0x20,0xf0
};
static const GLUTBitmapChar tr10_ch122 = { 4, 5, 0, 0, 5, tr10_ch122data };

static const unsigned char tr10_ch123data[] = {
   0x20,0x40,0x40,0x40,0x80,0x40,0x40,0x40,0x20
};
static const GLUTBitmapChar tr10_ch123 = { 3, 9, 0, 2, 4, tr10_ch123data };

static const unsigned char tr10_ch124data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar tr10_ch124 = { 1, 9, 0, 2, 2, tr10_ch124data };

static const unsigned char tr10_ch125data[] = {
   0x80,0x40,0x40,0x40,0x20,0x40,0x40,0x40,0x80
};
static const GLUTBitmapChar tr10_ch125 = { 3, 9, 0, 2, 4, tr10_ch125data };

static const unsigned char tr10_ch126data[] = {
   0x98,0x64
};
static const GLUTBitmapChar tr10_ch126 = { 6, 2, 0, -2, 7, tr10_ch126data };

static const unsigned char tr10_ch160data[] = {
   0x0
};
static const GLUTBitmapChar tr10_ch160 = { 1, 1, 0, 0, 2, tr10_ch160data };

static const unsigned char tr10_ch161data[] = {
   0x80,0x80,0x80,0x80,0x80,0x0,0x80
};
static const GLUTBitmapChar tr10_ch161 = { 1, 7, -1, 2, 3, tr10_ch161data };

static const unsigned char tr10_ch162data[] = {
   0x80,0xe0,0x90,0x80,0x90,0x70,0x10
};
static const GLUTBitmapChar tr10_ch162 = { 4, 7, 0, 1, 5, tr10_ch162data };

static const unsigned char tr10_ch163data[] = {
   0xf0,0xc8,0x40,0xe0,0x40,0x50,0x30
};
static const GLUTBitmapChar tr10_ch163 = { 5, 7, 0, 0, 5, tr10_ch163data };

static const unsigned char tr10_ch164data[] = {
   0x88,0x70,0x50,0x50,0x70,0x88
};
static const GLUTBitmapChar tr10_ch164 = { 5, 6, 0, -1, 5, tr10_ch164data };

static const unsigned char tr10_ch165data[] = {
   0x70,0x20,0xf8,0x20,0xd8,0x50,0x88
};
static const GLUTBitmapChar tr10_ch165 = { 5, 7, 0, 0, 5, tr10_ch165data };

static const unsigned char tr10_ch166data[] = {
   0x80,0x80,0x80,0x0,0x80,0x80,0x80
};
static const GLUTBitmapChar tr10_ch166 = { 1, 7, 0, 0, 2, tr10_ch166data };

static const unsigned char tr10_ch167data[] = {
   0xe0,0x90,0x20,0x50,0x90,0xa0,0x40,0x90,0x70
};
static const GLUTBitmapChar tr10_ch167 = { 4, 9, 0, 1, 5, tr10_ch167data };

static const unsigned char tr10_ch168data[] = {
   0xa0
};
static const GLUTBitmapChar tr10_ch168 = { 3, 1, -1, -6, 5, tr10_ch168data };

static const unsigned char tr10_ch169data[] = {
   0x38,0x44,0x9a,0xa2,0x9a,0x44,0x38
};
static const GLUTBitmapChar tr10_ch169 = { 7, 7, -1, 0, 9, tr10_ch169data };

static const unsigned char tr10_ch170data[] = {
   0xe0,0x0,0xa0,0x20,0xc0
};
static const GLUTBitmapChar tr10_ch170 = { 3, 5, 0, -2, 4, tr10_ch170data };

static const unsigned char tr10_ch171data[] = {
   0x50,0xa0,0xa0,0x50
};
static const GLUTBitmapChar tr10_ch171 = { 4, 4, 0, -1, 5, tr10_ch171data };

static const unsigned char tr10_ch172data[] = {
   0x8,0x8,0xf8
};
static const GLUTBitmapChar tr10_ch172 = { 5, 3, -1, -1, 7, tr10_ch172data };

static const unsigned char tr10_ch173data[] = {
   0xe0
};
static const GLUTBitmapChar tr10_ch173 = { 3, 1, 0, -2, 4, tr10_ch173data };

static const unsigned char tr10_ch174data[] = {
   0x38,0x44,0xaa,0xb2,0xba,0x44,0x38
};
static const GLUTBitmapChar tr10_ch174 = { 7, 7, -1, 0, 9, tr10_ch174data };

static const unsigned char tr10_ch175data[] = {
   0xe0
};
static const GLUTBitmapChar tr10_ch175 = { 3, 1, 0, -6, 4, tr10_ch175data };

static const unsigned char tr10_ch176data[] = {
   0x60,0x90,0x90,0x60
};
static const GLUTBitmapChar tr10_ch176 = { 4, 4, 0, -3, 4, tr10_ch176data };

static const unsigned char tr10_ch177data[] = {
   0xf8,0x0,0x20,0x20,0xf8,0x20,0x20
};
static const GLUTBitmapChar tr10_ch177 = { 5, 7, 0, 0, 6, tr10_ch177data };

static const unsigned char tr10_ch178data[] = {
   0xe0,0x40,0xa0,0x60
};
static const GLUTBitmapChar tr10_ch178 = { 3, 4, 0, -3, 3, tr10_ch178data };

static const unsigned char tr10_ch179data[] = {
   0xc0,0x20,0x40,0xe0
};
static const GLUTBitmapChar tr10_ch179 = { 3, 4, 0, -3, 3, tr10_ch179data };

static const unsigned char tr10_ch180data[] = {
   0x80,0x40
};
static const GLUTBitmapChar tr10_ch180 = { 2, 2, 0, -5, 3, tr10_ch180data };

static const unsigned char tr10_ch181data[] = {
   0x80,0x80,0xe8,0x90,0x90,0x90,0x90
};
static const GLUTBitmapChar tr10_ch181 = { 5, 7, 0, 2, 5, tr10_ch181data };

static const unsigned char tr10_ch182data[] = {
   0x28,0x28,0x28,0x28,0x68,0xe8,0xe8,0xe8,0x7c
};
static const GLUTBitmapChar tr10_ch182 = { 6, 9, 0, 2, 6, tr10_ch182data };

static const unsigned char tr10_ch183data[] = {
   0x80
};
static const GLUTBitmapChar tr10_ch183 = { 1, 1, 0, -2, 2, tr10_ch183data };

static const unsigned char tr10_ch184data[] = {
   0xc0,0x20,0x40
};
static const GLUTBitmapChar tr10_ch184 = { 3, 3, 0, 3, 4, tr10_ch184data };

static const unsigned char tr10_ch185data[] = {
   0xe0,0x40,0xc0,0x40
};
static const GLUTBitmapChar tr10_ch185 = { 3, 4, 0, -3, 3, tr10_ch185data };

static const unsigned char tr10_ch186data[] = {
   0xe0,0x0,0x40,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch186 = { 3, 5, 0, -2, 4, tr10_ch186data };

static const unsigned char tr10_ch187data[] = {
   0xa0,0x50,0x50,0xa0
};
static const GLUTBitmapChar tr10_ch187 = { 4, 4, 0, -1, 5, tr10_ch187data };

static const unsigned char tr10_ch188data[] = {
   0x44,0x3e,0x2c,0xf4,0x48,0xc8,0x44
};
static const GLUTBitmapChar tr10_ch188 = { 7, 7, 0, 0, 8, tr10_ch188data };

static const unsigned char tr10_ch189data[] = {
   0x4e,0x24,0x2a,0xf6,0x48,0xc8,0x44
};
static const GLUTBitmapChar tr10_ch189 = { 7, 7, 0, 0, 8, tr10_ch189data };

static const unsigned char tr10_ch190data[] = {
   0x44,0x3e,0x2c,0xd4,0x28,0x48,0xe4
};
static const GLUTBitmapChar tr10_ch190 = { 7, 7, 0, 0, 8, tr10_ch190data };

static const unsigned char tr10_ch191data[] = {
   0xe0,0xa0,0x80,0x40,0x40,0x0,0x40
};
static const GLUTBitmapChar tr10_ch191 = { 3, 7, 0, 2, 4, tr10_ch191data };

static const unsigned char tr10_ch192data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x10,0x20
};
static const GLUTBitmapChar tr10_ch192 = { 7, 10, 0, 0, 8, tr10_ch192data };

static const unsigned char tr10_ch193data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x10,0x8
};
static const GLUTBitmapChar tr10_ch193 = { 7, 10, 0, 0, 8, tr10_ch193data };

static const unsigned char tr10_ch194data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x28,0x10
};
static const GLUTBitmapChar tr10_ch194 = { 7, 10, 0, 0, 8, tr10_ch194data };

static const unsigned char tr10_ch195data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x28,0x14
};
static const GLUTBitmapChar tr10_ch195 = { 7, 10, 0, 0, 8, tr10_ch195data };

static const unsigned char tr10_ch196data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x28
};
static const GLUTBitmapChar tr10_ch196 = { 7, 9, 0, 0, 8, tr10_ch196data };

static const unsigned char tr10_ch197data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x10,0x28,0x10
};
static const GLUTBitmapChar tr10_ch197 = { 7, 10, 0, 0, 8, tr10_ch197data };

static const unsigned char tr10_ch198data[] = {
   0xef,0x49,0x78,0x2e,0x28,0x39,0x1f
};
static const GLUTBitmapChar tr10_ch198 = { 8, 7, 0, 0, 9, tr10_ch198data };

static const unsigned char tr10_ch199data[] = {
   0x60,0x10,0x20,0x78,0xc4,0x80,0x80,0x80,0xc4,0x7c
};
static const GLUTBitmapChar tr10_ch199 = { 6, 10, 0, 3, 7, tr10_ch199data };

static const unsigned char tr10_ch200data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x20,0x40
};
static const GLUTBitmapChar tr10_ch200 = { 5, 10, 0, 0, 6, tr10_ch200data };

static const unsigned char tr10_ch201data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x20,0x10
};
static const GLUTBitmapChar tr10_ch201 = { 5, 10, 0, 0, 6, tr10_ch201data };

static const unsigned char tr10_ch202data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x50,0x20
};
static const GLUTBitmapChar tr10_ch202 = { 5, 10, 0, 0, 6, tr10_ch202data };

static const unsigned char tr10_ch203data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x50
};
static const GLUTBitmapChar tr10_ch203 = { 5, 9, 0, 0, 6, tr10_ch203data };

static const unsigned char tr10_ch204data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0x40,0x80
};
static const GLUTBitmapChar tr10_ch204 = { 3, 10, 0, 0, 4, tr10_ch204data };

static const unsigned char tr10_ch205data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0x40,0x20
};
static const GLUTBitmapChar tr10_ch205 = { 3, 10, 0, 0, 4, tr10_ch205data };

static const unsigned char tr10_ch206data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch206 = { 3, 10, 0, 0, 4, tr10_ch206data };

static const unsigned char tr10_ch207data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0xa0
};
static const GLUTBitmapChar tr10_ch207 = { 3, 9, 0, 0, 4, tr10_ch207data };

static const unsigned char tr10_ch208data[] = {
   0xf8,0x4c,0x44,0xe4,0x44,0x4c,0xf8
};
static const GLUTBitmapChar tr10_ch208 = { 6, 7, 0, 0, 7, tr10_ch208data };

static const unsigned char tr10_ch209data[] = {
   0xe4,0x4c,0x4c,0x54,0x54,0x64,0xee,0x0,0x50,0x28
};
static const GLUTBitmapChar tr10_ch209 = { 7, 10, 0, 0, 8, tr10_ch209data };

static const unsigned char tr10_ch210data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x20,0x40
};
static const GLUTBitmapChar tr10_ch210 = { 6, 10, 0, 0, 7, tr10_ch210data };

static const unsigned char tr10_ch211data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x10,0x8
};
static const GLUTBitmapChar tr10_ch211 = { 6, 10, 0, 0, 7, tr10_ch211data };

static const unsigned char tr10_ch212data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x50,0x20
};
static const GLUTBitmapChar tr10_ch212 = { 6, 10, 0, 0, 7, tr10_ch212data };

static const unsigned char tr10_ch213data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x50,0x28
};
static const GLUTBitmapChar tr10_ch213 = { 6, 10, 0, 0, 7, tr10_ch213data };

static const unsigned char tr10_ch214data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x50
};
static const GLUTBitmapChar tr10_ch214 = { 6, 9, 0, 0, 7, tr10_ch214data };

static const unsigned char tr10_ch215data[] = {
   0x88,0x50,0x20,0x50,0x88
};
static const GLUTBitmapChar tr10_ch215 = { 5, 5, 0, 0, 6, tr10_ch215data };

static const unsigned char tr10_ch216data[] = {
   0x80,0x7c,0x66,0x52,0x52,0x4a,0x66,0x3e,0x1
};
static const GLUTBitmapChar tr10_ch216 = { 8, 9, 0, 1, 8, tr10_ch216data };

static const unsigned char tr10_ch217data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x10,0x20
};
static const GLUTBitmapChar tr10_ch217 = { 7, 10, 0, 0, 8, tr10_ch217data };

static const unsigned char tr10_ch218data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x10,0x8
};
static const GLUTBitmapChar tr10_ch218 = { 7, 10, 0, 0, 8, tr10_ch218data };

static const unsigned char tr10_ch219data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x28,0x10
};
static const GLUTBitmapChar tr10_ch219 = { 7, 10, 0, 0, 8, tr10_ch219data };

static const unsigned char tr10_ch220data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x28
};
static const GLUTBitmapChar tr10_ch220 = { 7, 9, 0, 0, 8, tr10_ch220data };

static const unsigned char tr10_ch221data[] = {
   0x38,0x10,0x10,0x28,0x28,0x44,0xee,0x0,0x10,0x8
};
static const GLUTBitmapChar tr10_ch221 = { 7, 10, 0, 0, 8, tr10_ch221data };

static const unsigned char tr10_ch222data[] = {
   0xe0,0x40,0x70,0x48,0x70,0x40,0xe0
};
static const GLUTBitmapChar tr10_ch222 = { 5, 7, 0, 0, 6, tr10_ch222data };

static const unsigned char tr10_ch223data[] = {
   0xe0,0x50,0x50,0x60,0x50,0x50,0x20
};
static const GLUTBitmapChar tr10_ch223 = { 4, 7, 0, 0, 5, tr10_ch223data };

static const unsigned char tr10_ch224data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0x40,0x80
};
static const GLUTBitmapChar tr10_ch224 = { 3, 8, 0, 0, 4, tr10_ch224data };

static const unsigned char tr10_ch225data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0x40,0x20
};
static const GLUTBitmapChar tr10_ch225 = { 3, 8, 0, 0, 4, tr10_ch225data };

static const unsigned char tr10_ch226data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch226 = { 3, 8, 0, 0, 4, tr10_ch226data };

static const unsigned char tr10_ch227data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0xa0,0x50
};
static const GLUTBitmapChar tr10_ch227 = { 4, 8, 0, 0, 4, tr10_ch227data };

static const unsigned char tr10_ch228data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0xa0
};
static const GLUTBitmapChar tr10_ch228 = { 3, 7, 0, 0, 4, tr10_ch228data };

static const unsigned char tr10_ch229data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x40,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch229 = { 3, 8, 0, 0, 4, tr10_ch229data };

static const unsigned char tr10_ch230data[] = {
   0xd8,0xa0,0x70,0x28,0xd8
};
static const GLUTBitmapChar tr10_ch230 = { 5, 5, 0, 0, 6, tr10_ch230data };

static const unsigned char tr10_ch231data[] = {
   0xc0,0x20,0x40,0x60,0x80,0x80,0x80,0x60
};
static const GLUTBitmapChar tr10_ch231 = { 3, 8, 0, 3, 4, tr10_ch231data };

static const unsigned char tr10_ch232data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0x40,0x80
};
static const GLUTBitmapChar tr10_ch232 = { 3, 8, 0, 0, 4, tr10_ch232data };

static const unsigned char tr10_ch233data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0x40,0x20
};
static const GLUTBitmapChar tr10_ch233 = { 3, 8, 0, 0, 4, tr10_ch233data };

static const unsigned char tr10_ch234data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch234 = { 3, 8, 0, 0, 4, tr10_ch234data };

static const unsigned char tr10_ch235data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0xa0
};
static const GLUTBitmapChar tr10_ch235 = { 3, 7, 0, 0, 4, tr10_ch235data };

static const unsigned char tr10_ch236data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0x40,0x80
};
static const GLUTBitmapChar tr10_ch236 = { 3, 8, 0, 0, 4, tr10_ch236data };

static const unsigned char tr10_ch237data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0x40,0x20
};
static const GLUTBitmapChar tr10_ch237 = { 3, 8, 0, 0, 4, tr10_ch237data };

static const unsigned char tr10_ch238data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch238 = { 3, 8, 0, 0, 4, tr10_ch238data };

static const unsigned char tr10_ch239data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0xa0
};
static const GLUTBitmapChar tr10_ch239 = { 3, 7, 0, 0, 4, tr10_ch239data };

static const unsigned char tr10_ch240data[] = {
   0x60,0x90,0x90,0x90,0x70,0xa0,0x70,0x40
};
static const GLUTBitmapChar tr10_ch240 = { 4, 8, 0, 0, 5, tr10_ch240data };

static const unsigned char tr10_ch241data[] = {
   0xd8,0x90,0x90,0x90,0xe0,0x0,0xa0,0x50
};
static const GLUTBitmapChar tr10_ch241 = { 5, 8, 0, 0, 5, tr10_ch241data };

static const unsigned char tr10_ch242data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0x20,0x40
};
static const GLUTBitmapChar tr10_ch242 = { 4, 8, 0, 0, 5, tr10_ch242data };

static const unsigned char tr10_ch243data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0x40,0x20
};
static const GLUTBitmapChar tr10_ch243 = { 4, 8, 0, 0, 5, tr10_ch243data };

static const unsigned char tr10_ch244data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0xa0,0x40
};
static const GLUTBitmapChar tr10_ch244 = { 4, 8, 0, 0, 5, tr10_ch244data };

static const unsigned char tr10_ch245data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0xa0,0x50
};
static const GLUTBitmapChar tr10_ch245 = { 4, 8, 0, 0, 5, tr10_ch245data };

static const unsigned char tr10_ch246data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0xa0
};
static const GLUTBitmapChar tr10_ch246 = { 4, 7, 0, 0, 5, tr10_ch246data };

static const unsigned char tr10_ch247data[] = {
   0x20,0x0,0xf8,0x0,0x20
};
static const GLUTBitmapChar tr10_ch247 = { 5, 5, 0, 0, 6, tr10_ch247data };

static const unsigned char tr10_ch248data[] = {
   0x80,0x70,0x48,0x48,0x48,0x38,0x4
};
static const GLUTBitmapChar tr10_ch248 = { 6, 7, 1, 1, 5, tr10_ch248data };

static const unsigned char tr10_ch249data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x20,0x40
};
static const GLUTBitmapChar tr10_ch249 = { 5, 8, 0, 0, 5, tr10_ch249data };

static const unsigned char tr10_ch250data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x40,0x20
};
static const GLUTBitmapChar tr10_ch250 = { 5, 8, 0, 0, 5, tr10_ch250data };

static const unsigned char tr10_ch251data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x50,0x20
};
static const GLUTBitmapChar tr10_ch251 = { 5, 8, 0, 0, 5, tr10_ch251data };

static const unsigned char tr10_ch252data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x50
};
static const GLUTBitmapChar tr10_ch252 = { 5, 7, 0, 0, 5, tr10_ch252data };

static const unsigned char tr10_ch253data[] = {
   0x80,0xc0,0x40,0x60,0xa0,0x90,0xb8,0x0,0x20,0x10
};
static const GLUTBitmapChar tr10_ch253 = { 5, 10, 0, 2, 5, tr10_ch253data };

static const unsigned char tr10_ch254data[] = {
   0xc0,0x80,0xe0,0x90,0x90,0x90,0xe0,0x80,0x80
};
static const GLUTBitmapChar tr10_ch254 = { 4, 9, 0, 2, 5, tr10_ch254data };

static const unsigned char tr10_ch255data[] = {
   0x80,0xc0,0x40,0x60,0xa0,0x90,0xb8,0x0,0xa0
};
static const GLUTBitmapChar tr10_ch255 = { 5, 9, 0, 2, 5, tr10_ch255data };


static const GLUTBitmapChar *tr10_chars[] = {
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   &tr10_ch32, &tr10_ch33, &tr10_ch34, &tr10_ch35, &tr10_ch36, &tr10_ch37, &tr10_ch38, &tr10_ch39, 
   &tr10_ch40, &tr10_ch41, &tr10_ch42, &tr10_ch43, &tr10_ch44, &tr10_ch45, &tr10_ch46, &tr10_ch47, 
   &tr10_ch48, &tr10_ch49, &tr10_ch50, &tr10_ch51, &tr10_ch52, &tr10_ch53, &tr10_ch54, &tr10_ch55, 
   &tr10_ch56, &tr10_ch57, &tr10_ch58, &tr10_ch59, &tr10_ch60, &tr10_ch61, &tr10_ch62, &tr10_ch63, 
   &tr10_ch64, &tr10_ch65, &tr10_ch66, &tr10_ch67, &tr10_ch68, &tr10_ch69, &tr10_ch70, &tr10_ch71, 
   &tr10_ch72, &tr10_ch73, &tr10_ch74, &tr10_ch75, &tr10_ch76, &tr10_ch77, &tr10_ch78, &tr10_ch79, 
   &tr10_ch80, &tr10_ch81, &tr10_ch82, &tr10_ch83, &tr10_ch84, &tr10_ch85, &tr10_ch86, &tr10_ch87, 
   &tr10_ch88, &tr10_ch89, &tr10_ch90, &tr10_ch91, &tr10_ch92, &tr10_ch93, &tr10_ch94, &tr10_ch95, 
   &tr10_ch96, &tr10_ch97, &tr10_ch98, &tr10_ch99, &tr10_ch100, &tr10_ch101, &tr10_ch102, &tr10_ch103, 
   &tr10_ch104, &tr10_ch105, &tr10_ch106, &tr10_ch107, &tr10_ch108, &tr10_ch109, &tr10_ch110, &tr10_ch111, 
   &tr10_ch112, &tr10_ch113, &tr10_ch114, &tr10_ch115, &tr10_ch116, &tr10_ch117, &tr10_ch118, &tr10_ch119, 
   &tr10_ch120, &tr10_ch121, &tr10_ch122, &tr10_ch123, &tr10_ch124, &tr10_ch125, &tr10_ch126, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   &tr10_ch160, &tr10_ch161, &tr10_ch162, &tr10_ch163, &tr10_ch164, &tr10_ch165, &tr10_ch166, &tr10_ch167, 
   &tr10_ch168, &tr10_ch169, &tr10_ch170, &tr10_ch171, &tr10_ch172, &tr10_ch173, &tr10_ch174, &tr10_ch175, 
   &tr10_ch176, &tr10_ch177, &tr10_ch178, &tr10_ch179, &tr10_ch180, &tr10_ch181, &tr10_ch182, &tr10_ch183, 
   &tr10_ch184, &tr10_ch185, &tr10_ch186, &tr10_ch187, &tr10_ch188, &tr10_ch189, &tr10_ch190, &tr10_ch191, 
   &tr10_ch192, &tr10_ch193, &tr10_ch194, &tr10_ch195, &tr10_ch196, &tr10_ch197, &tr10_ch198, &tr10_ch199, 
   &tr10_ch200, &tr10_ch201, &tr10_ch202, &tr10_ch203, &tr10_ch204, &tr10_ch205, &tr10_ch206, &tr10_ch207, 
   &tr10_ch208, &tr10_ch209, &tr10_ch210, &tr10_ch211, &tr10_ch212, &tr10_ch213, &tr10_ch214, &tr10_ch215, 
   &tr10_ch216, &tr10_ch217, &tr10_ch218, &tr10_ch219, &tr10_ch220, &tr10_ch221, &tr10_ch222, &tr10_ch223, 
   &tr10_ch224, &tr10_ch225, &tr10_ch226, &tr10_ch227, &tr10_ch228, &tr10_ch229, &tr10_ch230, &tr10_ch231, 
   &tr10_ch232, &tr10_ch233, &tr10_ch234, &tr10_ch235, &tr10_ch236, &tr10_ch237, &tr10_ch238, &tr10_ch239, 
   &tr10_ch240, &tr10_ch241, &tr10_ch242, &tr10_ch243, &tr10_ch244, &tr10_ch245, &tr10_ch246, &tr10_ch247, 
   &tr10_ch248, &tr10_ch249, &tr10_ch250, &tr10_ch251, &tr10_ch252, &tr10_ch253, &tr10_ch254, &tr10_ch255
};

static const GLUTBitmapFont _glutBitmapTimesRoman10 = {
   "-Adobe-Times-Medium-R-Normal--10-100-75-75-P-54-ISO8859-1",
   13, 256, tr10_chars
};

/* GLUTAPI void *glutBitmapTimesRoman10 = &_glutBitmapTimesRoman10; */
void * glutBitmapTimesRoman10 = (void *)&_glutBitmapTimesRoman10;
