struct PrefsHandle *	AllocPrefsHandle( APTR Name );
void						FreePrefsHandle( struct PrefsHandle *PrefsHandle );
void						SetPrefs( struct PrefsHandle *, ULONG ID, ULONG Tag, APTR Struct, UWORD Struct_Size );
ULONG						GetPrefs( struct PrefsHandle *, ULONG ID, ULONG Tag, APTR Struct, UWORD Struct_Size );
void						ReadPrefsHandle( struct PrefsHandle *, APTR Filename );
void						WritePrefsHandle( struct PrefsHandle *, APTR Filename );
struct PrefsStruct *	FindPrefs( struct PrefsHandle *, ULONG ID, ULONG Tag );
void						SetEntry( struct PrefsHandle *, ULONG ID, ULONG Tag, APTR Struct, UWORD Struct_Size, ULONG Entry );
ULONG						GetEntry( struct PrefsHandle *, ULONG ID, ULONG Tag, APTR Struct, UWORD Struct_Size, ULONG Entry );
BOOL						RemEntry( struct PrefsHandle *, ULONG ID, ULONG Tag, ULONG Entry );
