
BOOL					SCA_WBStart( APTR ArgArray , APTR Taglist, ULONG NumArgs );
void					SCA_SortNodes( struct ScalosNodeList *nodelist, struct Hook *, ULONG SortType );
struct AppObject *SCA_NewAddAppIcon( ULONG ID, ULONG UserData, struct Iconobject *, struct MessagePort *, APTR Taglist );
struct AppObject *SCA_NewAddAppWindow( ULONG ID, ULONG UserData, struct Window *, struct MessagePort *, APTR Taglist );
struct AppObject *SCA_NewAddAppMenuItem( ULONG ID, ULONG UserData, APTR Text, struct MessagePort *, APTR Taglist );
BOOL					SCA_RemoveAppObject( struct AppObject * );
struct MinNode *	SCA_AllocStdNode( struct ScalosNodeList *, ULONG NodeType );
struct MinNode *	SCA_AllocNode( struct ScalosNodeList *, ULONG Size );
void					SCA_FreeNode( struct ScalosNodeList *, struct MinNode * );
void					SCA_FreeAllNodes( struct ScalosNodeList * );
void					SCA_MoveNode( struct ScalosNodeList *, struct ScalosNodeList *, struct MinNode * );
void					SCA_SwapNodes( struct MinNode *, struct MinNode *, struct ScalosNodeList * );
BOOL					SCA_OpenIconWindow( APTR taglist );
struct ScaWindowList *SCA_LockWindowList( LONG accessmode );
void					SCA_UnLockWindowList( void );
struct ScalosMessage *SCA_AllocMessage( ULONG messagetype, UWORD additional_size );
void					SCA_FreeMessage( struct ScalosMessage *message );
struct DragHandle *SCA_InitDrag( struct Screen *screen );
void					SCA_EndDrag( struct DragHandle *DragHandle );
BOOL					SCA_AddBob( struct DragHandle *DragHandle, struct Bitmap *, APTR Mask, ULONG Width, ULONG Height, LONG XOffset, LONG YOffset );
void					SCA_DrawDrag( struct DragHandle *DragHandle, LONG X, LONG Y, ULONG Flags );
void					SCA_UpdateIcon( UBYTE WindowType, APTR UpdateIconStruct, ULONG ui_SIZE );
ULONG					SCA_MakeWBArgs( APTR Buffer, struct ScaIconNode *, ULONG ArgsSize );
void					SCA_FreeWBArgs( APTR Buffer, ULONG Number, ULONG Flags );
void					SCA_RemapBitmap( struct Bitmap *SrcBitmap, struct Bitmap *DestBitmap, APTR PenArray );
void					SCA_ScreenTitleMsg( APTR Format, APTR Args );
struct ScalosClass *SCA_MakeScalosClass( APTR ClassName, APTR SuperClassName, UWORD InstSize, APTR DispFunc );
BOOL					SCA_FreeScalosClass( struct ScalosClass *ScalosClass );
Object *	SCA_NewScalosObject( APTR ClassName, APTR TagList );
void					SCA_DisposeScalosObject( Object *Object );
