#
# Makefile for PLUGIN (020831)
#

default:
	cd mpegv; make
	cd mpegvlo; make
	cd cvid; make
	cd h263; make
	cd twos; make
	cd a52; make
	cd mpega; make
	cd pcm; make
	cd mace; make
	cd ima4; make
	cd msvc; make
	cd svq1; make
	cd xanim; make
	cd real; make

