#ifndef AROSVERSION_H
#define AROSVERSION_H

/*
 * The version headers for AOS3/4 are generated by a tool.
 * We don't use this for the AROS version.
 */

#define VERSION 19
#define REVISION 9
#define VERSIONSTR "19.9"
#define COPYRIGHT "Mailtext Open Source Team"
#define AUTHOR ""
#define __DCOPYRIGHT "Mailtext Open Source Team"
#define __MCCVERSION "19"
#define __MCPVERSION "19"
#endif

