#ifndef SNOOPTEXT_H
#define SNOOPTEXT_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_ZERO 0
#define MSG_PAUSE_GAD 1
#define MSG_DISABLE_GAD 2
#define MSG_HIDE_GAD 3
#define MSG_QUIT_GAD 4
#define MSG_OPENLOG_GAD 5
#define MSG_APPENDLOG_GAD 6
#define MSG_STARTLOG_GAD 7
#define MSG_SERIALLOG_GAD 8
#define MSG_CLOSELOG_GAD 9
#define MSG_SAVESET_GAD 10
#define MSG_FUNCTION_GAD 11
#define MSG_SETUP_GAD 12
#define MSG_STATUS_GAD 13
#define MSG_USE_GAD 14
#define MSG_UNDO_GAD 15
#define MSG_CANCEL_GAD 16
#define MSG_FUNCTION_TITLE 17
#define MSG_SHOWFAILS_GAD 18
#define MSG_SHOWCLI_GAD 19
#define MSG_SHOWFULLPATHS_GAD 20
#define MSG_USEDEVNAMES_GAD 21
#define MSG_MONPACKETS_GAD 22
#define MSG_MONALLPACKETS_GAD 23
#define MSG_MONROMCALLS_GAD 24
#define MSG_IGNOREWB_GAD 25
#define MSG_FINDPORT_GAD 26
#define MSG_FINDRESIDENT_GAD 27
#define MSG_FINDSEMAPHORE_GAD 28
#define MSG_FINDTASK_GAD 29
#define MSG_LOCKSCREEN_GAD 30
#define MSG_OPENDEVICE_GAD 31
#define MSG_OPENFONT_GAD 32
#define MSG_OPENLIBRARY_GAD 33
#define MSG_OPENRESOURCE_GAD 34
#define MSG_READTOOLTYPES_GAD 35
#define MSG_SENDREXX_GAD 36
#define MSG_PACKET_NAME 37
#define MSG_CHANGEDIR_GAD 38
#define MSG_DELETE_GAD 39
#define MSG_EXECUTE_GAD 40
#define MSG_GETVAR_GAD 41
#define MSG_LOADSEG_GAD 42
#define MSG_LOCKFILE_GAD 43
#define MSG_MAKEDIR_GAD 44
#define MSG_MAKELINK_GAD 45
#define MSG_OPENFILE_GAD 46
#define MSG_RENAME_GAD 47
#define MSG_RUNCOMMAND_GAD 48
#define MSG_SETVAR_GAD 49
#define MSG_SYSTEM_GAD 50
#define MSG_SELSYSTEM_GAD 51
#define MSG_SELDOS_GAD 52
#define MSG_ALL_GAD 53
#define MSG_NONE_GAD 54
#define MSG_SELECTED_GAD 55
#define MSG_MATCHNAME_GAD 56
#define MSG_SYSFUNCS_GAD 57
#define MSG_DOSFUNCS_GAD 58
#define MSG_SETTINGS_TITLE 59
#define MSG_HIDEMETHOD_GAD 60
#define MSG_CYL_HIDE_GAD 61
#define MSG_CYL_ICONIFY_GAD 62
#define MSG_CYL_TOOLSMENU_GAD 63
#define MSG_CYL_NONE_GAD 64
#define MSG_OPENON_GAD 65
#define MSG_CYL_DEFSCREEN_GAD 66
#define MSG_CYL_FRONTSCREEN_GAD 67
#define MSG_CYL_NAMEDSCREEN_GAD 68
#define MSG_LOGMODE_GAD 69
#define MSG_CYL_PROMPT_USER_GAD 70
#define MSG_CYL_APPEND_GAD 71
#define MSG_CYL_OVERWRITE_GAD 72
#define MSG_CYL_SERIALPORT_GAD 73
#define MSG_FILEIO_GAD 74
#define MSG_CYL_AUTOMATIC_GAD 75
#define MSG_CYL_IMMEDIATE_GAD 76
#define MSG_CYL_BUFFERED_GAD 77
#define MSG_BUFFERSIZE_GAD 78
#define MSG_BUFFORMAT_GAD 79
#define MSG_LOGFORMAT_GAD 80
#define MSG_HOTKEY_GAD 81
#define MSG_SCREENNAME_GAD 82
#define MSG_LOGFILE_GAD 83
#define MSG_WINDOWFONT_GAD 84
#define MSG_BUFFERFONT_GAD 85
#define MSG_FORMATEDIT_GAD 86
#define MSG_FORMATCOPYP_GAD 87
#define MSG_FORMATCOPYF_GAD 88
#define MSG_FORMAT_TITLE 89
#define MSG_AVAILABLE_GAD 90
#define MSG_CURFORMAT_GAD 91
#define MSG_FIELDWIDTH_GAD 92
#define MSG_GFONT_TITLE 93
#define MSG_BFONT_TITLE 94
#define MSG_PROJECT_MENU 95
#define MSG_PROJECT_OPENLOG 96
#define MSG_PROJECT_CLOSELOG 97
#define MSG_PROJECT_PAUSE 98
#define MSG_PROJECT_DISABLE 99
#define MSG_PROJECT_STEP 100
#define MSG_PROJECT_PRI 101
#define MSG_PROJECT_PRI_A 102
#define MSG_PROJECT_PRI_B 103
#define MSG_PROJECT_PRI_C 104
#define MSG_PROJECT_PRI_D 105
#define MSG_PROJECT_PRI_E 106
#define MSG_PROJECT_PRI_F 107
#define MSG_PROJECT_PRI_G 108
#define MSG_PROJECT_HELP 109
#define MSG_PROJECT_ABOUT 110
#define MSG_PROJECT_HIDE 111
#define MSG_PROJECT_QUIT 112
#define MSG_WINDOWS_MENU 113
#define MSG_WINDOWS_SETUP 114
#define MSG_WINDOWS_FUNCTION 115
#define MSG_WINDOWS_FORMAT 116
#define MSG_WINDOWS_WIDTH 117
#define MSG_WINDOWS_WIDTH_1 118
#define MSG_WINDOWS_WIDTH_2 119
#define MSG_WINDOWS_WIDTH_3 120
#define MSG_WINDOWS_WIDTH_4 121
#define MSG_WINDOWS_WIDTH_5 122
#define MSG_WINDOWS_ROW_QUAL 123
#define MSG_WINDOWS_ROW_ANY 124
#define MSG_WINDOWS_ROW_NONE 125
#define MSG_WINDOWS_ROW_SHIFT 126
#define MSG_WINDOWS_ROW_ALT 127
#define MSG_WINDOWS_ROW_CTRL 128
#define MSG_WINDOWS_ROW_ALL 129
#define MSG_WINDOWS_SPACING 130
#define MSG_WINDOWS_SPACING_NONE 131
#define MSG_WINDOWS_SPACING_1P 132
#define MSG_WINDOWS_SPACING_2P 133
#define MSG_WINDOWS_REFRESH 134
#define MSG_WINDOWS_REF_SIMPLE 135
#define MSG_WINDOWS_REF_SMART 136
#define MSG_WINDOWS_ALIGN 137
#define MSG_WINDOWS_ALIGN_LEFT 138
#define MSG_WINDOWS_ALIGN_RIGHT 139
#define MSG_WINDOWS_SHOWSTATUS 140
#define MSG_WINDOWS_SHOWGADGETS 141
#define MSG_WINDOWS_AUTO_OPEN 142
#define MSG_WINDOWS_DISABLE_HIDDEN 143
#define MSG_SETTINGS_MENU 144
#define MSG_SETTINGS_LOAD 145
#define MSG_SETTINGS_SAVE 146
#define MSG_SETTINGS_SAVEAS 147
#define MSG_SETTINGS_RESETDEFAULTS 148
#define MSG_SETTINGS_LASTSAVED 149
#define MSG_SETTINGS_RESTORE 150
#define MSG_SETTINGS_CREATEICONS 151
#define MSG_BUFFER_MENU 152
#define MSG_BUFFER_COPYWIN 153
#define MSG_BUFFER_COPYBUF 154
#define MSG_BUFFER_SAVEWIN 155
#define MSG_BUFFER_SAVEBUF 156
#define MSG_BUFFER_CLEARBUF 157
#define MSG_CALL_COL 158
#define MSG_DATE_COL 159
#define MSG_HUNK_COL 160
#define MSG_PROCESSID_COL 161
#define MSG_SEGNAME_COL 162
#define MSG_TIME_COL 163
#define MSG_COUNT_COL 164
#define MSG_PROCNAME_COL 165
#define MSG_ACTION_COL 166
#define MSG_FILENAME_COL 167
#define MSG_OPTIONS_COL 168
#define MSG_RESULT_COL 169
#define MSG_ACT_FINDPORT 170
#define MSG_ACT_FINDRESIDENT 171
#define MSG_ACT_FINDSEM 172
#define MSG_ACT_FINDTASK 173
#define MSG_ACT_LOCKSCREEN 174
#define MSG_ACT_OPENDEV 175
#define MSG_ACT_OPENFONT 176
#define MSG_ACT_OPENLIB 177
#define MSG_ACT_OPENRES 178
#define MSG_ACT_FINDTOOL 179
#define MSG_ACT_MATCHTOOL 180
#define MSG_ACT_SENDREXX 181
#define MSG_ACT_CHANGEDIR 182
#define MSG_ACT_DELETE 183
#define MSG_ACT_PDELETE 184
#define MSG_ACT_EXECUTE 185
#define MSG_ACT_GETVAR 186
#define MSG_ACT_FINDVAR 187
#define MSG_ACT_LOCK 188
#define MSG_ACT_PLOCK 189
#define MSG_ACT_LOADSEG 190
#define MSG_ACT_NEWLOADSEG 191
#define MSG_ACT_MAKEDIR 192
#define MSG_ACT_PMAKEDIR 193
#define MSG_ACT_MAKELINK 194
#define MSG_ACT_PMAKELINK 195
#define MSG_ACT_OPEN 196
#define MSG_ACT_POPEN 197
#define MSG_ACT_RENAME 198
#define MSG_ACT_PRENAME 199
#define MSG_ACT_RENAME2 200
#define MSG_ACT_PRENAME2 201
#define MSG_ACT_RUNCOMMAND 202
#define MSG_ACT_SETVAR 203
#define MSG_ACT_KILLVAR 204
#define MSG_ACT_SYSTEM 205
#define MSG_ACT_STARTUP 206
#define MSG_ACT_GET_BLOCK 207
#define MSG_ACT_SET_MAP 208
#define MSG_ACT_DIE 209
#define MSG_ACT_EVENT 210
#define MSG_ACT_CURRENT_VOLUME 211
#define MSG_ACT_LOCATE_OBJECT 212
#define MSG_ACT_RENAME_DISK 213
#define MSG_ACT_FREE_LOCK 214
#define MSG_ACT_DELETE_OBJECT 215
#define MSG_ACT_RENAME_OBJECT 216
#define MSG_ACT_MORE_CACHE 217
#define MSG_ACT_COPY_DIR 218
#define MSG_ACT_WAIT_CHAR 219
#define MSG_ACT_SET_PROTECT 220
#define MSG_ACT_CREATE_DIR 221
#define MSG_ACT_EXAMINE_OBJECT 222
#define MSG_ACT_EXAMINE_NEXT 223
#define MSG_ACT_DISK_INFO 224
#define MSG_ACT_INFO 225
#define MSG_ACT_FLUSH 226
#define MSG_ACT_SET_COMMENT 227
#define MSG_ACT_PARENT 228
#define MSG_ACT_TIMER 229
#define MSG_ACT_INHIBIT 230
#define MSG_ACT_DISK_TYPE 231
#define MSG_ACT_DISK_CHANGE 232
#define MSG_ACT_SET_DATE 233
#define MSG_ACT_SAME_LOCK 234
#define MSG_ACT_READ 235
#define MSG_ACT_WRITE 236
#define MSG_ACT_SCREEN_MODE 237
#define MSG_ACT_CHANGE_SIGNAL 238
#define MSG_ACT_READ_RETURN 239
#define MSG_ACT_WRITE_RETURN 240
#define MSG_ACT_FINDUPDATE 241
#define MSG_ACT_FINDINPUT 242
#define MSG_ACT_FINDOUTPUT 243
#define MSG_ACT_END 244
#define MSG_ACT_SEEK 245
#define MSG_ACT_FORMAT 246
#define MSG_ACT_MAKE_LINK 247
#define MSG_ACT_SET_FILE_SIZE 248
#define MSG_ACT_WRITE_PROTECT 249
#define MSG_ACT_READ_LINK 250
#define MSG_ACT_FH_FROM_LOCK 251
#define MSG_ACT_IS_FILESYSTEM 252
#define MSG_ACT_CHANGE_MODE 253
#define MSG_ACT_COPY_DIR_FH 254
#define MSG_ACT_PARENT_FH 255
#define MSG_ACT_EXAMINE_ALL 256
#define MSG_ACT_EXAMINE_FH 257
#define MSG_ACT_EXAMINE_ALL_END 258
#define MSG_ACT_SET_OWNER 259
#define MSG_ACT_DOUBLE 260
#define MSG_ACT_FORCE 261
#define MSG_ACT_STACK 262
#define MSG_ACT_QUEUE 263
#define MSG_ACT_DROP 264
#define MSG_ACT_LOCK_RECORD 265
#define MSG_ACT_FREE_RECORD 266
#define MSG_ACT_ADD_NOTIFY 267
#define MSG_ACT_REMOVE_NOTIFY 268
#define MSG_ACT_SERIALIZE_DISK 269
#define MSG_ACT_GET_DISK_FSSM 270
#define MSG_ACT_FREE_DISK_FSSM 271
#define MSG_ACT_RAWPACKET 272
#define MSG_RES_OKAY 273
#define MSG_RES_FAIL 274
#define MSG_RES_PAUSE 275
#define MSG_RES_MISSED 276
#define MSG_NULLSTR 277
#define MSG_OPT_UNKNOWN 278
#define MSG_OPT_READ 279
#define MSG_OPT_WRITE 280
#define MSG_OPT_READBAD 281
#define MSG_OPT_MODIFY 282
#define MSG_OPT_LIBVER 283
#define MSG_OPT_DEVUNIT 284
#define MSG_OPT_FONTSIZE 285
#define MSG_OPT_SOFTLINK 286
#define MSG_OPT_HARDLINK 287
#define MSG_OPT_LOCAL 288
#define MSG_OPT_ALIAS 289
#define MSG_OPT_GLOBAL 290
#define MSG_OPT_ANY 291
#define MSG_OPT_EXECSINGLE 292
#define MSG_OPT_EXECBATCH 293
#define MSG_SEG_MODULE_NOT_FOUND 294
#define MSG_ASL_LOADCONFIG 295
#define MSG_ASL_SAVECONFIG 296
#define MSG_ASL_DEFLOGNAME 297
#define MSG_ASL_NEWLOGNAME 298
#define MSG_ASL_SAVEWINDOW 299
#define MSG_ASL_SAVEBUFFER 300
#define MSG_ERROR_OPENSET 301
#define MSG_ERROR_OPENFUNC 302
#define MSG_ERROR_OPENMAIN 303
#define MSG_ERROR_NOBUFMEM 304
#define MSG_ERROR_INITPATCHES 305
#define MSG_ERROR_OPENFORMAT 306
#define MSG_ERROR_CREATEMENUS 307
#define MSG_ERROR_INITGUI 308
#define MSG_ERROR_RESIZE 309
#define MSG_ERROR_OPENFONT 310
#define MSG_ERROR_OPENFILEREQ 311
#define MSG_ERROR_SAVING_SETTINGS 312
#define MSG_ERROR_LOADING_SETTINGS 313
#define MSG_ERROR_SAVING_BUFFER 314
#define MSG_ERROR_SAVING_WINDOW 315
#define MSG_ERROR_UNPATCH 316
#define MSG_ERROR_NO_DISKFONT 317
#define MSG_ERROR_NO_ASL 318
#define MSG_ERROR_OKAY 319
#define MSG_ERROR_CANCEL 320
#define MSG_ERROR_STARTLOG 321
#define MSG_ERROR_NO_SCREEN 322
#define MSG_ERROR_FONT_PROPORTIONAL 323
#define MSG_ERROR_COPY_WIN_TO_CLIP 324
#define MSG_ERROR_COPY_ALL_TO_CLIP 325
#define MSG_REQ_FILE_EXISTS 326
#define MSG_REQ_APPEND_OVERWRITE_CANCEL 327
#define MSG_ERROR_CLI_NOPARAM 328
#define MSG_ERROR_CLI_FAILED 329
#define MSG_ERROR_CLI_UNKNOWN 330
#define MSG_CLI_USAGE 331
#define MSG_CLI_HELPBANNER 332
#define MSG_CMD_UNKNOWN 333
#define MSG_CMD_FAIL 334
#define MSG_CMD_NOPARAM 335
#define MSG_CMD_HEADER 336
#define MSG_CMD_PROMPT 337
#define MSG_STATUS_NORMAL 338
#define MSG_STATUS_PAUSED 339
#define MSG_STATUS_DISABLED 340
#define MSG_STATUS_LOGFILE 341
#define MSG_STATUS_LOGDEVICE 342
#define MSG_STATUS_LOGDEBUG 343
#define MSG_STATUS_SAVESET 344
#define MSG_STATUS_LOADSET 345
#define MSG_LOG_START 346
#define MSG_LOG_STOP 347
#define MSG_LOG_DISABLED 348
#define MSG_LOG_ENABLED 349
#define MSG_ERROR_NO_AMIGAGUIDE 350
#define MSG_ERROR_CREATE_AMIGAGUIDE 351
#define MSG_ERROR_AGUIDE_GENERIC 352
#define MSG_ERROR_AGUIDE_CANT_OPEN 353
#define MSG_HELPFILE_NAME 354
#define MSG_LINK_MAIN 355
#define MSG_LINK_MAINWIN 356
#define MSG_LINK_FUNCWIN 357
#define MSG_LINK_SETUPWIN 358
#define MSG_LINK_FORMATWIN 359
#define MSG_LINK_MENU_PROJECT 360
#define MSG_LINK_MENU_WINDOW 361
#define MSG_LINK_MENU_SETTINGS 362
#define MSG_LINK_MENU_BUFFER 363
#define MSG_COMMODITY_DESC 364
#define MSG_INVALID_HOTKEY 365
#define MSG_APPMENU_NAME 366
#define MSG_ABOUT_SNOOPDOS 367
#define NUM_OF_MSGS 368

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_ZERO_STR "(NULL-MSGID)"
#define MSG_PAUSE_GAD_STR "_Pause"
#define MSG_DISABLE_GAD_STR "_Disable"
#define MSG_HIDE_GAD_STR "_Hide"
#define MSG_QUIT_GAD_STR "_Quit"
#define MSG_OPENLOG_GAD_STR "_Open Log..."
#define MSG_APPENDLOG_GAD_STR "Append L_og"
#define MSG_STARTLOG_GAD_STR "Start L_og"
#define MSG_SERIALLOG_GAD_STR "Serial L_og"
#define MSG_CLOSELOG_GAD_STR "_Close Log"
#define MSG_SAVESET_GAD_STR "S_ave Settings"
#define MSG_FUNCTION_GAD_STR "_Functions..."
#define MSG_SETUP_GAD_STR "_Setup..."
#define MSG_STATUS_GAD_STR "Status"
#define MSG_USE_GAD_STR "_Use"
#define MSG_UNDO_GAD_STR "U_ndo"
#define MSG_CANCEL_GAD_STR "_Cancel"
#define MSG_FUNCTION_TITLE_STR "SnoopDos Functions"
#define MSG_SHOWFAILS_GAD_STR "Only show _fails"
#define MSG_SHOWCLI_GAD_STR "Show CL_I number"
#define MSG_SHOWFULLPATHS_GAD_STR "Show full _paths"
#define MSG_USEDEVNAMES_GAD_STR "Use _device names"
#define MSG_MONPACKETS_GAD_STR "Monitor pac_kets"
#define MSG_MONALLPACKETS_GAD_STR "Packet debu_gger"
#define MSG_MONROMCALLS_GAD_STR "Monitor R_OM calls"
#define MSG_IGNOREWB_GAD_STR "Ignore _Workbench/Shell"
#define MSG_FINDPORT_GAD_STR "FindPort"
#define MSG_FINDRESIDENT_GAD_STR "FindResident"
#define MSG_FINDSEMAPHORE_GAD_STR "FindSemaphore"
#define MSG_FINDTASK_GAD_STR "FindTask"
#define MSG_LOCKSCREEN_GAD_STR "LockScreen"
#define MSG_OPENDEVICE_GAD_STR "OpenDevice"
#define MSG_OPENFONT_GAD_STR "OpenFont"
#define MSG_OPENLIBRARY_GAD_STR "OpenLibrary"
#define MSG_OPENRESOURCE_GAD_STR "OpenResource"
#define MSG_READTOOLTYPES_GAD_STR "ReadToolTypes"
#define MSG_SENDREXX_GAD_STR "SendRexx"
#define MSG_PACKET_NAME_STR "DOS Packet Monitor"
#define MSG_CHANGEDIR_GAD_STR "ChangeDir"
#define MSG_DELETE_GAD_STR "Delete"
#define MSG_EXECUTE_GAD_STR "Execute"
#define MSG_GETVAR_GAD_STR "GetVar"
#define MSG_LOADSEG_GAD_STR "LoadSeg"
#define MSG_LOCKFILE_GAD_STR "Lock"
#define MSG_MAKEDIR_GAD_STR "MakeDir"
#define MSG_MAKELINK_GAD_STR "MakeLink"
#define MSG_OPENFILE_GAD_STR "Open"
#define MSG_RENAME_GAD_STR "Rename"
#define MSG_RUNCOMMAND_GAD_STR "RunCommand"
#define MSG_SETVAR_GAD_STR "SetVar"
#define MSG_SYSTEM_GAD_STR "System"
#define MSG_SELSYSTEM_GAD_STR "_System"
#define MSG_SELDOS_GAD_STR "_AmigaDOS"
#define MSG_ALL_GAD_STR "All"
#define MSG_NONE_GAD_STR "None"
#define MSG_SELECTED_GAD_STR "Selected"
#define MSG_MATCHNAME_GAD_STR "_Match name"
#define MSG_SYSFUNCS_GAD_STR "System Functions"
#define MSG_DOSFUNCS_GAD_STR "AmigaDOS Functions"
#define MSG_SETTINGS_TITLE_STR "SnoopDos Settings"
#define MSG_HIDEMETHOD_GAD_STR "_Hide method"
#define MSG_CYL_HIDE_GAD_STR "Invisible"
#define MSG_CYL_ICONIFY_GAD_STR "Iconify"
#define MSG_CYL_TOOLSMENU_GAD_STR "Tools Menu"
#define MSG_CYL_NONE_GAD_STR "None"
#define MSG_OPENON_GAD_STR "Open _window on"
#define MSG_CYL_DEFSCREEN_GAD_STR "Default Screen"
#define MSG_CYL_FRONTSCREEN_GAD_STR "Front Screen"
#define MSG_CYL_NAMEDSCREEN_GAD_STR "Named Screen"
#define MSG_LOGMODE_GAD_STR "Log _mode"
#define MSG_CYL_PROMPT_USER_GAD_STR "Prompt User"
#define MSG_CYL_APPEND_GAD_STR "Append"
#define MSG_CYL_OVERWRITE_GAD_STR "Overwrite"
#define MSG_CYL_SERIALPORT_GAD_STR "Serial port"
#define MSG_FILEIO_GAD_STR "File _I/O"
#define MSG_CYL_AUTOMATIC_GAD_STR "Automatic"
#define MSG_CYL_IMMEDIATE_GAD_STR "Immediate"
#define MSG_CYL_BUFFERED_GAD_STR "Buffered"
#define MSG_BUFFERSIZE_GAD_STR "Scroll buffe_r (Kb)"
#define MSG_BUFFORMAT_GAD_STR "_Buffer format"
#define MSG_LOGFORMAT_GAD_STR "_Logfile format"
#define MSG_HOTKEY_GAD_STR "Hot_key"
#define MSG_SCREENNAME_GAD_STR "Screen n_ame"
#define MSG_LOGFILE_GAD_STR "L_og file"
#define MSG_WINDOWFONT_GAD_STR "Window _font"
#define MSG_BUFFERFONT_GAD_STR "Buffer fon_t"
#define MSG_FORMATEDIT_GAD_STR "_Edit..."
#define MSG_FORMATCOPYP_GAD_STR "Co_py"
#define MSG_FORMATCOPYF_GAD_STR "Co_py  \040"
#define MSG_FORMAT_TITLE_STR "SnoopDos Format Editor"
#define MSG_AVAILABLE_GAD_STR "Available Fields"
#define MSG_CURFORMAT_GAD_STR "Current Format"
#define MSG_FIELDWIDTH_GAD_STR "Field _width"
#define MSG_GFONT_TITLE_STR "Select a new gadget font"
#define MSG_BFONT_TITLE_STR "Select a new buffer font"
#define MSG_PROJECT_MENU_STR " \0Project"
#define MSG_PROJECT_OPENLOG_STR "N\0Open log..."
#define MSG_PROJECT_CLOSELOG_STR "C\0Close log"
#define MSG_PROJECT_PAUSE_STR "P\0Pause"
#define MSG_PROJECT_DISABLE_STR "D\0Disable"
#define MSG_PROJECT_STEP_STR "V\0Single step"
#define MSG_PROJECT_PRI_STR " \0Task priority"
#define MSG_PROJECT_PRI_A_STR " \0-5"
#define MSG_PROJECT_PRI_B_STR " \0-2"
#define MSG_PROJECT_PRI_C_STR " \0-1"
#define MSG_PROJECT_PRI_D_STR " \0 0"
#define MSG_PROJECT_PRI_E_STR " \0+1"
#define MSG_PROJECT_PRI_F_STR " \0+2"
#define MSG_PROJECT_PRI_G_STR " \0+5"
#define MSG_PROJECT_HELP_STR "?\0Help..."
#define MSG_PROJECT_ABOUT_STR "!\0About..."
#define MSG_PROJECT_HIDE_STR "H\0Hide"
#define MSG_PROJECT_QUIT_STR "Q\0Quit"
#define MSG_WINDOWS_MENU_STR " \0Windows"
#define MSG_WINDOWS_SETUP_STR "E\0Show setup..."
#define MSG_WINDOWS_FUNCTION_STR "U\0Show functions..."
#define MSG_WINDOWS_FORMAT_STR "M\0Show format..."
#define MSG_WINDOWS_WIDTH_STR " \0Change window width"
#define MSG_WINDOWS_WIDTH_1_STR "*\0Best fit"
#define MSG_WINDOWS_WIDTH_2_STR "7\0 78 columns"
#define MSG_WINDOWS_WIDTH_3_STR "9\0 79 columns"
#define MSG_WINDOWS_WIDTH_4_STR "8\0 80 columns"
#define MSG_WINDOWS_WIDTH_5_STR "3\000130 columns"
#define MSG_WINDOWS_ROW_QUAL_STR " \0Row selection key"
#define MSG_WINDOWS_ROW_ANY_STR " \0Ignore"
#define MSG_WINDOWS_ROW_NONE_STR " \0None"
#define MSG_WINDOWS_ROW_SHIFT_STR " \0Shift"
#define MSG_WINDOWS_ROW_ALT_STR " \0Alt"
#define MSG_WINDOWS_ROW_CTRL_STR " \0Ctrl"
#define MSG_WINDOWS_ROW_ALL_STR " \0All"
#define MSG_WINDOWS_SPACING_STR " \0Text spacing"
#define MSG_WINDOWS_SPACING_NONE_STR "0\0None"
#define MSG_WINDOWS_SPACING_1P_STR "1\0001 pixel"
#define MSG_WINDOWS_SPACING_2P_STR "2\0002 pixels"
#define MSG_WINDOWS_REFRESH_STR " \0Window type"
#define MSG_WINDOWS_REF_SIMPLE_STR " \0Simple refresh"
#define MSG_WINDOWS_REF_SMART_STR " \0Smart refresh"
#define MSG_WINDOWS_ALIGN_STR " \0Target name"
#define MSG_WINDOWS_ALIGN_LEFT_STR "[\0Left aligned"
#define MSG_WINDOWS_ALIGN_RIGHT_STR "]\0Right aligned"
#define MSG_WINDOWS_SHOWSTATUS_STR "T\0Show status line?"
#define MSG_WINDOWS_SHOWGADGETS_STR "G\0Show gadgets?"
#define MSG_WINDOWS_AUTO_OPEN_STR "K\0Auto-open on output?"
#define MSG_WINDOWS_DISABLE_HIDDEN_STR " \0Disable when hidden?"
#define MSG_SETTINGS_MENU_STR " \0Settings"
#define MSG_SETTINGS_LOAD_STR "O\0Load..."
#define MSG_SETTINGS_SAVE_STR "S\0Save"
#define MSG_SETTINGS_SAVEAS_STR "A\0Save as..."
#define MSG_SETTINGS_RESETDEFAULTS_STR "F\0Reset to defaults"
#define MSG_SETTINGS_LASTSAVED_STR "L\0Last saved"
#define MSG_SETTINGS_RESTORE_STR "R\0Restore"
#define MSG_SETTINGS_CREATEICONS_STR "I\0Create icons?"
#define MSG_BUFFER_MENU_STR " \0Buffer"
#define MSG_BUFFER_COPYWIN_STR "X\0Copy window to clip"
#define MSG_BUFFER_COPYBUF_STR "Y\0Copy buffer to clip"
#define MSG_BUFFER_SAVEWIN_STR "W\0Save window..."
#define MSG_BUFFER_SAVEBUF_STR "B\0Save buffer..."
#define MSG_BUFFER_CLEARBUF_STR "Z\0Clear buffer"
#define MSG_CALL_COL_STR "CallAddr"
#define MSG_DATE_COL_STR "Date"
#define MSG_HUNK_COL_STR "Hunk:Offset"
#define MSG_PROCESSID_COL_STR "Task ID"
#define MSG_SEGNAME_COL_STR "Segment Name"
#define MSG_TIME_COL_STR "Time"
#define MSG_COUNT_COL_STR "Count"
#define MSG_PROCNAME_COL_STR "Process Name"
#define MSG_ACTION_COL_STR "Action"
#define MSG_FILENAME_COL_STR "Target Name"
#define MSG_OPTIONS_COL_STR "Options"
#define MSG_RESULT_COL_STR "Res."
#define MSG_ACT_FINDPORT_STR "FindPort"
#define MSG_ACT_FINDRESIDENT_STR "FindRes"
#define MSG_ACT_FINDSEM_STR "FindSem"
#define MSG_ACT_FINDTASK_STR "FindTask"
#define MSG_ACT_LOCKSCREEN_STR "LockScreen"
#define MSG_ACT_OPENDEV_STR "OpenDev"
#define MSG_ACT_OPENFONT_STR "OpenFont"
#define MSG_ACT_OPENLIB_STR "OpenLib"
#define MSG_ACT_OPENRES_STR "OpenRes"
#define MSG_ACT_FINDTOOL_STR "ToolType"
#define MSG_ACT_MATCHTOOL_STR "ToolValue"
#define MSG_ACT_SENDREXX_STR "SendRexx"
#define MSG_ACT_CHANGEDIR_STR "ChangeDir"
#define MSG_ACT_DELETE_STR "Delete"
#define MSG_ACT_PDELETE_STR "*Delete"
#define MSG_ACT_EXECUTE_STR "Execute"
#define MSG_ACT_GETVAR_STR "GetVar"
#define MSG_ACT_FINDVAR_STR "FindVar"
#define MSG_ACT_LOCK_STR "Lock"
#define MSG_ACT_PLOCK_STR "*Lock"
#define MSG_ACT_LOADSEG_STR "Load"
#define MSG_ACT_NEWLOADSEG_STR "NewLoad"
#define MSG_ACT_MAKEDIR_STR "MakeDir"
#define MSG_ACT_PMAKEDIR_STR "*MakeDir"
#define MSG_ACT_MAKELINK_STR "MakeLink"
#define MSG_ACT_PMAKELINK_STR "*MakeLink"
#define MSG_ACT_OPEN_STR "Open"
#define MSG_ACT_POPEN_STR "*Open"
#define MSG_ACT_RENAME_STR "Rename"
#define MSG_ACT_PRENAME_STR "*Rename"
#define MSG_ACT_RENAME2_STR "to -->"
#define MSG_ACT_PRENAME2_STR "*to -->"
#define MSG_ACT_RUNCOMMAND_STR "RunCommand"
#define MSG_ACT_SETVAR_STR "SetVar"
#define MSG_ACT_KILLVAR_STR "KillVar"
#define MSG_ACT_SYSTEM_STR "System"
#define MSG_ACT_STARTUP_STR "#STARTUP"
#define MSG_ACT_GET_BLOCK_STR "#GET_BLOCK"
#define MSG_ACT_SET_MAP_STR "#SET_MAP"
#define MSG_ACT_DIE_STR "#DIE"
#define MSG_ACT_EVENT_STR "#EVENT"
#define MSG_ACT_CURRENT_VOLUME_STR "#CUR_VOLUME"
#define MSG_ACT_LOCATE_OBJECT_STR "#LOC_OBJECT"
#define MSG_ACT_RENAME_DISK_STR "#REN_DISK"
#define MSG_ACT_FREE_LOCK_STR "#FREE_LOCK"
#define MSG_ACT_DELETE_OBJECT_STR "#DEL_OBJECT"
#define MSG_ACT_RENAME_OBJECT_STR "#REN_OBJECT"
#define MSG_ACT_MORE_CACHE_STR "#MORE_CACHE"
#define MSG_ACT_COPY_DIR_STR "#COPY_DIR"
#define MSG_ACT_WAIT_CHAR_STR "#WAIT_CHAR"
#define MSG_ACT_SET_PROTECT_STR "#SET_PROTECT"
#define MSG_ACT_CREATE_DIR_STR "#CREATE_DIR"
#define MSG_ACT_EXAMINE_OBJECT_STR "#EXAM_OBJECT"
#define MSG_ACT_EXAMINE_NEXT_STR "#EXAM_NEXT"
#define MSG_ACT_DISK_INFO_STR "#DISK_INFO"
#define MSG_ACT_INFO_STR "#INFO"
#define MSG_ACT_FLUSH_STR "#FLUSH"
#define MSG_ACT_SET_COMMENT_STR "#SET_COMMENT"
#define MSG_ACT_PARENT_STR "#PARENT"
#define MSG_ACT_TIMER_STR "#TIMER"
#define MSG_ACT_INHIBIT_STR "#INHIBIT"
#define MSG_ACT_DISK_TYPE_STR "#DISK_TYPE"
#define MSG_ACT_DISK_CHANGE_STR "#DISK_CHANGE"
#define MSG_ACT_SET_DATE_STR "#SET_DATE"
#define MSG_ACT_SAME_LOCK_STR "#SAME_LOCK"
#define MSG_ACT_READ_STR "#READ"
#define MSG_ACT_WRITE_STR "#WRITE"
#define MSG_ACT_SCREEN_MODE_STR "#SCREEN_MODE"
#define MSG_ACT_CHANGE_SIGNAL_STR "#CHANGE_SIG"
#define MSG_ACT_READ_RETURN_STR "#READ_RET"
#define MSG_ACT_WRITE_RETURN_STR "#WRITE_RET"
#define MSG_ACT_FINDUPDATE_STR "#FINDUPDATE"
#define MSG_ACT_FINDINPUT_STR "#FINDINPUT"
#define MSG_ACT_FINDOUTPUT_STR "#FINDOUTPUT"
#define MSG_ACT_END_STR "#END"
#define MSG_ACT_SEEK_STR "#SEEK"
#define MSG_ACT_FORMAT_STR "#FORMAT"
#define MSG_ACT_MAKE_LINK_STR "#MAKE_LINK"
#define MSG_ACT_SET_FILE_SIZE_STR "#SET_FILE_SIZE"
#define MSG_ACT_WRITE_PROTECT_STR "#WRITE_PROTECT"
#define MSG_ACT_READ_LINK_STR "#READ_LINK"
#define MSG_ACT_FH_FROM_LOCK_STR "#FH_FROM_LOCK"
#define MSG_ACT_IS_FILESYSTEM_STR "#IS_FILESYSTEM"
#define MSG_ACT_CHANGE_MODE_STR "#CHANGE_MODE"
#define MSG_ACT_COPY_DIR_FH_STR "#COPY_DIR_FH"
#define MSG_ACT_PARENT_FH_STR "#PARENT_FH"
#define MSG_ACT_EXAMINE_ALL_STR "#EXAM_ALL"
#define MSG_ACT_EXAMINE_FH_STR "#EXAM_FH"
#define MSG_ACT_EXAMINE_ALL_END_STR "#EXAM_ALL_END"
#define MSG_ACT_SET_OWNER_STR "#SET_OWNER"
#define MSG_ACT_DOUBLE_STR "#DOUBLE"
#define MSG_ACT_FORCE_STR "#FORCE"
#define MSG_ACT_STACK_STR "#STACK"
#define MSG_ACT_QUEUE_STR "#QUEUE"
#define MSG_ACT_DROP_STR "#DROP"
#define MSG_ACT_LOCK_RECORD_STR "#LOCK_RECORD"
#define MSG_ACT_FREE_RECORD_STR "#FREE_RECORD"
#define MSG_ACT_ADD_NOTIFY_STR "#ADD_NOTIFY"
#define MSG_ACT_REMOVE_NOTIFY_STR "#REMOVE_NOTIFY"
#define MSG_ACT_SERIALIZE_DISK_STR "#SERIALISE_DISK"
#define MSG_ACT_GET_DISK_FSSM_STR "#GET_DISK_FSSM"
#define MSG_ACT_FREE_DISK_FSSM_STR "#FREE_DISK_FSSM"
#define MSG_ACT_RAWPACKET_STR "#(%ld)"
#define MSG_RES_OKAY_STR "OK"
#define MSG_RES_FAIL_STR "Fail"
#define MSG_RES_PAUSE_STR "WAIT"
#define MSG_RES_MISSED_STR "Missed"
#define MSG_NULLSTR_STR "<NULL>"
#define MSG_OPT_UNKNOWN_STR "Unknown"
#define MSG_OPT_READ_STR "Read"
#define MSG_OPT_WRITE_STR "Write"
#define MSG_OPT_READBAD_STR "Read???"
#define MSG_OPT_MODIFY_STR "Modify"
#define MSG_OPT_LIBVER_STR "Ver %ld"
#define MSG_OPT_DEVUNIT_STR "Unit %ld"
#define MSG_OPT_FONTSIZE_STR "Size %ld"
#define MSG_OPT_SOFTLINK_STR "Soft"
#define MSG_OPT_HARDLINK_STR "Hard"
#define MSG_OPT_LOCAL_STR "Local"
#define MSG_OPT_ALIAS_STR "Alias"
#define MSG_OPT_GLOBAL_STR "Global"
#define MSG_OPT_ANY_STR "Any"
#define MSG_OPT_EXECSINGLE_STR "Single"
#define MSG_OPT_EXECBATCH_STR "Batch"
#define MSG_SEG_MODULE_NOT_FOUND_STR "Module not found"
#define MSG_ASL_LOADCONFIG_STR "Load settings file"
#define MSG_ASL_SAVECONFIG_STR "Save settings file"
#define MSG_ASL_DEFLOGNAME_STR "Select default log file or device"
#define MSG_ASL_NEWLOGNAME_STR "Select new log file or device"
#define MSG_ASL_SAVEWINDOW_STR "Save window contents as..."
#define MSG_ASL_SAVEBUFFER_STR "Save buffer contents as..."
#define MSG_ERROR_OPENSET_STR "Error opening Settings window!"
#define MSG_ERROR_OPENFUNC_STR "Error opening Functions window!"
#define MSG_ERROR_OPENMAIN_STR "Error opening main window!"
#define MSG_ERROR_NOBUFMEM_STR "Couldn't allocate %ldK\nof memory for new buffer\n(this is impossible!)"
#define MSG_ERROR_INITPATCHES_STR "Fatal error: couldn't install system patches."
#define MSG_ERROR_OPENFORMAT_STR "Error opening format editor window!"
#define MSG_ERROR_CREATEMENUS_STR "Error creating menus!"
#define MSG_ERROR_INITGUI_STR "Error initialising user interface!"
#define MSG_ERROR_RESIZE_STR "Error recreating gadgets after resize!"
#define MSG_ERROR_OPENFONT_STR "Error opening font requester!"
#define MSG_ERROR_OPENFILEREQ_STR "Error opening file requester!"
#define MSG_ERROR_SAVING_SETTINGS_STR "Error saving settings\nfile %s"
#define MSG_ERROR_LOADING_SETTINGS_STR "File %s is not a valid\nSnoopDos settings file."
#define MSG_ERROR_SAVING_BUFFER_STR "Error saving buffer contents to\nfile %s!"
#define MSG_ERROR_SAVING_WINDOW_STR "Error saving window contents to\nfile %s!"
#define MSG_ERROR_UNPATCH_STR "Warning: another application is still executing\nthe \"%s\" system function. I won't be able\nto fully quit until that application exits, but\nI won't bother you with any more requesters."
#define MSG_ERROR_NO_DISKFONT_STR "Error opening diskfont.library!\n\nFile and font requesters will be\nunavailable until diskfont.library\nis installed."
#define MSG_ERROR_NO_ASL_STR "Error opening asl.library!\n\nFile and font requesters will be\nunavailable until asl.library is\ninstalled."
#define MSG_ERROR_OKAY_STR "Okay"
#define MSG_ERROR_CANCEL_STR "Cancel"
#define MSG_ERROR_STARTLOG_STR "Error opening log file\n%s"
#define MSG_ERROR_NO_SCREEN_STR "Can't find a screen for SnoopDos to open on!"
#define MSG_ERROR_FONT_PROPORTIONAL_STR "Only fixed width fonts may be\nchosen for the buffer display."
#define MSG_ERROR_COPY_WIN_TO_CLIP_STR "Error copying window to clipboard!"
#define MSG_ERROR_COPY_ALL_TO_CLIP_STR "Error copying buffer to clipboard!"
#define MSG_REQ_FILE_EXISTS_STR "Warning: File %s already exists."
#define MSG_REQ_APPEND_OVERWRITE_CANCEL_STR "Append|Overwrite|Cancel"
#define MSG_ERROR_CLI_NOPARAM_STR "%s: Command requires a parameter.\n"
#define MSG_ERROR_CLI_FAILED_STR "%s: Command failed.\n"
#define MSG_ERROR_CLI_UNKNOWN_STR "%s: Unknown SnoopDos command.\n"
#define MSG_CLI_USAGE_STR "%s. Monitors DOS and System activity.\nUsage: %s [SETTINGS=filename] [LANGUAGE=filename] [HELP] commands ...\n"
#define MSG_CLI_HELPBANNER_STR "SnoopDos understands the following commands. Those marked * need a parameter.\nMost other commands can be prefixed by the word NO to reverse their effect.\nFor additional AmigaGuide help on any command, type SNOOPDOS HELP <cmdname>.\n\n"
#define MSG_CMD_UNKNOWN_STR "Unknown command: %s\n"
#define MSG_CMD_FAIL_STR "Command failed: %s\n"
#define MSG_CMD_NOPARAM_STR "Missing parameter: %s\n"
#define MSG_CMD_HEADER_STR "Enter SnoopDos command, EXIT to exit, or '?' for a command list.\n"
#define MSG_CMD_PROMPT_STR "SnoopDos>\040"
#define MSG_STATUS_NORMAL_STR "Monitoring system activity"
#define MSG_STATUS_PAUSED_STR "Paused at %ld:%02ld %s"
#define MSG_STATUS_DISABLED_STR "Disabled at %ld:%02ld %s"
#define MSG_STATUS_LOGFILE_STR "Logging to file %s"
#define MSG_STATUS_LOGDEVICE_STR "Logging to device %s"
#define MSG_STATUS_LOGDEBUG_STR "Logging to serial port debugger"
#define MSG_STATUS_SAVESET_STR "Saving settings to %s"
#define MSG_STATUS_LOADSET_STR "Loading settings from %s"
#define MSG_LOG_START_STR "\nSnoopDos logging started on %s, %s at %s\n\n"
#define MSG_LOG_STOP_STR "\nClosed SnoopDos log at %s\n"
#define MSG_LOG_DISABLED_STR "SnoopDos disabled at %s\n"
#define MSG_LOG_ENABLED_STR "SnoopDos enabled  at %s\n"
#define MSG_ERROR_NO_AMIGAGUIDE_STR "Can't open amigaguide.library v34.\nThus, no help is available."
#define MSG_ERROR_CREATE_AMIGAGUIDE_STR "Unexpected error while accessing AmigaGuide.\nNo help is available at this time."
#define MSG_ERROR_AGUIDE_GENERIC_STR "AmigaGuide error:\n%s"
#define MSG_ERROR_AGUIDE_CANT_OPEN_STR "Can't open help file %s. If you\nwant online help to be available, copy that\nfile to the directory HELP:ENGLISH."
#define MSG_HELPFILE_NAME_STR "SnoopDos.guide"
#define MSG_LINK_MAIN_STR "LINK MAIN"
#define MSG_LINK_MAINWIN_STR "LINK MainWindow"
#define MSG_LINK_FUNCWIN_STR "LINK FunctionWindow"
#define MSG_LINK_SETUPWIN_STR "LINK SettingsWindow"
#define MSG_LINK_FORMATWIN_STR "LINK FormatEditor"
#define MSG_LINK_MENU_PROJECT_STR "LINK Menu_Project"
#define MSG_LINK_MENU_WINDOW_STR "LINK Menu_Windows"
#define MSG_LINK_MENU_SETTINGS_STR "LINK Menu_Settings"
#define MSG_LINK_MENU_BUFFER_STR "LINK Menu_Buffer"
#define MSG_COMMODITY_DESC_STR "AmigaDOS and System monitor"
#define MSG_INVALID_HOTKEY_STR "invalid"
#define MSG_APPMENU_NAME_STR "Show SnoopDos"
#define MSG_ABOUT_SNOOPDOS_STR "%s\n\nAuthor: Eddy Carroll (ecarroll@iol.ie)\n\nARexx port name: %s\n\nThis release of SnoopDos may be freely distributed.\nIt may not be commercially distributed without the\nexplicit permission of the author. See the docs for\nmore details.\n\nFull source code is available from any Aminet site\nas /pub/aminet/util/moni/snoopdos31_src.lha."
#define NUM_OF_MSGS_STR "(end)"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG   cca_ID;
    STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
    {MSG_ZERO,(STRPTR)MSG_ZERO_STR},
    {MSG_PAUSE_GAD,(STRPTR)MSG_PAUSE_GAD_STR},
    {MSG_DISABLE_GAD,(STRPTR)MSG_DISABLE_GAD_STR},
    {MSG_HIDE_GAD,(STRPTR)MSG_HIDE_GAD_STR},
    {MSG_QUIT_GAD,(STRPTR)MSG_QUIT_GAD_STR},
    {MSG_OPENLOG_GAD,(STRPTR)MSG_OPENLOG_GAD_STR},
    {MSG_APPENDLOG_GAD,(STRPTR)MSG_APPENDLOG_GAD_STR},
    {MSG_STARTLOG_GAD,(STRPTR)MSG_STARTLOG_GAD_STR},
    {MSG_SERIALLOG_GAD,(STRPTR)MSG_SERIALLOG_GAD_STR},
    {MSG_CLOSELOG_GAD,(STRPTR)MSG_CLOSELOG_GAD_STR},
    {MSG_SAVESET_GAD,(STRPTR)MSG_SAVESET_GAD_STR},
    {MSG_FUNCTION_GAD,(STRPTR)MSG_FUNCTION_GAD_STR},
    {MSG_SETUP_GAD,(STRPTR)MSG_SETUP_GAD_STR},
    {MSG_STATUS_GAD,(STRPTR)MSG_STATUS_GAD_STR},
    {MSG_USE_GAD,(STRPTR)MSG_USE_GAD_STR},
    {MSG_UNDO_GAD,(STRPTR)MSG_UNDO_GAD_STR},
    {MSG_CANCEL_GAD,(STRPTR)MSG_CANCEL_GAD_STR},
    {MSG_FUNCTION_TITLE,(STRPTR)MSG_FUNCTION_TITLE_STR},
    {MSG_SHOWFAILS_GAD,(STRPTR)MSG_SHOWFAILS_GAD_STR},
    {MSG_SHOWCLI_GAD,(STRPTR)MSG_SHOWCLI_GAD_STR},
    {MSG_SHOWFULLPATHS_GAD,(STRPTR)MSG_SHOWFULLPATHS_GAD_STR},
    {MSG_USEDEVNAMES_GAD,(STRPTR)MSG_USEDEVNAMES_GAD_STR},
    {MSG_MONPACKETS_GAD,(STRPTR)MSG_MONPACKETS_GAD_STR},
    {MSG_MONALLPACKETS_GAD,(STRPTR)MSG_MONALLPACKETS_GAD_STR},
    {MSG_MONROMCALLS_GAD,(STRPTR)MSG_MONROMCALLS_GAD_STR},
    {MSG_IGNOREWB_GAD,(STRPTR)MSG_IGNOREWB_GAD_STR},
    {MSG_FINDPORT_GAD,(STRPTR)MSG_FINDPORT_GAD_STR},
    {MSG_FINDRESIDENT_GAD,(STRPTR)MSG_FINDRESIDENT_GAD_STR},
    {MSG_FINDSEMAPHORE_GAD,(STRPTR)MSG_FINDSEMAPHORE_GAD_STR},
    {MSG_FINDTASK_GAD,(STRPTR)MSG_FINDTASK_GAD_STR},
    {MSG_LOCKSCREEN_GAD,(STRPTR)MSG_LOCKSCREEN_GAD_STR},
    {MSG_OPENDEVICE_GAD,(STRPTR)MSG_OPENDEVICE_GAD_STR},
    {MSG_OPENFONT_GAD,(STRPTR)MSG_OPENFONT_GAD_STR},
    {MSG_OPENLIBRARY_GAD,(STRPTR)MSG_OPENLIBRARY_GAD_STR},
    {MSG_OPENRESOURCE_GAD,(STRPTR)MSG_OPENRESOURCE_GAD_STR},
    {MSG_READTOOLTYPES_GAD,(STRPTR)MSG_READTOOLTYPES_GAD_STR},
    {MSG_SENDREXX_GAD,(STRPTR)MSG_SENDREXX_GAD_STR},
    {MSG_PACKET_NAME,(STRPTR)MSG_PACKET_NAME_STR},
    {MSG_CHANGEDIR_GAD,(STRPTR)MSG_CHANGEDIR_GAD_STR},
    {MSG_DELETE_GAD,(STRPTR)MSG_DELETE_GAD_STR},
    {MSG_EXECUTE_GAD,(STRPTR)MSG_EXECUTE_GAD_STR},
    {MSG_GETVAR_GAD,(STRPTR)MSG_GETVAR_GAD_STR},
    {MSG_LOADSEG_GAD,(STRPTR)MSG_LOADSEG_GAD_STR},
    {MSG_LOCKFILE_GAD,(STRPTR)MSG_LOCKFILE_GAD_STR},
    {MSG_MAKEDIR_GAD,(STRPTR)MSG_MAKEDIR_GAD_STR},
    {MSG_MAKELINK_GAD,(STRPTR)MSG_MAKELINK_GAD_STR},
    {MSG_OPENFILE_GAD,(STRPTR)MSG_OPENFILE_GAD_STR},
    {MSG_RENAME_GAD,(STRPTR)MSG_RENAME_GAD_STR},
    {MSG_RUNCOMMAND_GAD,(STRPTR)MSG_RUNCOMMAND_GAD_STR},
    {MSG_SETVAR_GAD,(STRPTR)MSG_SETVAR_GAD_STR},
    {MSG_SYSTEM_GAD,(STRPTR)MSG_SYSTEM_GAD_STR},
    {MSG_SELSYSTEM_GAD,(STRPTR)MSG_SELSYSTEM_GAD_STR},
    {MSG_SELDOS_GAD,(STRPTR)MSG_SELDOS_GAD_STR},
    {MSG_ALL_GAD,(STRPTR)MSG_ALL_GAD_STR},
    {MSG_NONE_GAD,(STRPTR)MSG_NONE_GAD_STR},
    {MSG_SELECTED_GAD,(STRPTR)MSG_SELECTED_GAD_STR},
    {MSG_MATCHNAME_GAD,(STRPTR)MSG_MATCHNAME_GAD_STR},
    {MSG_SYSFUNCS_GAD,(STRPTR)MSG_SYSFUNCS_GAD_STR},
    {MSG_DOSFUNCS_GAD,(STRPTR)MSG_DOSFUNCS_GAD_STR},
    {MSG_SETTINGS_TITLE,(STRPTR)MSG_SETTINGS_TITLE_STR},
    {MSG_HIDEMETHOD_GAD,(STRPTR)MSG_HIDEMETHOD_GAD_STR},
    {MSG_CYL_HIDE_GAD,(STRPTR)MSG_CYL_HIDE_GAD_STR},
    {MSG_CYL_ICONIFY_GAD,(STRPTR)MSG_CYL_ICONIFY_GAD_STR},
    {MSG_CYL_TOOLSMENU_GAD,(STRPTR)MSG_CYL_TOOLSMENU_GAD_STR},
    {MSG_CYL_NONE_GAD,(STRPTR)MSG_CYL_NONE_GAD_STR},
    {MSG_OPENON_GAD,(STRPTR)MSG_OPENON_GAD_STR},
    {MSG_CYL_DEFSCREEN_GAD,(STRPTR)MSG_CYL_DEFSCREEN_GAD_STR},
    {MSG_CYL_FRONTSCREEN_GAD,(STRPTR)MSG_CYL_FRONTSCREEN_GAD_STR},
    {MSG_CYL_NAMEDSCREEN_GAD,(STRPTR)MSG_CYL_NAMEDSCREEN_GAD_STR},
    {MSG_LOGMODE_GAD,(STRPTR)MSG_LOGMODE_GAD_STR},
    {MSG_CYL_PROMPT_USER_GAD,(STRPTR)MSG_CYL_PROMPT_USER_GAD_STR},
    {MSG_CYL_APPEND_GAD,(STRPTR)MSG_CYL_APPEND_GAD_STR},
    {MSG_CYL_OVERWRITE_GAD,(STRPTR)MSG_CYL_OVERWRITE_GAD_STR},
    {MSG_CYL_SERIALPORT_GAD,(STRPTR)MSG_CYL_SERIALPORT_GAD_STR},
    {MSG_FILEIO_GAD,(STRPTR)MSG_FILEIO_GAD_STR},
    {MSG_CYL_AUTOMATIC_GAD,(STRPTR)MSG_CYL_AUTOMATIC_GAD_STR},
    {MSG_CYL_IMMEDIATE_GAD,(STRPTR)MSG_CYL_IMMEDIATE_GAD_STR},
    {MSG_CYL_BUFFERED_GAD,(STRPTR)MSG_CYL_BUFFERED_GAD_STR},
    {MSG_BUFFERSIZE_GAD,(STRPTR)MSG_BUFFERSIZE_GAD_STR},
    {MSG_BUFFORMAT_GAD,(STRPTR)MSG_BUFFORMAT_GAD_STR},
    {MSG_LOGFORMAT_GAD,(STRPTR)MSG_LOGFORMAT_GAD_STR},
    {MSG_HOTKEY_GAD,(STRPTR)MSG_HOTKEY_GAD_STR},
    {MSG_SCREENNAME_GAD,(STRPTR)MSG_SCREENNAME_GAD_STR},
    {MSG_LOGFILE_GAD,(STRPTR)MSG_LOGFILE_GAD_STR},
    {MSG_WINDOWFONT_GAD,(STRPTR)MSG_WINDOWFONT_GAD_STR},
    {MSG_BUFFERFONT_GAD,(STRPTR)MSG_BUFFERFONT_GAD_STR},
    {MSG_FORMATEDIT_GAD,(STRPTR)MSG_FORMATEDIT_GAD_STR},
    {MSG_FORMATCOPYP_GAD,(STRPTR)MSG_FORMATCOPYP_GAD_STR},
    {MSG_FORMATCOPYF_GAD,(STRPTR)MSG_FORMATCOPYF_GAD_STR},
    {MSG_FORMAT_TITLE,(STRPTR)MSG_FORMAT_TITLE_STR},
    {MSG_AVAILABLE_GAD,(STRPTR)MSG_AVAILABLE_GAD_STR},
    {MSG_CURFORMAT_GAD,(STRPTR)MSG_CURFORMAT_GAD_STR},
    {MSG_FIELDWIDTH_GAD,(STRPTR)MSG_FIELDWIDTH_GAD_STR},
    {MSG_GFONT_TITLE,(STRPTR)MSG_GFONT_TITLE_STR},
    {MSG_BFONT_TITLE,(STRPTR)MSG_BFONT_TITLE_STR},
    {MSG_PROJECT_MENU,(STRPTR)MSG_PROJECT_MENU_STR},
    {MSG_PROJECT_OPENLOG,(STRPTR)MSG_PROJECT_OPENLOG_STR},
    {MSG_PROJECT_CLOSELOG,(STRPTR)MSG_PROJECT_CLOSELOG_STR},
    {MSG_PROJECT_PAUSE,(STRPTR)MSG_PROJECT_PAUSE_STR},
    {MSG_PROJECT_DISABLE,(STRPTR)MSG_PROJECT_DISABLE_STR},
    {MSG_PROJECT_STEP,(STRPTR)MSG_PROJECT_STEP_STR},
    {MSG_PROJECT_PRI,(STRPTR)MSG_PROJECT_PRI_STR},
    {MSG_PROJECT_PRI_A,(STRPTR)MSG_PROJECT_PRI_A_STR},
    {MSG_PROJECT_PRI_B,(STRPTR)MSG_PROJECT_PRI_B_STR},
    {MSG_PROJECT_PRI_C,(STRPTR)MSG_PROJECT_PRI_C_STR},
    {MSG_PROJECT_PRI_D,(STRPTR)MSG_PROJECT_PRI_D_STR},
    {MSG_PROJECT_PRI_E,(STRPTR)MSG_PROJECT_PRI_E_STR},
    {MSG_PROJECT_PRI_F,(STRPTR)MSG_PROJECT_PRI_F_STR},
    {MSG_PROJECT_PRI_G,(STRPTR)MSG_PROJECT_PRI_G_STR},
    {MSG_PROJECT_HELP,(STRPTR)MSG_PROJECT_HELP_STR},
    {MSG_PROJECT_ABOUT,(STRPTR)MSG_PROJECT_ABOUT_STR},
    {MSG_PROJECT_HIDE,(STRPTR)MSG_PROJECT_HIDE_STR},
    {MSG_PROJECT_QUIT,(STRPTR)MSG_PROJECT_QUIT_STR},
    {MSG_WINDOWS_MENU,(STRPTR)MSG_WINDOWS_MENU_STR},
    {MSG_WINDOWS_SETUP,(STRPTR)MSG_WINDOWS_SETUP_STR},
    {MSG_WINDOWS_FUNCTION,(STRPTR)MSG_WINDOWS_FUNCTION_STR},
    {MSG_WINDOWS_FORMAT,(STRPTR)MSG_WINDOWS_FORMAT_STR},
    {MSG_WINDOWS_WIDTH,(STRPTR)MSG_WINDOWS_WIDTH_STR},
    {MSG_WINDOWS_WIDTH_1,(STRPTR)MSG_WINDOWS_WIDTH_1_STR},
    {MSG_WINDOWS_WIDTH_2,(STRPTR)MSG_WINDOWS_WIDTH_2_STR},
    {MSG_WINDOWS_WIDTH_3,(STRPTR)MSG_WINDOWS_WIDTH_3_STR},
    {MSG_WINDOWS_WIDTH_4,(STRPTR)MSG_WINDOWS_WIDTH_4_STR},
    {MSG_WINDOWS_WIDTH_5,(STRPTR)MSG_WINDOWS_WIDTH_5_STR},
    {MSG_WINDOWS_ROW_QUAL,(STRPTR)MSG_WINDOWS_ROW_QUAL_STR},
    {MSG_WINDOWS_ROW_ANY,(STRPTR)MSG_WINDOWS_ROW_ANY_STR},
    {MSG_WINDOWS_ROW_NONE,(STRPTR)MSG_WINDOWS_ROW_NONE_STR},
    {MSG_WINDOWS_ROW_SHIFT,(STRPTR)MSG_WINDOWS_ROW_SHIFT_STR},
    {MSG_WINDOWS_ROW_ALT,(STRPTR)MSG_WINDOWS_ROW_ALT_STR},
    {MSG_WINDOWS_ROW_CTRL,(STRPTR)MSG_WINDOWS_ROW_CTRL_STR},
    {MSG_WINDOWS_ROW_ALL,(STRPTR)MSG_WINDOWS_ROW_ALL_STR},
    {MSG_WINDOWS_SPACING,(STRPTR)MSG_WINDOWS_SPACING_STR},
    {MSG_WINDOWS_SPACING_NONE,(STRPTR)MSG_WINDOWS_SPACING_NONE_STR},
    {MSG_WINDOWS_SPACING_1P,(STRPTR)MSG_WINDOWS_SPACING_1P_STR},
    {MSG_WINDOWS_SPACING_2P,(STRPTR)MSG_WINDOWS_SPACING_2P_STR},
    {MSG_WINDOWS_REFRESH,(STRPTR)MSG_WINDOWS_REFRESH_STR},
    {MSG_WINDOWS_REF_SIMPLE,(STRPTR)MSG_WINDOWS_REF_SIMPLE_STR},
    {MSG_WINDOWS_REF_SMART,(STRPTR)MSG_WINDOWS_REF_SMART_STR},
    {MSG_WINDOWS_ALIGN,(STRPTR)MSG_WINDOWS_ALIGN_STR},
    {MSG_WINDOWS_ALIGN_LEFT,(STRPTR)MSG_WINDOWS_ALIGN_LEFT_STR},
    {MSG_WINDOWS_ALIGN_RIGHT,(STRPTR)MSG_WINDOWS_ALIGN_RIGHT_STR},
    {MSG_WINDOWS_SHOWSTATUS,(STRPTR)MSG_WINDOWS_SHOWSTATUS_STR},
    {MSG_WINDOWS_SHOWGADGETS,(STRPTR)MSG_WINDOWS_SHOWGADGETS_STR},
    {MSG_WINDOWS_AUTO_OPEN,(STRPTR)MSG_WINDOWS_AUTO_OPEN_STR},
    {MSG_WINDOWS_DISABLE_HIDDEN,(STRPTR)MSG_WINDOWS_DISABLE_HIDDEN_STR},
    {MSG_SETTINGS_MENU,(STRPTR)MSG_SETTINGS_MENU_STR},
    {MSG_SETTINGS_LOAD,(STRPTR)MSG_SETTINGS_LOAD_STR},
    {MSG_SETTINGS_SAVE,(STRPTR)MSG_SETTINGS_SAVE_STR},
    {MSG_SETTINGS_SAVEAS,(STRPTR)MSG_SETTINGS_SAVEAS_STR},
    {MSG_SETTINGS_RESETDEFAULTS,(STRPTR)MSG_SETTINGS_RESETDEFAULTS_STR},
    {MSG_SETTINGS_LASTSAVED,(STRPTR)MSG_SETTINGS_LASTSAVED_STR},
    {MSG_SETTINGS_RESTORE,(STRPTR)MSG_SETTINGS_RESTORE_STR},
    {MSG_SETTINGS_CREATEICONS,(STRPTR)MSG_SETTINGS_CREATEICONS_STR},
    {MSG_BUFFER_MENU,(STRPTR)MSG_BUFFER_MENU_STR},
    {MSG_BUFFER_COPYWIN,(STRPTR)MSG_BUFFER_COPYWIN_STR},
    {MSG_BUFFER_COPYBUF,(STRPTR)MSG_BUFFER_COPYBUF_STR},
    {MSG_BUFFER_SAVEWIN,(STRPTR)MSG_BUFFER_SAVEWIN_STR},
    {MSG_BUFFER_SAVEBUF,(STRPTR)MSG_BUFFER_SAVEBUF_STR},
    {MSG_BUFFER_CLEARBUF,(STRPTR)MSG_BUFFER_CLEARBUF_STR},
    {MSG_CALL_COL,(STRPTR)MSG_CALL_COL_STR},
    {MSG_DATE_COL,(STRPTR)MSG_DATE_COL_STR},
    {MSG_HUNK_COL,(STRPTR)MSG_HUNK_COL_STR},
    {MSG_PROCESSID_COL,(STRPTR)MSG_PROCESSID_COL_STR},
    {MSG_SEGNAME_COL,(STRPTR)MSG_SEGNAME_COL_STR},
    {MSG_TIME_COL,(STRPTR)MSG_TIME_COL_STR},
    {MSG_COUNT_COL,(STRPTR)MSG_COUNT_COL_STR},
    {MSG_PROCNAME_COL,(STRPTR)MSG_PROCNAME_COL_STR},
    {MSG_ACTION_COL,(STRPTR)MSG_ACTION_COL_STR},
    {MSG_FILENAME_COL,(STRPTR)MSG_FILENAME_COL_STR},
    {MSG_OPTIONS_COL,(STRPTR)MSG_OPTIONS_COL_STR},
    {MSG_RESULT_COL,(STRPTR)MSG_RESULT_COL_STR},
    {MSG_ACT_FINDPORT,(STRPTR)MSG_ACT_FINDPORT_STR},
    {MSG_ACT_FINDRESIDENT,(STRPTR)MSG_ACT_FINDRESIDENT_STR},
    {MSG_ACT_FINDSEM,(STRPTR)MSG_ACT_FINDSEM_STR},
    {MSG_ACT_FINDTASK,(STRPTR)MSG_ACT_FINDTASK_STR},
    {MSG_ACT_LOCKSCREEN,(STRPTR)MSG_ACT_LOCKSCREEN_STR},
    {MSG_ACT_OPENDEV,(STRPTR)MSG_ACT_OPENDEV_STR},
    {MSG_ACT_OPENFONT,(STRPTR)MSG_ACT_OPENFONT_STR},
    {MSG_ACT_OPENLIB,(STRPTR)MSG_ACT_OPENLIB_STR},
    {MSG_ACT_OPENRES,(STRPTR)MSG_ACT_OPENRES_STR},
    {MSG_ACT_FINDTOOL,(STRPTR)MSG_ACT_FINDTOOL_STR},
    {MSG_ACT_MATCHTOOL,(STRPTR)MSG_ACT_MATCHTOOL_STR},
    {MSG_ACT_SENDREXX,(STRPTR)MSG_ACT_SENDREXX_STR},
    {MSG_ACT_CHANGEDIR,(STRPTR)MSG_ACT_CHANGEDIR_STR},
    {MSG_ACT_DELETE,(STRPTR)MSG_ACT_DELETE_STR},
    {MSG_ACT_PDELETE,(STRPTR)MSG_ACT_PDELETE_STR},
    {MSG_ACT_EXECUTE,(STRPTR)MSG_ACT_EXECUTE_STR},
    {MSG_ACT_GETVAR,(STRPTR)MSG_ACT_GETVAR_STR},
    {MSG_ACT_FINDVAR,(STRPTR)MSG_ACT_FINDVAR_STR},
    {MSG_ACT_LOCK,(STRPTR)MSG_ACT_LOCK_STR},
    {MSG_ACT_PLOCK,(STRPTR)MSG_ACT_PLOCK_STR},
    {MSG_ACT_LOADSEG,(STRPTR)MSG_ACT_LOADSEG_STR},
    {MSG_ACT_NEWLOADSEG,(STRPTR)MSG_ACT_NEWLOADSEG_STR},
    {MSG_ACT_MAKEDIR,(STRPTR)MSG_ACT_MAKEDIR_STR},
    {MSG_ACT_PMAKEDIR,(STRPTR)MSG_ACT_PMAKEDIR_STR},
    {MSG_ACT_MAKELINK,(STRPTR)MSG_ACT_MAKELINK_STR},
    {MSG_ACT_PMAKELINK,(STRPTR)MSG_ACT_PMAKELINK_STR},
    {MSG_ACT_OPEN,(STRPTR)MSG_ACT_OPEN_STR},
    {MSG_ACT_POPEN,(STRPTR)MSG_ACT_POPEN_STR},
    {MSG_ACT_RENAME,(STRPTR)MSG_ACT_RENAME_STR},
    {MSG_ACT_PRENAME,(STRPTR)MSG_ACT_PRENAME_STR},
    {MSG_ACT_RENAME2,(STRPTR)MSG_ACT_RENAME2_STR},
    {MSG_ACT_PRENAME2,(STRPTR)MSG_ACT_PRENAME2_STR},
    {MSG_ACT_RUNCOMMAND,(STRPTR)MSG_ACT_RUNCOMMAND_STR},
    {MSG_ACT_SETVAR,(STRPTR)MSG_ACT_SETVAR_STR},
    {MSG_ACT_KILLVAR,(STRPTR)MSG_ACT_KILLVAR_STR},
    {MSG_ACT_SYSTEM,(STRPTR)MSG_ACT_SYSTEM_STR},
    {MSG_ACT_STARTUP,(STRPTR)MSG_ACT_STARTUP_STR},
    {MSG_ACT_GET_BLOCK,(STRPTR)MSG_ACT_GET_BLOCK_STR},
    {MSG_ACT_SET_MAP,(STRPTR)MSG_ACT_SET_MAP_STR},
    {MSG_ACT_DIE,(STRPTR)MSG_ACT_DIE_STR},
    {MSG_ACT_EVENT,(STRPTR)MSG_ACT_EVENT_STR},
    {MSG_ACT_CURRENT_VOLUME,(STRPTR)MSG_ACT_CURRENT_VOLUME_STR},
    {MSG_ACT_LOCATE_OBJECT,(STRPTR)MSG_ACT_LOCATE_OBJECT_STR},
    {MSG_ACT_RENAME_DISK,(STRPTR)MSG_ACT_RENAME_DISK_STR},
    {MSG_ACT_FREE_LOCK,(STRPTR)MSG_ACT_FREE_LOCK_STR},
    {MSG_ACT_DELETE_OBJECT,(STRPTR)MSG_ACT_DELETE_OBJECT_STR},
    {MSG_ACT_RENAME_OBJECT,(STRPTR)MSG_ACT_RENAME_OBJECT_STR},
    {MSG_ACT_MORE_CACHE,(STRPTR)MSG_ACT_MORE_CACHE_STR},
    {MSG_ACT_COPY_DIR,(STRPTR)MSG_ACT_COPY_DIR_STR},
    {MSG_ACT_WAIT_CHAR,(STRPTR)MSG_ACT_WAIT_CHAR_STR},
    {MSG_ACT_SET_PROTECT,(STRPTR)MSG_ACT_SET_PROTECT_STR},
    {MSG_ACT_CREATE_DIR,(STRPTR)MSG_ACT_CREATE_DIR_STR},
    {MSG_ACT_EXAMINE_OBJECT,(STRPTR)MSG_ACT_EXAMINE_OBJECT_STR},
    {MSG_ACT_EXAMINE_NEXT,(STRPTR)MSG_ACT_EXAMINE_NEXT_STR},
    {MSG_ACT_DISK_INFO,(STRPTR)MSG_ACT_DISK_INFO_STR},
    {MSG_ACT_INFO,(STRPTR)MSG_ACT_INFO_STR},
    {MSG_ACT_FLUSH,(STRPTR)MSG_ACT_FLUSH_STR},
    {MSG_ACT_SET_COMMENT,(STRPTR)MSG_ACT_SET_COMMENT_STR},
    {MSG_ACT_PARENT,(STRPTR)MSG_ACT_PARENT_STR},
    {MSG_ACT_TIMER,(STRPTR)MSG_ACT_TIMER_STR},
    {MSG_ACT_INHIBIT,(STRPTR)MSG_ACT_INHIBIT_STR},
    {MSG_ACT_DISK_TYPE,(STRPTR)MSG_ACT_DISK_TYPE_STR},
    {MSG_ACT_DISK_CHANGE,(STRPTR)MSG_ACT_DISK_CHANGE_STR},
    {MSG_ACT_SET_DATE,(STRPTR)MSG_ACT_SET_DATE_STR},
    {MSG_ACT_SAME_LOCK,(STRPTR)MSG_ACT_SAME_LOCK_STR},
    {MSG_ACT_READ,(STRPTR)MSG_ACT_READ_STR},
    {MSG_ACT_WRITE,(STRPTR)MSG_ACT_WRITE_STR},
    {MSG_ACT_SCREEN_MODE,(STRPTR)MSG_ACT_SCREEN_MODE_STR},
    {MSG_ACT_CHANGE_SIGNAL,(STRPTR)MSG_ACT_CHANGE_SIGNAL_STR},
    {MSG_ACT_READ_RETURN,(STRPTR)MSG_ACT_READ_RETURN_STR},
    {MSG_ACT_WRITE_RETURN,(STRPTR)MSG_ACT_WRITE_RETURN_STR},
    {MSG_ACT_FINDUPDATE,(STRPTR)MSG_ACT_FINDUPDATE_STR},
    {MSG_ACT_FINDINPUT,(STRPTR)MSG_ACT_FINDINPUT_STR},
    {MSG_ACT_FINDOUTPUT,(STRPTR)MSG_ACT_FINDOUTPUT_STR},
    {MSG_ACT_END,(STRPTR)MSG_ACT_END_STR},
    {MSG_ACT_SEEK,(STRPTR)MSG_ACT_SEEK_STR},
    {MSG_ACT_FORMAT,(STRPTR)MSG_ACT_FORMAT_STR},
    {MSG_ACT_MAKE_LINK,(STRPTR)MSG_ACT_MAKE_LINK_STR},
    {MSG_ACT_SET_FILE_SIZE,(STRPTR)MSG_ACT_SET_FILE_SIZE_STR},
    {MSG_ACT_WRITE_PROTECT,(STRPTR)MSG_ACT_WRITE_PROTECT_STR},
    {MSG_ACT_READ_LINK,(STRPTR)MSG_ACT_READ_LINK_STR},
    {MSG_ACT_FH_FROM_LOCK,(STRPTR)MSG_ACT_FH_FROM_LOCK_STR},
    {MSG_ACT_IS_FILESYSTEM,(STRPTR)MSG_ACT_IS_FILESYSTEM_STR},
    {MSG_ACT_CHANGE_MODE,(STRPTR)MSG_ACT_CHANGE_MODE_STR},
    {MSG_ACT_COPY_DIR_FH,(STRPTR)MSG_ACT_COPY_DIR_FH_STR},
    {MSG_ACT_PARENT_FH,(STRPTR)MSG_ACT_PARENT_FH_STR},
    {MSG_ACT_EXAMINE_ALL,(STRPTR)MSG_ACT_EXAMINE_ALL_STR},
    {MSG_ACT_EXAMINE_FH,(STRPTR)MSG_ACT_EXAMINE_FH_STR},
    {MSG_ACT_EXAMINE_ALL_END,(STRPTR)MSG_ACT_EXAMINE_ALL_END_STR},
    {MSG_ACT_SET_OWNER,(STRPTR)MSG_ACT_SET_OWNER_STR},
    {MSG_ACT_DOUBLE,(STRPTR)MSG_ACT_DOUBLE_STR},
    {MSG_ACT_FORCE,(STRPTR)MSG_ACT_FORCE_STR},
    {MSG_ACT_STACK,(STRPTR)MSG_ACT_STACK_STR},
    {MSG_ACT_QUEUE,(STRPTR)MSG_ACT_QUEUE_STR},
    {MSG_ACT_DROP,(STRPTR)MSG_ACT_DROP_STR},
    {MSG_ACT_LOCK_RECORD,(STRPTR)MSG_ACT_LOCK_RECORD_STR},
    {MSG_ACT_FREE_RECORD,(STRPTR)MSG_ACT_FREE_RECORD_STR},
    {MSG_ACT_ADD_NOTIFY,(STRPTR)MSG_ACT_ADD_NOTIFY_STR},
    {MSG_ACT_REMOVE_NOTIFY,(STRPTR)MSG_ACT_REMOVE_NOTIFY_STR},
    {MSG_ACT_SERIALIZE_DISK,(STRPTR)MSG_ACT_SERIALIZE_DISK_STR},
    {MSG_ACT_GET_DISK_FSSM,(STRPTR)MSG_ACT_GET_DISK_FSSM_STR},
    {MSG_ACT_FREE_DISK_FSSM,(STRPTR)MSG_ACT_FREE_DISK_FSSM_STR},
    {MSG_ACT_RAWPACKET,(STRPTR)MSG_ACT_RAWPACKET_STR},
    {MSG_RES_OKAY,(STRPTR)MSG_RES_OKAY_STR},
    {MSG_RES_FAIL,(STRPTR)MSG_RES_FAIL_STR},
    {MSG_RES_PAUSE,(STRPTR)MSG_RES_PAUSE_STR},
    {MSG_RES_MISSED,(STRPTR)MSG_RES_MISSED_STR},
    {MSG_NULLSTR,(STRPTR)MSG_NULLSTR_STR},
    {MSG_OPT_UNKNOWN,(STRPTR)MSG_OPT_UNKNOWN_STR},
    {MSG_OPT_READ,(STRPTR)MSG_OPT_READ_STR},
    {MSG_OPT_WRITE,(STRPTR)MSG_OPT_WRITE_STR},
    {MSG_OPT_READBAD,(STRPTR)MSG_OPT_READBAD_STR},
    {MSG_OPT_MODIFY,(STRPTR)MSG_OPT_MODIFY_STR},
    {MSG_OPT_LIBVER,(STRPTR)MSG_OPT_LIBVER_STR},
    {MSG_OPT_DEVUNIT,(STRPTR)MSG_OPT_DEVUNIT_STR},
    {MSG_OPT_FONTSIZE,(STRPTR)MSG_OPT_FONTSIZE_STR},
    {MSG_OPT_SOFTLINK,(STRPTR)MSG_OPT_SOFTLINK_STR},
    {MSG_OPT_HARDLINK,(STRPTR)MSG_OPT_HARDLINK_STR},
    {MSG_OPT_LOCAL,(STRPTR)MSG_OPT_LOCAL_STR},
    {MSG_OPT_ALIAS,(STRPTR)MSG_OPT_ALIAS_STR},
    {MSG_OPT_GLOBAL,(STRPTR)MSG_OPT_GLOBAL_STR},
    {MSG_OPT_ANY,(STRPTR)MSG_OPT_ANY_STR},
    {MSG_OPT_EXECSINGLE,(STRPTR)MSG_OPT_EXECSINGLE_STR},
    {MSG_OPT_EXECBATCH,(STRPTR)MSG_OPT_EXECBATCH_STR},
    {MSG_SEG_MODULE_NOT_FOUND,(STRPTR)MSG_SEG_MODULE_NOT_FOUND_STR},
    {MSG_ASL_LOADCONFIG,(STRPTR)MSG_ASL_LOADCONFIG_STR},
    {MSG_ASL_SAVECONFIG,(STRPTR)MSG_ASL_SAVECONFIG_STR},
    {MSG_ASL_DEFLOGNAME,(STRPTR)MSG_ASL_DEFLOGNAME_STR},
    {MSG_ASL_NEWLOGNAME,(STRPTR)MSG_ASL_NEWLOGNAME_STR},
    {MSG_ASL_SAVEWINDOW,(STRPTR)MSG_ASL_SAVEWINDOW_STR},
    {MSG_ASL_SAVEBUFFER,(STRPTR)MSG_ASL_SAVEBUFFER_STR},
    {MSG_ERROR_OPENSET,(STRPTR)MSG_ERROR_OPENSET_STR},
    {MSG_ERROR_OPENFUNC,(STRPTR)MSG_ERROR_OPENFUNC_STR},
    {MSG_ERROR_OPENMAIN,(STRPTR)MSG_ERROR_OPENMAIN_STR},
    {MSG_ERROR_NOBUFMEM,(STRPTR)MSG_ERROR_NOBUFMEM_STR},
    {MSG_ERROR_INITPATCHES,(STRPTR)MSG_ERROR_INITPATCHES_STR},
    {MSG_ERROR_OPENFORMAT,(STRPTR)MSG_ERROR_OPENFORMAT_STR},
    {MSG_ERROR_CREATEMENUS,(STRPTR)MSG_ERROR_CREATEMENUS_STR},
    {MSG_ERROR_INITGUI,(STRPTR)MSG_ERROR_INITGUI_STR},
    {MSG_ERROR_RESIZE,(STRPTR)MSG_ERROR_RESIZE_STR},
    {MSG_ERROR_OPENFONT,(STRPTR)MSG_ERROR_OPENFONT_STR},
    {MSG_ERROR_OPENFILEREQ,(STRPTR)MSG_ERROR_OPENFILEREQ_STR},
    {MSG_ERROR_SAVING_SETTINGS,(STRPTR)MSG_ERROR_SAVING_SETTINGS_STR},
    {MSG_ERROR_LOADING_SETTINGS,(STRPTR)MSG_ERROR_LOADING_SETTINGS_STR},
    {MSG_ERROR_SAVING_BUFFER,(STRPTR)MSG_ERROR_SAVING_BUFFER_STR},
    {MSG_ERROR_SAVING_WINDOW,(STRPTR)MSG_ERROR_SAVING_WINDOW_STR},
    {MSG_ERROR_UNPATCH,(STRPTR)MSG_ERROR_UNPATCH_STR},
    {MSG_ERROR_NO_DISKFONT,(STRPTR)MSG_ERROR_NO_DISKFONT_STR},
    {MSG_ERROR_NO_ASL,(STRPTR)MSG_ERROR_NO_ASL_STR},
    {MSG_ERROR_OKAY,(STRPTR)MSG_ERROR_OKAY_STR},
    {MSG_ERROR_CANCEL,(STRPTR)MSG_ERROR_CANCEL_STR},
    {MSG_ERROR_STARTLOG,(STRPTR)MSG_ERROR_STARTLOG_STR},
    {MSG_ERROR_NO_SCREEN,(STRPTR)MSG_ERROR_NO_SCREEN_STR},
    {MSG_ERROR_FONT_PROPORTIONAL,(STRPTR)MSG_ERROR_FONT_PROPORTIONAL_STR},
    {MSG_ERROR_COPY_WIN_TO_CLIP,(STRPTR)MSG_ERROR_COPY_WIN_TO_CLIP_STR},
    {MSG_ERROR_COPY_ALL_TO_CLIP,(STRPTR)MSG_ERROR_COPY_ALL_TO_CLIP_STR},
    {MSG_REQ_FILE_EXISTS,(STRPTR)MSG_REQ_FILE_EXISTS_STR},
    {MSG_REQ_APPEND_OVERWRITE_CANCEL,(STRPTR)MSG_REQ_APPEND_OVERWRITE_CANCEL_STR},
    {MSG_ERROR_CLI_NOPARAM,(STRPTR)MSG_ERROR_CLI_NOPARAM_STR},
    {MSG_ERROR_CLI_FAILED,(STRPTR)MSG_ERROR_CLI_FAILED_STR},
    {MSG_ERROR_CLI_UNKNOWN,(STRPTR)MSG_ERROR_CLI_UNKNOWN_STR},
    {MSG_CLI_USAGE,(STRPTR)MSG_CLI_USAGE_STR},
    {MSG_CLI_HELPBANNER,(STRPTR)MSG_CLI_HELPBANNER_STR},
    {MSG_CMD_UNKNOWN,(STRPTR)MSG_CMD_UNKNOWN_STR},
    {MSG_CMD_FAIL,(STRPTR)MSG_CMD_FAIL_STR},
    {MSG_CMD_NOPARAM,(STRPTR)MSG_CMD_NOPARAM_STR},
    {MSG_CMD_HEADER,(STRPTR)MSG_CMD_HEADER_STR},
    {MSG_CMD_PROMPT,(STRPTR)MSG_CMD_PROMPT_STR},
    {MSG_STATUS_NORMAL,(STRPTR)MSG_STATUS_NORMAL_STR},
    {MSG_STATUS_PAUSED,(STRPTR)MSG_STATUS_PAUSED_STR},
    {MSG_STATUS_DISABLED,(STRPTR)MSG_STATUS_DISABLED_STR},
    {MSG_STATUS_LOGFILE,(STRPTR)MSG_STATUS_LOGFILE_STR},
    {MSG_STATUS_LOGDEVICE,(STRPTR)MSG_STATUS_LOGDEVICE_STR},
    {MSG_STATUS_LOGDEBUG,(STRPTR)MSG_STATUS_LOGDEBUG_STR},
    {MSG_STATUS_SAVESET,(STRPTR)MSG_STATUS_SAVESET_STR},
    {MSG_STATUS_LOADSET,(STRPTR)MSG_STATUS_LOADSET_STR},
    {MSG_LOG_START,(STRPTR)MSG_LOG_START_STR},
    {MSG_LOG_STOP,(STRPTR)MSG_LOG_STOP_STR},
    {MSG_LOG_DISABLED,(STRPTR)MSG_LOG_DISABLED_STR},
    {MSG_LOG_ENABLED,(STRPTR)MSG_LOG_ENABLED_STR},
    {MSG_ERROR_NO_AMIGAGUIDE,(STRPTR)MSG_ERROR_NO_AMIGAGUIDE_STR},
    {MSG_ERROR_CREATE_AMIGAGUIDE,(STRPTR)MSG_ERROR_CREATE_AMIGAGUIDE_STR},
    {MSG_ERROR_AGUIDE_GENERIC,(STRPTR)MSG_ERROR_AGUIDE_GENERIC_STR},
    {MSG_ERROR_AGUIDE_CANT_OPEN,(STRPTR)MSG_ERROR_AGUIDE_CANT_OPEN_STR},
    {MSG_HELPFILE_NAME,(STRPTR)MSG_HELPFILE_NAME_STR},
    {MSG_LINK_MAIN,(STRPTR)MSG_LINK_MAIN_STR},
    {MSG_LINK_MAINWIN,(STRPTR)MSG_LINK_MAINWIN_STR},
    {MSG_LINK_FUNCWIN,(STRPTR)MSG_LINK_FUNCWIN_STR},
    {MSG_LINK_SETUPWIN,(STRPTR)MSG_LINK_SETUPWIN_STR},
    {MSG_LINK_FORMATWIN,(STRPTR)MSG_LINK_FORMATWIN_STR},
    {MSG_LINK_MENU_PROJECT,(STRPTR)MSG_LINK_MENU_PROJECT_STR},
    {MSG_LINK_MENU_WINDOW,(STRPTR)MSG_LINK_MENU_WINDOW_STR},
    {MSG_LINK_MENU_SETTINGS,(STRPTR)MSG_LINK_MENU_SETTINGS_STR},
    {MSG_LINK_MENU_BUFFER,(STRPTR)MSG_LINK_MENU_BUFFER_STR},
    {MSG_COMMODITY_DESC,(STRPTR)MSG_COMMODITY_DESC_STR},
    {MSG_INVALID_HOTKEY,(STRPTR)MSG_INVALID_HOTKEY_STR},
    {MSG_APPMENU_NAME,(STRPTR)MSG_APPMENU_NAME_STR},
    {MSG_ABOUT_SNOOPDOS,(STRPTR)MSG_ABOUT_SNOOPDOS_STR},
    {NUM_OF_MSGS,(STRPTR)NUM_OF_MSGS_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

static const char CatCompBlock[] =
{
    "\x00\x00\x00\x00\x00\x0E"
    MSG_ZERO_STR "\x00\x00"
    "\x00\x00\x00\x01\x00\x08"
    MSG_PAUSE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x02\x00\x0A"
    MSG_DISABLE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x03\x00\x06"
    MSG_HIDE_GAD_STR "\x00"
    "\x00\x00\x00\x04\x00\x06"
    MSG_QUIT_GAD_STR "\x00"
    "\x00\x00\x00\x05\x00\x0E"
    MSG_OPENLOG_GAD_STR "\x00\x00"
    "\x00\x00\x00\x06\x00\x0C"
    MSG_APPENDLOG_GAD_STR "\x00"
    "\x00\x00\x00\x07\x00\x0C"
    MSG_STARTLOG_GAD_STR "\x00\x00"
    "\x00\x00\x00\x08\x00\x0C"
    MSG_SERIALLOG_GAD_STR "\x00"
    "\x00\x00\x00\x09\x00\x0C"
    MSG_CLOSELOG_GAD_STR "\x00\x00"
    "\x00\x00\x00\x0A\x00\x10"
    MSG_SAVESET_GAD_STR "\x00\x00"
    "\x00\x00\x00\x0B\x00\x0E"
    MSG_FUNCTION_GAD_STR "\x00"
    "\x00\x00\x00\x0C\x00\x0A"
    MSG_SETUP_GAD_STR "\x00"
    "\x00\x00\x00\x0D\x00\x08"
    MSG_STATUS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x0E\x00\x06"
    MSG_USE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x0F\x00\x06"
    MSG_UNDO_GAD_STR "\x00"
    "\x00\x00\x00\x10\x00\x08"
    MSG_CANCEL_GAD_STR "\x00"
    "\x00\x00\x00\x11\x00\x14"
    MSG_FUNCTION_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x12\x00\x12"
    MSG_SHOWFAILS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x13\x00\x12"
    MSG_SHOWCLI_GAD_STR "\x00\x00"
    "\x00\x00\x00\x14\x00\x12"
    MSG_SHOWFULLPATHS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x15\x00\x12"
    MSG_USEDEVNAMES_GAD_STR "\x00"
    "\x00\x00\x00\x16\x00\x12"
    MSG_MONPACKETS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x17\x00\x12"
    MSG_MONALLPACKETS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x18\x00\x14"
    MSG_MONROMCALLS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x19\x00\x18"
    MSG_IGNOREWB_GAD_STR "\x00"
    "\x00\x00\x00\x1A\x00\x0A"
    MSG_FINDPORT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x1B\x00\x0E"
    MSG_FINDRESIDENT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x1C\x00\x0E"
    MSG_FINDSEMAPHORE_GAD_STR "\x00"
    "\x00\x00\x00\x1D\x00\x0A"
    MSG_FINDTASK_GAD_STR "\x00\x00"
    "\x00\x00\x00\x1E\x00\x0C"
    MSG_LOCKSCREEN_GAD_STR "\x00\x00"
    "\x00\x00\x00\x1F\x00\x0C"
    MSG_OPENDEVICE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x20\x00\x0A"
    MSG_OPENFONT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x21\x00\x0C"
    MSG_OPENLIBRARY_GAD_STR "\x00"
    "\x00\x00\x00\x22\x00\x0E"
    MSG_OPENRESOURCE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x23\x00\x0E"
    MSG_READTOOLTYPES_GAD_STR "\x00"
    "\x00\x00\x00\x24\x00\x0A"
    MSG_SENDREXX_GAD_STR "\x00\x00"
    "\x00\x00\x00\x25\x00\x14"
    MSG_PACKET_NAME_STR "\x00\x00"
    "\x00\x00\x00\x26\x00\x0A"
    MSG_CHANGEDIR_GAD_STR "\x00"
    "\x00\x00\x00\x27\x00\x08"
    MSG_DELETE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x28\x00\x08"
    MSG_EXECUTE_GAD_STR "\x00"
    "\x00\x00\x00\x29\x00\x08"
    MSG_GETVAR_GAD_STR "\x00\x00"
    "\x00\x00\x00\x2A\x00\x08"
    MSG_LOADSEG_GAD_STR "\x00"
    "\x00\x00\x00\x2B\x00\x06"
    MSG_LOCKFILE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x2C\x00\x08"
    MSG_MAKEDIR_GAD_STR "\x00"
    "\x00\x00\x00\x2D\x00\x0A"
    MSG_MAKELINK_GAD_STR "\x00\x00"
    "\x00\x00\x00\x2E\x00\x06"
    MSG_OPENFILE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x2F\x00\x08"
    MSG_RENAME_GAD_STR "\x00\x00"
    "\x00\x00\x00\x30\x00\x0C"
    MSG_RUNCOMMAND_GAD_STR "\x00\x00"
    "\x00\x00\x00\x31\x00\x08"
    MSG_SETVAR_GAD_STR "\x00\x00"
    "\x00\x00\x00\x32\x00\x08"
    MSG_SYSTEM_GAD_STR "\x00\x00"
    "\x00\x00\x00\x33\x00\x08"
    MSG_SELSYSTEM_GAD_STR "\x00"
    "\x00\x00\x00\x34\x00\x0A"
    MSG_SELDOS_GAD_STR "\x00"
    "\x00\x00\x00\x35\x00\x04"
    MSG_ALL_GAD_STR "\x00"
    "\x00\x00\x00\x36\x00\x06"
    MSG_NONE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x37\x00\x0A"
    MSG_SELECTED_GAD_STR "\x00\x00"
    "\x00\x00\x00\x38\x00\x0C"
    MSG_MATCHNAME_GAD_STR "\x00"
    "\x00\x00\x00\x39\x00\x12"
    MSG_SYSFUNCS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x3A\x00\x14"
    MSG_DOSFUNCS_GAD_STR "\x00\x00"
    "\x00\x00\x00\x3B\x00\x12"
    MSG_SETTINGS_TITLE_STR "\x00"
    "\x00\x00\x00\x3C\x00\x0E"
    MSG_HIDEMETHOD_GAD_STR "\x00\x00"
    "\x00\x00\x00\x3D\x00\x0A"
    MSG_CYL_HIDE_GAD_STR "\x00"
    "\x00\x00\x00\x3E\x00\x08"
    MSG_CYL_ICONIFY_GAD_STR "\x00"
    "\x00\x00\x00\x3F\x00\x0C"
    MSG_CYL_TOOLSMENU_GAD_STR "\x00\x00"
    "\x00\x00\x00\x40\x00\x06"
    MSG_CYL_NONE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x41\x00\x10"
    MSG_OPENON_GAD_STR "\x00"
    "\x00\x00\x00\x42\x00\x10"
    MSG_CYL_DEFSCREEN_GAD_STR "\x00\x00"
    "\x00\x00\x00\x43\x00\x0E"
    MSG_CYL_FRONTSCREEN_GAD_STR "\x00\x00"
    "\x00\x00\x00\x44\x00\x0E"
    MSG_CYL_NAMEDSCREEN_GAD_STR "\x00\x00"
    "\x00\x00\x00\x45\x00\x0A"
    MSG_LOGMODE_GAD_STR "\x00"
    "\x00\x00\x00\x46\x00\x0C"
    MSG_CYL_PROMPT_USER_GAD_STR "\x00"
    "\x00\x00\x00\x47\x00\x08"
    MSG_CYL_APPEND_GAD_STR "\x00\x00"
    "\x00\x00\x00\x48\x00\x0A"
    MSG_CYL_OVERWRITE_GAD_STR "\x00"
    "\x00\x00\x00\x49\x00\x0C"
    MSG_CYL_SERIALPORT_GAD_STR "\x00"
    "\x00\x00\x00\x4A\x00\x0A"
    MSG_FILEIO_GAD_STR "\x00"
    "\x00\x00\x00\x4B\x00\x0A"
    MSG_CYL_AUTOMATIC_GAD_STR "\x00"
    "\x00\x00\x00\x4C\x00\x0A"
    MSG_CYL_IMMEDIATE_GAD_STR "\x00"
    "\x00\x00\x00\x4D\x00\x0A"
    MSG_CYL_BUFFERED_GAD_STR "\x00\x00"
    "\x00\x00\x00\x4E\x00\x14"
    MSG_BUFFERSIZE_GAD_STR "\x00"
    "\x00\x00\x00\x4F\x00\x10"
    MSG_BUFFORMAT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x50\x00\x10"
    MSG_LOGFORMAT_GAD_STR "\x00"
    "\x00\x00\x00\x51\x00\x08"
    MSG_HOTKEY_GAD_STR "\x00"
    "\x00\x00\x00\x52\x00\x0E"
    MSG_SCREENNAME_GAD_STR "\x00\x00"
    "\x00\x00\x00\x53\x00\x0A"
    MSG_LOGFILE_GAD_STR "\x00"
    "\x00\x00\x00\x54\x00\x0E"
    MSG_WINDOWFONT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x55\x00\x0E"
    MSG_BUFFERFONT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x56\x00\x0A"
    MSG_FORMATEDIT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x57\x00\x06"
    MSG_FORMATCOPYP_GAD_STR "\x00"
    "\x00\x00\x00\x58\x00\x0A"
    MSG_FORMATCOPYF_GAD_STR "\x00\x00"
    "\x00\x00\x00\x59\x00\x18"
    MSG_FORMAT_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x5A\x00\x12"
    MSG_AVAILABLE_GAD_STR "\x00\x00"
    "\x00\x00\x00\x5B\x00\x10"
    MSG_CURFORMAT_GAD_STR "\x00\x00"
    "\x00\x00\x00\x5C\x00\x0E"
    MSG_FIELDWIDTH_GAD_STR "\x00\x00"
    "\x00\x00\x00\x5D\x00\x1A"
    MSG_GFONT_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x5E\x00\x1A"
    MSG_BFONT_TITLE_STR "\x00\x00"
    "\x00\x00\x00\x5F\x00\x0A"
    MSG_PROJECT_MENU_STR "\x00"
    "\x00\x00\x00\x60\x00\x0E"
    MSG_PROJECT_OPENLOG_STR "\x00"
    "\x00\x00\x00\x61\x00\x0C"
    MSG_PROJECT_CLOSELOG_STR "\x00"
    "\x00\x00\x00\x62\x00\x08"
    MSG_PROJECT_PAUSE_STR "\x00"
    "\x00\x00\x00\x63\x00\x0A"
    MSG_PROJECT_DISABLE_STR "\x00"
    "\x00\x00\x00\x64\x00\x0E"
    MSG_PROJECT_STEP_STR "\x00"
    "\x00\x00\x00\x65\x00\x10"
    MSG_PROJECT_PRI_STR "\x00"
    "\x00\x00\x00\x66\x00\x06"
    MSG_PROJECT_PRI_A_STR "\x00\x00"
    "\x00\x00\x00\x67\x00\x06"
    MSG_PROJECT_PRI_B_STR "\x00\x00"
    "\x00\x00\x00\x68\x00\x06"
    MSG_PROJECT_PRI_C_STR "\x00\x00"
    "\x00\x00\x00\x69\x00\x06"
    MSG_PROJECT_PRI_D_STR "\x00\x00"
    "\x00\x00\x00\x6A\x00\x06"
    MSG_PROJECT_PRI_E_STR "\x00\x00"
    "\x00\x00\x00\x6B\x00\x06"
    MSG_PROJECT_PRI_F_STR "\x00\x00"
    "\x00\x00\x00\x6C\x00\x06"
    MSG_PROJECT_PRI_G_STR "\x00\x00"
    "\x00\x00\x00\x6D\x00\x0A"
    MSG_PROJECT_HELP_STR "\x00"
    "\x00\x00\x00\x6E\x00\x0C"
    MSG_PROJECT_ABOUT_STR "\x00\x00"
    "\x00\x00\x00\x6F\x00\x08"
    MSG_PROJECT_HIDE_STR "\x00\x00"
    "\x00\x00\x00\x70\x00\x08"
    MSG_PROJECT_QUIT_STR "\x00\x00"
    "\x00\x00\x00\x71\x00\x0A"
    MSG_WINDOWS_MENU_STR "\x00"
    "\x00\x00\x00\x72\x00\x10"
    MSG_WINDOWS_SETUP_STR "\x00"
    "\x00\x00\x00\x73\x00\x14"
    MSG_WINDOWS_FUNCTION_STR "\x00"
    "\x00\x00\x00\x74\x00\x12"
    MSG_WINDOWS_FORMAT_STR "\x00\x00"
    "\x00\x00\x00\x75\x00\x16"
    MSG_WINDOWS_WIDTH_STR "\x00"
    "\x00\x00\x00\x76\x00\x0C"
    MSG_WINDOWS_WIDTH_1_STR "\x00\x00"
    "\x00\x00\x00\x77\x00\x0E"
    MSG_WINDOWS_WIDTH_2_STR "\x00"
    "\x00\x00\x00\x78\x00\x0E"
    MSG_WINDOWS_WIDTH_3_STR "\x00"
    "\x00\x00\x00\x79\x00\x0E"
    MSG_WINDOWS_WIDTH_4_STR "\x00"
    "\x00\x00\x00\x7A\x00\x0E"
    MSG_WINDOWS_WIDTH_5_STR "\x00"
    "\x00\x00\x00\x7B\x00\x14"
    MSG_WINDOWS_ROW_QUAL_STR "\x00"
    "\x00\x00\x00\x7C\x00\x0A"
    MSG_WINDOWS_ROW_ANY_STR "\x00\x00"
    "\x00\x00\x00\x7D\x00\x08"
    MSG_WINDOWS_ROW_NONE_STR "\x00\x00"
    "\x00\x00\x00\x7E\x00\x08"
    MSG_WINDOWS_ROW_SHIFT_STR "\x00"
    "\x00\x00\x00\x7F\x00\x06"
    MSG_WINDOWS_ROW_ALT_STR "\x00"
    "\x00\x00\x00\x80\x00\x08"
    MSG_WINDOWS_ROW_CTRL_STR "\x00\x00"
    "\x00\x00\x00\x81\x00\x06"
    MSG_WINDOWS_ROW_ALL_STR "\x00"
    "\x00\x00\x00\x82\x00\x10"
    MSG_WINDOWS_SPACING_STR "\x00\x00"
    "\x00\x00\x00\x83\x00\x08"
    MSG_WINDOWS_SPACING_NONE_STR "\x00\x00"
    "\x00\x00\x00\x84\x00\x0A"
    MSG_WINDOWS_SPACING_1P_STR "\x00"
    "\x00\x00\x00\x85\x00\x0C"
    MSG_WINDOWS_SPACING_2P_STR "\x00\x00"
    "\x00\x00\x00\x86\x00\x0E"
    MSG_WINDOWS_REFRESH_STR "\x00"
    "\x00\x00\x00\x87\x00\x12"
    MSG_WINDOWS_REF_SIMPLE_STR "\x00\x00"
    "\x00\x00\x00\x88\x00\x10"
    MSG_WINDOWS_REF_SMART_STR "\x00"
    "\x00\x00\x00\x89\x00\x0E"
    MSG_WINDOWS_ALIGN_STR "\x00"
    "\x00\x00\x00\x8A\x00\x10"
    MSG_WINDOWS_ALIGN_LEFT_STR "\x00\x00"
    "\x00\x00\x00\x8B\x00\x10"
    MSG_WINDOWS_ALIGN_RIGHT_STR "\x00"
    "\x00\x00\x00\x8C\x00\x14"
    MSG_WINDOWS_SHOWSTATUS_STR "\x00"
    "\x00\x00\x00\x8D\x00\x10"
    MSG_WINDOWS_SHOWGADGETS_STR "\x00"
    "\x00\x00\x00\x8E\x00\x18"
    MSG_WINDOWS_AUTO_OPEN_STR "\x00\x00"
    "\x00\x00\x00\x8F\x00\x18"
    MSG_WINDOWS_DISABLE_HIDDEN_STR "\x00\x00"
    "\x00\x00\x00\x90\x00\x0C"
    MSG_SETTINGS_MENU_STR "\x00\x00"
    "\x00\x00\x00\x91\x00\x0A"
    MSG_SETTINGS_LOAD_STR "\x00"
    "\x00\x00\x00\x92\x00\x08"
    MSG_SETTINGS_SAVE_STR "\x00\x00"
    "\x00\x00\x00\x93\x00\x0E"
    MSG_SETTINGS_SAVEAS_STR "\x00\x00"
    "\x00\x00\x00\x94\x00\x14"
    MSG_SETTINGS_RESETDEFAULTS_STR "\x00"
    "\x00\x00\x00\x95\x00\x0E"
    MSG_SETTINGS_LASTSAVED_STR "\x00\x00"
    "\x00\x00\x00\x96\x00\x0A"
    MSG_SETTINGS_RESTORE_STR "\x00"
    "\x00\x00\x00\x97\x00\x10"
    MSG_SETTINGS_CREATEICONS_STR "\x00"
    "\x00\x00\x00\x98\x00\x0A"
    MSG_BUFFER_MENU_STR "\x00\x00"
    "\x00\x00\x00\x99\x00\x16"
    MSG_BUFFER_COPYWIN_STR "\x00"
    "\x00\x00\x00\x9A\x00\x16"
    MSG_BUFFER_COPYBUF_STR "\x00"
    "\x00\x00\x00\x9B\x00\x12"
    MSG_BUFFER_SAVEWIN_STR "\x00\x00"
    "\x00\x00\x00\x9C\x00\x12"
    MSG_BUFFER_SAVEBUF_STR "\x00\x00"
    "\x00\x00\x00\x9D\x00\x10"
    MSG_BUFFER_CLEARBUF_STR "\x00\x00"
    "\x00\x00\x00\x9E\x00\x0A"
    MSG_CALL_COL_STR "\x00\x00"
    "\x00\x00\x00\x9F\x00\x06"
    MSG_DATE_COL_STR "\x00\x00"
    "\x00\x00\x00\xA0\x00\x0C"
    MSG_HUNK_COL_STR "\x00"
    "\x00\x00\x00\xA1\x00\x08"
    MSG_PROCESSID_COL_STR "\x00"
    "\x00\x00\x00\xA2\x00\x0E"
    MSG_SEGNAME_COL_STR "\x00\x00"
    "\x00\x00\x00\xA3\x00\x06"
    MSG_TIME_COL_STR "\x00\x00"
    "\x00\x00\x00\xA4\x00\x06"
    MSG_COUNT_COL_STR "\x00"
    "\x00\x00\x00\xA5\x00\x0E"
    MSG_PROCNAME_COL_STR "\x00\x00"
    "\x00\x00\x00\xA6\x00\x08"
    MSG_ACTION_COL_STR "\x00\x00"
    "\x00\x00\x00\xA7\x00\x0C"
    MSG_FILENAME_COL_STR "\x00"
    "\x00\x00\x00\xA8\x00\x08"
    MSG_OPTIONS_COL_STR "\x00"
    "\x00\x00\x00\xA9\x00\x06"
    MSG_RESULT_COL_STR "\x00\x00"
    "\x00\x00\x00\xAA\x00\x0A"
    MSG_ACT_FINDPORT_STR "\x00\x00"
    "\x00\x00\x00\xAB\x00\x08"
    MSG_ACT_FINDRESIDENT_STR "\x00"
    "\x00\x00\x00\xAC\x00\x08"
    MSG_ACT_FINDSEM_STR "\x00"
    "\x00\x00\x00\xAD\x00\x0A"
    MSG_ACT_FINDTASK_STR "\x00\x00"
    "\x00\x00\x00\xAE\x00\x0C"
    MSG_ACT_LOCKSCREEN_STR "\x00\x00"
    "\x00\x00\x00\xAF\x00\x08"
    MSG_ACT_OPENDEV_STR "\x00"
    "\x00\x00\x00\xB0\x00\x0A"
    MSG_ACT_OPENFONT_STR "\x00\x00"
    "\x00\x00\x00\xB1\x00\x08"
    MSG_ACT_OPENLIB_STR "\x00"
    "\x00\x00\x00\xB2\x00\x08"
    MSG_ACT_OPENRES_STR "\x00"
    "\x00\x00\x00\xB3\x00\x0A"
    MSG_ACT_FINDTOOL_STR "\x00\x00"
    "\x00\x00\x00\xB4\x00\x0A"
    MSG_ACT_MATCHTOOL_STR "\x00"
    "\x00\x00\x00\xB5\x00\x0A"
    MSG_ACT_SENDREXX_STR "\x00\x00"
    "\x00\x00\x00\xB6\x00\x0A"
    MSG_ACT_CHANGEDIR_STR "\x00"
    "\x00\x00\x00\xB7\x00\x08"
    MSG_ACT_DELETE_STR "\x00\x00"
    "\x00\x00\x00\xB8\x00\x08"
    MSG_ACT_PDELETE_STR "\x00"
    "\x00\x00\x00\xB9\x00\x08"
    MSG_ACT_EXECUTE_STR "\x00"
    "\x00\x00\x00\xBA\x00\x08"
    MSG_ACT_GETVAR_STR "\x00\x00"
    "\x00\x00\x00\xBB\x00\x08"
    MSG_ACT_FINDVAR_STR "\x00"
    "\x00\x00\x00\xBC\x00\x06"
    MSG_ACT_LOCK_STR "\x00\x00"
    "\x00\x00\x00\xBD\x00\x06"
    MSG_ACT_PLOCK_STR "\x00"
    "\x00\x00\x00\xBE\x00\x06"
    MSG_ACT_LOADSEG_STR "\x00\x00"
    "\x00\x00\x00\xBF\x00\x08"
    MSG_ACT_NEWLOADSEG_STR "\x00"
    "\x00\x00\x00\xC0\x00\x08"
    MSG_ACT_MAKEDIR_STR "\x00"
    "\x00\x00\x00\xC1\x00\x0A"
    MSG_ACT_PMAKEDIR_STR "\x00\x00"
    "\x00\x00\x00\xC2\x00\x0A"
    MSG_ACT_MAKELINK_STR "\x00\x00"
    "\x00\x00\x00\xC3\x00\x0A"
    MSG_ACT_PMAKELINK_STR "\x00"
    "\x00\x00\x00\xC4\x00\x06"
    MSG_ACT_OPEN_STR "\x00\x00"
    "\x00\x00\x00\xC5\x00\x06"
    MSG_ACT_POPEN_STR "\x00"
    "\x00\x00\x00\xC6\x00\x08"
    MSG_ACT_RENAME_STR "\x00\x00"
    "\x00\x00\x00\xC7\x00\x08"
    MSG_ACT_PRENAME_STR "\x00"
    "\x00\x00\x00\xC8\x00\x08"
    MSG_ACT_RENAME2_STR "\x00\x00"
    "\x00\x00\x00\xC9\x00\x08"
    MSG_ACT_PRENAME2_STR "\x00"
    "\x00\x00\x00\xCA\x00\x0C"
    MSG_ACT_RUNCOMMAND_STR "\x00\x00"
    "\x00\x00\x00\xCB\x00\x08"
    MSG_ACT_SETVAR_STR "\x00\x00"
    "\x00\x00\x00\xCC\x00\x08"
    MSG_ACT_KILLVAR_STR "\x00"
    "\x00\x00\x00\xCD\x00\x08"
    MSG_ACT_SYSTEM_STR "\x00\x00"
    "\x00\x00\x00\xCE\x00\x0A"
    MSG_ACT_STARTUP_STR "\x00\x00"
    "\x00\x00\x00\xCF\x00\x0C"
    MSG_ACT_GET_BLOCK_STR "\x00\x00"
    "\x00\x00\x00\xD0\x00\x0A"
    MSG_ACT_SET_MAP_STR "\x00\x00"
    "\x00\x00\x00\xD1\x00\x06"
    MSG_ACT_DIE_STR "\x00\x00"
    "\x00\x00\x00\xD2\x00\x08"
    MSG_ACT_EVENT_STR "\x00\x00"
    "\x00\x00\x00\xD3\x00\x0C"
    MSG_ACT_CURRENT_VOLUME_STR "\x00"
    "\x00\x00\x00\xD4\x00\x0C"
    MSG_ACT_LOCATE_OBJECT_STR "\x00"
    "\x00\x00\x00\xD5\x00\x0A"
    MSG_ACT_RENAME_DISK_STR "\x00"
    "\x00\x00\x00\xD6\x00\x0C"
    MSG_ACT_FREE_LOCK_STR "\x00\x00"
    "\x00\x00\x00\xD7\x00\x0C"
    MSG_ACT_DELETE_OBJECT_STR "\x00"
    "\x00\x00\x00\xD8\x00\x0C"
    MSG_ACT_RENAME_OBJECT_STR "\x00"
    "\x00\x00\x00\xD9\x00\x0C"
    MSG_ACT_MORE_CACHE_STR "\x00"
    "\x00\x00\x00\xDA\x00\x0A"
    MSG_ACT_COPY_DIR_STR "\x00"
    "\x00\x00\x00\xDB\x00\x0C"
    MSG_ACT_WAIT_CHAR_STR "\x00\x00"
    "\x00\x00\x00\xDC\x00\x0E"
    MSG_ACT_SET_PROTECT_STR "\x00\x00"
    "\x00\x00\x00\xDD\x00\x0C"
    MSG_ACT_CREATE_DIR_STR "\x00"
    "\x00\x00\x00\xDE\x00\x0E"
    MSG_ACT_EXAMINE_OBJECT_STR "\x00\x00"
    "\x00\x00\x00\xDF\x00\x0C"
    MSG_ACT_EXAMINE_NEXT_STR "\x00\x00"
    "\x00\x00\x00\xE0\x00\x0C"
    MSG_ACT_DISK_INFO_STR "\x00\x00"
    "\x00\x00\x00\xE1\x00\x06"
    MSG_ACT_INFO_STR "\x00"
    "\x00\x00\x00\xE2\x00\x08"
    MSG_ACT_FLUSH_STR "\x00\x00"
    "\x00\x00\x00\xE3\x00\x0E"
    MSG_ACT_SET_COMMENT_STR "\x00\x00"
    "\x00\x00\x00\xE4\x00\x08"
    MSG_ACT_PARENT_STR "\x00"
    "\x00\x00\x00\xE5\x00\x08"
    MSG_ACT_TIMER_STR "\x00\x00"
    "\x00\x00\x00\xE6\x00\x0A"
    MSG_ACT_INHIBIT_STR "\x00\x00"
    "\x00\x00\x00\xE7\x00\x0C"
    MSG_ACT_DISK_TYPE_STR "\x00\x00"
    "\x00\x00\x00\xE8\x00\x0E"
    MSG_ACT_DISK_CHANGE_STR "\x00\x00"
    "\x00\x00\x00\xE9\x00\x0A"
    MSG_ACT_SET_DATE_STR "\x00"
    "\x00\x00\x00\xEA\x00\x0C"
    MSG_ACT_SAME_LOCK_STR "\x00\x00"
    "\x00\x00\x00\xEB\x00\x06"
    MSG_ACT_READ_STR "\x00"
    "\x00\x00\x00\xEC\x00\x08"
    MSG_ACT_WRITE_STR "\x00\x00"
    "\x00\x00\x00\xED\x00\x0E"
    MSG_ACT_SCREEN_MODE_STR "\x00\x00"
    "\x00\x00\x00\xEE\x00\x0C"
    MSG_ACT_CHANGE_SIGNAL_STR "\x00"
    "\x00\x00\x00\xEF\x00\x0A"
    MSG_ACT_READ_RETURN_STR "\x00"
    "\x00\x00\x00\xF0\x00\x0C"
    MSG_ACT_WRITE_RETURN_STR "\x00\x00"
    "\x00\x00\x00\xF1\x00\x0C"
    MSG_ACT_FINDUPDATE_STR "\x00"
    "\x00\x00\x00\xF2\x00\x0C"
    MSG_ACT_FINDINPUT_STR "\x00\x00"
    "\x00\x00\x00\xF3\x00\x0C"
    MSG_ACT_FINDOUTPUT_STR "\x00"
    "\x00\x00\x00\xF4\x00\x06"
    MSG_ACT_END_STR "\x00\x00"
    "\x00\x00\x00\xF5\x00\x06"
    MSG_ACT_SEEK_STR "\x00"
    "\x00\x00\x00\xF6\x00\x08"
    MSG_ACT_FORMAT_STR "\x00"
    "\x00\x00\x00\xF7\x00\x0C"
    MSG_ACT_MAKE_LINK_STR "\x00\x00"
    "\x00\x00\x00\xF8\x00\x10"
    MSG_ACT_SET_FILE_SIZE_STR "\x00\x00"
    "\x00\x00\x00\xF9\x00\x10"
    MSG_ACT_WRITE_PROTECT_STR "\x00\x00"
    "\x00\x00\x00\xFA\x00\x0C"
    MSG_ACT_READ_LINK_STR "\x00\x00"
    "\x00\x00\x00\xFB\x00\x0E"
    MSG_ACT_FH_FROM_LOCK_STR "\x00"
    "\x00\x00\x00\xFC\x00\x10"
    MSG_ACT_IS_FILESYSTEM_STR "\x00\x00"
    "\x00\x00\x00\xFD\x00\x0E"
    MSG_ACT_CHANGE_MODE_STR "\x00\x00"
    "\x00\x00\x00\xFE\x00\x0E"
    MSG_ACT_COPY_DIR_FH_STR "\x00\x00"
    "\x00\x00\x00\xFF\x00\x0C"
    MSG_ACT_PARENT_FH_STR "\x00\x00"
    "\x00\x00\x01\x00\x00\x0A"
    MSG_ACT_EXAMINE_ALL_STR "\x00"
    "\x00\x00\x01\x01\x00\x0A"
    MSG_ACT_EXAMINE_FH_STR "\x00\x00"
    "\x00\x00\x01\x02\x00\x0E"
    MSG_ACT_EXAMINE_ALL_END_STR "\x00"
    "\x00\x00\x01\x03\x00\x0C"
    MSG_ACT_SET_OWNER_STR "\x00\x00"
    "\x00\x00\x01\x04\x00\x08"
    MSG_ACT_DOUBLE_STR "\x00"
    "\x00\x00\x01\x05\x00\x08"
    MSG_ACT_FORCE_STR "\x00\x00"
    "\x00\x00\x01\x06\x00\x08"
    MSG_ACT_STACK_STR "\x00\x00"
    "\x00\x00\x01\x07\x00\x08"
    MSG_ACT_QUEUE_STR "\x00\x00"
    "\x00\x00\x01\x08\x00\x06"
    MSG_ACT_DROP_STR "\x00"
    "\x00\x00\x01\x09\x00\x0E"
    MSG_ACT_LOCK_RECORD_STR "\x00\x00"
    "\x00\x00\x01\x0A\x00\x0E"
    MSG_ACT_FREE_RECORD_STR "\x00\x00"
    "\x00\x00\x01\x0B\x00\x0C"
    MSG_ACT_ADD_NOTIFY_STR "\x00"
    "\x00\x00\x01\x0C\x00\x10"
    MSG_ACT_REMOVE_NOTIFY_STR "\x00\x00"
    "\x00\x00\x01\x0D\x00\x10"
    MSG_ACT_SERIALIZE_DISK_STR "\x00"
    "\x00\x00\x01\x0E\x00\x10"
    MSG_ACT_GET_DISK_FSSM_STR "\x00\x00"
    "\x00\x00\x01\x0F\x00\x10"
    MSG_ACT_FREE_DISK_FSSM_STR "\x00"
    "\x00\x00\x01\x10\x00\x08"
    MSG_ACT_RAWPACKET_STR "\x00\x00"
    "\x00\x00\x01\x11\x00\x04"
    MSG_RES_OKAY_STR "\x00\x00"
    "\x00\x00\x01\x12\x00\x06"
    MSG_RES_FAIL_STR "\x00\x00"
    "\x00\x00\x01\x13\x00\x06"
    MSG_RES_PAUSE_STR "\x00\x00"
    "\x00\x00\x01\x14\x00\x08"
    MSG_RES_MISSED_STR "\x00\x00"
    "\x00\x00\x01\x15\x00\x08"
    MSG_NULLSTR_STR "\x00\x00"
    "\x00\x00\x01\x16\x00\x08"
    MSG_OPT_UNKNOWN_STR "\x00"
    "\x00\x00\x01\x17\x00\x06"
    MSG_OPT_READ_STR "\x00\x00"
    "\x00\x00\x01\x18\x00\x06"
    MSG_OPT_WRITE_STR "\x00"
    "\x00\x00\x01\x19\x00\x08"
    MSG_OPT_READBAD_STR "\x00"
    "\x00\x00\x01\x1A\x00\x08"
    MSG_OPT_MODIFY_STR "\x00\x00"
    "\x00\x00\x01\x1B\x00\x08"
    MSG_OPT_LIBVER_STR "\x00"
    "\x00\x00\x01\x1C\x00\x0A"
    MSG_OPT_DEVUNIT_STR "\x00\x00"
    "\x00\x00\x01\x1D\x00\x0A"
    MSG_OPT_FONTSIZE_STR "\x00\x00"
    "\x00\x00\x01\x1E\x00\x06"
    MSG_OPT_SOFTLINK_STR "\x00\x00"
    "\x00\x00\x01\x1F\x00\x06"
    MSG_OPT_HARDLINK_STR "\x00\x00"
    "\x00\x00\x01\x20\x00\x06"
    MSG_OPT_LOCAL_STR "\x00"
    "\x00\x00\x01\x21\x00\x06"
    MSG_OPT_ALIAS_STR "\x00"
    "\x00\x00\x01\x22\x00\x08"
    MSG_OPT_GLOBAL_STR "\x00\x00"
    "\x00\x00\x01\x23\x00\x04"
    MSG_OPT_ANY_STR "\x00"
    "\x00\x00\x01\x24\x00\x08"
    MSG_OPT_EXECSINGLE_STR "\x00\x00"
    "\x00\x00\x01\x25\x00\x06"
    MSG_OPT_EXECBATCH_STR "\x00"
    "\x00\x00\x01\x26\x00\x12"
    MSG_SEG_MODULE_NOT_FOUND_STR "\x00\x00"
    "\x00\x00\x01\x27\x00\x14"
    MSG_ASL_LOADCONFIG_STR "\x00\x00"
    "\x00\x00\x01\x28\x00\x14"
    MSG_ASL_SAVECONFIG_STR "\x00\x00"
    "\x00\x00\x01\x29\x00\x22"
    MSG_ASL_DEFLOGNAME_STR "\x00"
    "\x00\x00\x01\x2A\x00\x1E"
    MSG_ASL_NEWLOGNAME_STR "\x00"
    "\x00\x00\x01\x2B\x00\x1C"
    MSG_ASL_SAVEWINDOW_STR "\x00\x00"
    "\x00\x00\x01\x2C\x00\x1C"
    MSG_ASL_SAVEBUFFER_STR "\x00\x00"
    "\x00\x00\x01\x2D\x00\x20"
    MSG_ERROR_OPENSET_STR "\x00\x00"
    "\x00\x00\x01\x2E\x00\x20"
    MSG_ERROR_OPENFUNC_STR "\x00"
    "\x00\x00\x01\x2F\x00\x1C"
    MSG_ERROR_OPENMAIN_STR "\x00\x00"
    "\x00\x00\x01\x30\x00\x46"
    MSG_ERROR_NOBUFMEM_STR "\x00"
    "\x00\x00\x01\x31\x00\x2E"
    MSG_ERROR_INITPATCHES_STR "\x00"
    "\x00\x00\x01\x32\x00\x24"
    MSG_ERROR_OPENFORMAT_STR "\x00"
    "\x00\x00\x01\x33\x00\x16"
    MSG_ERROR_CREATEMENUS_STR "\x00"
    "\x00\x00\x01\x34\x00\x24"
    MSG_ERROR_INITGUI_STR "\x00\x00"
    "\x00\x00\x01\x35\x00\x28"
    MSG_ERROR_RESIZE_STR "\x00\x00"
    "\x00\x00\x01\x36\x00\x1E"
    MSG_ERROR_OPENFONT_STR "\x00"
    "\x00\x00\x01\x37\x00\x1E"
    MSG_ERROR_OPENFILEREQ_STR "\x00"
    "\x00\x00\x01\x38\x00\x1E"
    MSG_ERROR_SAVING_SETTINGS_STR "\x00"
    "\x00\x00\x01\x39\x00\x30"
    MSG_ERROR_LOADING_SETTINGS_STR "\x00\x00"
    "\x00\x00\x01\x3A\x00\x2A"
    MSG_ERROR_SAVING_BUFFER_STR "\x00\x00"
    "\x00\x00\x01\x3B\x00\x2A"
    MSG_ERROR_SAVING_WINDOW_STR "\x00\x00"
    "\x00\x00\x01\x3C\x00\xB8"
    MSG_ERROR_UNPATCH_STR "\x00\x00"
    "\x00\x00\x01\x3D\x00\x74"
    MSG_ERROR_NO_DISKFONT_STR "\x00\x00"
    "\x00\x00\x01\x3E\x00\x6A"
    MSG_ERROR_NO_ASL_STR "\x00\x00"
    "\x00\x00\x01\x3F\x00\x06"
    MSG_ERROR_OKAY_STR "\x00\x00"
    "\x00\x00\x01\x40\x00\x08"
    MSG_ERROR_CANCEL_STR "\x00\x00"
    "\x00\x00\x01\x41\x00\x1A"
    MSG_ERROR_STARTLOG_STR "\x00"
    "\x00\x00\x01\x42\x00\x2E"
    MSG_ERROR_NO_SCREEN_STR "\x00\x00"
    "\x00\x00\x01\x43\x00\x3E"
    MSG_ERROR_FONT_PROPORTIONAL_STR "\x00\x00"
    "\x00\x00\x01\x44\x00\x24"
    MSG_ERROR_COPY_WIN_TO_CLIP_STR "\x00\x00"
    "\x00\x00\x01\x45\x00\x24"
    MSG_ERROR_COPY_ALL_TO_CLIP_STR "\x00\x00"
    "\x00\x00\x01\x46\x00\x22"
    MSG_REQ_FILE_EXISTS_STR "\x00\x00"
    "\x00\x00\x01\x47\x00\x18"
    MSG_REQ_APPEND_OVERWRITE_CANCEL_STR "\x00"
    "\x00\x00\x01\x48\x00\x24"
    MSG_ERROR_CLI_NOPARAM_STR "\x00\x00"
    "\x00\x00\x01\x49\x00\x16"
    MSG_ERROR_CLI_FAILED_STR "\x00\x00"
    "\x00\x00\x01\x4A\x00\x20"
    MSG_ERROR_CLI_UNKNOWN_STR "\x00\x00"
    "\x00\x00\x01\x4B\x00\x6E"
    MSG_CLI_USAGE_STR "\x00\x00"
    "\x00\x00\x01\x4C\x00\xEA"
    MSG_CLI_HELPBANNER_STR "\x00\x00"
    "\x00\x00\x01\x4D\x00\x16"
    MSG_CMD_UNKNOWN_STR "\x00\x00"
    "\x00\x00\x01\x4E\x00\x14"
    MSG_CMD_FAIL_STR "\x00"
    "\x00\x00\x01\x4F\x00\x18"
    MSG_CMD_NOPARAM_STR "\x00\x00"
    "\x00\x00\x01\x50\x00\x42"
    MSG_CMD_HEADER_STR "\x00"
    "\x00\x00\x01\x51\x00\x0C"
    MSG_CMD_PROMPT_STR "\x00\x00"
    "\x00\x00\x01\x52\x00\x1C"
    MSG_STATUS_NORMAL_STR "\x00\x00"
    "\x00\x00\x01\x53\x00\x18"
    MSG_STATUS_PAUSED_STR "\x00\x00"
    "\x00\x00\x01\x54\x00\x1A"
    MSG_STATUS_DISABLED_STR "\x00\x00"
    "\x00\x00\x01\x55\x00\x14"
    MSG_STATUS_LOGFILE_STR "\x00\x00"
    "\x00\x00\x01\x56\x00\x16"
    MSG_STATUS_LOGDEVICE_STR "\x00\x00"
    "\x00\x00\x01\x57\x00\x20"
    MSG_STATUS_LOGDEBUG_STR "\x00"
    "\x00\x00\x01\x58\x00\x16"
    MSG_STATUS_SAVESET_STR "\x00"
    "\x00\x00\x01\x59\x00\x1A"
    MSG_STATUS_LOADSET_STR "\x00\x00"
    "\x00\x00\x01\x5A\x00\x2C"
    MSG_LOG_START_STR "\x00"
    "\x00\x00\x01\x5B\x00\x1C"
    MSG_LOG_STOP_STR "\x00"
    "\x00\x00\x01\x5C\x00\x1A"
    MSG_LOG_DISABLED_STR "\x00\x00"
    "\x00\x00\x01\x5D\x00\x1A"
    MSG_LOG_ENABLED_STR "\x00\x00"
    "\x00\x00\x01\x5E\x00\x40"
    MSG_ERROR_NO_AMIGAGUIDE_STR "\x00\x00"
    "\x00\x00\x01\x5F\x00\x50"
    MSG_ERROR_CREATE_AMIGAGUIDE_STR "\x00"
    "\x00\x00\x01\x60\x00\x16"
    MSG_ERROR_AGUIDE_GENERIC_STR "\x00\x00"
    "\x00\x00\x01\x61\x00\x70"
    MSG_ERROR_AGUIDE_CANT_OPEN_STR "\x00"
    "\x00\x00\x01\x62\x00\x10"
    MSG_HELPFILE_NAME_STR "\x00\x00"
    "\x00\x00\x01\x63\x00\x0A"
    MSG_LINK_MAIN_STR "\x00"
    "\x00\x00\x01\x64\x00\x10"
    MSG_LINK_MAINWIN_STR "\x00"
    "\x00\x00\x01\x65\x00\x14"
    MSG_LINK_FUNCWIN_STR "\x00"
    "\x00\x00\x01\x66\x00\x14"
    MSG_LINK_SETUPWIN_STR "\x00"
    "\x00\x00\x01\x67\x00\x12"
    MSG_LINK_FORMATWIN_STR "\x00"
    "\x00\x00\x01\x68\x00\x12"
    MSG_LINK_MENU_PROJECT_STR "\x00"
    "\x00\x00\x01\x69\x00\x12"
    MSG_LINK_MENU_WINDOW_STR "\x00"
    "\x00\x00\x01\x6A\x00\x14"
    MSG_LINK_MENU_SETTINGS_STR "\x00\x00"
    "\x00\x00\x01\x6B\x00\x12"
    MSG_LINK_MENU_BUFFER_STR "\x00\x00"
    "\x00\x00\x01\x6C\x00\x1C"
    MSG_COMMODITY_DESC_STR "\x00"
    "\x00\x00\x01\x6D\x00\x08"
    MSG_INVALID_HOTKEY_STR "\x00"
    "\x00\x00\x01\x6E\x00\x0E"
    MSG_APPMENU_NAME_STR "\x00"
    "\x00\x00\x01\x6F\x01\x4C"
    MSG_ABOUT_SNOOPDOS_STR "\x00\x00"
    "\x00\x00\x01\x70\x00\x06"
    NUM_OF_MSGS_STR "\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};


#ifdef CATCOMP_CODE

STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
LONG   *l;
UWORD  *w;
STRPTR  builtIn;

    l = (LONG *)CatCompBlock;

    while (*l != stringNum)
    {
        w = (UWORD *)((ULONG)l + 4);
        l = (LONG *)((ULONG)l + (ULONG)*w + 6);
    }
    builtIn = (STRPTR)((ULONG)l + 6);

#define XLocaleBase LocaleBase
#define LocaleBase li->li_LocaleBase
    
    if (LocaleBase)
        return(GetCatalogStr(li->li_Catalog,stringNum,builtIn));
#define LocaleBase XLocaleBase
#undef XLocaleBase

    return(builtIn);
}


#endif /* CATCOMP_CODE */


/****************************************************************************/


#endif /* SNOOPTEXT_H */
