#ifndef INLINE4_ICONOBJECT_H
#define INLINE4_ICONOBJECT_H

/*
** This file was auto generated by idltool 52.1.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_CLASSUSR_H
#include <intuition/classusr.h>
#endif
#ifndef WORKBENCH_WORKBENCH_H
#include <workbench/workbench.h>
#endif
#include <interfaces/iconobject.h>

/* Inline macros for Interface "main" */
#define NewIconObject(name, tagList) IIconobject->NewIconObject((name), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define NewIconObjectTags(...) IIconobject->NewIconObjectTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define NewIconObjectTags(vargs...) IIconobject->NewIconObjectTags(## vargs) 
#endif
#define DisposeIconObject(iconObject) IIconobject->DisposeIconObject((iconObject)) 
#define GetDefIconObject(iconType, tagList) IIconobject->GetDefIconObject((iconType), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetDefIconObjectTags(...) IIconobject->GetDefIconObjectTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetDefIconObjectTags(vargs...) IIconobject->GetDefIconObjectTags(## vargs) 
#endif
#define PutIconObject(iconObject, path, tagList) IIconobject->PutIconObject((iconObject), (path), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PutIconObjectTags(iconObject, ...) IIconobject->PutIconObjectTags((iconObject), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PutIconObjectTags(iconObject, vargs...) IIconobject->PutIconObjectTags(iconObject, ## vargs) 
#endif
#define IsIconName(fileName) IIconobject->IsIconName((fileName)) 
#define Convert2IconObject(diskObject) IIconobject->Convert2IconObject((diskObject)) 
#define Convert2IconObjectA(diskObject, tagList) IIconobject->Convert2IconObjectA((diskObject), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define Convert2IconObjectTags(...) IIconobject->Convert2IconObjectTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define Convert2IconObjectTags(vargs...) IIconobject->Convert2IconObjectTags(## vargs) 
#endif

#endif /* INLINE4_ICONOBJECT_H */
