#ifndef INLINE4_PM_H
#define INLINE4_PM_H

/*
** This file was auto generated by idltool 52.1.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_PM_H
#include <libraries/pm.h>
#endif
#include <interfaces/pm.h>

/* Inline macros for Interface "main" */
#define PM_MakeMenuA(tags) IPopupMenu->PM_MakeMenuA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_MakeMenu(...) IPopupMenu->PM_MakeMenu(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_MakeMenu(...) IPopupMenu->PM_MakeMenu(## vargs) 
#endif
#define PM_MakeItemA(tags) IPopupMenu->PM_MakeItemA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_MakeItem(...) IPopupMenu->PM_MakeItem(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_MakeItem(...) IPopupMenu->PM_MakeItem(## vargs) 
#endif
#define PM_FreePopupMenu(menu) IPopupMenu->PM_FreePopupMenu((menu)) 
#define PM_OpenPopupMenuA(wnd, tags) IPopupMenu->PM_OpenPopupMenuA((wnd), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_OpenPopupMenu(...) IPopupMenu->PM_OpenPopupMenu(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_OpenPopupMenu(vargs...) IPopupMenu->PM_OpenPopupMenu(## vargs) 
#endif
#define PM_MakeIDListA(tags) IPopupMenu->PM_MakeIDListA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_MakeIDList(...) IPopupMenu->PM_MakeIDList(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_MakeIDList(...) IPopupMenu->PM_MakeIDList(## vargs) 
#endif
#define PM_ItemChecked(pm, id) IPopupMenu->PM_ItemChecked((pm), (id)) 
#define PM_GetItemAttrsA(item, tags) IPopupMenu->PM_GetItemAttrsA((item), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_GetItemAttrs(...) IPopupMenu->PM_GetItemAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_GetItemAttrs(vargs...) IPopupMenu->PM_GetItemAttrs(## vargs) 
#endif
#define PM_SetItemAttrsA(item, tags) IPopupMenu->PM_SetItemAttrsA((item), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_SetItemAttrs(...) IPopupMenu->PM_SetItemAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_SetItemAttrs(vargs...) IPopupMenu->PM_SetItemAttrs(## vargs) 
#endif
#define PM_FindItem(menu, id) IPopupMenu->PM_FindItem((menu), (id)) 
#define PM_AlterState(menu, idlst, action) IPopupMenu->PM_AlterState((menu), (idlst), (action)) 
#define PM_ExLstA(id) IPopupMenu->PM_ExLstA((id)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_ExLst(...) IPopupMenu->PM_ExLst(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_ExLst(...) IPopupMenu->PM_ExLst(## vargs) 
#endif
#define PM_FilterIMsgA(window, menu, imsg, tags) IPopupMenu->PM_FilterIMsgA((window), (menu), (imsg), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_FilterIMsg(window, menu, ...) IPopupMenu->PM_FilterIMsg((window), (menu), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_FilterIMsg(window, menu, vargs...) IPopupMenu->PM_FilterIMsg(window, menu, ## vargs) 
#endif
#define PM_InsertMenuItemA(menu, tags) IPopupMenu->PM_InsertMenuItemA((menu), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_InsertMenuItem(...) IPopupMenu->PM_InsertMenuItem(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_InsertMenuItem(vargs...) IPopupMenu->PM_InsertMenuItem(## vargs) 
#endif
#define PM_RemoveMenuItem(menu, item) IPopupMenu->PM_RemoveMenuItem((menu), (item)) 
#define PM_AbortHook(handle) IPopupMenu->PM_AbortHook((handle)) 
#define PM_GetVersion() IPopupMenu->PM_GetVersion() 
#define PM_ReloadPrefs() IPopupMenu->PM_ReloadPrefs() 
#define PM_LayoutMenuA(window, menu, tags) IPopupMenu->PM_LayoutMenuA((window), (menu), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define PM_LayoutMenu(window, ...) IPopupMenu->PM_LayoutMenu((window), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define PM_LayoutMenu(window, vargs...) IPopupMenu->PM_LayoutMenu(window, ## vargs) 
#endif
#define PM_FreeIDList(list) IPopupMenu->PM_FreeIDList((list)) 

#endif /* INLINE4_PM_H */
