#ifndef INLINE4_PREFERENCES_H
#define INLINE4_PREFERENCES_H

/*
** This file was auto generated by idltool 52.1.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef SCALOS_PREFERENCES_H
#include <scalos/preferences.h>
#endif
#include <interfaces/preferences.h>

/* Inline macros for Interface "main" */
#define AllocPrefsHandle(name) IPreferences->AllocPrefsHandle((name)) 
#define FreePrefsHandle(prefsHandle) IPreferences->FreePrefsHandle((prefsHandle)) 
#define SetPreferences(prefsHandle, iD, prefsTag, a1arg, struct_Size) IPreferences->SetPreferences((prefsHandle), (iD), (prefsTag), (a1arg), (struct_Size)) 
#define GetPreferences(prefsHandle, iD, prefsTag, a1arg, struct_Size) IPreferences->GetPreferences((prefsHandle), (iD), (prefsTag), (a1arg), (struct_Size)) 
#define ReadPrefsHandle(prefsHandle, filename) IPreferences->ReadPrefsHandle((prefsHandle), (filename)) 
#define WritePrefsHandle(prefsHandle, filename) IPreferences->WritePrefsHandle((prefsHandle), (filename)) 
#define FindPreferences(prefsHandle, iD, prefsTag) IPreferences->FindPreferences((prefsHandle), (iD), (prefsTag)) 
#define SetEntry(prefsHandle, iD, prefsTag, a1arg, struct_Size, entry) IPreferences->SetEntry((prefsHandle), (iD), (prefsTag), (a1arg), (struct_Size), (entry)) 
#define GetEntry(prefsHandle, iD, prefsTag, a1arg, struct_Size, entry) IPreferences->GetEntry((prefsHandle), (iD), (prefsTag), (a1arg), (struct_Size), (entry)) 
#define RemEntry(prefsHandle, iD, prefsTag, entry) IPreferences->RemEntry((prefsHandle), (iD), (prefsTag), (entry)) 

#endif /* INLINE4_PREFERENCES_H */
