#ifndef INLINE4_SCALOSPREVIEWPLUGIN_H
#define INLINE4_SCALOSPREVIEWPLUGIN_H

/*
** This file was auto generated by idltool 52.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef SCALOS_SCALOS_H
#include <scalos/scalos.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#include <interfaces/scalospreviewplugin.h>

/* Inline macros for Interface "main" */
#define SCAPreviewGenerate(wt, dirLock, iconName, tagList) IScalosPreviewPlugin->SCAPreviewGenerate((wt), (dirLock), (iconName), (tagList)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SCAPreviewGenerateTags(wt, dirLock, ...) IScalosPreviewPlugin->SCAPreviewGenerateTags((wt), (dirLock), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SCAPreviewGenerateTags(wt, dirLock, vargs...) IScalosPreviewPlugin->SCAPreviewGenerateTags(wt, dirLock, ## vargs) 
#endif

#endif /* INLINE4_SCALOSPREVIEWPLUGIN_H */
