#ifndef INLINE4_SCALOSPREFSPLUGIN_H
#define INLINE4_SCALOSPREFSPLUGIN_H

/*
** This file was auto generated by idltool 52.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/scalosprefsplugin.h>

/* Inline macros for Interface "main" */
#define SCAGetPrefsInfo(which) IScalosPrefsPlugin->SCAGetPrefsInfo((which)) 

#endif /* INLINE4_SCALOSPREFSPLUGIN_H */
