/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/preferences.h>
#include <proto/preferences.h>


static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }


STATIC struct Library * stub_OpenPPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenPPC };

STATIC APTR stub_ClosePPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClosePPC };

STATIC APTR stub_ExpungePPC(ULONG *regarray __attribute__((unused)))
{
    return NULL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray __attribute__((unused)))
{
    return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static APTR stub_AllocPrefsHandlePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	return Self->AllocPrefsHandle(
		(CONST_STRPTR)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_AllocPrefsHandle = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_AllocPrefsHandlePPC };

static VOID stub_FreePrefsHandlePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	Self->FreePrefsHandle(
		(APTR)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_FreePrefsHandle = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_FreePrefsHandlePPC };

static VOID stub_SetPreferencesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	Self->SetPreferences(
		(APTR)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(const APTR)regarray[9],
		(UWORD)(regarray[2] & 0xffff)
	);
}
STATIC CONST struct EmuTrap stub_SetPreferences = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SetPreferencesPPC };

static ULONG stub_GetPreferencesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	return Self->GetPreferences(
		(APTR)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(APTR)regarray[9],
		(UWORD)(regarray[2] & 0xffff)
	);
}
STATIC CONST struct EmuTrap stub_GetPreferences = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_GetPreferencesPPC };

static VOID stub_ReadPrefsHandlePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	Self->ReadPrefsHandle(
		(APTR)regarray[8],
		(CONST_STRPTR)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_ReadPrefsHandle = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_ReadPrefsHandlePPC };

static VOID stub_WritePrefsHandlePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	Self->WritePrefsHandle(
		(APTR)regarray[8],
		(CONST_STRPTR)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_WritePrefsHandle = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_WritePrefsHandlePPC };

static struct PrefsStruct * stub_FindPreferencesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	return Self->FindPreferences(
		(APTR)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_FindPreferences = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_FindPreferencesPPC };

static VOID stub_SetEntryPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	Self->SetEntry(
		(APTR)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(const APTR)regarray[9],
		(UWORD)(regarray[2] & 0xffff),
		(ULONG)regarray[3]
	);
}
STATIC CONST struct EmuTrap stub_SetEntry = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SetEntryPPC };

static ULONG stub_GetEntryPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	return Self->GetEntry(
		(APTR)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(APTR)regarray[9],
		(UWORD)(regarray[2] & 0xffff),
		(ULONG)regarray[3]
	);
}
STATIC CONST struct EmuTrap stub_GetEntry = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_GetEntryPPC };

static ULONG stub_RemEntryPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct PreferencesIFace *Self = (struct PreferencesIFace *) ExtLib->MainIFace;

	return Self->RemEntry(
		(APTR)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(ULONG)regarray[2]
	);
}
STATIC CONST struct EmuTrap stub_RemEntry = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_RemEntryPPC };

CONST CONST_APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_AllocPrefsHandle,
	&stub_FreePrefsHandle,
	&stub_SetPreferences,
	&stub_GetPreferences,
	&stub_ReadPrefsHandle,
	&stub_WritePrefsHandle,
	&stub_FindPreferences,
	&stub_SetEntry,
	&stub_GetEntry,
	&stub_RemEntry,
	(CONST_APTR)-1
};
