#ifndef SCALOSPLUGIN_INTERFACE_DEF_H
#define SCALOSPLUGIN_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.7.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ScalosPluginIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct ScalosPluginIFace *Self);
	ULONG APICALL (*Release)(struct ScalosPluginIFace *Self);
	void APICALL (*Expunge)(struct ScalosPluginIFace *Self);
	struct Interface * APICALL (*Clone)(struct ScalosPluginIFace *Self);
	const struct ScaClassInfo * APICALL (*SCAGetClassInfo)(struct ScalosPluginIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* SCALOSPLUGIN_INTERFACE_DEF_H */
