#ifndef INLINE4_GUIGFX_H
#define INLINE4_GUIGFX_H

/*
** This file was auto generated by idltool 52.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/guigfx.h>

/* Inline macros for Interface "main" */
#define MakePictureA(array, width, height, tags) IGuiGFX->MakePictureA((array), (width), (height), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define MakePicture(array, width, ...) IGuiGFX->MakePicture((array), (width), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define MakePicture(array, width, vargs...) IGuiGFX->MakePicture(array, width, ## vargs) 
#endif
#define LoadPictureA(filename, tags) IGuiGFX->LoadPictureA((filename), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LoadPicture(...) IGuiGFX->LoadPicture(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LoadPicture(vargs...) IGuiGFX->LoadPicture(## vargs) 
#endif
#define ReadPictureA(rp, colormap, x, y, width, height, tags) IGuiGFX->ReadPictureA((rp), (colormap), (x), (y), (width), (height), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ReadPicture(rp, colormap, x, y, width, ...) IGuiGFX->ReadPicture((rp), (colormap), (x), (y), (width), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ReadPicture(rp, colormap, x, y, width, vargs...) IGuiGFX->ReadPicture(rp, colormap, x, y, width, ## vargs) 
#endif
#define ClonePictureA(pic, tags) IGuiGFX->ClonePictureA((pic), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ClonePicture(...) IGuiGFX->ClonePicture(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ClonePicture(vargs...) IGuiGFX->ClonePicture(## vargs) 
#endif
#define DeletePicture(pic) IGuiGFX->DeletePicture((pic)) 
#define AddPictureA(psm, pic, tags) IGuiGFX->AddPictureA((psm), (pic), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AddPicture(psm, ...) IGuiGFX->AddPicture((psm), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AddPicture(psm, vargs...) IGuiGFX->AddPicture(psm, ## vargs) 
#endif
#define AddPaletteA(psm, palette, tags) IGuiGFX->AddPaletteA((psm), (palette), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AddPalette(psm, ...) IGuiGFX->AddPalette((psm), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AddPalette(psm, vargs...) IGuiGFX->AddPalette(psm, ## vargs) 
#endif
#define AddPixelArrayA(psm, array, width, height, tags) IGuiGFX->AddPixelArrayA((psm), (array), (width), (height), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AddPixelArray(psm, array, width, ...) IGuiGFX->AddPixelArray((psm), (array), (width), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AddPixelArray(psm, array, width, vargs...) IGuiGFX->AddPixelArray(psm, array, width, ## vargs) 
#endif
#define RemColorHandle(colorhandle) IGuiGFX->RemColorHandle((colorhandle)) 
#define CreatePenShareMapA(tags) IGuiGFX->CreatePenShareMapA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreatePenShareMap(...) IGuiGFX->CreatePenShareMap(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreatePenShareMap(...) IGuiGFX->CreatePenShareMap(## vargs) 
#endif
#define DeletePenShareMap(psm) IGuiGFX->DeletePenShareMap((psm)) 
#define ObtainDrawHandleA(psm, rp, cm, tags) IGuiGFX->ObtainDrawHandleA((psm), (rp), (cm), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define ObtainDrawHandle(psm, rp, ...) IGuiGFX->ObtainDrawHandle((psm), (rp), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define ObtainDrawHandle(psm, rp, vargs...) IGuiGFX->ObtainDrawHandle(psm, rp, ## vargs) 
#endif
#define ReleaseDrawHandle(drawhandle) IGuiGFX->ReleaseDrawHandle((drawhandle)) 
#define DrawPictureA(drawhandle, pic, x, y, tags) IGuiGFX->DrawPictureA((drawhandle), (pic), (x), (y), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DrawPicture(drawhandle, pic, x, ...) IGuiGFX->DrawPicture((drawhandle), (pic), (x), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DrawPicture(drawhandle, pic, x, vargs...) IGuiGFX->DrawPicture(drawhandle, pic, x, ## vargs) 
#endif
#define MapPaletteA(drawhandle, palette, pentab, tags) IGuiGFX->MapPaletteA((drawhandle), (palette), (pentab), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define MapPalette(drawhandle, palette, ...) IGuiGFX->MapPalette((drawhandle), (palette), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define MapPalette(drawhandle, palette, vargs...) IGuiGFX->MapPalette(drawhandle, palette, ## vargs) 
#endif
#define MapPenA(drawhandle, rgb, tags) IGuiGFX->MapPenA((drawhandle), (rgb), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define MapPen(drawhandle, ...) IGuiGFX->MapPen((drawhandle), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define MapPen(drawhandle, vargs...) IGuiGFX->MapPen(drawhandle, ## vargs) 
#endif
#define CreatePictureBitMapA(drawhandle, pic, tags) IGuiGFX->CreatePictureBitMapA((drawhandle), (pic), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreatePictureBitMap(drawhandle, ...) IGuiGFX->CreatePictureBitMap((drawhandle), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreatePictureBitMap(drawhandle, vargs...) IGuiGFX->CreatePictureBitMap(drawhandle, ## vargs) 
#endif
#define DoPictureMethodA(pic, method, arguments) IGuiGFX->DoPictureMethodA((pic), (method), (arguments)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DoPictureMethod(pic, ...) IGuiGFX->DoPictureMethod((pic), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DoPictureMethod(pic, vargs...) IGuiGFX->DoPictureMethod(pic, ## vargs) 
#endif
#define GetPictureAttrsA(pic, tags) IGuiGFX->GetPictureAttrsA((pic), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define GetPictureAttrs(...) IGuiGFX->GetPictureAttrs(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define GetPictureAttrs(vargs...) IGuiGFX->GetPictureAttrs(## vargs) 
#endif
#define LockPictureA(pic, mode, args) IGuiGFX->LockPictureA((pic), (mode), (args)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define LockPicture(pic, ...) IGuiGFX->LockPicture((pic), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define LockPicture(pic, vargs...) IGuiGFX->LockPicture(pic, ## vargs) 
#endif
#define UnLockPicture(pic, mode) IGuiGFX->UnLockPicture((pic), (mode)) 
#define IsPictureA(filename, tags) IGuiGFX->IsPictureA((filename), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IsPicture(...) IGuiGFX->IsPicture(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IsPicture(vargs...) IGuiGFX->IsPicture(## vargs) 
#endif
#define CreateDirectDrawHandleA(drawhandle, sw, sh, dw, dh, tags) IGuiGFX->CreateDirectDrawHandleA((drawhandle), (sw), (sh), (dw), (dh), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreateDirectDrawHandle(drawhandle, sw, sh, dw, ...) IGuiGFX->CreateDirectDrawHandle((drawhandle), (sw), (sh), (dw), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreateDirectDrawHandle(drawhandle, sw, sh, dw, vargs...) IGuiGFX->CreateDirectDrawHandle(drawhandle, sw, sh, dw, ## vargs) 
#endif
#define DeleteDirectDrawHandle(ddh) IGuiGFX->DeleteDirectDrawHandle((ddh)) 
#define DirectDrawTrueColorA(ddh, array, x, y, tags) IGuiGFX->DirectDrawTrueColorA((ddh), (array), (x), (y), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define DirectDrawTrueColor(ddh, array, x, ...) IGuiGFX->DirectDrawTrueColor((ddh), (array), (x), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define DirectDrawTrueColor(ddh, array, x, vargs...) IGuiGFX->DirectDrawTrueColor(ddh, array, x, ## vargs) 
#endif
#define CreatePictureMaskA(pic, mask, maskwidth, tags) IGuiGFX->CreatePictureMaskA((pic), (mask), (maskwidth), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreatePictureMask(pic, mask, ...) IGuiGFX->CreatePictureMask((pic), (mask), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreatePictureMask(pic, mask, vargs...) IGuiGFX->CreatePictureMask(pic, mask, ## vargs) 
#endif

#endif /* INLINE4_GUIGFX_H */
