/****************************************************************
   This file was created automatically by `FlexCat V1.0'
   Do NOT edit by hand!
****************************************************************/

#ifndef amosaic_CAT_H
#define amosaic_CAT_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif	/*  !EXEC_TYPES_H	    */
#ifndef LIBRARIES_LOCALE_H
#include <libraries/locale.h>
#endif	/*  !LIBRARIES_LOCALE_H     */


/*  Prototypes	*/
extern void OpenamosaicCatalog(struct Locale *, STRPTR);
extern void CloseamosaicCatalog(void);
extern CONST_STRPTR GetamosaicString(LONG);

/*  Definitions */
#define MSG_MENU_PROJECT 0
#define MSG_MENU_OPEN_URL 1
#define MSG_MENU_OPEN_URL_SC 2
#define MSG_MENU_OPEN_LOCAL 3
#define MSG_MENU_OPEN_LOCAL_SC 4
#define MSG_MENU_RELOAD_CURRENT 5
#define MSG_MENU_RELOAD_CURRENT_SC 6
#define MSG_MENU_REFRESH_CURRENT 7
#define MSG_MENU_URL_TO_CLIPBOARD 8
#define MSG_MENU_URL_TO_CLIPBOARD_SC 9
#define MSG_MENU_CLIPBOARD_TO_URL 10
#define MSG_MENU_CLIPBOARD_TO_URL_SC 11
#define MSG_MENU_FIND_IN_CURRENT 12
#define MSG_MENU_FIND_IN_CURRENT_SC 13
#define MSG_MENU_VIEW_SOURCE 14
#define MSG_MENU_VIEW_SOURCE_SC 15
#define MSG_MENU_SAVE_AS 16
#define MSG_MENU_SAVE_AS_SC 17
#define MSG_MENU_PRINT 18
#define MSG_MENU_PRINT_SC 19
#define MSG_MENU_ABOUT 20
#define MSG_MENU_ABOUT_SC 21
#define MSG_MENU_QUIT 22
#define MSG_MENU_QUIT_SC 23
#define MSG_MENU_EDIT 24
#define MSG_MENU_COPY 25
#define MSG_MENU_COPY_SC 26
#define MSG_MENU_OPTIONS 27
#define MSG_MENU_LOAD_TO_DISK 28
#define MSG_MENU_LOAD_TO_DISK_SC 29
#define MSG_MENU_DELAY_IMAGE_LOADING 30
#define MSG_MENU_DELAY_IMAGE_LOADING_SC 31
#define MSG_MENU_LOAD_IMAGES 32
#define MSG_MENU_LOAD_IMAGES_SC 33
#define MSG_MENU_ISINDEX_TO_FORM 34
#define MSG_MENU_BUTTONS 35
#define MSG_MENU_TEXT_ONLY 36
#define MSG_MENU_TEXT_ONLY_SC 37
#define MSG_MENU_IMAGES_ONLY 38
#define MSG_MENU_IMAGES_ONLY_SC 39
#define MSG_MENU_IMAGES_AND_TEXT 40
#define MSG_MENU_IMAGES_AND_TEXT_SC 41
#define MSG_MENU_FLUSH_IMAGE_CACHE 42
#define MSG_MENU_FLUSH_IMAGE_CACHE_SC 43
#define MSG_MENU_CLEAR_GLOBAL_HISTORY 44
#define MSG_MENU_CLEAR_GLOBAL_HISTORY_SC 45
#define MSG_MENU_NAVIGATE 46
#define MSG_MENU_BACK 47
#define MSG_MENU_BACK_SC 48
#define MSG_MENU_FORWARD 49
#define MSG_MENU_FORWARD_SC 50
#define MSG_MENU_HOME_DOCUMENT 51
#define MSG_MENU_HOME_DOCUMENT_SC 52
#define MSG_MENU_WINDOW_HISTORY 53
#define MSG_MENU_WINDOW_HISTORY_SC 54
#define MSG_MENU_HOTLIST 55
#define MSG_MENU_HOTLIST_SC 56
#define MSG_MENU_ADD_HOTLIST 57
#define MSG_MENU_ADD_HOTLIST_SC 58
#define MSG_MENU_REXX 59
#define MSG_MENU_MACRO 60
#define MSG_MENU_MACRO_SC 61
#define MSG_GADGET_TITLE 62
#define MSG_GADGET_URL 63
#define MSG_HOTLIST_ADD 64
#define MSG_HOTLIST_NEW 65
#define MSG_HOTLIST_DELETE 66
#define MSG_HOTLIST_EDIT 67
#define MSG_HOTLIST_SORT 68
#define MSG_HOTLIST_MOVE 69
#define MSG_HOTLIST_PARENT 70
#define MSG_HOTLIST_EDITGROUP_TITLE 71
#define MSG_HOTLIST_GROUP_DEFAULTNAME 72
#define MSG_HOTLIST_EDIT_WINDOW_TITLE 73
#define MSG_HOTLIST_EDIT_TITLE 74
#define MSG_HOTLIST_EDIT_URL 75
#define MSG_HOTLIST_EDIT_OK 76
#define MSG_HOTLIST_EDIT_CANCEL 77
#define MSG_BUTTON_BACK 78
#define MSG_BUTTON_BACK_SC 79
#define MSG_BUTTON_FORWARD 80
#define MSG_BUTTON_FORWARD_SC 81
#define MSG_BUTTON_RELOAD 82
#define MSG_BUTTON_RELOAD_SC 83
#define MSG_BUTTON_HOME 84
#define MSG_BUTTON_HOME_SC 85
#define MSG_BUTTON_OPEN 86
#define MSG_REQ_URL_TITLE 87
#define MSG_REQ_URL_URL 88
#define MSG_REQ_URL_OPEN 89
#define MSG_REQ_URL_CLEAR 90
#define MSG_REQ_URL_CANCEL 91
#define MSG_WIN_SOURCE_TITLE 92
#define MSG_REQ_FINDRESULT_TITLE 93
#define MSG_REQ_FINDRESULT_NO_MATCHES 94
#define MSG_REQ_FINDRESULT_NO_MORE_MATCHES 95
#define MSG_REQ_FINDRESULT_OK 96
#define MSG_REQ_FIND_TITLE 97
#define MSG_REQ_FIND_STRING 98
#define MSG_REQ_FIND_CASELESS 99
#define MSG_REQ_FIND_BACKWARDS 100
#define MSG_REQ_FIND_FIND 101
#define MSG_REQ_FIND_CLEAR 102
#define MSG_REQ_FIND_CANCEL 103
#define MSG_REQ_SAVE_FILEREQ_TITLE 104
#define MSG_REQ_SAVE_FILEREQ_POSTEXT 105
#define MSG_REQ_SAVE_TITLE 106
#define MSG_REQ_SAVE_FILEFORMAT 107
#define MSG_REQ_SAVE_FILEFORMAT_PLAIN 108
#define MSG_REQ_SAVE_FILEFORMAT_FORMATTED 109
#define MSG_REQ_SAVE_FILEFORMAT_HTML 110
#define MSG_REQ_SAVE_FILE 111
#define MSG_REQ_SAVE_SAVE 112
#define MSG_REQ_SAVE_CLEAR 113
#define MSG_REQ_SAVE_CANCEL 114
#define MSG_REQ_SAVEBINARY_TITLE 115
#define MSG_REQ_SAVEBINARY_POSTEXT 116
#define MSG_REQ_ABOUT_TITLE 117
#define MSG_REQ_ABOUT_OK 118
#define MSG_REQ_OPEN_LOCAL_TITLE 119
#define MSG_REQ_MACRO_TITLE 120
#define MSG_REQ_MACRO_MACRO 121
#define MSG_REQ_MACRO_RUN 122
#define MSG_REQ_MACRO_CLEAR 123
#define MSG_REQ_MACRO_CANCEL 124
#define MSG_REQ_MACRO_FILEREQ_TITLE 125
#define MSG_REQ_FORM_READY 126
#define MSG_REQ_SHOW_THEM 127
#define MSG_REQ_CONSTRUCTING 128

#endif /*   !amosaic_CAT_H  */
