
OBJS = \
	Startup.o 
	
Program			= Startup.o

TARGETS			= aros os3 morphos os4
OBJDIRS			= 
MAKEDIRS		= 
INSTALLDIR		= ../lib
CCFLAGS = -O0

NOLINK			= 1
BUILD_LIBRARY	= 0
PREP			= #-DDEBUG

	include ../Makefile.mk
