/* defs.h */
typedef enum { MENU0,MENU1,MENU2,MENU3 } MENUSTRIP;
typedef enum { ABOUT,TITLE,START,CONT,COLOR,SAVE,QUIT } MENULIST0;
typedef enum { NEXT,MANDELBROT,JULIA,ULTIMATE,LCOSZ,ESINZ,LEXPZ,BIOMORPH,BIOTYPE
             , NEWTON,NEWTONTYPE,MAGNET0,MAGNET1,MAGNET2,MAGNET3
             } MENULIST1;
typedef enum { NEXTdummy,STRATT,CYCLIC,CYCLETYPE } MENULIST1b;
typedef enum { LO,HI,NO,LA } MENULIST2;
typedef enum { D2RECT,D3RECT,SPHERE } MENULIST3;
typedef enum { BIO0,BIO1,BIO2,BIO3,BIO4,BIO5 } BIOS;
typedef enum { NR0,NR1,NR2,NR3,NR4,NR5 } NRS;
typedef enum { CYCLE0,CYCLE1,CYCLE2,CYCLE3,CYCLE4,CYCLE5 } CYC;


