(APTR) LibW3D_CreateContext,    
(APTR) LibW3D_DestroyContext,    
(APTR) LibW3D_GetState,    
(APTR) LibW3D_SetState,    
    
(APTR) LibW3D_CheckDriver,    
(APTR) LibW3D_LockHardware,    
(APTR) LibW3D_UnLockHardware,    
(APTR) LibW3D_WaitIdle,    
(APTR) LibW3D_CheckIdle,    
(APTR) LibW3D_Query,    
(APTR) LibW3D_GetTexFmtInfo,    
    
(APTR) LibW3D_AllocTexObj,    
(APTR) LibW3D_FreeTexObj,    
(APTR) LibW3D_ReleaseTexture,    
(APTR) LibW3D_FlushTextures,    
(APTR) LibW3D_SetFilter,    
(APTR) LibW3D_SetTexEnv,    
(APTR) LibW3D_SetWrapMode,    
(APTR) LibW3D_UpdateTexImage,    
(APTR) LibW3D_UploadTexture,    
    
(APTR) LibW3D_DrawLine,    
(APTR) LibW3D_DrawPoint,    
(APTR) LibW3D_DrawTriangle,    
(APTR) LibW3D_DrawTriFan,    
(APTR) LibW3D_DrawTriStrip,    
    
(APTR) LibW3D_SetAlphaMode,    
(APTR) LibW3D_SetBlendMode,    
(APTR) LibW3D_SetDrawRegion,    
(APTR) LibW3D_SetFogParams,    
(APTR) LibW3D_SetColorMask,    
(APTR) LibW3D_SetStencilFunc,    
    
(APTR) LibW3D_AllocZBuffer,    
(APTR) LibW3D_FreeZBuffer,    
(APTR) LibW3D_ClearZBuffer,    
(APTR) LibW3D_ReadZPixel,    
(APTR) LibW3D_ReadZSpan,    
(APTR) LibW3D_SetZCompareMode,    
    
(APTR) LibW3D_AllocStencilBuffer,    
(APTR) LibW3D_ClearStencilBuffer,    
(APTR) LibW3D_FillStencilBuffer,    
(APTR) LibW3D_FreeStencilBuffer,    
(APTR) LibW3D_ReadStencilPixel,    
(APTR) LibW3D_ReadStencilSpan,    
    
(APTR) LibW3D_SetLogicOp,    
(APTR) LibW3D_Hint,    
(APTR) LibW3D_SetDrawRegionWBM,    
(APTR) LibW3D_GetDriverState,    
(APTR) LibW3D_Flush,    
(APTR) LibW3D_SetPenMask,    
(APTR) LibW3D_SetStencilOp,    
(APTR) LibW3D_SetWriteMask,    
(APTR) LibW3D_WriteStencilPixel,    
(APTR) LibW3D_WriteStencilSpan,    
(APTR) LibW3D_WriteZPixel,    
(APTR) LibW3D_WriteZSpan,    
(APTR) LibW3D_SetCurrentColor,    
(APTR) LibW3D_SetCurrentPen,    
(APTR) LibW3D_UpdateTexSubImage,    
(APTR) LibW3D_FreeAllTexObj,    
(APTR) LibW3D_GetDestFmt,    
    
(APTR) LibW3D_DrawLineStrip,    
(APTR) LibW3D_DrawLineLoop,    
(APTR) LibW3D_GetDrivers,    
(APTR) LibW3D_QueryDriver,    
(APTR) LibW3D_GetDriverTexFmtInfo,    
(APTR) LibW3D_RequestMode,    
(APTR) LibW3D_SetScissor,    
(APTR) LibW3D_FlushFrame,    
(APTR) LibW3D_TestMode,    
(APTR) LibW3D_SetChromaTestBounds,    
(APTR) LibW3D_ClearDrawRegion,    
    
(APTR) LibW3D_DrawTriangleV,    
(APTR) LibW3D_DrawTriFanV,    
(APTR) LibW3D_DrawTriStripV,    
(APTR) LibW3D_GetScreenmodeList,    
(APTR) LibW3D_FreeScreenmodeList,    
(APTR) LibW3D_BestModeID,    
    
(APTR) LibW3D_VertexPointer,    
(APTR) LibW3D_TexCoordPointer,    
(APTR) LibW3D_ColorPointer,    
(APTR) LibW3D_BindTexture,    
(APTR) LibW3D_DrawArray,    
(APTR) LibW3D_DrawElements,    
(APTR) LibW3D_SetFrontFace,    
