enum codes { ID_GOTOANCHOR = 900, ID_CONFIGSCROLLBARS,
	       ID_UPARROW, ID_DOWNARROW, ID_LEFTARROW, ID_RIGHTARROW,
	       ID_IMAGELOAD, ID_MUIRESIZE,ID_STRINGURL,
	       ID_POSTTEXT,ID_GETTEXT
	   };
