/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Dataspace"
#define F_CLASS_VERSION                         3
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "03.00 (2005/08/08)"

#include <feelin/class_startup.c>

#include "Private.h"