TOP = ../../..


CC = gcc
CP = cp
ECHO = echo
DEFINES = -D_AROS
RM = rm

FLAGS = -nostartfiles -nostdlib -Wl,-i

BINDIR = $(TOP)/bin/linux-i386/gen
LIBDIR = $(TOP)/bin/linux-i386/AROS/lib
AROSDIR = $(TOP)/bin/linux-i386/AROS


OS_INCLUDES_DIR = $(BINDIR)/include
USER_INCLUDES_DIR = $(TOP)/bin/linux-i386/AROS/Include

OS_INCLUDES = -I$(OS_INCLUDES_DIR)
USER_INCLUDES = -I. -I$(USER_INCLUDES_DIR)

LIBS = -L$(LIBDIR) -lbgui -larosc -larosm -lamiga

STARTUP = $(LIBDIR)/startup.o
 
%.o : %.c 
	@$(ECHO) "Compiling $@..."
	@$(CC) $(OS_INCLUDES) $(USER_INCLUDES) $(DEFINES) -c $^ -o $@

test1	: test1.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test2	: test2.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test3	: test3.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test4	: test4.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test5	: test5.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test6	: test6.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test7	: test7.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test8	: test8.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test9	: test9.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test10	: test10.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test11	: test11.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/

test13	: test13.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 
	@$(ECHO) Installing BGUI testprogram $@ to root dir
	@$(CP) $@ $(AROSDIR)/


clean:
	@$(RM) -rf *.o
