TOP = ../../..


CC = gcc
DEFINES = -D_AROS


BINDIR = $(TOP)/bin/linux-i386/gen
LIBDIR = $(TOP)/bin/linux-i386/AROS/lib

OS_INCLUDES_DIR = $(BINDIR)/include
USER_INCLUDES_DIR = $(TOP)/bin/linux-i386/AROS/Include

OS_INCLUDES = -I$(OS_INCLUDES_DIR)
USER_INCLUDES = -I. -I$(USER_INCLUDES_DIR)
 
%.o : %.c 
	$(CC) $(OS_INCLUDES) $(USER_INCLUDES) $(DEFINES) $^ -o $@ -L$(LIBDIR) -larosc -lamiga -lbgui -lm

test1	: test1.o
test2	: test2.o
test3	: test3.o
test4	: test4.o
test5	: test5.o
test6	: test6.o
test7	: test7.o
test8	: test8.o
test9	: test9.o
test10	: test10.o
test11	: test11.o
test13	: test13.o

