TOP = ../../..


CC = gcc
CP = cp
ECHO = echo
DEFINES = -D_AROS
RM = rm

FLAGS = -nostartfiles -nostdlib -Wl,-i

BINDIR = $(TOP)/bin/linux-i386/gen
LIBDIR = $(TOP)/bin/linux-i386/AROS/lib
AROSDIR = $(TOP)/bin/linux-i386/AROS

BGUIPROGDIR = $(AROSDIR)/bgui

OS_INCLUDES_DIR = $(BINDIR)/include
USER_INCLUDES_DIR = $(TOP)/bin/linux-i386/AROS/Include

OS_INCLUDES = -I$(OS_INCLUDES_DIR)
USER_INCLUDES = -I. -I .. -I$(USER_INCLUDES_DIR)

LIBS = -L$(LIBDIR) -lbgui -larosc -larosm -lamiga

STARTUP = $(LIBDIR)/startup.o

FILES = test1 \
	test2 \
	test3 \
	test4 \
	test5 \
	test6 \
	test7 \
	test8 \
	test9 \
	test13

TARGETS = $(foreach f,$(FILES),$(BGUIPROGDIR)/$(f))

%.o : %.c 
	@$(ECHO) "Compiling $@..."
	@$(CC) $(OS_INCLUDES) $(USER_INCLUDES) $(DEFINES) -c $^ -o $@

$(BGUIPROGDIR)/% : %.o
	@$(CC) $(FLAGS) $(STARTUP) $^ -o $@ $(LIBS) 

all : $(TARGETS)

clean:
	@$(ECHO) Cleaning BGUI testprograms
	@$(RM) -rf *.o $(BGUIPROGDIR)/test*
