#ifndef VPDF_STRINGS_H
#define VPDF_STRINGS_H


/*   This file was created automatically by catcomp.pl
 *   DO NOT EDIT BY HAND!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_NUMBERS

#define MSG_APPLICATION_DESCRIPTION 0
#define MSG_PRINTER_RANGE 1
#define MSG_PRINTER_PAGES 2
#define MSG_PRINTER_FIRSTPAGE 3
#define MSG_PRINTER_LASTPAGE 4
#define MSG_PRINTER_MANUAL 5
#define MSG_PRINTER_RESET 6
#define MSG_PRINTER_REVERSE 7
#define MSG_PRINTER_ORIENTATION 8
#define MSG_PRINTER_COPIES 9
#define MSG_PRINTER_COLLATE 10
#define MSG_PRINTER_SCALING 11
#define MSG_PRINTER_PAGESPERSHEET 12
#define MSG_PRINTER_ORDER 13
#define MSG_PRINTER_AUTOROTATE 14
#define MSG_PRINTER_DRIVER 15
#define MSG_PRINTER_PREFERENCES 16
#define MSG_PRINTER_WINTITLE 17
#define MSG_PRINTER_PRINT 18
#define MSG_PRINTER_CANCEL 19
#define MSG_PRINTER_OUTPUT 20
#define MSG_PRINTER_ODD 21
#define MSG_PRINTER_EVEN 22
#define MSG_PRINTER_ODDEVEN 23
#define MSG_PRINTER_NONE 24
#define MSG_PRINTER_BEST 25
#define MSG_PRINTER_MULTIPLE 26
#define MSG_PRINTER_CUSTOM 27
#define MSG_PRINTER_HORIZONTAL_VERTICAL 28
#define MSG_PRINTER_HORIZONTAL_VERTICALREVERSED 29
#define MSG_PRINTER_HORIZONTALREVERSED_VERTICAL 30
#define MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_REVERSED 31
#define MSG_PRINTER_VERTICAL_HORIZONTAL 32
#define MSG_PRINTER_VERTICALREVERSED_HORIZONTAL 33
#define MSG_PRINTER_VERTICAL_HORIZONTALREVERSED 34
#define MSG_PRINTER_VERTICAL_REVERSED_HORIZONTALREVERSED 35
#define MSG_PRINTER_ABORT 36
#define MSG_MENU_PROJECT 37
#define MSG_MENU_NEWWIN 38
#define MSG_MENU_NEWTAB 39
#define MSG_MENU_FILE 40
#define MSG_MENU_RECENT 41
#define MSG_MENU_PRINT 42
#define MSG_MENU_ABOUT 43
#define MSG_MENU_QUIT 44
#define MSG_MENU_EDIT 45
#define MSG_MENU_COPY 46
#define MSG_MENU_LOG 47
#define MSG_MENU_SETTINGS 48
#define MSG_MENU_SETTINGS_SETTINGS 49
#define MSG_MENU_SETTINGS_SAVE 50
#define MSG_MENU_SETTINGS_MUI 51
#define MSG_MENU_WINDOWS 52
#define MSG_NOFILE 53
#define MSG_SAVE 54
#define MSG_CANCEL 55
#define MSG_USE 56
#define MSG_WINDOWS 57
#define MSG_SETTINGS_LAYOUT 58
#define MSG_SETTINGS_SCALING 59
#define MSG_SETTINGS_OUTLINE 60
#define MSG_SETTINGS_DOCUMENT 61
#define MSG_SETTINGS_LOGWINDOW 62
#define MSG_REQ_OPEN 63
#define MSG_REQ_SAVE 64
#define MSG_REQ_DRAWER 65
#define MSG_TOOLBAR_ZOOMIN 66
#define MSG_TOOLBAR_ZOOMOUT 67
#define MSG_TOOLBAR_COUNTERCLOCKWISE 68
#define MSG_TOOLBAR_CLOCKWISE 69
#define MSG_TOOLBAR_MARK 70
#define MSG_TOOLBAR_SCROLL 71
#define MSG_TOOLBAR_OUTLINE 72
#define MSG_TOOLBAR_FITPAGE 73
#define MSG_TOOLBAR_FITWIDTH 74
#define MSG_TOOLBAR_SINGLE 75
#define MSG_TOOLBAR_CONTINUOUS 76
#define MSG_TOOLBAR_FACING 77
#define MSG_TOOLBAR_CONT_FACING 78
#define MSG_SEARCH_NEXT 79
#define MSG_SEARCH_PREV 80
#define MSG_SEARCH_END 81
#define MSG_SEARCH_LABEL 82
#define MSG_SLIDER_PAGE 83

#endif /* CATCOMP_NUMBERS */


#ifdef CATCOMP_STRINGS

#define MSG_APPLICATION_DESCRIPTION_STR "PDF Viewer"
#define MSG_PRINTER_RANGE_STR "Print Range"
#define MSG_PRINTER_PAGES_STR "Pages:"
#define MSG_PRINTER_FIRSTPAGE_STR "First Page:"
#define MSG_PRINTER_LASTPAGE_STR "Last Page:"
#define MSG_PRINTER_MANUAL_STR "Manual Selection"
#define MSG_PRINTER_RESET_STR "Reset"
#define MSG_PRINTER_REVERSE_STR "Reverse Pages"
#define MSG_PRINTER_ORIENTATION_STR "Page Orientation"
#define MSG_PRINTER_COPIES_STR "Copies:"
#define MSG_PRINTER_COLLATE_STR "Collate"
#define MSG_PRINTER_SCALING_STR "Page Scaling:"
#define MSG_PRINTER_PAGESPERSHEET_STR "Pages per Sheet:"
#define MSG_PRINTER_ORDER_STR "Pages Order:"
#define MSG_PRINTER_AUTOROTATE_STR "Auto Rotate and Center"
#define MSG_PRINTER_DRIVER_STR "Driver"
#define MSG_PRINTER_PREFERENCES_STR "Printer Preferences"
#define MSG_PRINTER_WINTITLE_STR "VPDF · Print Document"
#define MSG_PRINTER_PRINT_STR "Print"
#define MSG_PRINTER_CANCEL_STR "Cancel"
#define MSG_PRINTER_OUTPUT_STR "Output:"
#define MSG_PRINTER_ODD_STR "Odd"
#define MSG_PRINTER_EVEN_STR "Even"
#define MSG_PRINTER_ODDEVEN_STR "Odd and Even"
#define MSG_PRINTER_NONE_STR "None"
#define MSG_PRINTER_BEST_STR "Best"
#define MSG_PRINTER_MULTIPLE_STR "Multiple pages per sheet"
#define MSG_PRINTER_CUSTOM_STR "Custom"
#define MSG_PRINTER_HORIZONTAL_VERTICAL_STR "Horizontal-Vertical"
#define MSG_PRINTER_HORIZONTAL_VERTICALREVERSED_STR "Horizontal - Vertical Reversed"
#define MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_STR "Horizontal Reversed-Vertical"
#define MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_REVERSED_STR "Horizontal Reversed-Vertical Reversed"
#define MSG_PRINTER_VERTICAL_HORIZONTAL_STR "Vertical-Horizontal"
#define MSG_PRINTER_VERTICALREVERSED_HORIZONTAL_STR "Vertical Reversed-Horizontal"
#define MSG_PRINTER_VERTICAL_HORIZONTALREVERSED_STR "Vertical-Horizontal Reversed"
#define MSG_PRINTER_VERTICAL_REVERSED_HORIZONTALREVERSED_STR "Vertical Reversed-Horizontal Reversed"
#define MSG_PRINTER_ABORT_STR "Abort"
#define MSG_MENU_PROJECT_STR "Project"
#define MSG_MENU_NEWWIN_STR "New Window..."
#define MSG_MENU_NEWTAB_STR "New Tab"
#define MSG_MENU_FILE_STR "Open File..."
#define MSG_MENU_RECENT_STR "Open Recent..."
#define MSG_MENU_PRINT_STR "Print..."
#define MSG_MENU_ABOUT_STR "About..."
#define MSG_MENU_QUIT_STR "Quit"
#define MSG_MENU_EDIT_STR "Edit"
#define MSG_MENU_COPY_STR "Copy"
#define MSG_MENU_LOG_STR "Log..."
#define MSG_MENU_SETTINGS_STR "Settings"
#define MSG_MENU_SETTINGS_SETTINGS_STR "Settings..."
#define MSG_MENU_SETTINGS_SAVE_STR "Save as Default"
#define MSG_MENU_SETTINGS_MUI_STR "MUI..."
#define MSG_MENU_WINDOWS_STR "Windows"
#define MSG_NOFILE_STR "No file loaded."
#define MSG_SAVE_STR "_Save"
#define MSG_CANCEL_STR "_Cancel"
#define MSG_USE_STR "_Use"
#define MSG_WINDOWS_STR "Windows"
#define MSG_SETTINGS_LAYOUT_STR "Layout:"
#define MSG_SETTINGS_SCALING_STR "Scaling:"
#define MSG_SETTINGS_OUTLINE_STR "Open document outline"
#define MSG_SETTINGS_DOCUMENT_STR "Document"
#define MSG_SETTINGS_LOGWINDOW_STR "Open log window automatically"
#define MSG_REQ_OPEN_STR "Select File to Open..."
#define MSG_REQ_SAVE_STR "Select File to Save..."
#define MSG_REQ_DRAWER_STR "Select Drawer..."
#define MSG_TOOLBAR_ZOOMIN_STR "Zoom In"
#define MSG_TOOLBAR_ZOOMOUT_STR "Zoom Out"
#define MSG_TOOLBAR_COUNTERCLOCKWISE_STR "Rotate counterclockwise"
#define MSG_TOOLBAR_CLOCKWISE_STR "Rotate clockwise"
#define MSG_TOOLBAR_MARK_STR "Mark"
#define MSG_TOOLBAR_SCROLL_STR "Scroll"
#define MSG_TOOLBAR_OUTLINE_STR "Outline"
#define MSG_TOOLBAR_FITPAGE_STR "Fit Page"
#define MSG_TOOLBAR_FITWIDTH_STR "Fit Width"
#define MSG_TOOLBAR_SINGLE_STR "Single"
#define MSG_TOOLBAR_CONTINUOUS_STR "Continuous"
#define MSG_TOOLBAR_FACING_STR "Facing"
#define MSG_TOOLBAR_CONT_FACING_STR "Continuous Facing"
#define MSG_SEARCH_NEXT_STR "_Next"
#define MSG_SEARCH_PREV_STR "_Prev"
#define MSG_SEARCH_END_STR "End of Document"
#define MSG_SEARCH_LABEL_STR "Search:"
#define MSG_SLIDER_PAGE_STR "Page %ld"

#endif /* CATCOMP_STRINGS */


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
	LONG   cca_ID;
	STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
	{MSG_APPLICATION_DESCRIPTION, (STRPTR)MSG_APPLICATION_DESCRIPTION_STR},
	{MSG_PRINTER_RANGE, (STRPTR)MSG_PRINTER_RANGE_STR},
	{MSG_PRINTER_PAGES, (STRPTR)MSG_PRINTER_PAGES_STR},
	{MSG_PRINTER_FIRSTPAGE, (STRPTR)MSG_PRINTER_FIRSTPAGE_STR},
	{MSG_PRINTER_LASTPAGE, (STRPTR)MSG_PRINTER_LASTPAGE_STR},
	{MSG_PRINTER_MANUAL, (STRPTR)MSG_PRINTER_MANUAL_STR},
	{MSG_PRINTER_RESET, (STRPTR)MSG_PRINTER_RESET_STR},
	{MSG_PRINTER_REVERSE, (STRPTR)MSG_PRINTER_REVERSE_STR},
	{MSG_PRINTER_ORIENTATION, (STRPTR)MSG_PRINTER_ORIENTATION_STR},
	{MSG_PRINTER_COPIES, (STRPTR)MSG_PRINTER_COPIES_STR},
	{MSG_PRINTER_COLLATE, (STRPTR)MSG_PRINTER_COLLATE_STR},
	{MSG_PRINTER_SCALING, (STRPTR)MSG_PRINTER_SCALING_STR},
	{MSG_PRINTER_PAGESPERSHEET, (STRPTR)MSG_PRINTER_PAGESPERSHEET_STR},
	{MSG_PRINTER_ORDER, (STRPTR)MSG_PRINTER_ORDER_STR},
	{MSG_PRINTER_AUTOROTATE, (STRPTR)MSG_PRINTER_AUTOROTATE_STR},
	{MSG_PRINTER_DRIVER, (STRPTR)MSG_PRINTER_DRIVER_STR},
	{MSG_PRINTER_PREFERENCES, (STRPTR)MSG_PRINTER_PREFERENCES_STR},
	{MSG_PRINTER_WINTITLE, (STRPTR)MSG_PRINTER_WINTITLE_STR},
	{MSG_PRINTER_PRINT, (STRPTR)MSG_PRINTER_PRINT_STR},
	{MSG_PRINTER_CANCEL, (STRPTR)MSG_PRINTER_CANCEL_STR},
	{MSG_PRINTER_OUTPUT, (STRPTR)MSG_PRINTER_OUTPUT_STR},
	{MSG_PRINTER_ODD, (STRPTR)MSG_PRINTER_ODD_STR},
	{MSG_PRINTER_EVEN, (STRPTR)MSG_PRINTER_EVEN_STR},
	{MSG_PRINTER_ODDEVEN, (STRPTR)MSG_PRINTER_ODDEVEN_STR},
	{MSG_PRINTER_NONE, (STRPTR)MSG_PRINTER_NONE_STR},
	{MSG_PRINTER_BEST, (STRPTR)MSG_PRINTER_BEST_STR},
	{MSG_PRINTER_MULTIPLE, (STRPTR)MSG_PRINTER_MULTIPLE_STR},
	{MSG_PRINTER_CUSTOM, (STRPTR)MSG_PRINTER_CUSTOM_STR},
	{MSG_PRINTER_HORIZONTAL_VERTICAL, (STRPTR)MSG_PRINTER_HORIZONTAL_VERTICAL_STR},
	{MSG_PRINTER_HORIZONTAL_VERTICALREVERSED, (STRPTR)MSG_PRINTER_HORIZONTAL_VERTICALREVERSED_STR},
	{MSG_PRINTER_HORIZONTALREVERSED_VERTICAL, (STRPTR)MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_STR},
	{MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_REVERSED, (STRPTR)MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_REVERSED_STR},
	{MSG_PRINTER_VERTICAL_HORIZONTAL, (STRPTR)MSG_PRINTER_VERTICAL_HORIZONTAL_STR},
	{MSG_PRINTER_VERTICALREVERSED_HORIZONTAL, (STRPTR)MSG_PRINTER_VERTICALREVERSED_HORIZONTAL_STR},
	{MSG_PRINTER_VERTICAL_HORIZONTALREVERSED, (STRPTR)MSG_PRINTER_VERTICAL_HORIZONTALREVERSED_STR},
	{MSG_PRINTER_VERTICAL_REVERSED_HORIZONTALREVERSED, (STRPTR)MSG_PRINTER_VERTICAL_REVERSED_HORIZONTALREVERSED_STR},
	{MSG_PRINTER_ABORT, (STRPTR)MSG_PRINTER_ABORT_STR},
	{MSG_MENU_PROJECT, (STRPTR)MSG_MENU_PROJECT_STR},
	{MSG_MENU_NEWWIN, (STRPTR)MSG_MENU_NEWWIN_STR},
	{MSG_MENU_NEWTAB, (STRPTR)MSG_MENU_NEWTAB_STR},
	{MSG_MENU_FILE, (STRPTR)MSG_MENU_FILE_STR},
	{MSG_MENU_RECENT, (STRPTR)MSG_MENU_RECENT_STR},
	{MSG_MENU_PRINT, (STRPTR)MSG_MENU_PRINT_STR},
	{MSG_MENU_ABOUT, (STRPTR)MSG_MENU_ABOUT_STR},
	{MSG_MENU_QUIT, (STRPTR)MSG_MENU_QUIT_STR},
	{MSG_MENU_EDIT, (STRPTR)MSG_MENU_EDIT_STR},
	{MSG_MENU_COPY, (STRPTR)MSG_MENU_COPY_STR},
	{MSG_MENU_LOG, (STRPTR)MSG_MENU_LOG_STR},
	{MSG_MENU_SETTINGS, (STRPTR)MSG_MENU_SETTINGS_STR},
	{MSG_MENU_SETTINGS_SETTINGS, (STRPTR)MSG_MENU_SETTINGS_SETTINGS_STR},
	{MSG_MENU_SETTINGS_SAVE, (STRPTR)MSG_MENU_SETTINGS_SAVE_STR},
	{MSG_MENU_SETTINGS_MUI, (STRPTR)MSG_MENU_SETTINGS_MUI_STR},
	{MSG_MENU_WINDOWS, (STRPTR)MSG_MENU_WINDOWS_STR},
	{MSG_NOFILE, (STRPTR)MSG_NOFILE_STR},
	{MSG_SAVE, (STRPTR)MSG_SAVE_STR},
	{MSG_CANCEL, (STRPTR)MSG_CANCEL_STR},
	{MSG_USE, (STRPTR)MSG_USE_STR},
	{MSG_WINDOWS, (STRPTR)MSG_WINDOWS_STR},
	{MSG_SETTINGS_LAYOUT, (STRPTR)MSG_SETTINGS_LAYOUT_STR},
	{MSG_SETTINGS_SCALING, (STRPTR)MSG_SETTINGS_SCALING_STR},
	{MSG_SETTINGS_OUTLINE, (STRPTR)MSG_SETTINGS_OUTLINE_STR},
	{MSG_SETTINGS_DOCUMENT, (STRPTR)MSG_SETTINGS_DOCUMENT_STR},
	{MSG_SETTINGS_LOGWINDOW, (STRPTR)MSG_SETTINGS_LOGWINDOW_STR},
	{MSG_REQ_OPEN, (STRPTR)MSG_REQ_OPEN_STR},
	{MSG_REQ_SAVE, (STRPTR)MSG_REQ_SAVE_STR},
	{MSG_REQ_DRAWER, (STRPTR)MSG_REQ_DRAWER_STR},
	{MSG_TOOLBAR_ZOOMIN, (STRPTR)MSG_TOOLBAR_ZOOMIN_STR},
	{MSG_TOOLBAR_ZOOMOUT, (STRPTR)MSG_TOOLBAR_ZOOMOUT_STR},
	{MSG_TOOLBAR_COUNTERCLOCKWISE, (STRPTR)MSG_TOOLBAR_COUNTERCLOCKWISE_STR},
	{MSG_TOOLBAR_CLOCKWISE, (STRPTR)MSG_TOOLBAR_CLOCKWISE_STR},
	{MSG_TOOLBAR_MARK, (STRPTR)MSG_TOOLBAR_MARK_STR},
	{MSG_TOOLBAR_SCROLL, (STRPTR)MSG_TOOLBAR_SCROLL_STR},
	{MSG_TOOLBAR_OUTLINE, (STRPTR)MSG_TOOLBAR_OUTLINE_STR},
	{MSG_TOOLBAR_FITPAGE, (STRPTR)MSG_TOOLBAR_FITPAGE_STR},
	{MSG_TOOLBAR_FITWIDTH, (STRPTR)MSG_TOOLBAR_FITWIDTH_STR},
	{MSG_TOOLBAR_SINGLE, (STRPTR)MSG_TOOLBAR_SINGLE_STR},
	{MSG_TOOLBAR_CONTINUOUS, (STRPTR)MSG_TOOLBAR_CONTINUOUS_STR},
	{MSG_TOOLBAR_FACING, (STRPTR)MSG_TOOLBAR_FACING_STR},
	{MSG_TOOLBAR_CONT_FACING, (STRPTR)MSG_TOOLBAR_CONT_FACING_STR},
	{MSG_SEARCH_NEXT, (STRPTR)MSG_SEARCH_NEXT_STR},
	{MSG_SEARCH_PREV, (STRPTR)MSG_SEARCH_PREV_STR},
	{MSG_SEARCH_END, (STRPTR)MSG_SEARCH_END_STR},
	{MSG_SEARCH_LABEL, (STRPTR)MSG_SEARCH_LABEL_STR},
	{MSG_SLIDER_PAGE, (STRPTR)MSG_SLIDER_PAGE_STR},
};

#endif /* CATCOMP_ARRAY */


#ifdef NEW_CATCOMP_ARRAY_IDS

/*  The following IDs can be used to access CATCOMP_ARRAY entries comfortably by a named define.
 *  This are not catalog IDs!
 *
 *  Do not use this feature if you want to keep code compatibility with original
 *  CBM CatComp code output.
 */
enum
{
	MSG_APPLICATION_DESCRIPTION_ID,
	MSG_PRINTER_RANGE_ID,
	MSG_PRINTER_PAGES_ID,
	MSG_PRINTER_FIRSTPAGE_ID,
	MSG_PRINTER_LASTPAGE_ID,
	MSG_PRINTER_MANUAL_ID,
	MSG_PRINTER_RESET_ID,
	MSG_PRINTER_REVERSE_ID,
	MSG_PRINTER_ORIENTATION_ID,
	MSG_PRINTER_COPIES_ID,
	MSG_PRINTER_COLLATE_ID,
	MSG_PRINTER_SCALING_ID,
	MSG_PRINTER_PAGESPERSHEET_ID,
	MSG_PRINTER_ORDER_ID,
	MSG_PRINTER_AUTOROTATE_ID,
	MSG_PRINTER_DRIVER_ID,
	MSG_PRINTER_PREFERENCES_ID,
	MSG_PRINTER_WINTITLE_ID,
	MSG_PRINTER_PRINT_ID,
	MSG_PRINTER_CANCEL_ID,
	MSG_PRINTER_OUTPUT_ID,
	MSG_PRINTER_ODD_ID,
	MSG_PRINTER_EVEN_ID,
	MSG_PRINTER_ODDEVEN_ID,
	MSG_PRINTER_NONE_ID,
	MSG_PRINTER_BEST_ID,
	MSG_PRINTER_MULTIPLE_ID,
	MSG_PRINTER_CUSTOM_ID,
	MSG_PRINTER_HORIZONTAL_VERTICAL_ID,
	MSG_PRINTER_HORIZONTAL_VERTICALREVERSED_ID,
	MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_ID,
	MSG_PRINTER_HORIZONTALREVERSED_VERTICAL_REVERSED_ID,
	MSG_PRINTER_VERTICAL_HORIZONTAL_ID,
	MSG_PRINTER_VERTICALREVERSED_HORIZONTAL_ID,
	MSG_PRINTER_VERTICAL_HORIZONTALREVERSED_ID,
	MSG_PRINTER_VERTICAL_REVERSED_HORIZONTALREVERSED_ID,
	MSG_PRINTER_ABORT_ID,
	MSG_MENU_PROJECT_ID,
	MSG_MENU_NEWWIN_ID,
	MSG_MENU_NEWTAB_ID,
	MSG_MENU_FILE_ID,
	MSG_MENU_RECENT_ID,
	MSG_MENU_PRINT_ID,
	MSG_MENU_ABOUT_ID,
	MSG_MENU_QUIT_ID,
	MSG_MENU_EDIT_ID,
	MSG_MENU_COPY_ID,
	MSG_MENU_LOG_ID,
	MSG_MENU_SETTINGS_ID,
	MSG_MENU_SETTINGS_SETTINGS_ID,
	MSG_MENU_SETTINGS_SAVE_ID,
	MSG_MENU_SETTINGS_MUI_ID,
	MSG_MENU_WINDOWS_ID,
	MSG_NOFILE_ID,
	MSG_SAVE_ID,
	MSG_CANCEL_ID,
	MSG_USE_ID,
	MSG_WINDOWS_ID,
	MSG_SETTINGS_LAYOUT_ID,
	MSG_SETTINGS_SCALING_ID,
	MSG_SETTINGS_OUTLINE_ID,
	MSG_SETTINGS_DOCUMENT_ID,
	MSG_SETTINGS_LOGWINDOW_ID,
	MSG_REQ_OPEN_ID,
	MSG_REQ_SAVE_ID,
	MSG_REQ_DRAWER_ID,
	MSG_TOOLBAR_ZOOMIN_ID,
	MSG_TOOLBAR_ZOOMOUT_ID,
	MSG_TOOLBAR_COUNTERCLOCKWISE_ID,
	MSG_TOOLBAR_CLOCKWISE_ID,
	MSG_TOOLBAR_MARK_ID,
	MSG_TOOLBAR_SCROLL_ID,
	MSG_TOOLBAR_OUTLINE_ID,
	MSG_TOOLBAR_FITPAGE_ID,
	MSG_TOOLBAR_FITWIDTH_ID,
	MSG_TOOLBAR_SINGLE_ID,
	MSG_TOOLBAR_CONTINUOUS_ID,
	MSG_TOOLBAR_FACING_ID,
	MSG_TOOLBAR_CONT_FACING_ID,
	MSG_SEARCH_NEXT_ID,
	MSG_SEARCH_PREV_ID,
	MSG_SEARCH_END_ID,
	MSG_SEARCH_LABEL_ID,
	MSG_SLIDER_PAGE_ID,
	NEW_CATCOMP_ARRAY_ID_COUNT
};
#endif /* NEW_CATCOMP_ARRAY_IDS */


#endif /* VPDF_STRINGS_H */
