#ifndef VPDF_STRINGS_H
#define VPDF_STRINGS_H


/*   This file was created automatically by catcomp.pl
 *   DO NOT EDIT BY HAND!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_NUMBERS

#define MSG_APPLICATION_DESCRIPTION 0
#define MSG_PRINTER_RANGE 1
#define MSG_PRINTER_PAGES 2
#define MSG_PRINTER_FIRSTPAGE 3
#define MSG_PRINTER_LASTPAGE 4
#define MSG_PRINTER_MANUAL 5
#define MSG_PRINTER_RESET 6
#define MSG_PRINTER_REVERSE 7
#define MSG_PRINTER_ORIENTATION 8
#define MSG_PRINTER_COPIES 9
#define MSG_PRINTER_COLLATE 10
#define MSG_PRINTER_SCALING 11
#define MSG_PRINTER_PAGESPERSHEET 12
#define MSG_PRINTER_ORDER 13
#define MSG_PRINTER_AUTOROTATE 14
#define MSG_PRINTER_DRIVER 15
#define MSG_PRINTER_PREFERENCES 16
#define MSG_PRINTER_WINTITLE 17
#define MSG_PRINTER_PRINT 18
#define MSG_PRINTER_CANCEL 19
#define MSG_PRINTER_OUTPUT 20
#define MSG_PRINTER_ODD 21
#define MSG_PRINTER_EVEN 22
#define MSG_PRINTER_ODDEVEN 23
#define MSG_PRINTER_NONE 24
#define MSG_PRINTER_BEST 25
#define MSG_PRINTER_MULTIPLE 26
#define MSG_PRINTER_CUSTOM 27
#define MSG_PRINTER_HORIZONTAL 28
#define MSG_PRINTER_VERTICAL 29
#define MSG_PRINTER_HORIZONTALREVERT 30
#define MSG_PRINTER_VERTICALREVERT 31

#endif /* CATCOMP_NUMBERS */


#ifdef CATCOMP_STRINGS

#define MSG_APPLICATION_DESCRIPTION_STR "PDF Viewer"
#define MSG_PRINTER_RANGE_STR "Print Range"
#define MSG_PRINTER_PAGES_STR "Pages:"
#define MSG_PRINTER_FIRSTPAGE_STR "First Page:"
#define MSG_PRINTER_LASTPAGE_STR "Last Page:"
#define MSG_PRINTER_MANUAL_STR "Manual Selection"
#define MSG_PRINTER_RESET_STR "Reset"
#define MSG_PRINTER_REVERSE_STR "Reverse Pages"
#define MSG_PRINTER_ORIENTATION_STR "Page Orientation"
#define MSG_PRINTER_COPIES_STR "Copies:"
#define MSG_PRINTER_COLLATE_STR "Collate"
#define MSG_PRINTER_SCALING_STR "Page Scaling:"
#define MSG_PRINTER_PAGESPERSHEET_STR "Pages per Sheet:"
#define MSG_PRINTER_ORDER_STR "Pages Order:"
#define MSG_PRINTER_AUTOROTATE_STR "Auto Rotate and Center"
#define MSG_PRINTER_DRIVER_STR "Driver"
#define MSG_PRINTER_PREFERENCES_STR "Printer Preferences"
#define MSG_PRINTER_WINTITLE_STR "VPDF · Print Document"
#define MSG_PRINTER_PRINT_STR "Print"
#define MSG_PRINTER_CANCEL_STR "Cancel"
#define MSG_PRINTER_OUTPUT_STR "Output:"
#define MSG_PRINTER_ODD_STR "Odd"
#define MSG_PRINTER_EVEN_STR "Even"
#define MSG_PRINTER_ODDEVEN_STR "Odd and Even"
#define MSG_PRINTER_NONE_STR "None"
#define MSG_PRINTER_BEST_STR "Best"
#define MSG_PRINTER_MULTIPLE_STR "Multiple pages per sheet"
#define MSG_PRINTER_CUSTOM_STR "Custom"
#define MSG_PRINTER_HORIZONTAL_STR "Horizontal"
#define MSG_PRINTER_VERTICAL_STR "Vertical"
#define MSG_PRINTER_HORIZONTALREVERT_STR "Horizontal reversed"
#define MSG_PRINTER_VERTICALREVERT_STR "Vertical reversed"

#endif /* CATCOMP_STRINGS */


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
	LONG   cca_ID;
	STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
	{MSG_APPLICATION_DESCRIPTION, (STRPTR)MSG_APPLICATION_DESCRIPTION_STR},
	{MSG_PRINTER_RANGE, (STRPTR)MSG_PRINTER_RANGE_STR},
	{MSG_PRINTER_PAGES, (STRPTR)MSG_PRINTER_PAGES_STR},
	{MSG_PRINTER_FIRSTPAGE, (STRPTR)MSG_PRINTER_FIRSTPAGE_STR},
	{MSG_PRINTER_LASTPAGE, (STRPTR)MSG_PRINTER_LASTPAGE_STR},
	{MSG_PRINTER_MANUAL, (STRPTR)MSG_PRINTER_MANUAL_STR},
	{MSG_PRINTER_RESET, (STRPTR)MSG_PRINTER_RESET_STR},
	{MSG_PRINTER_REVERSE, (STRPTR)MSG_PRINTER_REVERSE_STR},
	{MSG_PRINTER_ORIENTATION, (STRPTR)MSG_PRINTER_ORIENTATION_STR},
	{MSG_PRINTER_COPIES, (STRPTR)MSG_PRINTER_COPIES_STR},
	{MSG_PRINTER_COLLATE, (STRPTR)MSG_PRINTER_COLLATE_STR},
	{MSG_PRINTER_SCALING, (STRPTR)MSG_PRINTER_SCALING_STR},
	{MSG_PRINTER_PAGESPERSHEET, (STRPTR)MSG_PRINTER_PAGESPERSHEET_STR},
	{MSG_PRINTER_ORDER, (STRPTR)MSG_PRINTER_ORDER_STR},
	{MSG_PRINTER_AUTOROTATE, (STRPTR)MSG_PRINTER_AUTOROTATE_STR},
	{MSG_PRINTER_DRIVER, (STRPTR)MSG_PRINTER_DRIVER_STR},
	{MSG_PRINTER_PREFERENCES, (STRPTR)MSG_PRINTER_PREFERENCES_STR},
	{MSG_PRINTER_WINTITLE, (STRPTR)MSG_PRINTER_WINTITLE_STR},
	{MSG_PRINTER_PRINT, (STRPTR)MSG_PRINTER_PRINT_STR},
	{MSG_PRINTER_CANCEL, (STRPTR)MSG_PRINTER_CANCEL_STR},
	{MSG_PRINTER_OUTPUT, (STRPTR)MSG_PRINTER_OUTPUT_STR},
	{MSG_PRINTER_ODD, (STRPTR)MSG_PRINTER_ODD_STR},
	{MSG_PRINTER_EVEN, (STRPTR)MSG_PRINTER_EVEN_STR},
	{MSG_PRINTER_ODDEVEN, (STRPTR)MSG_PRINTER_ODDEVEN_STR},
	{MSG_PRINTER_NONE, (STRPTR)MSG_PRINTER_NONE_STR},
	{MSG_PRINTER_BEST, (STRPTR)MSG_PRINTER_BEST_STR},
	{MSG_PRINTER_MULTIPLE, (STRPTR)MSG_PRINTER_MULTIPLE_STR},
	{MSG_PRINTER_CUSTOM, (STRPTR)MSG_PRINTER_CUSTOM_STR},
	{MSG_PRINTER_HORIZONTAL, (STRPTR)MSG_PRINTER_HORIZONTAL_STR},
	{MSG_PRINTER_VERTICAL, (STRPTR)MSG_PRINTER_VERTICAL_STR},
	{MSG_PRINTER_HORIZONTALREVERT, (STRPTR)MSG_PRINTER_HORIZONTALREVERT_STR},
	{MSG_PRINTER_VERTICALREVERT, (STRPTR)MSG_PRINTER_VERTICALREVERT_STR},
};

#endif /* CATCOMP_ARRAY */


#ifdef NEW_CATCOMP_ARRAY_IDS

/*  The following IDs can be used to access CATCOMP_ARRAY entries comfortably by a named define.
 *  This are not catalog IDs!
 *
 *  Do not use this feature if you want to keep code compatibility with original
 *  CBM CatComp code output.
 */
enum
{
	MSG_APPLICATION_DESCRIPTION_ID,
	MSG_PRINTER_RANGE_ID,
	MSG_PRINTER_PAGES_ID,
	MSG_PRINTER_FIRSTPAGE_ID,
	MSG_PRINTER_LASTPAGE_ID,
	MSG_PRINTER_MANUAL_ID,
	MSG_PRINTER_RESET_ID,
	MSG_PRINTER_REVERSE_ID,
	MSG_PRINTER_ORIENTATION_ID,
	MSG_PRINTER_COPIES_ID,
	MSG_PRINTER_COLLATE_ID,
	MSG_PRINTER_SCALING_ID,
	MSG_PRINTER_PAGESPERSHEET_ID,
	MSG_PRINTER_ORDER_ID,
	MSG_PRINTER_AUTOROTATE_ID,
	MSG_PRINTER_DRIVER_ID,
	MSG_PRINTER_PREFERENCES_ID,
	MSG_PRINTER_WINTITLE_ID,
	MSG_PRINTER_PRINT_ID,
	MSG_PRINTER_CANCEL_ID,
	MSG_PRINTER_OUTPUT_ID,
	MSG_PRINTER_ODD_ID,
	MSG_PRINTER_EVEN_ID,
	MSG_PRINTER_ODDEVEN_ID,
	MSG_PRINTER_NONE_ID,
	MSG_PRINTER_BEST_ID,
	MSG_PRINTER_MULTIPLE_ID,
	MSG_PRINTER_CUSTOM_ID,
	MSG_PRINTER_HORIZONTAL_ID,
	MSG_PRINTER_VERTICAL_ID,
	MSG_PRINTER_HORIZONTALREVERT_ID,
	MSG_PRINTER_VERTICALREVERT_ID,
	NEW_CATCOMP_ARRAY_ID_COUNT
};

/* Some SimpleCat compatibility.
 * Don't use this define if you don't have to.
 */
#define CATCOMP_LASTID NEW_CATCOMP_ARRAY_ID_COUNT

#endif /* NEW_CATCOMP_ARRAY_IDS */


#endif /* VPDF_STRINGS_H */
