/*
 *  Source machine generated by GadToolsBox V1.4
 *  which is (c) Copyright 1991,92 Jaba Development
 */

#include "find.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = NULL;
APTR                   VisualInfo = NULL;
struct Window         *Project0Wnd = NULL;
struct Gadget         *Project0GList = NULL;
struct Menu           *Project0Menus = NULL;
struct IntuiMessage    Project0Msg;
struct Gadget         *Project0Gadgets[21];
UWORD                  Project0Left = 0;
UWORD                  Project0Top = 22;
UWORD                  Project0Width = 607;
UWORD                  Project0Height = 164;
UBYTE                 *Project0Wdt = (UBYTE *)"Find V1.0";
struct TextAttr       *Font, Attr;
UWORD                  FontX, FontY;
UWORD                  OffX, OffY;

UBYTE *output0Labels[] = {
	(UBYTE *)"None",
	(UBYTE *)"File",
	(UBYTE *)"Printer",
	NULL };

struct NewMenu Project0NewMenu[] = {
	NM_TITLE, (STRPTR)"Project", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Load...", (STRPTR)"L", 0, 0L, (APTR)Project0loadconfig,
	NM_ITEM, (STRPTR)"Save...", (STRPTR)"S", 0, 0L, (APTR)Project0saveconfig,
	NM_ITEM, (STRPTR)"Save as...", (STRPTR)"V", 0, 0L, (APTR)Project0saveasconfig,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Save as Default", (STRPTR)"D", 0, 0L, (APTR)Project0savedefault,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"About", (STRPTR)"A", 0, 0L, (APTR)Project0about,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
 NM_ITEM, (STRPTR)"Hide Window", (STRPTR)"H", 0, 0L, (APTR)Project0CloseWindow,
	NM_ITEM, (STRPTR)"Quit Program", (STRPTR)"Q", 0, 0L, (APTR)Project0quit,
	NM_TITLE, (STRPTR)"Settings", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Reset to default", (STRPTR)"Z", 0L, 0L, (APTR)Project0reset,
	NM_ITEM, (STRPTR)"Reset to last saved", (STRPTR)"A", 0L, 0L, (APTR)Project0resetdef,
 NM_TITLE, (STRPTR)"Options", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Write Icons", (STRPTR)"I", CHECKIT|CHECKED|MENUTOGGLE, 0L, (APTR)Project0writeicons,
	NM_END, NULL, NULL, 0, 0L, NULL };

UWORD Project0GTypes[] = {
	LISTVIEW_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	CYCLE_KIND,
	STRING_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	BUTTON_KIND,
	INTEGER_KIND,
	BUTTON_KIND,
	STRING_KIND,
	BUTTON_KIND,
	STRING_KIND,
	TEXT_KIND,
 INTEGER_KIND,
 INTEGER_KIND
};

struct NewGadget Project0NGad[] = {
	312, 15, 279, 92, (UBYTE *)"Matches found", NULL, GD_Gadget00, PLACETEXT_ABOVE, NULL, (APTR)Gadget00Clicked,
	108, 44, 186, 13, (UBYTE *)"S_earch", NULL, GD_pattern, PLACETEXT_LEFT, NULL, (APTR)patternClicked,
	256, 59, 38, 14, (UBYTE *)"_Insert", NULL, GD_insert, PLACETEXT_LEFT, NULL, (APTR)insertClicked,
	256, 93, 38, 14, (UBYTE *)"S_ubstitute", NULL, GD_sub, PLACETEXT_LEFT, NULL, (APTR)subClicked,
	256, 76, 38, 14, (UBYTE *)"De_lete", NULL, GD_del, PLACETEXT_LEFT, NULL, (APTR)delClicked,
	7, 59, 38, 14, (UBYTE *)"Dist_ance filter", NULL, GD_filter, PLACETEXT_RIGHT, NULL, (APTR)filterClicked,
	310, 112, 109, 14, (UBYTE *)"Out_put", NULL, GD_output, PLACETEXT_RIGHT, NULL, (APTR)outputClicked,
	482, 112, 109, 14, NULL, NULL, GD_outfilename, 0, NULL, (APTR)outfilenameClicked,
	310, 132, 26, 11, (UBYTE *)"_Wordnumber", NULL, GD_flag_wnum, PLACETEXT_RIGHT, NULL, (APTR)flag_wnumClicked,
	310, 147, 26, 11, (UBYTE *)"Linenu_mber", NULL, GD_flag_linenumber, PLACETEXT_RIGHT, NULL, (APTR)flag_linenumberClicked,
	484, 132, 26, 11, (UBYTE *)"Distan_ce", NULL, GD_flag_distance, PLACETEXT_RIGHT, NULL, (APTR)flag_distClicked,
	484, 147, 26, 11, (UBYTE *)"Wo_rd", NULL, GD_flag_word, PLACETEXT_RIGHT, NULL, (APTR)flag_wordClicked,
	7, 126, 109, 14, (UBYTE *)"_Start", NULL, GD_start, PLACETEXT_IN, NULL, (APTR)startClicked,
	7, 76, 38, 14, (UBYTE *)"Si_ze", NULL, GD_size, PLACETEXT_RIGHT, NULL, (APTR)sizeClicked,
	185, 126, 109, 14, (UBYTE *)"Stop _Q", NULL, GD_stop, PLACETEXT_IN, NULL, (APTR)stopClicked,
	108, 9, 186, 13, (UBYTE *)"_File", NULL, GD_filestring, PLACETEXT_LEFT, NULL, (APTR)filestringClicked,
	7, 9, 26, 11, (UBYTE *)"_?", NULL, GD_requestfile, PLACETEXT_IN, NULL, (APTR)requestfileClicked,
	108, 26, 186, 13, (UBYTE *)"_Delimiter", NULL, GD_delim, PLACETEXT_LEFT, NULL, (APTR)delimClicked,
	8, 143, 286, 15, NULL, NULL, GD_errors, 0, NULL, NULL,
 7,107,70,14,(UBYTE *)"_Fr_om <-Line",NULL,GD_fromline,PLACETEXT_RIGHT,NULL,(APTR)fromlineClicked,
 224,107,70,14,(UBYTE *)"->_To ",NULL,GD_toline,PLACETEXT_LEFT,NULL,(APTR)tolineClicked, 
};

ULONG Project0GTags[] = {
	(GTLV_ReadOnly), TRUE, (TAG_DONE),
	(GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTIN_Number), 1, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTIN_Number), 2, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTIN_Number), 3, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTIN_Number), 5, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTCY_Labels), (ULONG)&output0Labels[ 0 ], (GT_Underscore), '_', (TAG_DONE),
	(GTST_MaxChars), 256, (GA_Disabled), TRUE, (TAG_DONE),
	(GTCB_Checked), TRUE, (GT_Underscore), '_', (TAG_DONE),
	(GTCB_Checked), TRUE, (GT_Underscore), '_', (TAG_DONE),
	(GT_Underscore), '_', (TAG_DONE),
	(GTCB_Checked), TRUE, (GT_Underscore), '_', (TAG_DONE),
	(GT_Underscore), '_', (TAG_DONE),
	(GTIN_Number), 40, (GTIN_MaxChars), 5, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GT_Underscore), '_', (GA_Disabled), TRUE, (TAG_DONE),
	(GT_Underscore), '_',(GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (TAG_DONE),
	(GT_Underscore), '_', (TAG_DONE),
	(GTST_MaxChars), 256, (STRINGA_Justification), (GACT_STRINGCENTER), (GT_Underscore), '_', (TAG_DONE),
	(GTTX_Text), (ULONG)"Find V1.0 © 1993 CEKASOFT", (GTTX_Border), TRUE, (GTTX_CopyText), TRUE, (TAG_DONE),
 (GT_Underscore),'_',GTIN_Number,1,GTIN_MaxChars,6,(STRINGA_Justification),(GACT_STRINGCENTER),TAG_DONE,
 (GT_Underscore),'_',GTIN_Number,2,GTIN_MaxChars,6,STRINGA_Justification,GACT_STRINGCENTER,TAG_DONE,
};

static UWORD ComputeX( UWORD value )
{
	return(( UWORD )((( FontX * value ) + 4 ) / 8 ));
}

static UWORD ComputeY( UWORD value )
{
	return(( UWORD )((( FontY * value ) + 4 ) / 8 ));
}

static void ComputeFont( UWORD width, UWORD height )
{
	Font = &Attr;
	Font->ta_Name = (STRPTR)GfxBase->DefaultFont->tf_Message.mn_Node.ln_Name;
	Font->ta_YSize = FontY = GfxBase->DefaultFont->tf_YSize;
	FontX = GfxBase->DefaultFont->tf_XSize;

	OffX = Scr->WBorLeft;
	OffY = Scr->RastPort.TxHeight + Scr->WBorTop + 1;

	if ( width && height ) {
		if (( ComputeX( width ) + OffX + Scr->WBorRight ) > Scr->Width )
			goto UseTopaz;
		if (( ComputeY( height ) + OffY + Scr->WBorBottom ) > Scr->Height )
			goto UseTopaz;
	}
	return;

UseTopaz:
	Font->ta_Name = (STRPTR)"topaz.font";
	FontX = FontY = Font->ta_YSize = 8;
}

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	ComputeFont( 0, 0 );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

void Project0Render( void )
{
 if(!Project0Menus)
 {
  if(Project0Menus = CreateMenus( Project0NewMenu, GTMN_FrontPen, 0L, TAG_DONE ))
   {
  	LayoutMenus( Project0Menus, VisualInfo, TAG_DONE );
   SetMenuStrip(Project0Wnd,Project0Menus);
  }
 }
 info.App.awd = AddAppWindow(0,0,Project0Wnd,info.App.port,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_Gadget00],Project0Wnd,NULL,GA_Disabled,info.misc.disable,GTLV_Labels,&info.match.list,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_insert],Project0Wnd,NULL,GTIN_Number,info.weight.ins,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_sub],Project0Wnd,NULL,GTIN_Number,info.weight.sub,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_del],Project0Wnd,NULL,GTIN_Number,info.weight.del,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_outfilename],Project0Wnd,NULL,GTST_String,info.strings.outfile,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_output],Project0Wnd,NULL,GTCY_Active,(ULONG)info.misc.out,GA_Disabled,info.misc.disable,TAG_DONE);
 switch(info.misc.out)
 {
  case 0 : GT_SetGadgetAttrs(Project0Gadgets[GDX_outfilename],Project0Wnd,NULL,GA_Disabled,TRUE,TAG_DONE);
           break;   
  case 1 : GT_SetGadgetAttrs(Project0Gadgets[GDX_outfilename],Project0Wnd,NULL,GA_Disabled,FALSE,TAG_DONE);
           break;
  case 2 : GT_SetGadgetAttrs(Project0Gadgets[GDX_outfilename],Project0Wnd,NULL,GA_Disabled,TRUE,TAG_DONE);
           break;
 };
 GT_SetGadgetAttrs(Project0Gadgets[GDX_filter],Project0Wnd,NULL,GTIN_Number,info.match.filter,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_filestring],Project0Wnd,NULL,GTST_String,info.strings.filename,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_pattern],Project0Wnd,NULL,GTST_String,info.strings.search,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_delim],Project0Wnd,NULL,GTST_String,info.strings.delim,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_size],Project0Wnd,NULL,GTIN_Number,info.data.size,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_flag_wnum],Project0Wnd,NULL,GTCB_Checked,(ULONG)info.flags.wnum,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_flag_linenumber],Project0Wnd,NULL,GTCB_Checked,(ULONG)info.flags.linenum,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_flag_distance],Project0Wnd,NULL,GTCB_Checked,(ULONG)info.flags.dist,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_flag_word],Project0Wnd,NULL,GTCB_Checked,(ULONG)info.flags.word,GA_Disabled,info.misc.disable,TAG_DONE);
 GT_SetGadgetAttrs(Project0Gadgets[GDX_requestfile],Project0Wnd,NULL,GA_Disabled,info.misc.disable,TAG_DONE); 
 GT_SetGadgetAttrs(Project0Gadgets[GDX_stop],Project0Wnd,NULL,GA_Disabled,!info.misc.disable,TAG_DONE); 
 GT_SetGadgetAttrs(Project0Gadgets[GDX_start],Project0Wnd,NULL,GA_Disabled,info.misc.disable,TAG_DONE);  
 GT_SetGadgetAttrs(Project0Gadgets[GDX_fromline],Project0Wnd,NULL,GTIN_Number,info.misc.fromline,GA_Disabled,info.misc.disable,TAG_DONE); 
 GT_SetGadgetAttrs(Project0Gadgets[GDX_toline],Project0Wnd,NULL,GTIN_Number,info.misc.toline,GA_Disabled,info.misc.disable,TAG_DONE);  
 putmsg(info.misc.lasterror);
 if(info.misc.disable) GT_SetGadgetAttrs(Project0Gadgets[GDX_outfilename],Project0Wnd,NULL,GA_Disabled,TRUE,TAG_DONE);
 sprintf(info.title,"Find V1.0 Hotkey <%s>",info.broker.hotkey);
 SetWindowTitles(Project0Wnd,info.title,NULL);
}

int HandleProject0IDCMP( void )
{
	struct IntuiMessage	*m;
	struct MenuItem		*n;
	int			(*func)(void);
	int			running = TRUE;

	while( m = GT_GetIMsg( Project0Wnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&Project0Msg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( Project0Msg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( Project0Wnd );
				Project0Render();
				GT_EndRefresh( Project0Wnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = Project0CloseWindow();
				break;

			case	IDCMP_VANILLAKEY:
				running = Project0VanillaKey();
				break;

			case	IDCMP_GADGETUP:
			case	IDCMP_GADGETDOWN:
				func = ( void * )(( struct Gadget * )Project0Msg.IAddress )->UserData;
				running = func();
				break;

			case	IDCMP_MENUPICK:
				while( Project0Msg.Code != MENUNULL ) {
					n = ItemAddress( Project0Menus, Project0Msg.Code );
					func = (void *)(GTMENUITEM_USERDATA( n ));
					running = func();
					Project0Msg.Code = n->NextSelect;
				}
				break;
		}
	}
	return( running );
}

int OpenProject0Window( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = Project0Left, wtop = Project0Top, ww, wh;

	ComputeFont( Project0Width, Project0Height );

	ww = ComputeX( Project0Width );
	wh = ComputeY( Project0Height );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &Project0GList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Project0_CNT; lc++ ) {

		CopyMem((char * )&Project0NGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		Project0Gadgets[ lc ] = g = CreateGadgetA((ULONG)Project0GTypes[ lc ], g, &ng, ( struct TagItem * )&Project0GTags[ tc ] );

		while( Project0GTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( Project0Wnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	LISTVIEWIDCMP|STRINGIDCMP|INTEGERIDCMP|CYCLEIDCMP|CHECKBOXIDCMP|BUTTONIDCMP|TEXTIDCMP|IDCMP_MENUPICK|IDCMP_CLOSEWINDOW|IDCMP_VANILLAKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_ACTIVATE|WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH,
				WA_Gadgets,	Project0GList,
				WA_Title,	Project0Wdt,
				WA_ScreenTitle,	"Find V1.0 ©1993 CEKASOFT All Rights Reserved",
				WA_PubScreen,	Scr,
				WA_AutoAdjust,	TRUE,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( Project0Wnd, NULL );

	ComputeFont( Project0Width, Project0Height );

	DrawBevelBox( Project0Wnd->RPort, OffX + ComputeX( 3 ),
					OffY + ComputeY( 121 ),
					ComputeX( 295 ),
					ComputeY( 41 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( Project0Wnd->RPort, OffX + ComputeX( 3 ),
					OffY + ComputeY( 2 ),
					ComputeX( 296 ),
					ComputeY( 119 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( Project0Wnd->RPort, OffX + ComputeX( 301 ),
					OffY + ComputeY( 1 ),
					ComputeX( 298 ),
					ComputeY( 161 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );

	Project0Render();
 SetSignals();
	return( 0L );
}

void CloseProject0Window( void )
{
	if ( Project0Menus      ) {
		ClearMenuStrip( Project0Wnd );
		FreeMenus( Project0Menus );
		Project0Menus = NULL;	}

	if ( Project0Wnd        ) {
  if(info.App.awd)
  {
   RemoveAppWindow(info.App.awd);
   info.App.awd = NULL;
  }
		CloseWindow( Project0Wnd );
		Project0Wnd = NULL;
	}

	if ( Project0GList      ) {
		FreeGadgets( Project0GList );
		Project0GList = NULL;
	}
 SetSignals();
}
