#ifndef CYBERGRAPHICS_INTERFACE_DEF_H
#define CYBERGRAPHICS_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

struct CyberGfxIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct CyberGfxIFace *Self);
	uint32 APICALL (*Release)(struct CyberGfxIFace *Self);
	void APICALL (*Expunge)(struct CyberGfxIFace *Self);
	struct Interface * APICALL (*Clone)(struct CyberGfxIFace *Self);
	void APICALL (*Reserved1)(struct CyberGfxIFace *Self);
	void APICALL (*Reserved2)(struct CyberGfxIFace *Self);
	void APICALL (*Reserved3)(struct CyberGfxIFace *Self);
	void APICALL (*Reserved4)(struct CyberGfxIFace *Self);
	BOOL APICALL (*IsCyberModeID)(struct CyberGfxIFace *Self, ULONG displayID);
	ULONG APICALL (*BestCModeIDTagList)(struct CyberGfxIFace *Self, struct TagItem * bestModeIDTags);
	ULONG APICALL (*BestCModeIDTags)(struct CyberGfxIFace *Self, ...);
	ULONG APICALL (*CModeRequestTagList)(struct CyberGfxIFace *Self, APTR modeRequest, struct TagItem * modeRequestTags);
	ULONG APICALL (*CModeRequestTags)(struct CyberGfxIFace *Self, APTR modeRequest, ...);
	struct List * APICALL (*AllocCModeListTagList)(struct CyberGfxIFace *Self, struct TagItem * modeListTags);
	struct List * APICALL (*AllocCModeListTags)(struct CyberGfxIFace *Self, ...);
	VOID APICALL (*FreeCModeList)(struct CyberGfxIFace *Self, struct List * modeList);
	void APICALL (*Reserved5)(struct CyberGfxIFace *Self);
	LONG APICALL (*ScalePixelArray)(struct CyberGfxIFace *Self, APTR srcRect, UWORD srcW, UWORD srcH, UWORD srcMod, struct RastPort * rp, UWORD destX, UWORD destY, UWORD destW, UWORD destH, UBYTE srcFormat);
	ULONG APICALL (*GetCyberMapAttr)(struct CyberGfxIFace *Self, struct BitMap * cyberGfxBitmap, ULONG cyberAttrTag);
	ULONG APICALL (*GetCyberIDAttr)(struct CyberGfxIFace *Self, ULONG cyberIDAttr, ULONG cyberDisplayModeID);
	ULONG APICALL (*ReadRGBPixel)(struct CyberGfxIFace *Self, struct RastPort * rp, UWORD x, UWORD y);
	LONG APICALL (*WriteRGBPixel)(struct CyberGfxIFace *Self, struct RastPort * rp, UWORD x, UWORD y, ULONG argb);
	ULONG APICALL (*ReadPixelArray)(struct CyberGfxIFace *Self, APTR destRect, UWORD destX, UWORD destY, UWORD destMod, struct RastPort * rp, UWORD srcX, UWORD srcY, UWORD sizeX, UWORD sizeY, UBYTE destFormat);
	ULONG APICALL (*WritePixelArray)(struct CyberGfxIFace *Self, APTR srcRect, UWORD srcX, UWORD srcY, UWORD srcMod, struct RastPort * rp, UWORD destX, UWORD destY, UWORD sizeX, UWORD sizeY, UBYTE srcFormat);
	ULONG APICALL (*MovePixelArray)(struct CyberGfxIFace *Self, UWORD srcX, UWORD srcY, struct RastPort * rp, UWORD destX, UWORD destY, UWORD sizeX, UWORD sizeY);
	void APICALL (*Reserved6)(struct CyberGfxIFace *Self);
	ULONG APICALL (*InvertPixelArray)(struct CyberGfxIFace *Self, struct RastPort * rp, UWORD destX, UWORD destY, UWORD sizeX, UWORD sizeY);
	ULONG APICALL (*FillPixelArray)(struct CyberGfxIFace *Self, struct RastPort * rp, UWORD destX, UWORD destY, UWORD sizeX, UWORD sizeY, ULONG aRGB);
	VOID APICALL (*DoCDrawMethodTagList)(struct CyberGfxIFace *Self, struct Hook * hook, struct RastPort * rp, struct TagItem * tagList);
	VOID APICALL (*DoCDrawMethodTags)(struct CyberGfxIFace *Self, struct Hook * hook, struct RastPort * rp, ...);
	VOID APICALL (*CVideoCtrlTagList)(struct CyberGfxIFace *Self, struct ViewPort * viewPort, struct TagItem * tagList);
	VOID APICALL (*CVideoCtrlTags)(struct CyberGfxIFace *Self, struct ViewPort * viewPort, ...);
	APTR APICALL (*LockBitMapTagList)(struct CyberGfxIFace *Self, APTR bitMap, struct TagItem * tagList);
	APTR APICALL (*LockBitMapTags)(struct CyberGfxIFace *Self, APTR bitMap, ...);
	VOID APICALL (*UnLockBitMap)(struct CyberGfxIFace *Self, APTR handle);
	VOID APICALL (*UnLockBitMapTagList)(struct CyberGfxIFace *Self, APTR handle, struct TagItem * tagList);
	VOID APICALL (*UnLockBitMapTags)(struct CyberGfxIFace *Self, APTR handle, ...);
	ULONG APICALL (*ExtractColor)(struct CyberGfxIFace *Self, struct RastPort * rp, struct BitMap * bitMap, ULONG colour, ULONG srcX, ULONG srcY, ULONG width, ULONG height);
	void APICALL (*Reserved7)(struct CyberGfxIFace *Self);
	ULONG APICALL (*WriteLUTPixelArray)(struct CyberGfxIFace *Self, APTR srcRect, UWORD srcX, UWORD srcY, UWORD srcMod, struct RastPort * rp, APTR colorTab, UWORD destX, UWORD destY, UWORD sizeX, UWORD sizeY, UBYTE cTFormat);
	void APICALL (*Reserved8)(struct CyberGfxIFace *Self);
	void APICALL (*Reserved9)(struct CyberGfxIFace *Self);
	ULONG APICALL (*WritePixelArrayAlpha)(struct CyberGfxIFace *Self, APTR srcRect, UWORD srcX, UWORD srcY, UWORD srcMod, struct RastPort * rp, UWORD destX, UWORD destY, UWORD sizeX, UWORD sizeY, ULONG globalAlpha);
	VOID APICALL (*BltTemplateAlpha)(struct CyberGfxIFace *Self, UBYTE * source, LONG xSrc, LONG srcMod, struct RastPort * destRP, ULONG xDest, ULONG yDest, ULONG xSize, ULONG ySize);
	VOID APICALL (*ProcessPixelArray)(struct CyberGfxIFace *Self, struct RastPort * rp, ULONG destX, ULONG destY, ULONG sizeX, ULONG sizeY, ULONG operation, LONG value, struct TagItem * taglist);
	VOID APICALL (*ProcessPixelArrayTags)(struct CyberGfxIFace *Self, struct RastPort * rp, ULONG destX, ULONG destY, ULONG sizeX, ULONG sizeY, ULONG operation, LONG value, ...);
	ULONG APICALL (*BltBitMapAlpha)(struct CyberGfxIFace *Self, struct BitMap * srcBitMap, WORD srcX, WORD srcY, struct BitMap * destBitMap, WORD destX, WORD destY, WORD sizeX, WORD sizeY, struct TagItem * taglist);
	ULONG APICALL (*BltBitMapRastPortAlpha)(struct CyberGfxIFace *Self, struct BitMap * srcBitMap, WORD srcX, WORD srcY, struct RastPort * destRP, WORD destX, WORD destY, WORD sizeX, WORD sizeY, struct TagItem * taglist);
	void APICALL (*Reserved10)(struct CyberGfxIFace *Self);
	void APICALL (*Reserved11)(struct CyberGfxIFace *Self);
	LONG APICALL (*ScalePixelArrayAlpha)(struct CyberGfxIFace *Self, APTR srcRect, UWORD srcW, UWORD srcH, UWORD srcMod, struct RastPort * rp, UWORD destX, UWORD destY, UWORD destW, UWORD destH, ULONG globalAlpha);
};

#endif /* CYBERGRAPHICS_INTERFACE_DEF_H */
