#ifndef PREFERENCES_INTERFACE_DEF_H
#define PREFERENCES_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef SCALOS_PREFERENCES_H
#include <scalos/preferences.h>
#endif

struct PreferencesIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct PreferencesIFace *Self);
	uint32 APICALL (*Release)(struct PreferencesIFace *Self);
	void APICALL (*Expunge)(struct PreferencesIFace *Self);
	struct Interface * APICALL (*Clone)(struct PreferencesIFace *Self);
	APTR APICALL (*AllocPrefsHandle)(struct PreferencesIFace *Self, CONST_STRPTR name);
	VOID APICALL (*FreePrefsHandle)(struct PreferencesIFace *Self, APTR prefsHandle);
	VOID APICALL (*SetPreferences)(struct PreferencesIFace *Self, APTR prefsHandle, ULONG iD, ULONG prefsTag, const APTR a1arg, UWORD struct_Size);
	ULONG APICALL (*GetPreferences)(struct PreferencesIFace *Self, APTR prefsHandle, ULONG iD, ULONG prefsTag, APTR a1arg, UWORD struct_Size);
	VOID APICALL (*ReadPrefsHandle)(struct PreferencesIFace *Self, APTR prefsHandle, CONST_STRPTR filename);
	VOID APICALL (*WritePrefsHandle)(struct PreferencesIFace *Self, APTR prefsHandle, CONST_STRPTR filename);
	struct PrefsStruct * APICALL (*FindPreferences)(struct PreferencesIFace *Self, APTR prefsHandle, ULONG iD, ULONG prefsTag);
	VOID APICALL (*SetEntry)(struct PreferencesIFace *Self, APTR prefsHandle, ULONG iD, ULONG prefsTag, const APTR a1arg, UWORD struct_Size, ULONG entry);
	ULONG APICALL (*GetEntry)(struct PreferencesIFace *Self, APTR prefsHandle, ULONG iD, ULONG prefsTag, APTR a1arg, UWORD struct_Size, ULONG entry);
	ULONG APICALL (*RemEntry)(struct PreferencesIFace *Self, APTR prefsHandle, ULONG iD, ULONG prefsTag, ULONG entry);
};

#endif /* PREFERENCES_INTERFACE_DEF_H */
