#ifndef SCALOS_INTERFACE_DEF_H
#define SCALOS_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_CLASSUSR_H
#include <intuition/classusr.h>
#endif
#ifndef WORKBENCH_STARTUP_H
#include <workbench/startup.h>
#endif
#ifndef SCALOS_SCALOS_H
#include <scalos/scalos.h>
#endif

struct ScalosIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct ScalosIFace *Self);
	uint32 APICALL (*Release)(struct ScalosIFace *Self);
	void APICALL (*Expunge)(struct ScalosIFace *Self);
	struct Interface * APICALL (*Clone)(struct ScalosIFace *Self);
	BOOL APICALL (*SCA_WBStart)(struct ScalosIFace *Self, APTR argArray, CONST struct TagItem * tagList, ULONG numArgs);
	BOOL APICALL (*SCA_WBStartTags)(struct ScalosIFace *Self, APTR argArray, ULONG numArgs, ...);
	VOID APICALL (*SCA_SortNodes)(struct ScalosIFace *Self, struct ScalosNodeList * nodelist, struct Hook * sortHook, ULONG sortType);
	struct AppObject * APICALL (*SCA_NewAddAppIcon)(struct ScalosIFace *Self, ULONG iD, ULONG userData, Object * iconObj, struct MsgPort * msgPort, CONST struct TagItem * tagList);
	struct AppObject * APICALL (*SCA_NewAddAppIconTags)(struct ScalosIFace *Self, ULONG iD, ULONG userData, Object * iconObj, struct MsgPort * msgPort, ...);
	BOOL APICALL (*SCA_RemoveAppObject)(struct ScalosIFace *Self, struct AppObject * appObj);
	struct AppObject * APICALL (*SCA_NewAddAppWindow)(struct ScalosIFace *Self, ULONG iD, ULONG userData, struct Window * win, struct MsgPort * msgPort, CONST struct TagItem * tagList);
	struct AppObject * APICALL (*SCA_NewAddAppWindowTags)(struct ScalosIFace *Self, ULONG iD, ULONG userData, struct Window * win, struct MsgPort * msgPort, ...);
	struct AppObject * APICALL (*SCA_NewAddAppMenuItem)(struct ScalosIFace *Self, ULONG iD, ULONG userData, CONST_STRPTR text, struct MsgPort * msgPort, CONST struct TagItem * tagList);
	struct AppObject * APICALL (*SCA_NewAddAppMenuItemTags)(struct ScalosIFace *Self, ULONG iD, ULONG userData, CONST_STRPTR text, struct MsgPort * msgPort, ...);
	struct MinNode * APICALL (*SCA_AllocStdNode)(struct ScalosIFace *Self, struct ScalosNodeList * nodeList, ULONG nodeType);
	struct MinNode * APICALL (*SCA_AllocNode)(struct ScalosIFace *Self, struct ScalosNodeList * nodeList, ULONG size);
	VOID APICALL (*SCA_FreeNode)(struct ScalosIFace *Self, struct ScalosNodeList * nodeList, struct MinNode * minNode);
	VOID APICALL (*SCA_FreeAllNodes)(struct ScalosIFace *Self, struct ScalosNodeList * nodeList);
	VOID APICALL (*SCA_MoveNode)(struct ScalosIFace *Self, struct ScalosNodeList * srcNodeList, struct ScalosNodeList * destNodeList, struct MinNode * minNode);
	VOID APICALL (*SCA_SwapNodes)(struct ScalosIFace *Self, struct MinNode * minNode1, struct MinNode * minNode2, struct ScalosNodeList * nodeList);
	BOOL APICALL (*SCA_OpenIconWindow)(struct ScalosIFace *Self, CONST struct TagItem * tagList);
	BOOL APICALL (*SCA_OpenIconWindowTags)(struct ScalosIFace *Self, ...);
	struct ScaWindowList * APICALL (*SCA_LockWindowList)(struct ScalosIFace *Self, LONG accessmode);
	VOID APICALL (*SCA_UnLockWindowList)(struct ScalosIFace *Self);
	struct ScalosMessage * APICALL (*SCA_AllocMessage)(struct ScalosIFace *Self, ULONG messagetype, UWORD additional_size);
	VOID APICALL (*SCA_FreeMessage)(struct ScalosIFace *Self, struct ScalosMessage * message);
	struct DragHandle * APICALL (*SCA_InitDrag)(struct ScalosIFace *Self, struct Screen * screen);
	VOID APICALL (*SCA_EndDrag)(struct ScalosIFace *Self, struct DragHandle * dragHandle);
	BOOL APICALL (*SCA_AddBob)(struct ScalosIFace *Self, struct DragHandle * dragHandle, struct BitMap * bm, APTR mask, ULONG width, ULONG height, LONG xOffset, LONG yOffset);
	VOID APICALL (*SCA_DrawDrag)(struct ScalosIFace *Self, struct DragHandle * dragHandle, LONG x, LONG y, ULONG flags);
	VOID APICALL (*SCA_UpdateIcon)(struct ScalosIFace *Self, UBYTE windowType, APTR updateIconStruct, ULONG ui_SIZE);
	ULONG APICALL (*SCA_MakeWBArgs)(struct ScalosIFace *Self, struct WBArg * buffer, struct ScaIconNode * in, ULONG argsSize);
	VOID APICALL (*SCA_FreeWBArgs)(struct ScalosIFace *Self, struct WBArg * buffer, ULONG number, ULONG flags);
	VOID APICALL (*SCA_RemapBitmap)(struct ScalosIFace *Self, struct BitMap * srcBitmap, struct BitMap * destBitmap, APTR penArray);
	VOID APICALL (*SCA_ScreenTitleMsg)(struct ScalosIFace *Self, CONST_STRPTR format, APTR args);
	VOID APICALL (*SCA_ScreenTitleMsgArgs)(struct ScalosIFace *Self, CONST_STRPTR format, ...);
	struct ScalosClass * APICALL (*SCA_MakeScalosClass)(struct ScalosIFace *Self, CONST_STRPTR className, CONST_STRPTR superClassName, UWORD instSize, APTR dispFunc);
	BOOL APICALL (*SCA_FreeScalosClass)(struct ScalosIFace *Self, struct ScalosClass * scalosClass);
	Object * APICALL (*SCA_NewScalosObject)(struct ScalosIFace *Self, CONST_STRPTR className, CONST struct TagItem * tagList);
	Object * APICALL (*SCA_NewScalosObjectTags)(struct ScalosIFace *Self, CONST_STRPTR className, ...);
	VOID APICALL (*SCA_DisposeScalosObject)(struct ScalosIFace *Self, Object * obj);
	ULONG APICALL (*SCA_ScalosControlA)(struct ScalosIFace *Self, CONST_STRPTR name, CONST struct TagItem * tagList);
	ULONG APICALL (*SCA_ScalosControl)(struct ScalosIFace *Self, CONST_STRPTR name, ...);
	ULONG APICALL (*SCA_ScalosControlTags)(struct ScalosIFace *Self, CONST_STRPTR name, ...);
	Object * APICALL (*SCA_GetDefIconObject)(struct ScalosIFace *Self, BPTR dirLock, CONST_STRPTR name);
	struct ScaWindowStruct * APICALL (*SCA_OpenDrawerByName)(struct ScalosIFace *Self, CONST_STRPTR path, struct TagItem * tagList);
	struct ScaWindowStruct * APICALL (*SCA_OpenDrawerByNameTags)(struct ScalosIFace *Self, CONST_STRPTR path, ...);
	ULONG APICALL (*SCA_CountWBArgs)(struct ScalosIFace *Self, struct ScaIconNode * in);
	Object * APICALL (*SCA_GetDefIconObjectA)(struct ScalosIFace *Self, BPTR dirLock, CONST_STRPTR name, struct TagItem * tagList);
	Object * APICALL (*SCA_GetDefIconObjectTags)(struct ScalosIFace *Self, BPTR dirLock, CONST_STRPTR name, ...);
	ULONG APICALL (*SCA_LockDrag)(struct ScalosIFace *Self, struct DragHandle * dragHandle);
	ULONG APICALL (*SCA_UnlockDrag)(struct ScalosIFace *Self, struct DragHandle * dragHandle);
};

#endif /* SCALOS_INTERFACE_DEF_H */
