#ifndef SCALOSMENUPLUGIN_INTERFACE_DEF_H
#define SCALOSMENUPLUGIN_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 51.3.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef  INTUITION_CLASSUSR_H
#include <intuition/classusr.h>
#endif
#ifndef  WORKBENCH_STARTUP_H
#include <workbench/startup.h>
#endif
#ifndef  SCALOS_SCALOS_H
#include <scalos/scalos.h>
#endif


struct ScalosMenuPluginIFace
	{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct ScalosMenuPluginIFace *Self);
	ULONG APICALL (*Release)(struct ScalosMenuPluginIFace *Self);
	void APICALL (*Expunge)(struct ScalosMenuPluginIFace *Self);
	struct Interface * APICALL (*Clone)(struct ScalosMenuPluginIFace *Self);

	void APICALL (*SCAMenuFunction)(struct ScalosMenuPluginIFace *self, struct ScaWindowTask *wt, struct ScaIconNode *in);
	};

#endif /* SCALOSMENUPLUGIN_INTERFACE_DEF_H */
