#!/bin/sh
#
# Create an apache.conf file
#

BASEDIR=$(cd $(dirname "$0")/.. ; pwd)

. site.conf

if [ -r "$2" ]; then
    rm -f "$2.bak"
    mv "$2" "$2.bak"
fi

cat > "$2" <<EOF
# To use this file, please append the following line in httpd.conf
# or access.conf:
#
#    Include $BASEDIR/data/apache.conf
#
#and restart Apache.
EOF

sed \
    -e "s:\@HOSTNAME\@:$HOSTNAME:" \
    -e "s:\@BASEDIR\@:$BASEDIR:" \
    -e "s:\@MAILMAN\@:$MAILMAN:" \
    "$1" >> "$2"

