/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/scalos.h>
#include <proto/scalos.h>


static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }


STATIC struct Library * stub_OpenPPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenPPC };

STATIC APTR stub_ClosePPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClosePPC };

STATIC APTR stub_ExpungePPC(ULONG *regarray __attribute__((unused)))
{
    return NULL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray __attribute__((unused)))
{
    return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static BOOL stub_SCA_WBStartPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_WBStart(
		(APTR)regarray[8],
		(CONST struct TagItem *)regarray[9],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_WBStart = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_WBStartPPC };

static VOID stub_SCA_SortNodesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_SortNodes(
		(struct ScalosNodeList *)regarray[8],
		(struct Hook *)regarray[9],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_SortNodes = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_SortNodesPPC };

static struct AppObject * stub_SCA_NewAddAppIconPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_NewAddAppIcon(
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(Object *)regarray[8],
		(struct MsgPort *)regarray[9],
		(CONST struct TagItem *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_NewAddAppIcon = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_NewAddAppIconPPC };

static BOOL stub_SCA_RemoveAppObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_RemoveAppObject(
		(struct AppObject *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_RemoveAppObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_RemoveAppObjectPPC };

static struct AppObject * stub_SCA_NewAddAppWindowPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_NewAddAppWindow(
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(struct Window *)regarray[8],
		(struct MsgPort *)regarray[9],
		(CONST struct TagItem *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_NewAddAppWindow = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_NewAddAppWindowPPC };

static struct AppObject * stub_SCA_NewAddAppMenuItemPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_NewAddAppMenuItem(
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(CONST_STRPTR)regarray[8],
		(struct MsgPort *)regarray[9],
		(CONST struct TagItem *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_NewAddAppMenuItem = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_NewAddAppMenuItemPPC };

static struct MinNode * stub_SCA_AllocStdNodePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_AllocStdNode(
		(struct ScalosNodeList *)regarray[8],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_AllocStdNode = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_AllocStdNodePPC };

static struct MinNode * stub_SCA_AllocNodePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_AllocNode(
		(struct ScalosNodeList *)regarray[8],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_AllocNode = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_AllocNodePPC };

static VOID stub_SCA_FreeNodePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_FreeNode(
		(struct ScalosNodeList *)regarray[8],
		(struct MinNode *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_FreeNode = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_FreeNodePPC };

static VOID stub_SCA_FreeAllNodesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_FreeAllNodes(
		(struct ScalosNodeList *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_FreeAllNodes = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_FreeAllNodesPPC };

static VOID stub_SCA_MoveNodePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_MoveNode(
		(struct ScalosNodeList *)regarray[8],
		(struct ScalosNodeList *)regarray[9],
		(struct MinNode *)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_MoveNode = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_MoveNodePPC };

static VOID stub_SCA_SwapNodesPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_SwapNodes(
		(struct MinNode *)regarray[8],
		(struct MinNode *)regarray[9],
		(struct ScalosNodeList *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_SwapNodes = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_SwapNodesPPC };

static BOOL stub_SCA_OpenIconWindowPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_OpenIconWindow(
		(CONST struct TagItem *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_OpenIconWindow = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_OpenIconWindowPPC };

static struct ScaWindowList * stub_SCA_LockWindowListPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_LockWindowList(
		(LONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_LockWindowList = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_LockWindowListPPC };

static VOID stub_SCA_UnLockWindowListPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_UnLockWindowList(
	);
}
STATIC CONST struct EmuTrap stub_SCA_UnLockWindowList = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_UnLockWindowListPPC };

static struct ScalosMessage * stub_SCA_AllocMessagePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_AllocMessage(
		(ULONG)regarray[0],
		(UWORD)(regarray[1] & 0xffff)
	);
}
STATIC CONST struct EmuTrap stub_SCA_AllocMessage = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_AllocMessagePPC };

static VOID stub_SCA_FreeMessagePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_FreeMessage(
		(struct ScalosMessage *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_FreeMessage = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_FreeMessagePPC };

static struct DragHandle * stub_SCA_InitDragPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_InitDrag(
		(struct Screen *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_InitDrag = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_InitDragPPC };

static VOID stub_SCA_EndDragPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_EndDrag(
		(struct DragHandle *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_EndDrag = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_EndDragPPC };

static BOOL stub_SCA_AddBobPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_AddBob(
		(struct DragHandle *)regarray[8],
		(struct BitMap *)regarray[9],
		(APTR)regarray[10],
		(ULONG)regarray[0],
		(ULONG)regarray[1],
		(LONG)regarray[2],
		(LONG)regarray[3]
	);
}
STATIC CONST struct EmuTrap stub_SCA_AddBob = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_AddBobPPC };

static VOID stub_SCA_DrawDragPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_DrawDrag(
		(struct DragHandle *)regarray[8],
		(LONG)regarray[0],
		(LONG)regarray[1],
		(ULONG)regarray[2]
	);
}
STATIC CONST struct EmuTrap stub_SCA_DrawDrag = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_DrawDragPPC };

static VOID stub_SCA_UpdateIconPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_UpdateIcon(
		(UBYTE)(regarray[0] & 0xff),
		(APTR)regarray[8],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_SCA_UpdateIcon = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_UpdateIconPPC };

static ULONG stub_SCA_MakeWBArgsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_MakeWBArgs(
		(struct WBArg *)regarray[8],
		(struct ScaIconNode *)regarray[9],
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_SCA_MakeWBArgs = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_MakeWBArgsPPC };

static VOID stub_SCA_FreeWBArgsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_FreeWBArgs(
		(struct WBArg *)regarray[8],
		(ULONG)regarray[0],
		(ULONG)regarray[1]
	);
}
STATIC CONST struct EmuTrap stub_SCA_FreeWBArgs = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_FreeWBArgsPPC };

static VOID stub_SCA_RemapBitmapPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_RemapBitmap(
		(struct BitMap *)regarray[8],
		(struct BitMap *)regarray[9],
		(APTR)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_RemapBitmap = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_RemapBitmapPPC };

static VOID stub_SCA_ScreenTitleMsgPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_ScreenTitleMsg(
		(CONST_STRPTR)regarray[8],
		(APTR)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_ScreenTitleMsg = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_ScreenTitleMsgPPC };

static struct ScalosClass * stub_SCA_MakeScalosClassPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_MakeScalosClass(
		(CONST_STRPTR)regarray[8],
		(CONST_STRPTR)regarray[9],
		(UWORD)(regarray[0] & 0xffff),
		(APTR)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_MakeScalosClass = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_MakeScalosClassPPC };

static BOOL stub_SCA_FreeScalosClassPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_FreeScalosClass(
		(struct ScalosClass *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_FreeScalosClass = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_FreeScalosClassPPC };

static Object * stub_SCA_NewScalosObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_NewScalosObject(
		(CONST_STRPTR)regarray[8],
		(CONST struct TagItem *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_NewScalosObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_NewScalosObjectPPC };

static VOID stub_SCA_DisposeScalosObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	Self->SCA_DisposeScalosObject(
		(Object *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_DisposeScalosObject = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_SCA_DisposeScalosObjectPPC };

static ULONG stub_SCA_ScalosControlAPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_ScalosControlA(
		(CONST_STRPTR)regarray[8],
		(CONST struct TagItem *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_ScalosControlA = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_ScalosControlAPPC };

static Object * stub_SCA_GetDefIconObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_GetDefIconObject(
		(BPTR)regarray[8],
		(CONST_STRPTR)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_GetDefIconObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_GetDefIconObjectPPC };

static struct ScaWindowStruct * stub_SCA_OpenDrawerByNamePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_OpenDrawerByName(
		(CONST_STRPTR)regarray[8],
		(struct TagItem *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_SCA_OpenDrawerByName = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_OpenDrawerByNamePPC };

static ULONG stub_SCA_CountWBArgsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_CountWBArgs(
		(struct ScaIconNode *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_SCA_CountWBArgs = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_CountWBArgsPPC };

static Object * stub_SCA_GetDefIconObjectAPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct ScalosIFace *Self = (struct ScalosIFace *) ExtLib->MainIFace;

	return Self->SCA_GetDefIconObjectA(
		(BPTR)regarray[8],
		(CONST_STRPTR)regarray[9],
		(struct TagItem *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_SCA_GetDefIconObjectA = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_SCA_GetDefIconObjectAPPC };

CONST CONST_APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_SCA_WBStart,
	&stub_SCA_SortNodes,
	&stub_SCA_NewAddAppIcon,
	&stub_SCA_RemoveAppObject,
	&stub_SCA_NewAddAppWindow,
	&stub_SCA_NewAddAppMenuItem,
	&stub_SCA_AllocStdNode,
	&stub_SCA_AllocNode,
	&stub_SCA_FreeNode,
	&stub_SCA_FreeAllNodes,
	&stub_SCA_MoveNode,
	&stub_SCA_SwapNodes,
	&stub_SCA_OpenIconWindow,
	&stub_SCA_LockWindowList,
	&stub_SCA_UnLockWindowList,
	&stub_SCA_AllocMessage,
	&stub_SCA_FreeMessage,
	&stub_SCA_InitDrag,
	&stub_SCA_EndDrag,
	&stub_SCA_AddBob,
	&stub_SCA_DrawDrag,
	&stub_SCA_UpdateIcon,
	&stub_SCA_MakeWBArgs,
	&stub_SCA_FreeWBArgs,
	&stub_SCA_RemapBitmap,
	&stub_SCA_ScreenTitleMsg,
	&stub_SCA_MakeScalosClass,
	&stub_SCA_FreeScalosClass,
	&stub_SCA_NewScalosObject,
	&stub_SCA_DisposeScalosObject,
	&stub_SCA_ScalosControlA,
	&stub_SCA_GetDefIconObject,
	&stub_SCA_OpenDrawerByName,
	&stub_SCA_CountWBArgs,
	&stub_SCA_GetDefIconObjectA,
	(CONST_APTR)-1
};
