/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/iconobject.h>
#include <proto/iconobject.h>


static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }


STATIC struct Library * stub_OpenPPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenPPC };

STATIC APTR stub_ClosePPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClosePPC };

STATIC APTR stub_ExpungePPC(ULONG *regarray __attribute__((unused)))
{
    return NULL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray __attribute__((unused)))
{
    return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static Object * stub_NewIconObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	return Self->NewIconObject(
		(CONST_STRPTR)regarray[8],
		(CONST struct TagItem *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_NewIconObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_NewIconObjectPPC };

static VOID stub_DisposeIconObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	Self->DisposeIconObject(
		(Object *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_DisposeIconObject = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_DisposeIconObjectPPC };

static Object * stub_GetDefIconObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	return Self->GetDefIconObject(
		(ULONG)regarray[0],
		(CONST struct TagItem *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_GetDefIconObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_GetDefIconObjectPPC };

static LONG stub_PutIconObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	return Self->PutIconObject(
		(Object *)regarray[8],
		(CONST_STRPTR)regarray[9],
		(CONST struct TagItem *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_PutIconObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_PutIconObjectPPC };

static ULONG stub_IsIconNamePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	return Self->IsIconName(
		(CONST_STRPTR)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_IsIconName = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_IsIconNamePPC };

static Object * stub_Convert2IconObjectPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	return Self->Convert2IconObject(
		(struct DiskObject *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_Convert2IconObject = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Convert2IconObjectPPC };

static Object * stub_Convert2IconObjectAPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct IconobjectIFace *Self = (struct IconobjectIFace *) ExtLib->MainIFace;

	return Self->Convert2IconObjectA(
		(struct DiskObject *)regarray[8],
		(CONST struct TagItem *)regarray[9]
	);
}
STATIC CONST struct EmuTrap stub_Convert2IconObjectA = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_Convert2IconObjectAPPC };

CONST CONST_APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_NewIconObject,
	&stub_DisposeIconObject,
	&stub_GetDefIconObject,
	&stub_PutIconObject,
	&stub_IsIconName,
	&stub_Convert2IconObject,
	&stub_Convert2IconObjectA,
	(CONST_APTR)-1
};
