TOP = ../../../..

include $(TOP)/config/host.cfg

# Must kill TARGET_ARCH here since this is implicitly used by make
TARGET_ARCH :=

CC = gcc
DEFINES = -D_AROS
MAKE = make
ECHO = echo
RM = rm

AROSDIR = $(ARCHDIR)/AROS
AROS_INCLUDES = $(AROSDIR)/Include

OS_INCLUDES = -I$(OS_INCLUDES_DIR) -I../..

INCLUDES = $(USER_INCLUDES) $(OS_INCLUDES) $(DEFINES)

CFLAGS = $(INCLUDES)

TARGETS =  bguiclass_lib.o bguiclass_libtag.o bguiclass_libendtag.o

all: $(TARGETS)

clean : 
	@$(RM) -rf $(TARGET)
