
OBJS = \
	Main.o							\
	FileReader.o					\
	FileWriter.o					\
	ReaderHook.o					\
	WriterHook.o					\
	rAIFFAudio.o					\
	rRAWAudio.o						\
	rSplitISOData.o				\
	rISOData.o						\
	rMP3Audio.o						\
	rWAVAudio.o						\
	wRAWAudioData.o				\
	wSplitISOData.o				\
	wAIFFAudio.o					\
	wWAVAudio.o						\
	wCUESession.o					\
	rCUESession.o					\
	rNRGSession.o
	
Program			= DTLibIO.module

TARGETS			= aros os3 morphos os4
OBJDIRS			= 
MAKEDIRS			= 

BUILD_LIBRARY	= 0

INCOPTS			= 
LIBOPTS			= -lGeneric -lLibrary -lC 

OWNSTARTUP		= 1
AROS_LIBOPTS	= 
M68K_LIBOPTS	=
MOS_LIBOPTS		=
OS4_LIBOPTS		=

	include ../Generic/Makefile.mk
