#ifndef INLINE4_IDENTIFY_H
#define INLINE4_IDENTIFY_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline macros for Interface "main" */
#define IdExpansion(TagList) IIdentify->IdExpansion(TagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdExpansionTags(...) IIdentify->IdExpansionTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdExpansionTags(...) IIdentify->IdExpansionTags(## vargs) 
#endif
#define IdHardware(Type, TagList) IIdentify->IdHardware(Type, TagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdHardwareTags(...) IIdentify->IdHardwareTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdHardwareTags(vargs...) IIdentify->IdHardwareTags(## vargs) 
#endif
#define IdAlert(ID, TagList) IIdentify->IdAlert(ID, TagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdAlertTags(...) IIdentify->IdAlertTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdAlertTags(vargs...) IIdentify->IdAlertTags(## vargs) 
#endif
#define IdFunction(LibName, Offset, TagList) IIdentify->IdFunction(LibName, Offset, TagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdFunctionTags(LibName, ...) IIdentify->IdFunctionTags(LibName, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdFunctionTags(LibName, vargs...) IIdentify->IdFunctionTags(LibName, ## vargs) 
#endif
#define IdHardwareNum(Type, TagList) IIdentify->IdHardwareNum(Type, TagList) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdHardwareNumTags(...) IIdentify->IdHardwareNumTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdHardwareNumTags(vargs...) IIdentify->IdHardwareNumTags(## vargs) 
#endif
#define IdHardwareUpdate() IIdentify->IdHardwareUpdate() 
#define IdFormatString(String, Buffer, Length, Tags) IIdentify->IdFormatString(String, Buffer, Length, Tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdFormatStringTags(String, Buffer, ...) IIdentify->IdFormatStringTags(String, Buffer, __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdFormatStringTags(String, Buffer, vargs...) IIdentify->IdFormatStringTags(String, Buffer, ## vargs) 
#endif
#define IdEstimateFormatSize(String, Tags) IIdentify->IdEstimateFormatSize(String, Tags) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define IdEstimateFormatSizeTags(...) IIdentify->IdEstimateFormatSizeTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define IdEstimateFormatSizeTags(vargs...) IIdentify->IdEstimateFormatSizeTags(## vargs) 
#endif

#endif /* INLINE4_IDENTIFY_H */
