
all: demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8 demo9

demo1: demo1.c
	gcc demo1.c -I../include -o demo1 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo1

demo2: demo2.c
	gcc demo2.c -I../include -o demo2 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo2

demo3: demo3.c
	gcc demo3.c -I../include -o demo3 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo3

demo4: demo4.c
	gcc demo4.c -I../include -o demo4 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo4

demo5: demo5.c
	gcc demo5.c -I../include -o demo5 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo5

demo6: demo6.c
	gcc demo6.c -I../include -o demo6 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo6

demo7: demo7.c
	gcc demo7.c -I../include -o demo7 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo7

demo8: demo8.c
	gcc demo8.c -I../include -o demo8 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo8

demo9: demo9.c
	gcc demo9.c -I../include -o demo9 -noixemul
	ppc-morphos-strip --strip-unneeded --remove-section=.comment demo9










