#ifndef DESCRIPTOR_H
#define DESCRIPTOR_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_AUDIO_MODINFOTXT1 100
#define MSG_AUDIO_MODINFOTXT2 101
#define MSG_AUDIO_MODINFOTXT3 102
#define MSG_AUDIO_NOCIA 103
#define MSG_AUDIO_LOAD 104
#define MSG_AUDIO_MODINFO1 105
#define MSG_AUDIO_MODINFO2 106
#define MSG_AUDIO_CORRUPT8SVX 107
#define MSG_AUDIO_ASKFREQUENCY 108
#define MSG_AUDIO_NOAUDIO 109
#define MSG_AUDIO_INFO1 110
#define MSG_AUDIO_INFO2 111
#define MSG_AUDIO_ASKTYPE 112
#define MSG_AUDIO_TYPEANSWER1 113
#define MSG_AUDIO_TYPEANSWER2 114
#define MSG_AUDIO_CONFIG_ASKHZ 115
#define MSG_AUDIO_CONFIG_PLAYMETHOD 116
#define MSG_AUDIO_CONFIG_PLAYMETHOD1 117
#define MSG_AUDIO_CONFIG_PLAYMETHOD2 118
#define MSG_AUDIO_CONFIG_PLAYMETHOD3 119
#define MSG_AUDIO_CONFIG_FREQUENCY 120
#define MSG_AUDIO_CONFIG_BUFFER 121
#define MSG_CLOCK_FORMATSTRING 150
#define MSG_COPYNAMESOURCE 200
#define MSG_COPYNAMEDESTINATION 201
#define MSG_COPYING 202
#define MSG_COPYING2 203
#define MSG_COPIED 204
#define MSG_COPY_NEWNAME 205
#define MSG_COPY_OVERWRITE 206
#define MSG_COPY_NOFREESPACE 207
#define MSG_COPYMOVE_CONFIG_REFRESH 208
#define MSG_COPYMOVE_CONFIG_REFRESH1 209
#define MSG_COPYMOVE_CONFIG_REFRESH2 210
#define MSG_COPYMOVE_CONFIG_REFRESH3 211
#define MSG_COPYMOVE_CONFIG_OVERWRITE 212
#define MSG_COPYMOVE_CONFIG_OVERWRITE1 213
#define MSG_COPYMOVE_CONFIG_OVERWRITE2 214
#define MSG_COPYMOVE_CONFIG_COMMENT 215
#define MSG_COPYMOVE_CONFIG_PROTECTION 216
#define MSG_COPYMOVE_CONFIG_DATE 217
#define MSG_COPYMOVE_CONFIG_CHECKFREESPACE 218
#define MSG_COPYMOVE_CONFIG_COPYBUFFER 219
#define MSG_DELETING 220
#define MSG_DELETED 221
#define MSG_DELETE_ASKDELETE 222
#define MSG_DELETE_ASKDIRECTORY 223
#define MSG_DELETE_DELPROTECTED 224
#define MSG_DELETE_CONFIG_ASKDELETE 225
#define MSG_DELETE_CONFIG_ASKDIR 226
#define MSG_DELETE_CONFIG_DELPROT 227
#define MSG_MOVING 228
#define MSG_MOVED 229
#define MSG_DISKSIZING 230
#define MSG_DISKSIZED 231
#define MSG_DIRNAME 250
#define MSG_DIRRING 251
#define MSG_DIRREDLINE1 252
#define MSG_DIRREDLINE2 253
#define MSG_DIRMETER 254
#define MSG_DIRMETER_RW 255
#define MSG_PARENT_CONFIG_BUFFERS 256
#define MSG_DISKINFO 300
#define MSG_DISKINFO_WPROT 301
#define MSG_DISKINFO_VALIDATING 302
#define MSG_DISKINFO_VALIDATED 303
#define MSG_DISKINFO_UNKNOWN 304
#define MSG_SLEEP_SLEEPWINDOW 350
#define MSG_SLEEP_APPICON 351
#define MSG_EXE_COMMAND 400
#define MSG_EXE_SHELLWINDOW 401
#define MSG_EXE_TIMEOUT 402
#define MSG_EXE_NOSHELLWINDOW 403
#define MSG_EXE_CONFIG_CD 404
#define MSG_EXE_CONFIG_RESCAN 405
#define MSG_EXE_CONFIG_SOURCE 406
#define MSG_EXE_CONFIG_DESTINATION 407
#define MSG_EXE_CONFIG_SOURCEDEST 408
#define MSG_EXE_CONFIG_STARTSCREEN 409
#define MSG_EXE_CONFIG_ENDSCREEN 410
#define MSG_EXE_CONFIG_WBFRONT 411
#define MSG_EXE_CONFIG_FMFRONT 412
#define MSG_EXE_CONFIG_NOCHANGE 413
#define MSG_EXE_SYNTAXERROR 414
#define MSG_EXE_FAILED 415
#define MSG_EXE_EXECUTING 416
#define MSG_FILECLICKNAME 450
#define MSG_FILECLICKING 451
#define MSG_FILECLICK_PICTURE 452
#define MSG_FILECLICK_SOUND 453
#define MSG_FILECLICK_EXECUTABLE 454
#define MSG_FILECLICK_WBICON 455
#define MSG_FILECLICK_MODULE 456
#define MSG_FILECLICK_ASC 457
#define MSG_FILECLICK_HEX 458
#define MSG_FILECLICK_FONT 459
#define MSG_MAIN_WARNING 500
#define MSG_MAIN_PROCESSES 501
#define MSG_MAIN_WINDOWS 502
#define MSG_MAIN_AREYOUSURE 503
#define MSG_MAIN_QUIT 504
#define MSG_MAIN_REQUEST 505
#define MSG_MAIN_ABORT 506
#define MSG_MAIN_ABORTED 507
#define MSG_MAIN_COMPLETED 508
#define MSG_MAIN_CONTINUE 509
#define MSG_MAIN_ABORTMODPLAY 510
#define MSG_MAIN_FMALREADY 511
#define MSG_MAIN_WINERR1 512
#define MSG_MAIN_SCRERR1 513
#define MSG_MAIN_ERRNOBITMAP 514
#define MSG_MAIN_NOSOURCE 515
#define MSG_MAIN_NOSOURCEFILE 516
#define MSG_MAIN_NODESTINATION 517
#define MSG_MAIN_VISITORWINDOWS 518
#define MSG_MAIN_REGISTERTITLE 519
#define MSG_MAIN_REGISTERNAME 520
#define MSG_MAIN_REGISTERED 521
#define MSG_MAIN_UNREGISTERED 522
#define MSG_MAIN_ABOUT 523
#define MSG_MAIN_PROGRAMMEDBY 524
#define MSG_MAIN_CMENUTXT 525
#define MSG_MAIN_CMENULABEL 526
#define MSG_MAIN_CMENUKEYS 527
#define MSG_MAIN_SHAREWARE 528
#define MSG_MAIN_DATATYPEERROR 529
#define MSG_FMDOS_SEEKERR 550
#define MSG_FMDOS_READERR 551
#define MSG_FMDOS_UEOF 552
#define MSG_FMDOS_WRITEERR 553
#define MSG_FMDOS_OPENERR 554
#define MSG_FMDOS_OPENRERR 555
#define MSG_FMDOS_OPENWERR 556
#define MSG_FMDOS_NOBUFMEM 557
#define MSG_FMDOS_EXAMINEERR 558
#define MSG_FMDOS_EXNEXTERR 559
#define MSG_FMDOS_LOCKERR 560
#define MSG_FMDOS_RENAMEERR 561
#define MSG_FMDOS_COMMENTERR 562
#define MSG_FMDOS_DATEERR 563
#define MSG_FMDOS_PROTERR 564
#define MSG_FMDOS_MAKEDIRERR 565
#define MSG_FMDOS_CHIPMEM 566
#define MSG_FMDOS_PUBLICMEM 567
#define MSG_FMDOS_ALLOCATEERR 568
#define MSG_FMDOS_RELABELERR 569
#define MSG_FMDOS_DELETEERR 570
#define MSG_FMDOS_REMDELPROT 571
#define MSG_FMDOS_DECRUNCHING 572
#define MSG_FMDOS_ZEROSIZE 573
#define MSG_OPERATE_ASKNAME 600
#define MSG_OPERATE_ASKFLAGS 601
#define MSG_OPERATE_ASKCOMMENT 602
#define MSG_OPERATE_ASKDATE 603
#define MSG_OPERATE_CREATEICON 604
#define MSG_OPERATE_DEFAULTDRAWER 605
#define MSG_OPERATE_ADD 606
#define MSG_OPERATE_SUB 607
#define MSG_OPERATE_CHANGE 608
#define MSG_OPERATE_FORMATINSTALL 609
#define MSG_OPERATE_FORMATINSTALLNAME 610
#define MSG_OPERATE_FFS 611
#define MSG_OPERATE_INT 612
#define MSG_OPERATE_DIRCACHE 613
#define MSG_OPERATE_DOFORMAT 614
#define MSG_OPERATE_DOQFORMAT 615
#define MSG_OPERATE_DOINSTALL 616
#define MSG_OPERATE_VERIFY 617
#define MSG_OPERATE_INHIBITERR 618
#define MSG_OPERATE_INSTALLING 619
#define MSG_OPERATE_INSTALLERR 620
#define MSG_OPERATE_FORMATTING 621
#define MSG_OPERATE_VERIFYING 622
#define MSG_OPERATE_INITIALIZING 623
#define MSG_OPERATE_DEFAULTNAME 624
#define MSG_OPERATE_INITIALIZEERR 625
#define MSG_REQ_FATALERR 650
#define MSG_REQ_ANSWER1 651
#define MSG_REQ_ANSWER2 652
#define MSG_REQ_DOSERR 653
#define MSG_REQ_ERROR 654
#define MSG_SCR_SCRERR2 700
#define MSG_SCR_WINERR2 701
#define MSG_SCR_MEMERR 702
#define MSG_SCR_FONTERR1 703
#define MSG_SHOWPIC_HIRES 750
#define MSG_SHOWPIC_SHIRES 751
#define MSG_SHOWPIC_LACE 752
#define MSG_SHOWPIC_HAM6 753
#define MSG_SHOWPIC_HAM8 754
#define MSG_SHOWPIC_EHB 755
#define MSG_SHOWPIC_NOPICTURE 756
#define MSG_SHOWPIC_INFO1 757
#define MSG_SHOWPIC_INFO2 758
#define MSG_SHOWPIC_ERRNOSCREEN 759
#define MSG_SHOWPIC_CORRUPT 760
#define MSG_SHOWICON_TITLE 761
#define MSG_SHOWFONT_TITLE 762
#define MSG_SHOWFONT_ASKSIZE 763
#define MSG_SHOWTEXTINFO1 800
#define MSG_SHOWTEXTINFO2 801
#define MSG_SHOWTEXT_LINENUMBER 802
#define MSG_SHOWTEXT_SEARCHSTRING 803
#define MSG_SHOWTEXT_CONFIG_INFOLINE 804
#define MSG_TASKWINDOW_LISTS 850
#define MSG_TASKWINDOW_DEVLIST 851
#define MSG_TASKWINDOW_EMPTY 852
#define MSG_PARSE_SORTBY 900
#define MSG_PARSE_SORTUP 901
#define MSG_PARSE_SORTDOWN 902
#define MSG_PARSE_MIX 903
#define MSG_PARSE_DRAWERS 904
#define MSG_PARSE_NAMEMATCH 905
#define MSG_PARSE_CASEINSENSITIVE 906
#define MSG_PARSE_CASESENSITIVE 907
#define MSG_PARSE_SIZEMATCH 908
#define MSG_PARSE_SIZEEQUAL 909
#define MSG_PARSE_SIZENOEQUAL 910
#define MSG_PARSE_BETWEEN 911
#define MSG_PARSE_NOTBETWEEN 912
#define MSG_PARSE_SIZESMALLER 913
#define MSG_PARSE_SIZELARGER 914
#define MSG_PARSE_PROTMATCH 915
#define MSG_PARSE_DATEMATCH 916
#define MSG_PARSE_DATEOLDER 917
#define MSG_PARSE_DATENEWER 918
#define MSG_PARSE_COMMENTMATCH 919
#define MSG_PARSE_FILES 920
#define MSG_PARSE_DIRS 921
#define MSG_PARSE_TYPE1 922
#define MSG_PARSE_TYPE2 923
#define MSG_PARSE_TYPE3 924
#define MSG_FDEDIT_GADGETS 950
#define MSG_FDEDIT_ASC 951
#define MSG_FDEDIT_HEX 952
#define MSG_FDEDIT_FILEINFO1 953
#define MSG_FDEDIT_DISKINFO1 954
#define MSG_FDEDIT_DISKROOT1 955
#define MSG_FDEDIT_DISKROOT2 956
#define MSG_FDEDIT_DISKROOT3 957
#define MSG_FDEDIT_DISKFILE1 958
#define MSG_FDEDIT_DISKFILE2 959
#define MSG_FDEDIT_DISKFILE3 960
#define MSG_FDEDIT_DISKDIR1 961
#define MSG_FDEDIT_DISKDIR2 962
#define MSG_FDEDIT_DISKDIR3 963
#define MSG_FDEDIT_DISKLIST1 964
#define MSG_FDEDIT_DISKLIST3 965
#define MSG_FDEDIT_DISKDATA1 966
#define MSG_FDEDIT_DISKDATA3 967
#define MSG_FDEDIT_DISKUNKNOWN 968
#define MSG_FDEDIT_DISKBTSH 969
#define MSG_FDEDIT_CALCCHECKSUM 970
#define MSG_FDEDIT_SEARCH 971
#define MSG_FDEDIT_SEARCHING 972
#define MSG_FDEDIT_ILLEGALSEARCH 973
#define MSG_FDEDIT_BYTENUMBER 974
#define MSG_FDEDIT_CONFIG_NOLOWCYL 975
#define MSG_YES 1000
#define MSG_NO 1001
#define MSG_RETRY 1002
#define MSG_OK 1003
#define MSG_CANCEL 1004
#define MSG_SKIP 1005
#define MSG_IGNORE 1006
#define MSG_SAVE 1007
#define MSG_YESN 1008
#define MSG_NON 1009
#define MSG_OKN 1010
#define MSG_ALL 1011
#define MSG_DEVICE_ERROR 1050
#define MSG_DEVICE_ERRORS 1051
#define MSG_CONFIG_NAME 2000
#define MSG_CONFIG_OLDCONFIG 2001
#define MSG_CONFIG_SCREEN 2002
#define MSG_CONFIG_COMMANDS 2003
#define MSG_CONFIG_GENERAL 2004
#define MSG_CONFIG_DATATYPES 2005
#define MSG_CONFIG_MAINSCREEN 2100
#define MSG_CONFIG_TEXTSCREEN 2101
#define MSG_CONFIG_TEXTFONT 2102
#define MSG_CONFIG_LISTFONT 2103
#define MSG_CONFIG_SHOWFONT 2104
#define MSG_CONFIG_REQFONT 2105
#define MSG_CONFIG_LAYOUT 2106
#define MSG_CONFIG_DIRLAYOUT 2107
#define MSG_CONFIG_PALETTE 2108
#define MSG_CONFIG_SCREENTYPE 2200
#define MSG_CONFIG_SCREENTYPE1 2201
#define MSG_CONFIG_SCREENTYPE2 2202
#define MSG_CONFIG_SCREENTYPE3 2203
#define MSG_CONFIG_SCREENWINDOW 2204
#define MSG_CONFIG_LAYOUTHOR 2205
#define MSG_CONFIG_LAYOUTVER 2206
#define MSG_CONFIG_LAYOUT_DIRLIST 2207
#define MSG_CONFIG_LAYOUT_MENUBAR 2208
#define MSG_CONFIG_LAYOUT_RIGHTALIGNMENT 2209
#define MSG_CONFIG_LAYOUT_RIGHTLOCK 2210
#define MSG_CONFIG_LAYOUT_WIDTH 2211
#define MSG_CONFIG_LAYOUT_CMENUPOS 2212
#define MSG_CONFIG_LAYOUT_CMENUSIZE 2213
#define MSG_CONFIG_LAYOUT_CMENUALIGNMENT 2214
#define MSG_CONFIG_SCRFORMAT 2215
#define MSG_CONFIG_FONTFORMAT 2216
#define MSG_CONFIG_VSCROLL 2217
#define MSG_CONFIG_HSCROLL 2218
#define MSG_CONFIG_SCROLLSMOOTH 2219
#define MSG_CONFIG_SCROLLJUMP 2220
#define MSG_CONFIG_ON 2400
#define MSG_CONFIG_OFF 2401
#define MSG_CONFIG_UP 2402
#define MSG_CONFIG_DOWN 2403
#define MSG_CONFIG_DOSREQUESTER 2404
#define MSG_CONFIG_PRIORITYMAIN 2405
#define MSG_CONFIG_PRIORITYHIGH 2406
#define MSG_CONFIG_PRIORITYMED 2407
#define MSG_CONFIG_PRIORITYLOW 2408
#define MSG_CONFIG_DOSBUFSIZE 2409
#define MSG_CONFIG_DOUBLECLICK 2410
#define MSG_CONFIG_RIGHTMOUSE 2411
#define MSG_CONFIG_RIGHTMOUSE_DOUBLECLICK 2412
#define MSG_CONFIG_RIGHTMOUSE_PARENT 2413
#define MSG_CONFIG_USEDT_PICTURE 2414
#define MSG_CONFIG_USEDT_SAMPLE 2415
#define MSG_CONFIG_USEDT_ASC 2416
#define MSG_CONFIG_USEDT_HEX 2417
#define MSG_CONFIG_USEDT_MOD 2418
#define MSG_CONFIG_USEDT_ICON 2419
#define MSG_CONFIG_USEDT_FONT 2420
#define MSG_CONFIG_USEDT_EXECUTE 2421
#define MSG_CONFIG_EDITPALETTE 2500
#define MSG_CONFIG_PENS 2501
#define MSG_CONFIG_COMUSERCOMMAND 2502
#define MSG_CONFIG_COMBUILDINCOMMANDS 2503
#define MSG_CONFIG_COMBARCOMMANDS 2504
#define MSG_CONFIG_COMCORNERCOMMANDS 2505
#define MSG_CONFIG_COMHIDDENCOMMANDS 2506
#define MSG_CONFIG_COMBUILDUSERKEY 2507
#define MSG_CONFIG_COMSLOTSFULL 2508
#define MSG_CONFIG_COMEDITCONFIG 2509
#define MSG_CONFIG_COMMOVEGADGETBAR 2510
#define MSG_CONFIG_COMMOVECORNERMENU 2511
#define MSG_CONFIG_COMMOVEHIDDEN 2512
#define MSG_CONFIG_COMCOPYGADGETBAR 2513
#define MSG_CONFIG_COMCOPYCORNERMENU 2514
#define MSG_CONFIG_COMDUPLICATECOMMAND 2515
#define MSG_CONFIG_COMREMOVECOMMAND 2516
#define MSG_CONFIG_COMNEWUSERCOMMAND 2517
#define MSG_CONFIG_COMLABEL 2518
#define MSG_CONFIG_COMPATTERN 2519
#define MSG_CONFIG_COMOFFSET 2520
#define MSG_CONFIG_COMSIGNATURE 2521
#define MSG_CONFIG_COMCOMMAND 2522
#define MSG_CONFIG_COMSTACK 2523
#define MSG_CONFIG_COMKEY 2524
#define MSG_CONFIG_COMFRONTPEN 2525
#define MSG_CONFIG_COMBACKPEN 2526
#define MSG_CONFIG_COMPRI 2527
#define MSG_CONFIG_COMLOWPRI 2528
#define MSG_CONFIG_COMMEDPRI 2529
#define MSG_CONFIG_COMHIGHPRI 2530
#define MSG_CONFIG_COMSWAP 2531
#define MSG_CONFIG_COMCHANGE 2532

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};


#ifdef CATCOMP_CODE

STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
LONG   *l;
UWORD  *w;
STRPTR  builtIn;

    l = (LONG *)CatCompBlock;

    while (*l != stringNum)
    {
        w = (UWORD *)((ULONG)l + 4);
        l = (LONG *)((ULONG)l + (ULONG)*w + 6);
    }
    builtIn = (STRPTR)((ULONG)l + 6);

#define XLocaleBase LocaleBase
#define LocaleBase li->li_LocaleBase
    
    if (LocaleBase)
        return(GetCatalogStr(li->li_Catalog,stringNum,builtIn));
#define LocaleBase XLocaleBase
#undef XLocaleBase

    return(builtIn);
}


#endif /* CATCOMP_CODE */


/****************************************************************************/


#endif /* DESCRIPTOR_H */
