/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "PopFile"
#define F_CLASS_VERSION                         2
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "02.00 (2005/08/03)"

#include <feelin/class_startup.c>

#include "Private.h"
