#ifndef WB_DEVELOPERS_H
#define WB_DEVELOPERS_H

char *developers[] = {
  "Aaron Digulla (Coordinator)",
  "Matthias Fleischer (Exec, DOS, drivers)",
  "Peter Boeckmann (Sparc, Alpha)",
  "Iain Templeton (HIDDs, Docs)",
  "Peter Bortas",
  "Martin Recktenwald (WWW, layers)",
  "Lennard voor den Dag (Amiga port, layers)",
  "Chris Lawrence (Linux/m68k)",
  "Geert Uytterhoeven (Linux/m68k)",
  "Kars de Jong (misc)",
  "Nils Henrik Lorentzen (GadTools, Asl, input.device)",
  "Stefan Ruppert (Datatypes)",
  "Harald Frank (Amiga port)",
  "Martin Steigerwald (Beta tester)",
  "Sebastian Rittau (Includes, Gadtools, Docs)",
  "L. A. Guest (CLI tools)",
  "Johan Alfredsson (Commodities)",
  "Stefan Berger (Math, DOS, Arp)",
  "Jesper Skov (Linux/m68k)",
  "Wez Furlong (Shell)",
  "Stefan Czinczoll (WWW)",
  "John J. Karcher (Slim Binaries)",
  "Adrian Brown (Win95 port)",
  "Henning Kiel (Games, Misc)",
  "Przemys³aw Szczygielski (Alpha port)",
  "Michael Schulz (x86 standalone)",
  "Adrian Brown (Wintel port)",
  "Mattias Gustavsson (Solaris port)",
  "Stefan Reinauer",
  "Christopher D. Judd",
  "Tommy Johansson",
  "Paolo Costabel",
  "Daniel Verite",
  "Michael Roth",
  "Nico Heinz",
  "Bernhard Fastenrath",
  "Thomas Schwarz",
  "Yannick Koehler",
  "Hans Van Ingelgom",
  "Ross Cohen",
  "Janos Farkas",
  "Morten Holm",
  "Robert Lumley",
  "Sven Drieling",
  "James McArthur",
  "Gregor Goldbach",
  "Jim Cooper",
  "Claus Herrmann",
  "Marco Fanciulli",
  "Jörg Rebenstorf",
  "Gabriele Del Prete",
  "Milos Masopust",
  "Joseph M. Hinkle",
  "Armin Obersteiner",
  "Joakim Ogren",
  "Erhan Bilgili",
  "Bernardo Innocenti",
  "Wojciech Czyz",
  "Fabio Rotondo",
  "Paul Firth",
  "Vitas Povilaitis",
  "Bill Sidhipong",
  "Cristiano Contin",
  "Lars S. Jessen",
  "Patrice Le Gurun",
  "Branko Collin",
  "Paolo Pisati",
  "Giulio Eulisse",
  "Karl Staas",
  "Fabio Alemagna",
  "Mathieu Chouinard",
  "Pawel Kolodziejski",
  "Eirik Nicolai Synnes",
  "Phill Wooller",
  "Helmut Steger",
  "Jonathan Adamczewski",
  "Richard Tew",
  "Panagiwths Katsaloulis",
  "Michael Aldred",
  "Johan Grip",
  "Ujvary, Bela Istvan",
  "Aard Keimpema",
  "Peter H. Froehlich",
  "Robert Falk",
  "Richard Drummond",
  "Rory Toma",
  "Troein Carl",
  "Philippe GOETZ",
  "Mark Junker",
  "James Woodcock",
  "Dwight Schauer",
  "Thomas Eriksson",
  "Adam Chodorowski",
  "Daniel Schwill",
  "Magnani Christophe",
  "Sebastian Bauer",
  "Markus Poellmann",
  "Mathias Spjuth",
  "Eric Johnson",
  "Artur P. Kuptel",
  "KOIKE Masanori",
  "Sebastian Heutling",
  "Christopher Tagoe",
  "Tobias Seiler",
  "Dennis Paulisch",
  "Lars Bischoff",
  "Henrik Berglund",
  "Ronny Loken",
  
  NULL 
};

#endif
