/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Document"
#define F_CLASS_VERSION                         2
#define F_CLASS_REVISION                        2
#define F_CLASS_VERSION_STRING                  "02.02 (2005/08/22)"

#include <feelin/class_startup.c>

#include "Private.h"
