library.o: library.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h private.h rev.h ../include/mcc_common.h \
  ../include/SDI_hook.h ../include/SDI_lib.h ../include/SDI_stdarg.h \
  icon.bh ../include/mccinit.c
utils.o: utils.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h
loc.o: loc.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h
class.o: class.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h rev.h private.h
debug.o: debug.c
coloradjust.o: coloradjust.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h
backgroundadjust.o: backgroundadjust.c class.h \
  ../include/proto/cybergraphics.h ../include/proto/muimaster.h \
  ../include/libraries/mui.h ../include/interfaces/muimaster.h \
  ../include/inline4/muimaster.h ../include/mui/TheBar_mcc.h \
  ../include/mui/TheBar_mcp.h ../include/SDI_compiler.h \
  ../include/SDI_stdarg.h ../include/SDI_compiler.h ../include/SDI_hook.h \
  debug.h loc.h class_protos.h
penadjust.o: penadjust.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h
popbackground.o: popbackground.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h
poppen.o: poppen.c class.h ../include/proto/cybergraphics.h \
  ../include/proto/muimaster.h ../include/libraries/mui.h \
  ../include/interfaces/muimaster.h ../include/inline4/muimaster.h \
  ../include/mui/TheBar_mcc.h ../include/mui/TheBar_mcp.h \
  ../include/SDI_compiler.h ../include/SDI_stdarg.h \
  ../include/SDI_compiler.h ../include/SDI_hook.h debug.h loc.h \
  class_protos.h
