/*
**	PhonePanel.h
**
**	Gadget IDs used by the phonebook
**
**	Copyright © 1990-1996 by Olaf `Olsen' Barthel
**		All Rights Reserved
**
**	:ts=4
*/

#ifndef _PHONEPANEL_H
#define _PHONEPANEL_H 1

enum	{	GAD_GROUPID=1000,GAD_NAMELIST,GAD_COMMENTLINE,
			GAD_MOVE_FIRST,GAD_MOVE_UP,GAD_MOVE_DOWN,GAD_MOVE_LAST,
			GAD_EDIT,GAD_ADD,GAD_COPY,GAD_DELETE,
			GAD_USE,GAD_COPY_CONFIG,GAD_MAKE_GROUP,GAD_SPLIT_GROUP,
			GAD_SELECT,GAD_CLEAR,GAD_TOGGLE_ALL,GAD_SELECT_ALL,GAD_CLEAR_ALL,GAD_PATTERN,GAD_DIAL,
			GAD_PASSWORD,GAD_LOAD,GAD_MERGE,GAD_SAVE,GAD_PRINT,GAD_SORT,GAD_SORT_ORDER,
			GAD_MAIN_AUTODIAL,GAD_MAIN_EXIT_WHEN_FINISHED,

			GAD_SYSTEM_NAME,GAD_COMMENT,GAD_NUMBERS,GAD_QUICK_MENU,GAD_USER_NAME,GAD_USER_PASSWORD,
			GAD_SERIAL_STATE,GAD_SERIAL_EDIT,GAD_MODEM_STATE,GAD_MODEM_EDIT,
			GAD_SCREEN_STATE,GAD_SCREEN_EDIT,GAD_TERMINAL_STATE,GAD_TERMINAL_EDIT,
			GAD_EMULATION_STATE,GAD_EMULATION_EDIT,GAD_CLIPBOARD_STATE,GAD_CLIPBOARD_EDIT,
			GAD_CAPTURE_STATE,GAD_CAPTURE_EDIT,GAD_COMMAND_STATE,GAD_COMMAND_EDIT,
			GAD_MISC_STATE,GAD_MISC_EDIT,GAD_PATH_STATE,GAD_PATH_EDIT,
			GAD_TRANSFER_STATE,GAD_TRANSFER_EDIT,GAD_TRANSLATION_STATE,GAD_TRANSLATION_EDIT,
			GAD_MACRO_STATE,GAD_MACRO_EDIT,GAD_CURSOR_STATE,GAD_CURSOR_EDIT,
			GAD_FASTMACRO_STATE,GAD_FASTMACRO_EDIT,GAD_RATE_STATE,GAD_RATE_EDIT,
			GAD_FIRST_ENTRY,GAD_PREVIOUS_ENTRY,GAD_NEXT_ENTRY,GAD_LAST_ENTRY,GAD_CLOSE,
			GAD_AUTODIAL,GAD_HIDE_USERNAME_PASSWORD,

			GAD_SELECT_MODE,GAD_SELECT_NAME,GAD_SELECT_NUMBER,GAD_SELECT_COMMENT,GAD_SELECT_APPLY,
			GAD_SELECT_APPLY_AND_CLOSE,GAD_SELECT_CLOSE,

			GAD_GROUP_LIST,GAD_GROUP_NAME,GAD_GROUP_OK,GAD_GROUP_CANCEL,

			GAD_SORT_CRITERIA,GAD_SORT_REVERSE,GAD_SORT_AND_CLOSE,GAD_SORT_IT,GAD_SORT_JUST_CLOSE,

			GAD_NEW_PASSWORD,GAD_REPEAT_PASSWORD,GAD_USE_NEW_PASSWORD,GAD_CLEAR_PASSWORD,
			GAD_CANCEL_PASSWORD
		};

#endif	/* _PHONEPANEL_H */
