#define WANDERERVERS    0
#define WANDERERREV     86
#define WANDERERSTR     "Wanderer 0.87 (02.11.2011)"
#define WANDERERAUTH    "The AROS Dev Team"
#define WANDERERCOPY    "© " WANDERERAUTH
#define VERSION "$VER:  " WANDERERSTR " " WANDERERCOPY
