#include <errno.h>
#include <caf/errors.h>
static char *g_noerrno = "Error code not found in errno table";

#ifdef __AROS__
static struct ErrnoEntry ErrnoTable[MAX_ERRNO] = 
{
	{ EPERM, "Operation not permitted" },
	{ ENOENT, "No such file or directory" },
	{ ESRCH, "No such process" },
	{ EINTR, "Interrupted system call" },
	{ EIO, "error" },
	{ ENXIO, "No such device or address" },
	{ E2BIG, "Arg list too long" },
	{ ENOEXEC, "Exec format error" },
	{ EBADF, "Bad file number" },
	{ ECHILD, "No child processes" },
	{ EAGAIN, "Try again" },
	{ ENOMEM, "Out of memory" },
	{ EACCES, "Permission denied" },
	{ EFAULT, "Bad address" },
	{ ENOTBLK, "Block device required" },
	{ EBUSY, "Device or resource busy" },
	{ EEXIST, "File exists" },
	{ EXDEV, "Cross-device link " },
	{ ENODEV, "No such device" },
	{ ENOTDIR, "Not a directory" },
	{ EISDIR, "Is a directory" },
	{ EINVAL, "Invalid argument" },
	{ ENFILE, "File table overflow" },
	{ EMFILE, "Too many open files" },
	{ ENOTTY, "Not a typewriter" },
	{ ETXTBSY, "Text file busy" },
	{ EFBIG, "File too large" },
	{ ENOSPC, "No space left on device" },
	{ ESPIPE, "Illegal seek" },
	{ EROFS, "Read-only file system" },
	{ EMLINK, "Too many links" },
	{ EPIPE, "Broken pipe" },
	{ EDOM, "Math argument out of domain of func" },
	{ ERANGE, "Math result not representable" },
	{ EDEADLK, "Resource deadlock would occur" },
	{ ENAMETOOLONG, "File name too long" },
	{ ENOLCK, "No record locks available" },
	{ ENOSYS, "Function not implemented" },
	{ ENOTEMPTY, "Directory not empty" },
	{ ELOOP, "Too many symbolic links encountered" },
	{ EWOULDBLOCK, "Operation would block" },
	{ ENOMSG, "No message of desired type" },
	{ EIDRM, "dentifier removed" },
	{ ECHRNG, "Channel number out of range" },
	{ EL2NSYNC, "Level 2 not synchronized" },
	{ EL3HLT, "Level 3 halted" },
	{ EL3RST, "Level 3 reset" },
	{ ELNRNG, "Link number out of range" },
	{ EUNATCH, "Protocol driver not attached" },
	{ ENOCSI, "No CSI structure available" },
	{ EL2HLT, "Level 2 halted" },
	{ EBADE, "Invalid exchange" },
	{ EBADR, "Invalid request descriptor" },
	{ EXFULL, "Exchange full" },
	{ ENOANO, "No anode" },
	{ EBADRQC, "Invalid request code" },
	{ EBADSLT, "Invalid slot" },
	{ EBFONT, "Bad font file format" },
	{ ENOSTR, "Device not a stream" },
	{ ENODATA, "No data available" },
	{ ETIME, "Timer expired" },
	{ ENOSR, "Out of streams resources" },
	{ ENONET, "Machine is not on the network" },
	{ ENOPKG, "ackage not installed" },
	{ EREMOTE, "Object is remote" },
	{ ENOLINK , "Link has been severed" },
	{ EADV, "Advertise error" },
	{ ESRMNT, "Srmount error" },
	{ ECOMM, "Communication error on send" },
	{ EPROTO, "Protocol error" },
	{ EMULTIHOP, "Multihop attempted" },
	{ EDOTDOT, "RFS specific error" },
	{ EBADMSG, "Not a data message" },
	{ EOVERFLOW, "Value too large for defined data type" },
	{ ENOTUNIQ, "Name not unique on network" },
	{ EBADFD, "ile descriptor in bad state" },
	{ EREMCHG, "Remote address changed" },
	{ ELIBACC, "Can not access a needed shared library" },
	{ ELIBBAD, "Accessing a corrupted shared library" },
	{ ELIBSCN, ".lib section in a.out corrupted" },
	{ ELIBMAX, "Attempting to link in too many shared libraries" },
	{ ELIBEXEC, "Cannot exec a shared library directly" },
	{ EILSEQ, "Illegal byte sequence" },
	{ ERESTART, "Interrupted system call should be restarted" },
	{ ESTRPIPE, "Streams pipe error" },
	{ EUSERS, "Too many users" },
	{ ENOTSOCK, "Socket operation on non-socket" },
	{ EDESTADDRREQ, "Destination address required" },
	{ EMSGSIZE, "Message too long" },
	{ EPROTOTYPE, "Protocol wrong type for socket" },
	{ ENOPROTOOPT, "Protocol not available" },
	{ EPROTONOSUPPORT, "Protocol not supported" },
	{ ESOCKTNOSUPPORT, "Socket type not supported" },
	{ EOPNOTSUPP, "Operation not supported on transport endpoint" },
	{ EPFNOSUPPORT, "Protocol family not supported" },
	{ EAFNOSUPPORT, "Address family not supported by protocol" },
	{ EADDRINUSE, " Address already in use" },
	{ EADDRNOTAVAIL, "Cannot assign requested address" },
	{ ENETDOWN, "Network is down" },
	{ ENETUNREACH, "Network is unreachable" },
	{ ENETRESET, "Network dropped connection because of reset" },
	{ ECONNABORTED, "Software caused connection abort" },
	{ ECONNRESET, "Connection reset by peer" },
	{ ENOBUFS, "No buffer space available" },
	{ EISCONN, "Transport endpoint is already connected" },
	{ ENOTCONN, "Transport endpoint is not connected" },
	{ ESHUTDOWN, "Cannot send after transport endpoint shutdown" },
	{ ETOOMANYREFS, "Too many references: cannot splice" },
	{ ETIMEDOUT, "Connection timed out" },
	{ ECONNREFUSED, "Connection refused" },
	{ EHOSTDOWN, "Host is down" },
	{ EHOSTUNREACH, "No route to host" },
	{ EALREADY, "Operation already in progress" },
	{ EINPROGRESS, "Operation now in progress" },
	{ ESTALE, "Stale NFS file handle" },
	{ EUCLEAN, "Structure needs cleaning" },
	{ ENOTNAM, "Not a XENIX named type file" },
	{ ENAVAIL, "No XENIX semaphores available" },
	{ EISNAM, "Is a named type file" },
	{ EREMOTEIO, "Remote I/O error" },
	{ EDQUOT, "Quota exceeded" },
	{ 0, "No error" }
};

#if MAX_ERRNO != 122
#error Errno array problem in errors.c
#endif
#endif

#ifdef __MORPHOS__
#define MAX_ERRNO 80
static struct ErrnoEntry ErrnoTable[MAX_ERRNO] = 
{
	{ EPERM,  "Operation not permitted" },
	{ ENOENT,  "No such file or directory" },
	{ ESRCH,  "No such process" },
	{ EINTR,  "Interrupted system call" },
	{ EIO,  "Input/output error" },
	{ ENXIO,  "Device not configured" },
	{ E2BIG,  "Argument list too long" },
	{ ENOEXEC,  "Exec format error" },
	{ EBADF,  "Bad file descriptor" },
	{ ECHILD,  "No child processes" },
	{ EDEADLK,  "Resource deadlock avoided" },
	{ ENOMEM,  "Cannot allocate memory" },
	{ EACCES,  "Permission denied" },
	{ EFAULT,  "Bad address" },
	{ ENOTBLK,  "Block device required" },
	{ EBUSY,  "Device busy" },
	{ EEXIST,  "File exists" },
	{ EXDEV,  "Cross-device link" },
	{ ENODEV,  "Operation not supported by device" },
	{ ENOTDIR,  "Not a directory" },
	{ EISDIR,  "Is a directory" },
	{ EINVAL,  "Invalid argument" },
	{ ENFILE,  "Too many open files in system" },
	{ EMFILE,  "Too many open files" },
	{ ENOTTY,  "Inappropriate ioctl for device" },
	{ ETXTBSY,  "Text file busy" },
	{ EFBIG,  "File too large" },
	{ ENOSPC,  "No space left on device" },
	{ ESPIPE,  "Illegal seek" },
	{ EROFS,  "Read-only file system" },
	{ EMLINK,  "Too many links" },
	{ EPIPE,  "Broken pipe" },
	{ EDOM,  "Numerical argument out of domain" },
	{ ERANGE,  "Result too large" },
	{ EAGAIN,  "Resource temporarily unavailable" },
	{ EWOULDBLOCK,  "Operation would block" },
	{ EINPROGRESS,  "Operation now in progress" },
	{ EALREADY,  "Operation already in progress" },
	{ ENOTSOCK,  "Socket operation on non-socket" },
	{ EDESTADDRREQ,  "Destination address required" },
	{ EMSGSIZE,  "Message too long" },
	{ EPROTOTYPE,  "Protocol wrong type for socket" },
	{ ENOPROTOOPT,  "Protocol not available" },
	{ EPROTONOSUPPORT,  "Protocol not supported" },
	{ ESOCKTNOSUPPORT,  "Socket type not supported" },
	{ EOPNOTSUPP,  "Operation not supported on socket" },
	{ EPFNOSUPPORT,  "Protocol family not supported" },
	{ EAFNOSUPPORT,  "Address family not supported by protocol family" },
	{ EADDRINUSE,  "Address already in use" },
	{ EADDRNOTAVAIL,  "Can't assign requested address" },
	{ ENETDOWN,  "Network is down" },
	{ ENETUNREACH,  "Network is unreachable" },
	{ ENETRESET,  "Network dropped connection on reset" },
	{ ECONNABORTED,  "Software caused connection abort" },
	{ ECONNRESET,  "Connection reset by peer" },
	{ ENOBUFS,  "No buffer space available" },
	{ EISCONN,  "Socket is already connected" },
	{ ENOTCONN,  "Socket is not connected" },
	{ ESHUTDOWN,  "Can't send after socket shutdown" },
	{ ETOOMANYREFS,  "Too many references: can't splice" },
	{ ETIMEDOUT,  "Connection timed out" },
	{ ECONNREFUSED,  "Connection refused" },
	{ ELOOP,  "Too many levels of symbolic links" },
	{ ENAMETOOLONG,  "File name too long" },
	{ EHOSTDOWN,  "Host is down" },
	{ EHOSTUNREACH,  "No route to host" },
	{ ENOTEMPTY,  "Directory not empty" },
	{ EPROCLIM,  "Too many processes" },
	{ EUSERS,  "Too many users" },
	{ EDQUOT,  "Disc quota exceeded" },
	{ ESTALE,  "Stale NFS file handle" },
	{ EREMOTE,  "Too many levels of remote in path" },
	{ EBADRPC,  "RPC struct is bad" },
	{ ERPCMISMATCH,  "RPC version wrong" },
	{ EPROGUNAVAIL,  "RPC prog. not avail" },
	{ EPROGMISMATCH,  "Program version wrong" },
	{ EPROCUNAVAIL,  "Bad procedure for program" },
	{ ENOLCK,  "No locks available" },
	{ ENOSYS,  "Function not implemented" },
	{ EFTYPE,  "Inappropriate file type or format" }
};
#endif

char *GetErrnoDesc(int err_code)
{
	int i;
	
	for (i = 0; i < MAX_ERRNO; i++) {
		if (ErrnoTable[i].error_code == err_code)
			return ErrnoTable[i].error_desc;
	}
	
	return g_noerrno;
}
