
OBJS = \
	Wrapper.o						\
	Globals.o						\
	GUI.o							\
	MUITracks.o						\
	MUIPageSelect.o					\
	MUITracksISOBuilder.o			\
	MUITracksDataAudio.o			\
	MUITracksSession.o				\
	MUIMedia.o						\
	MUIContents.o					\
	MUIDrive.o						\
	MUISettings.o					\
	MUIRecord.o						\
	MUIDriveSelect.o				\
	MUISpeedSelect.o				\
	MUIPopDevice.o					\
	MUIPopDOSDevice.o				\
	MUIPopUnit.o					\
	MUICommon.o						\
	MUIPopISOElement.o				\
	MUIPopAction.o					\
	Components/MUIToolBar.o			\
	Components/MUIWindowMenu.o		\
	Components/MUI.o				\
	Components/MUIList.o			\
	Components/MUITree.o			\
	Components/MUIPopup.o			\
	Components/MUIPopString.o		\
	Components/MUIPopText.o			\
	Components/MUIPopAsl.o			\
	Components/FileReq.o			\
	Components/MUIPictureClass.o
	
Program			= MUI.interface

TARGETS			= aros os3 morphos os4
OBJDIRS			= Components
MAKEDIRS		= 

BUILD_LIBRARY	= 0

INCOPTS			= 
LIBOPTS			= -lLibrary -lGeneric -lC

OWNSTARTUP		= 1
AROS_LIBOPTS	= 
M68K_LIBOPTS	=
MOS_LIBOPTS		=
OS4_LIBOPTS		=

	include ../../Generic/Makefile.mk

// vim: noet ts=4
